import { CaseStatus, PriorityLevel, Prisma, RiskLevel } from '../../generated/prisma';
import prisma from '../../lib/prisma';
import { buildAssetReadWhere, buildCaseReadWhere, type OrganizationalPrincipal } from '../../security/organizational-scope';
import { buildPublicReportReadWhere } from '../public-reports/public-report.service';

export const GEOSPATIAL_ANALYSIS_VERSION='ODYSSEY_GEOSPATIAL_HOTSPOTS_V1';
export const GRID_SIZE_DEGREES=0.01;
const BATCH_SIZE=500,HOTSPOT_LIMIT=100,CONTRIBUTOR_LIMIT=20;
const activeCaseStatuses=Object.values(CaseStatus).filter(status=>status!==CaseStatus.CLOSED&&status!==CaseStatus.CANCELLED);
const priorityWeight:Record<PriorityLevel,number>={LOW:1,MEDIUM:2,HIGH:3,VERY_HIGH:4,CRITICAL:5};
const priorityOrder:PriorityLevel[]=[PriorityLevel.CRITICAL,PriorityLevel.VERY_HIGH,PriorityLevel.HIGH,PriorityLevel.MEDIUM,PriorityLevel.LOW];
const riskOrder:RiskLevel[]=[RiskLevel.CRITICAL,RiskLevel.VERY_HIGH,RiskLevel.HIGH,RiskLevel.MODERATE,RiskLevel.LOW,RiskLevel.VERY_LOW];

type Coordinate={latitude:number;longitude:number};
type Organization={id:string;name:string}|null;
type Coverage={eligibleRecords:number;mappedRecords:number;unmappedRecords:number;invalidCoordinateCount:number;coveragePercentage:number};
type Cell={cellId:string;latitudeIndex:number;longitudeIndex:number;department:Organization;jurisdiction:Organization;latitudeTotal:number;longitudeTotal:number;pointCount:number;assetIds:Set<string>;caseIds:Set<string>;publicReportCount:number;riskCounts:Record<string,number>;priorityCounts:Record<string,number>;severityComponents:Record<string,number>};

function numeric(value:unknown):number|null{if(typeof value==='number')return Number.isFinite(value)?value:null;if(value instanceof Prisma.Decimal){const result=value.toNumber();return Number.isFinite(result)?result:null;}return null;}
export function validCoordinate(latitude:unknown,longitude:unknown):Coordinate|null{const lat=numeric(latitude),lon=numeric(longitude);return lat!==null&&lon!==null&&lat>=-90&&lat<=90&&lon>=-180&&lon<=180?{latitude:lat,longitude:lon}:null;}
export function coordinateState(latitude:unknown,longitude:unknown):'VALID'|'MISSING'|'INVALID'{if(latitude===null||latitude===undefined){return longitude===null||longitude===undefined?'MISSING':'INVALID';}if(longitude===null||longitude===undefined)return'INVALID';return validCoordinate(latitude,longitude)?'VALID':'INVALID';}
const gridIndex=(value:number)=>Math.floor(Number((value/GRID_SIZE_DEGREES).toFixed(9)));
export function gridCell(coordinate:Coordinate){const latitudeIndex=gridIndex(coordinate.latitude),longitudeIndex=gridIndex(coordinate.longitude);return{latitudeIndex,longitudeIndex,cellId:`G001:${latitudeIndex}:${longitudeIndex}`};}
export function centroid(points:Coordinate[]):Coordinate|null{return points.length?{latitude:Number((points.reduce((sum,p)=>sum+p.latitude,0)/points.length).toFixed(6)),longitude:Number((points.reduce((sum,p)=>sum+p.longitude,0)/points.length).toFixed(6))}:null;}
const blankCoverage=():Coverage=>({eligibleRecords:0,mappedRecords:0,unmappedRecords:0,invalidCoordinateCount:0,coveragePercentage:0});
function recordCoverage(coverage:Coverage,latitude:unknown,longitude:unknown){coverage.eligibleRecords++;const state=coordinateState(latitude,longitude);if(state==='VALID')coverage.mappedRecords++;else{coverage.unmappedRecords++;if(state==='INVALID')coverage.invalidCoordinateCount++;}}
function finishCoverage(coverage:Coverage){coverage.coveragePercentage=coverage.eligibleRecords?Number((coverage.mappedRecords/coverage.eligibleRecords*100).toFixed(1)):0;return coverage;}
function allowedAtOrAbove<T extends string>(value:T|undefined,order:T[]){return value?order.slice(0,order.indexOf(value)+1):order;}

export async function analyzeGeospatialHotspots(principal:OrganizationalPrincipal,filters:{departmentId?:string;jurisdictionId?:string;minimumPriority?:PriorityLevel;minimumRisk?:RiskLevel}={}){
 return prisma.$transaction(async tx=>{
  const coverage={assets:blankCoverage(),activeCases:blankCoverage(),publicReports:blankCoverage(),overall:blankCoverage()},cells=new Map<string,Cell>(),bounds:Coordinate[]=[];
  const cellFor=(coordinate:Coordinate,department:Organization,jurisdiction:Organization)=>{const grid=gridCell(coordinate),key=`${department?.id??'UNASSIGNED'}:${jurisdiction?.id??'UNASSIGNED'}:${grid.cellId}`;let cell=cells.get(key);if(!cell){cell={...grid,cellId:key,department,jurisdiction,latitudeTotal:0,longitudeTotal:0,pointCount:0,assetIds:new Set(),caseIds:new Set(),publicReportCount:0,riskCounts:{},priorityCounts:{},severityComponents:{CRITICAL:0,VERY_HIGH:0,HIGH:0,MEDIUM:0,LOW:0}};cells.set(key,cell);}cell.latitudeTotal+=coordinate.latitude;cell.longitudeTotal+=coordinate.longitude;cell.pointCount++;bounds.push(coordinate);return cell;};
  const traverse=async<T extends{id:string}>(find:(cursor?:string)=>Promise<T[]>,visit:(row:T)=>void)=>{let cursor:string|undefined;do{const rows=await find(cursor);rows.forEach(visit);cursor=rows.length===BATCH_SIZE?rows.at(-1)!.id:undefined;}while(cursor);};
  await traverse(cursor=>tx.asset.findMany({where:{AND:[buildAssetReadWhere(principal),filters.departmentId?{departmentId:filters.departmentId}:{},filters.jurisdictionId?{jurisdictionId:filters.jurisdictionId}:{}]},select:{id:true,latitude:true,longitude:true,department:{select:{id:true,name:true}},jurisdiction:{select:{id:true,name:true}}},orderBy:{id:'asc'},take:BATCH_SIZE,...(cursor?{cursor:{id:cursor},skip:1}:{})}),asset=>{recordCoverage(coverage.assets,asset.latitude,asset.longitude);const point=validCoordinate(asset.latitude,asset.longitude);if(point)cellFor(point,asset.department,asset.jurisdiction).assetIds.add(asset.id);});
  await traverse(cursor=>tx.case.findMany({where:{AND:[buildCaseReadWhere(principal),{status:{in:activeCaseStatuses}},filters.departmentId?{asset:{departmentId:filters.departmentId}}:{},filters.jurisdictionId?{asset:{jurisdictionId:filters.jurisdictionId}}:{},filters.minimumPriority?{priorityLevel:{in:allowedAtOrAbove(filters.minimumPriority,priorityOrder)}}:{},filters.minimumRisk?{riskLevel:{in:allowedAtOrAbove(filters.minimumRisk,riskOrder)}}:{}]},select:{id:true,riskLevel:true,priorityLevel:true,asset:{select:{id:true,latitude:true,longitude:true,department:{select:{id:true,name:true}},jurisdiction:{select:{id:true,name:true}}}}},orderBy:{id:'asc'},take:BATCH_SIZE,...(cursor?{cursor:{id:cursor},skip:1}:{})}),currentCase=>{recordCoverage(coverage.activeCases,currentCase.asset.latitude,currentCase.asset.longitude);const point=validCoordinate(currentCase.asset.latitude,currentCase.asset.longitude);if(!point)return;const cell=cellFor(point,currentCase.asset.department,currentCase.asset.jurisdiction);cell.caseIds.add(currentCase.id);cell.assetIds.add(currentCase.asset.id);if(currentCase.riskLevel)cell.riskCounts[currentCase.riskLevel]=(cell.riskCounts[currentCase.riskLevel]||0)+1;if(currentCase.priorityLevel){cell.priorityCounts[currentCase.priorityLevel]=(cell.priorityCounts[currentCase.priorityLevel]||0)+1;cell.severityComponents[currentCase.priorityLevel]+=priorityWeight[currentCase.priorityLevel];}});
  await traverse(cursor=>tx.publicReport.findMany({where:{AND:[buildPublicReportReadWhere(principal),{status:{not: 'REJECTED'}},filters.departmentId?{departmentId:filters.departmentId}:{},filters.jurisdictionId?{jurisdictionId:filters.jurisdictionId}:{}]},select:{id:true,latitude:true,longitude:true,department:{select:{id:true,name:true}},jurisdiction:{select:{id:true,name:true}}},orderBy:{id:'asc'},take:BATCH_SIZE,...(cursor?{cursor:{id:cursor},skip:1}:{})}),report=>{recordCoverage(coverage.publicReports,report.latitude,report.longitude);const point=validCoordinate(report.latitude,report.longitude);if(point)cellFor(point,report.department,report.jurisdiction).publicReportCount++;});
  for(const source of [coverage.assets,coverage.activeCases,coverage.publicReports])for(const key of ['eligibleRecords','mappedRecords','unmappedRecords','invalidCoordinateCount'] as const)coverage.overall[key]+=source[key];
  Object.values(coverage).forEach(finishCoverage);
  const allHotspots=[...cells.values()].map(cell=>{const recordCount=cell.assetIds.size+cell.caseIds.size+cell.publicReportCount,criticalCount=(cell.priorityCounts.CRITICAL||0)+(cell.riskCounts.CRITICAL||0),severityIndex=Object.values(cell.severityComponents).reduce((sum,value)=>sum+value,0),highestPriority=priorityOrder.find(value=>cell.priorityCounts[value])??null;return{cellId:cell.cellId,center:{latitude:Number((cell.latitudeTotal/cell.pointCount).toFixed(6)),longitude:Number((cell.longitudeTotal/cell.pointCount).toFixed(6))},department:cell.department,jurisdiction:cell.jurisdiction,assetCount:cell.assetIds.size,activeCaseCount:cell.caseIds.size,publicReportCount:cell.publicReportCount,recordCount,riskCounts:cell.riskCounts,priorityCounts:cell.priorityCounts,highestPriority,severityIndex,severityComponents:cell.severityComponents,contributingAssetIds:[...cell.assetIds].sort().slice(0,CONTRIBUTOR_LIMIT),contributingCaseIds:[...cell.caseIds].sort().slice(0,CONTRIBUTOR_LIMIT),contributorsTruncated:cell.assetIds.size>CONTRIBUTOR_LIMIT||cell.caseIds.size>CONTRIBUTOR_LIMIT,qualification:criticalCount>0?'CRITICAL_RECORD':recordCount>=2?'MULTI_RECORD_CONCENTRATION':null};}).filter(cell=>cell.qualification).sort((a,b)=>b.severityIndex-a.severityIndex||((b.priorityCounts.CRITICAL||0)-(a.priorityCounts.CRITICAL||0))||b.activeCaseCount-a.activeCaseCount||b.recordCount-a.recordCount||a.cellId.localeCompare(b.cellId));
  const hotspots=allHotspots.slice(0,HOTSPOT_LIMIT),mapBounds=bounds.length?{south:Math.min(...bounds.map(p=>p.latitude)),west:Math.min(...bounds.map(p=>p.longitude)),north:Math.max(...bounds.map(p=>p.latitude)),east:Math.max(...bounds.map(p=>p.longitude))}:null;
  return{analysisVersion:GEOSPATIAL_ANALYSIS_VERSION,generatedAt:new Date(),scope:{visibility:principal.role==='SYSTEM_ADMIN'?'GLOBAL':'DEPARTMENT_JURISDICTION',departmentId:filters.departmentId??(principal.role==='SYSTEM_ADMIN'?null:principal.departmentId),jurisdictionId:filters.jurisdictionId??(principal.role==='SYSTEM_ADMIN'?null:principal.jurisdictionId),activeCaseStatuses,publicReportStatusesIncluded:['SUBMITTED','UNDER_REVIEW','ACCEPTED'],minimumPriority:filters.minimumPriority??null,minimumRisk:filters.minimumRisk??null},method:{type:'FIXED_GRID',gridSizeDegrees:GRID_SIZE_DEGREES,cellIdentity:'organization IDs plus floor(latitude/0.01) and floor(longitude/0.01)',severity:'sum of current Case priority weights; public reports do not add severity',hotspotThreshold:'at least two distinct represented records, or one CRITICAL current Case'},coverage,summary:{uniqueMappedAssets:new Set([...cells.values()].flatMap(cell=>[...cell.assetIds])).size,activeMappedCases:[...cells.values()].reduce((sum,cell)=>sum+cell.caseIds.size,0),mappedPublicReports:[...cells.values()].reduce((sum,cell)=>sum+cell.publicReportCount,0),totalHotspots:allHotspots.length,hotspotsReturned:hotspots.length},hotspots,truncation:{limit:HOTSPOT_LIMIT,totalHotspots:allHotspots.length,hotspotsReturned:hotspots.length,truncated:allHotspots.length>HOTSPOT_LIMIT},mapBounds,complete:true,disclosure:'Observed hotspots describe concentrations in current recorded data with valid coordinates. They are not predictions of future failure.'};
 },{isolationLevel:Prisma.TransactionIsolationLevel.RepeatableRead,timeout:30000});
}
