import prisma from '../../lib/prisma';
import { ExecutionBlockerCategory, ExecutionTaskStatus, Prisma } from '../../generated/prisma';
import { buildExecutionPlanMutationWhere, buildExecutionPlanReadWhere, buildExecutionTaskMutationWhere, OrganizationalPrincipal } from '../../security/organizational-scope';
import { ExecutionError } from './execution-error';

export const blockerCategories = Object.values(ExecutionBlockerCategory);
const terminal = new Set<ExecutionTaskStatus>([ExecutionTaskStatus.VERIFIED, ExecutionTaskStatus.CANCELLED]);
const minutes = (from?: Date | null, to?: Date | null) => from && to ? Math.round((to.getTime() - from.getTime()) / 60000) : null;
function range(start: Date, end: Date) { if (!(start < end)) throw new ExecutionError('INVALID_SCHEDULE_RANGE', 400, 'Planned start must precede planned end.'); }

export async function updatePlanSchedule(planId:string,input:{plannedStartAt:Date;plannedEndAt:Date;reason:string},principal:OrganizationalPrincipal){
  range(input.plannedStartAt,input.plannedEndAt); if(!input.reason.trim())throw new ExecutionError('INVALID_INPUT',400,'Schedule change reason is required.');
  return prisma.$transaction(async tx=>{const plan=await tx.executionPlan.findFirst({where:{id:planId,...buildExecutionPlanMutationWhere(principal)},include:{tasks:{select:{id:true,plannedStartAt:true,plannedEndAt:true}}}});if(!plan)throw new ExecutionError('EXECUTION_PLAN_NOT_FOUND',404,'Execution plan not found.');
    const outside=plan.tasks.find(t=>(t.plannedStartAt&&t.plannedStartAt<input.plannedStartAt)||(t.plannedEndAt&&t.plannedEndAt>input.plannedEndAt));if(outside)throw new ExecutionError('TASK_SCHEDULE_OUTSIDE_PLAN',409,'Plan dates must encompass scheduled tasks.');
    await tx.executionScheduleRevision.create({data:{executionPlanId:plan.id,previousStartAt:plan.plannedStartAt,previousEndAt:plan.plannedEndAt,newStartAt:input.plannedStartAt,newEndAt:input.plannedEndAt,changedById:principal.id,changeReason:input.reason.trim()}});
    return tx.executionPlan.update({where:{id:plan.id},data:{plannedStartAt:input.plannedStartAt,plannedEndAt:input.plannedEndAt}});
  },{isolationLevel:Prisma.TransactionIsolationLevel.Serializable});
}

export async function updateTaskSchedule(taskId:string,input:{plannedStartAt:Date;plannedEndAt:Date;reason:string},principal:OrganizationalPrincipal){
  range(input.plannedStartAt,input.plannedEndAt);if(!input.reason.trim())throw new ExecutionError('INVALID_INPUT',400,'Schedule change reason is required.');
  return prisma.$transaction(async tx=>{const task=await tx.executionTask.findFirst({where:{id:taskId,...buildExecutionTaskMutationWhere(principal)},include:{executionPlan:true}});if(!task)throw new ExecutionError('EXECUTION_TASK_NOT_FOUND',404,'Execution task not found.');const p=task.executionPlan;if(p.plannedStartAt&&input.plannedStartAt<p.plannedStartAt||p.plannedEndAt&&input.plannedEndAt>p.plannedEndAt)throw new ExecutionError('TASK_SCHEDULE_OUTSIDE_PLAN',409,'Task schedule must be within the plan schedule.');
    await tx.executionScheduleRevision.create({data:{executionPlanId:p.id,executionTaskId:task.id,previousStartAt:task.plannedStartAt,previousEndAt:task.plannedEndAt,newStartAt:input.plannedStartAt,newEndAt:input.plannedEndAt,changedById:principal.id,changeReason:input.reason.trim()}});return tx.executionTask.update({where:{id:task.id},data:{plannedStartAt:input.plannedStartAt,plannedEndAt:input.plannedEndAt}});
  },{isolationLevel:Prisma.TransactionIsolationLevel.Serializable});
}

export async function addDependency(taskId:string,predecessorTaskId:string,principal:OrganizationalPrincipal){if(taskId===predecessorTaskId)throw new ExecutionError('SELF_DEPENDENCY',400,'A task cannot depend on itself.');return prisma.$transaction(async tx=>{const task=await tx.executionTask.findFirst({where:{id:taskId,...buildExecutionTaskMutationWhere(principal)},select:{id:true,executionPlanId:true}});if(!task)throw new ExecutionError('EXECUTION_TASK_NOT_FOUND',404,'Execution task not found.');const predecessor=await tx.executionTask.findFirst({where:{id:predecessorTaskId,executionPlanId:task.executionPlanId},select:{id:true}});if(!predecessor)throw new ExecutionError('DEPENDENCY_TASK_NOT_FOUND',404,'Predecessor task not found in this execution plan.');const edges=await tx.executionTaskDependency.findMany({where:{executionPlanId:task.executionPlanId},select:{predecessorTaskId:true,dependentTaskId:true}});const graph=new Map<string,string[]>();for(const e of edges)graph.set(e.predecessorTaskId,[...(graph.get(e.predecessorTaskId)||[]),e.dependentTaskId]);const stack=[task.id],seen=new Set<string>();while(stack.length){const n=stack.pop()!;if(n===predecessor.id)throw new ExecutionError('DEPENDENCY_CYCLE',409,'Dependency would create a cycle.');if(seen.has(n))continue;seen.add(n);stack.push(...(graph.get(n)||[]));}try{return await tx.executionTaskDependency.create({data:{executionPlanId:task.executionPlanId,dependentTaskId:task.id,predecessorTaskId:predecessor.id,createdById:principal.id}})}catch(error){if(error instanceof Prisma.PrismaClientKnownRequestError&&error.code==='P2002')throw new ExecutionError('DUPLICATE_DEPENDENCY',409,'Dependency already exists.');throw error;}},{isolationLevel:Prisma.TransactionIsolationLevel.Serializable});}
export async function removeDependency(taskId:string,predecessorTaskId:string,principal:OrganizationalPrincipal){const task=await prisma.executionTask.findFirst({where:{id:taskId,...buildExecutionTaskMutationWhere(principal)},select:{id:true}});if(!task)throw new ExecutionError('EXECUTION_TASK_NOT_FOUND',404,'Execution task not found.');const deleted=await prisma.executionTaskDependency.deleteMany({where:{dependentTaskId:task.id,predecessorTaskId}});if(!deleted.count)throw new ExecutionError('DEPENDENCY_NOT_FOUND',404,'Dependency not found.');return{removed:true};}

export function taskScheduleStatus(task:any,asOf:Date){if(!task.plannedStartAt||!task.plannedEndAt)return'UNSCHEDULED';const completed=task.verifiedAt??task.completionSubmittedAt;if(completed)return completed<=task.plannedEndAt?'COMPLETED_ON_TIME':'COMPLETED_LATE';if(task.startedAt)return asOf>task.plannedEndAt?'OVERDUE':task.startedAt<=task.plannedStartAt?'STARTED_ON_TIME':'STARTED_LATE';return asOf>task.plannedEndAt?'OVERDUE':asOf>task.plannedStartAt?'NOT_STARTED_LATE':'NOT_STARTED_ON_SCHEDULE';}
const analysisBatchSize=500,presentationTaskLimit=100;
const analysisTaskSelect={id:true,sequenceNumber:true,status:true,plannedStartAt:true,plannedEndAt:true,assignedAt:true,startedAt:true,completionSubmittedAt:true,verifiedAt:true,dependencies:{select:{predecessorTask:{select:{id:true,sequenceNumber:true,status:true}}}}} as const;
function analyzeTask(task:any,asOf:Date){const scheduleStatus=taskScheduleStatus(task,asOf),unmetDependencies=task.dependencies.filter((d:any)=>d.predecessorTask.status!==ExecutionTaskStatus.VERIFIED).map((d:any)=>d.predecessorTask);return{...task,scheduleStatus,plannedDurationMinutes:minutes(task.plannedStartAt,task.plannedEndAt),varianceMinutes:task.plannedEndAt?minutes(task.plannedEndAt,task.verifiedAt??task.completionSubmittedAt):null,cycleTimes:{assignmentToStartMinutes:minutes(task.assignedAt,task.startedAt),startToCompletionSubmissionMinutes:minutes(task.startedAt,task.completionSubmittedAt),completionSubmissionToVerificationMinutes:minutes(task.completionSubmittedAt,task.verifiedAt),assignmentToVerificationMinutes:minutes(task.assignedAt,task.verifiedAt)},unmetDependencies};}
export async function analyzeSchedule(planId:string,principal:OrganizationalPrincipal,asOf=new Date()){
  return prisma.$transaction(async tx=>{const plan=await tx.executionPlan.findFirst({where:{id:planId,...buildExecutionPlanReadWhere(principal)},include:{scheduleRevisions:{orderBy:{changedAt:'desc'},take:50}}});
  if(!plan)throw new ExecutionError('EXECUTION_PLAN_NOT_FOUND',404,'Execution plan not found.');
  const counts=new Map<string,number>(),presentationTasks:any[]=[];let taskCount=0,blocked=0,unresolvedDependencyCount=0,firstStartedAt:Date|undefined,cursor:string|undefined;
  do{
    const rows=await tx.executionTask.findMany({where:{executionPlanId:plan.id},select:analysisTaskSelect,orderBy:{id:'asc'},take:analysisBatchSize,...(cursor?{cursor:{id:cursor},skip:1}:{})});
    for(const row of rows){const task=analyzeTask(row,asOf);taskCount++;counts.set(task.scheduleStatus,(counts.get(task.scheduleStatus)||0)+1);if(task.status===ExecutionTaskStatus.BLOCKED)blocked++;unresolvedDependencyCount+=task.unmetDependencies.length;if(task.startedAt&&(!firstStartedAt||task.startedAt<firstStartedAt))firstStartedAt=task.startedAt;presentationTasks.push(task);presentationTasks.sort((a,b)=>a.sequenceNumber-b.sequenceNumber||a.id.localeCompare(b.id));if(presentationTasks.length>presentationTaskLimit)presentationTasks.pop();}
    cursor=rows.length===analysisBatchSize?rows[rows.length-1].id:undefined;
  }while(cursor);
  const count=(status:string)=>counts.get(status)||0,unscheduled=count('UNSCHEDULED'),overdue=count('OVERDUE'),late=count('COMPLETED_LATE');let status='ON_SCHEDULE';if(!taskCount||unscheduled===taskCount)status='INSUFFICIENT_SCHEDULE_DATA';else if(plan.status==='COMPLETED')status='COMPLETED';else if(overdue)status='OVERDUE';else if(blocked||unscheduled)status='ATTENTION_REQUIRED';const reasons:string[]=[];if(overdue)reasons.push(`${overdue} task(s) are overdue against the approved plan.`);if(blocked)reasons.push(`${blocked} task(s) have a recorded unresolved blocker.`);if(unscheduled)reasons.push(`${unscheduled} task(s) have no planned schedule.`);if(late)reasons.push(`${late} task(s) completed after their planned end.`);if(!reasons.length)reasons.push('No recorded schedule exception requires attention as of the reference time.');return{asOf,plan:{id:plan.id,status:plan.status,plannedStartAt:plan.plannedStartAt,plannedEndAt:plan.plannedEndAt,plannedDurationMinutes:minutes(plan.plannedStartAt,plan.plannedEndAt),createdToFirstStartMinutes:minutes(plan.createdAt,firstStartedAt),createdToCompletionMinutes:minutes(plan.createdAt,plan.completedAt)},health:{status,taskCount,scheduledTaskCount:taskCount-unscheduled,unscheduledTaskCount:unscheduled,overdueTaskCount:overdue,blockedTaskCount:blocked,completedOnTimeCount:count('COMPLETED_ON_TIME'),completedLateCount:late,unresolvedDependencyCount,reasons},tasks:presentationTasks,tasksTruncated:taskCount>presentationTaskLimit};},{isolationLevel:Prisma.TransactionIsolationLevel.RepeatableRead});
}
