import { createHash } from 'node:crypto';
import { z } from 'zod';
import prisma from '../../lib/prisma';
import { ExternalObservationType, ObservationQualityState, ObservationSourceType, ObservationValidationState, Prisma, SystemRole } from '../../generated/prisma';
import type { OrganizationalPrincipal } from '../../security/organizational-scope';
import { appendIntegrityEvent, integrityTextDigest } from '../integrity/integrity.service';

const common=z.object({sourceId:z.string().uuid(),sourceRecordId:z.string().trim().min(1).max(200),sourceVersion:z.string().trim().min(1).max(80),observationType:z.nativeEnum(ExternalObservationType),schemaVersion:z.string().trim().min(1).max(80),observedAt:z.coerce.date(),assetId:z.string().uuid().optional(),caseId:z.string().uuid().optional(),departmentId:z.string().uuid().optional(),jurisdictionId:z.string().uuid().optional(),normalizedData:z.record(z.unknown()),sourceMetadata:z.record(z.unknown()).default({})});
const weather=z.object({temperatureC:z.number().min(-100).max(100).optional(),rainfallMm:z.number().nonnegative().optional(),windSpeedKph:z.number().nonnegative().optional(),weatherCondition:z.string().max(100).optional()}).refine(v=>Object.keys(v).length>0);
const traffic=z.object({estimatedVolume:z.number().int().nonnegative().optional(),congestionLevel:z.enum(['LOW','MODERATE','HIGH','CRITICAL']).optional()}).refine(v=>Object.keys(v).length>0);
const sensor=z.object({metric:z.string().trim().min(1).max(100),value:z.number(),unit:z.string().trim().min(1).max(40)});
const generic=z.record(z.union([z.string(),z.number(),z.boolean(),z.null()])).refine(v=>Object.keys(v).length>0);
const canonical=(v:unknown):string=>Array.isArray(v)?`[${v.map(canonical).join(',')}]`:v&&typeof v==='object'?`{${Object.entries(v as Record<string,unknown>).sort(([a],[b])=>a.localeCompare(b)).map(([k,x])=>`${JSON.stringify(k)}:${canonical(x)}`).join(',')}}`:JSON.stringify(v);
export class ObservationError extends Error{constructor(public code:string,public status=400){super(code)}}
type ObservationActor=OrganizationalPrincipal|string;
const actor=(value:ObservationActor)=>typeof value==='string'?{id:value,role:SystemRole.SYSTEM_ADMIN}:value;

export async function ingestObservation(raw:unknown,actorValue:ObservationActor){
 const input=common.parse(raw);if(input.observedAt.getTime()>Date.now()+5*60_000)throw new ObservationError('OBSERVED_AT_IN_FUTURE');
 const normalized=(input.observationType===ExternalObservationType.WEATHER?weather:input.observationType===ExternalObservationType.TRAFFIC?traffic:input.observationType===ExternalObservationType.SENSOR?sensor:generic).parse(input.normalizedData);
 let fingerprint='';
 try{return await prisma.$transaction(async tx=>{const source=await tx.observationSource.findUnique({where:{id:input.sourceId}});if(!source)throw new ObservationError('OBSERVATION_SOURCE_NOT_FOUND',404);if(!source.isActive)throw new ObservationError('OBSERVATION_SOURCE_INACTIVE',409);
  let asset=input.assetId?await tx.asset.findUnique({where:{id:input.assetId}}):null;let targetCase=input.caseId?await tx.case.findUnique({where:{id:input.caseId},include:{asset:true}}):null;if(input.assetId&&!asset)throw new ObservationError('ASSET_NOT_FOUND',404);if(input.caseId&&!targetCase)throw new ObservationError('CASE_NOT_FOUND',404);if(targetCase&&asset&&targetCase.assetId!==asset.id)throw new ObservationError('CASE_ASSET_MISMATCH');if(targetCase&&!asset)asset=targetCase.asset;const departmentId=asset?.departmentId??input.departmentId,jurisdictionId=asset?.jurisdictionId??input.jurisdictionId;if(!departmentId||!jurisdictionId)throw new ObservationError('ORGANIZATIONAL_SCOPE_REQUIRED');const jurisdiction=await tx.jurisdiction.findUnique({where:{id:jurisdictionId}});if(!jurisdiction||jurisdiction.departmentId!==departmentId)throw new ObservationError('ORGANIZATIONAL_SCOPE_INVALID');if(source.departmentId&&(source.departmentId!==departmentId||(source.jurisdictionId&&source.jurisdictionId!==jurisdictionId)))throw new ObservationError('SOURCE_SCOPE_MISMATCH');
  const material={sourceId:input.sourceId,sourceRecordId:input.sourceRecordId,sourceVersion:input.sourceVersion,observationType:input.observationType,schemaVersion:input.schemaVersion,observedAt:input.observedAt.toISOString(),assetId:asset?.id??null,caseId:targetCase?.id??null,departmentId,jurisdictionId,normalizedData:normalized,sourceMetadata:input.sourceMetadata};fingerprint=`sha256:${createHash('sha256').update(canonical(material)).digest('hex')}`;const existing=await tx.externalObservation.findUnique({where:{sourceId_sourceRecordId:{sourceId:input.sourceId,sourceRecordId:input.sourceRecordId}}});if(existing){if(existing.fingerprint!==fingerprint)throw new ObservationError('OBSERVATION_IDEMPOTENCY_CONFLICT',409);return{observation:existing,created:false};}
  const observation=await tx.externalObservation.create({data:{...material,observedAt:input.observedAt,normalizedData:normalized as Prisma.InputJsonValue,sourceMetadata:input.sourceMetadata as Prisma.InputJsonValue,qualityState:ObservationQualityState.VALID,validationState:ObservationValidationState.ACCEPTED,fingerprint,ingestedById:actor(actorValue).id}});
  await appendIntegrityEvent(tx,{eventType:'EXTERNAL_OBSERVATION_INGESTED',sourceEventKey:`EXTERNAL_OBSERVATION:${observation.id}`,resourceType:'ExternalObservation',resourceId:observation.id,actor:actor(actorValue),departmentId,jurisdictionId,occurredAt:observation.ingestedAt,facts:{sourceId:observation.sourceId,sourceRecordIdDigest:integrityTextDigest(observation.sourceRecordId),sourceVersion:observation.sourceVersion,observationType:observation.observationType,schemaVersion:observation.schemaVersion,observedAt:observation.observedAt.toISOString(),assetId:observation.assetId,caseId:observation.caseId,qualityState:observation.qualityState,validationState:observation.validationState,fingerprint:observation.fingerprint}});return{observation,created:true};
 },{isolationLevel:Prisma.TransactionIsolationLevel.Serializable});}catch(error){if(error instanceof Prisma.PrismaClientKnownRequestError&&error.code==='P2002'){const winner=await prisma.externalObservation.findUnique({where:{sourceId_sourceRecordId:{sourceId:input.sourceId,sourceRecordId:input.sourceRecordId}}});if(winner?.fingerprint===fingerprint)return{observation:winner,created:false};throw new ObservationError('OBSERVATION_IDEMPOTENCY_CONFLICT',409);}throw error;}
}

export const sourceCreateSchema=z.object({sourceCode:z.string().trim().min(1).max(80).transform(v=>v.toUpperCase()),versionNumber:z.number().int().positive(),name:z.string().trim().min(1).max(160),sourceType:z.nativeEnum(ObservationSourceType),providerReference:z.string().trim().min(1).max(240),description:z.string().trim().max(1000).optional(),contractVersion:z.string().trim().min(1).max(80),provenanceMetadata:z.record(z.unknown()).default({}),departmentId:z.string().uuid().nullable().optional(),jurisdictionId:z.string().uuid().nullable().optional()});
export async function registerObservationSource(raw:unknown,principal:OrganizationalPrincipal){const input=sourceCreateSchema.parse(raw);if(input.jurisdictionId){const jurisdiction=await prisma.jurisdiction.findUnique({where:{id:input.jurisdictionId}});if(!jurisdiction||jurisdiction.departmentId!==input.departmentId)throw new ObservationError('SOURCE_SCOPE_INVALID');}return prisma.$transaction(async tx=>{const created=await tx.observationSource.create({data:{...input,provenanceMetadata:input.provenanceMetadata as Prisma.InputJsonValue,createdById:principal.id}});await appendIntegrityEvent(tx,{eventType:'OBSERVATION_SOURCE_REGISTERED',sourceEventKey:`OBSERVATION_SOURCE:${created.id}`,resourceType:'ObservationSource',resourceId:created.id,actor:principal,departmentId:created.departmentId,jurisdictionId:created.jurisdictionId,occurredAt:created.createdAt,facts:{sourceCode:created.sourceCode,versionNumber:created.versionNumber,sourceType:created.sourceType,providerReferenceDigest:integrityTextDigest(created.providerReference),contractVersion:created.contractVersion,isActive:created.isActive}});return created;});}
export async function deactivateObservationSource(id:string,reason:string,principal:OrganizationalPrincipal){return prisma.$transaction(async tx=>{const found=await tx.observationSource.findUnique({where:{id}});if(!found)throw new ObservationError('OBSERVATION_SOURCE_NOT_FOUND',404);if(!found.isActive)throw new ObservationError('OBSERVATION_SOURCE_INACTIVE',409);const value=await tx.observationSource.update({where:{id},data:{isActive:false,deactivatedAt:new Date(),deactivatedById:principal.id,deactivationReason:reason}});await appendIntegrityEvent(tx,{eventType:'OBSERVATION_SOURCE_DEACTIVATED',sourceEventKey:`OBSERVATION_SOURCE_DEACTIVATED:${id}`,resourceType:'ObservationSource',resourceId:id,actor:principal,departmentId:value.departmentId,jurisdictionId:value.jurisdictionId,occurredAt:value.deactivatedAt!,facts:{sourceCode:value.sourceCode,versionNumber:value.versionNumber,isActive:value.isActive,deactivatedById:principal.id,deactivationReasonDigest:integrityTextDigest(value.deactivationReason)}});return value;});}
