import{describe,expect,it}from'vitest';import{analyzeConditionHistory,type ConditionSourceObservation}from'../src/modules/assets/condition-history.service';
const observation=(id:string,date:string,score:number|null,overrides:Partial<ConditionSourceObservation>={}):ConditionSourceObservation=>({inspectionId:id,caseId:`case-${id}`,inspectionDate:new Date(date),createdAt:new Date(date),structuralCondition:'FAIR',crackSeverity:'MODERATE',corrosionLevel:'MODERATE',trafficImportance:'HIGH',hospitalRoute:false,weatherRisk:'LOW',heavyRainExpected:false,estimatedDailyUsers:1000,assessment:score===null?null:{id:`risk-${id}`,riskScore:score,riskLevel:score>=75?'VERY_HIGH':score>=50?'HIGH':'MODERATE',priorityLevel:score>=75?'VERY_HIGH':score>=50?'HIGH':'MEDIUM',assessmentVersion:'ODYSSEY_RISK_V1',createdAt:new Date(date)},...overrides});
describe('deterministic longitudinal condition analytics',()=>{
 it('returns insufficient readiness and trend for no observations',()=>{const value=analyzeConditionHistory([],false);expect(value).toMatchObject({observationCount:0,latestVsPrevious:null,trend:{state:'INSUFFICIENT_DATA'},readiness:{state:'INSUFFICIENT'}})});
 it('treats one observation as a baseline without a fake delta',()=>{const value=analyzeConditionHistory([observation('a','2026-01-01',40)],true);expect(value.latestVsPrevious).toBeNull();expect(value.trend.state).toBe('INSUFFICIENT_DATA');expect(value.readiness.reasons[0]).toMatch(/baseline/)});
 it('classifies worsening, improving, stable and mixed histories transparently',()=>{const early=observation('a','2026-01-01',40,{structuralCondition:'FAIR',crackSeverity:'MODERATE'});expect(analyzeConditionHistory([early,observation('b','2026-03-01',80,{structuralCondition:'POOR',crackSeverity:'SEVERE'})],true).trend.state).toBe('WORSENING');expect(analyzeConditionHistory([observation('a','2026-01-01',80,{structuralCondition:'POOR'}),observation('b','2026-03-01',40,{structuralCondition:'FAIR'})],true).trend.state).toBe('IMPROVING');expect(analyzeConditionHistory([early,observation('b','2026-03-01',40)],true).trend.state).toBe('STABLE');expect(analyzeConditionHistory([early,observation('b','2026-03-01',70,{structuralCondition:'GOOD'})],true).trend.state).toBe('MIXED')});
 it('reports missing values and assessment mismatch without defaults',()=>{const value=analyzeConditionHistory([observation('a','2026-01-01',40,{estimatedDailyUsers:null}),observation('b','2026-03-01',null)],false);expect(value.completeness.fields.estimatedDailyUsers).toEqual({present:1,missing:1,status:'PARTIAL'});expect(value.pairedAssessmentCount).toBe(1);expect(value.latestVsPrevious?.riskScoreDelta).toBeNull();expect(value.readiness.reasons.join(' ')).toMatch(/do not have a paired risk assessment|does not have a paired risk assessment/)});
 it('uses inspection date and stable ID tie-break ordering',()=>{const value=analyzeConditionHistory([observation('z','2026-01-01',60),observation('a','2026-01-01',40)],true);expect(value.latestVsPrevious).toMatchObject({previousInspectionId:'a',latestInspectionId:'z',riskScoreDelta:20})});
 it('requires three paired observations spanning thirty days for sufficient readiness',()=>{const value=analyzeConditionHistory([observation('a','2026-01-01',40),observation('b','2026-02-01',45),observation('c','2026-03-01',50)],true);expect(value.readiness.state).toBe('SUFFICIENT_FOR_TREND')});
});
