import express from'express';import request from'supertest';import{SignJWT}from'jose';import{beforeEach,describe,expect,it,vi}from'vitest';import{getAuthConfig}from'../src/config/auth';
const mocks=vi.hoisted(()=>({user:vi.fn(),asset:vi.fn(),inspections:vi.fn()}));vi.mock('../src/lib/prisma',()=>({default:{user:{findUnique:mocks.user},asset:{findUnique:mocks.asset},inspection:{findMany:mocks.inspections}}}));import routes from'../src/modules/assets/asset.routes';
const app=express();app.use(express.json());app.use('/api/v1/assets',routes);async function auth(role='OFFICER',departmentId='dep-a',jurisdictionId='jur-a'){const user={id:`u-${role}`,role,status:'ACTIVE',departmentId,jurisdictionId};mocks.user.mockResolvedValue(user);const c=getAuthConfig();return`Bearer ${await new SignJWT({}).setProtectedHeader({alg:'HS256'}).setSubject(user.id).setIssuer(c.issuer).setAudience(c.audience).setIssuedAt().setExpirationTime('5m').sign(c.secret)}`}
const asset={id:'asset-a',assetCode:'BR-1',name:'Bridge',assetType:'BRIDGE',departmentId:'dep-a',jurisdictionId:'jur-a',latitude:18,longitude:73};
beforeEach(()=>{vi.clearAllMocks();mocks.asset.mockResolvedValue(asset);mocks.inspections.mockResolvedValue([])});
describe('GET asset condition history',()=>{
 it.each(['OFFICER','AUDITOR','POLICY_ADMIN','SYSTEM_ADMIN'])('allows authenticated %s reads under existing asset visibility',(async role=>{const response=await request(app).get('/api/v1/assets/asset-a/condition-history').set('Authorization',await auth(role)).expect(200);expect(response.body.data.summary.observationCount).toBe(0);expect(mocks.inspections).toHaveBeenCalledWith(expect.objectContaining({where:{case:{assetId:'asset-a'}},take:101}))}));
 it('uses both scope dimensions and returns indistinguishable 404 for missing or cross-scope assets',async()=>{mocks.asset.mockResolvedValue(null);const response=await request(app).get('/api/v1/assets/asset-x/condition-history').set('Authorization',await auth()).expect(404);expect(response.body.error.code).toBe('ASSET_NOT_FOUND');expect(mocks.asset).toHaveBeenCalledWith({where:{id:'asset-x',AND:[{departmentId:'dep-a',jurisdictionId:'jur-a'}]}});expect(mocks.inspections).not.toHaveBeenCalled()});
 it('keeps SYSTEM_ADMIN lookup global',async()=>{await request(app).get('/api/v1/assets/asset-a/condition-history').set('Authorization',await auth('SYSTEM_ADMIN')).expect(200);expect(mocks.asset).toHaveBeenCalledWith({where:{id:'asset-a',AND:[{}]}})});
 it('aggregates multiple cases, pairs only real assessments and exposes provenance',async()=>{mocks.inspections.mockResolvedValue([{id:'i2',caseId:'case-2',inspectionDate:new Date('2026-02-01'),createdAt:new Date('2026-02-01'),structuralCondition:'POOR',crackSeverity:'SEVERE',corrosionLevel:'HIGH',trafficImportance:'HIGH',hospitalRoute:true,weatherRisk:'HIGH',heavyRainExpected:true,estimatedDailyUsers:null,riskAssessments:[]},{id:'i1',caseId:'case-1',inspectionDate:new Date('2026-01-01'),createdAt:new Date('2026-01-01'),structuralCondition:'FAIR',crackSeverity:'MODERATE',corrosionLevel:'MODERATE',trafficImportance:'HIGH',hospitalRoute:true,weatherRisk:'LOW',heavyRainExpected:false,estimatedDailyUsers:1000,riskAssessments:[{id:'r1',riskScore:40,riskLevel:'MODERATE',priorityLevel:'MEDIUM',assessmentVersion:'V1',createdAt:new Date('2026-01-01')}]}]);const response=await request(app).get('/api/v1/assets/asset-a/condition-history').set('Authorization',await auth()).expect(200);expect(response.body.data.observations.map((x:{caseId:string})=>x.caseId)).toEqual(['case-2','case-1']);expect(response.body.data.summary.pairedAssessmentCount).toBe(1);expect(response.body.data.provenance.sourceRiskAssessmentIds).toEqual(['r1'])});
});
