import express from 'express'; import request from 'supertest'; import { beforeEach, describe, expect, it, vi } from 'vitest'; import { SignJWT } from 'jose'; import { getAuthConfig } from '../src/config/auth';
const mocks = vi.hoisted(() => ({ user: vi.fn(), prepare: vi.fn(), list: vi.fn(), get: vi.fn() }));
vi.mock('../src/lib/prisma', () => ({ default: { user: { findUnique: mocks.user } } }));
vi.mock('../src/modules/decision-packages/decision-package.service', () => { class DecisionPackageError extends Error { constructor(public code: string, public status: number, message: string, public reasons?: any[]) { super(message); } } return { DecisionPackageError, prepareDecisionPackage: mocks.prepare, listDecisionPackages: mocks.list, getDecisionPackage: mocks.get }; });
import routes from '../src/modules/decision-packages/decision-package.routes'; const app = express(); app.use(express.json()); app.use('/api/v1', routes); const caseId = '11111111-1111-4111-8111-111111111111', packageId = '22222222-2222-4222-8222-222222222222';
async function auth(role: string) { const id = `user-${role}`; mocks.user.mockResolvedValue({ id, role, status: 'ACTIVE', departmentId: 'dep', jurisdictionId: 'jur' }); const c = getAuthConfig(); return `Bearer ${await new SignJWT({}).setProtectedHeader({ alg: 'HS256' }).setSubject(id).setIssuer(c.issuer).setAudience(c.audience).setIssuedAt().setExpirationTime('5m').sign(c.secret)}`; }
describe('Decision Package routes', () => { beforeEach(() => { vi.clearAllMocks(); mocks.prepare.mockResolvedValue({ id: 'package', reused: false }); mocks.list.mockResolvedValue([]); mocks.get.mockResolvedValue({ id: 'package' }); });
  it('requires authentication', async () => { await request(app).post(`/api/v1/cases/${caseId}/decision-packages`).expect(401); await request(app).get(`/api/v1/cases/${caseId}/decision-packages`).expect(401); });
  it.each(['OFFICER', 'SYSTEM_ADMIN'])('allows %s to prepare without a readiness bypass', async (role) => { await request(app).post(`/api/v1/cases/${caseId}/decision-packages?force=true`).set('Authorization', await auth(role)).send({ skipReadiness: true, packageVersion: 99, preparedById: 'forged' }).expect(201); expect(mocks.prepare).toHaveBeenCalledWith(caseId, expect.objectContaining({ role })); });
  it.each(['OFFICER', 'AUDITOR', 'SYSTEM_ADMIN'])('allows scoped %s package reads', async (role) => { const header = await auth(role); await request(app).get(`/api/v1/cases/${caseId}/decision-packages`).set('Authorization', header).expect(200); await request(app).get(`/api/v1/cases/${caseId}/decision-packages/${packageId}`).set('Authorization', header).expect(200); });
  it('keeps AUDITOR read-only', async () => { await request(app).post(`/api/v1/cases/${caseId}/decision-packages`).set('Authorization', await auth('AUDITOR')).expect(403); });
  it('denies POLICY_ADMIN operational access', async () => { const header = await auth('POLICY_ADMIN'); await request(app).post(`/api/v1/cases/${caseId}/decision-packages`).set('Authorization', header).expect(403); await request(app).get(`/api/v1/cases/${caseId}/decision-packages`).set('Authorization', header).expect(403); });
  it('returns controlled invalid UUID responses', async () => { await request(app).get('/api/v1/cases/not-a-uuid/decision-packages').set('Authorization', await auth('OFFICER')).expect(400); });
});
