import{describe,expect,it,vi}from'vitest';import{assertGeoMutationAllowed,createDemoGeoPlan,DEMO_ASSET_COORDINATES,DEMO_PUBLIC_REPORT_COORDINATES,runDemoGeo,type DemoGeoStore,type GeoRecord}from'../scripts/enrich-demo-geolocation';
const assets=():GeoRecord[]=>DEMO_ASSET_COORDINATES.map((x,i)=>({id:`a${i}`,assetCode:x.assetCode,name:x.name,assetType:x.assetType,latitude:x.assetCode==='BR-101'?x.latitude:null,longitude:x.assetCode==='BR-101'?x.longitude:null,conditionStatus:'UNCHANGED'}));
const reports=():GeoRecord[]=>DEMO_PUBLIC_REPORT_COORDINATES.map((x,i)=>({id:`r${i}`,reportNumber:`JNV-PUB-${i}`,title:x.title,locationText:x.locationText,category:x.category,latitude:null,longitude:null,status:i<2?'SUBMITTED':'UNDER_REVIEW',departmentId:i===3?'d':null,assetId:i===3?'a7':null,createdCaseId:i===4?'c9':null,reporterName:'must-not-be-output'}));
function store(assetRows=assets(),reportRows=reports()){const apply=vi.fn(async(updates)=>{for(const update of updates){const rows=update.kind==='asset'?assetRows:reportRows,row=rows.find(x=>x.id===update.id)!;row.latitude=update.latitude;row.longitude=update.longitude;}});return{value:{listAssets:async()=>assetRows,listReports:async()=>reportRows,apply} satisfies DemoGeoStore,apply,assetRows,reportRows};}
describe('controlled synthetic demo geolocation',()=>{
 it('uses a stable bounded manifest',()=>{expect(DEMO_ASSET_COORDINATES.map(x=>x.assetCode)).toEqual(['BR-101','BR-204','FL-301','RD-410','BR-212','RD-118','FL-509','RD-330']);expect(DEMO_PUBLIC_REPORT_COORDINATES).toHaveLength(6);for(const x of [...DEMO_ASSET_COORDINATES,...DEMO_PUBLIC_REPORT_COORDINATES]){expect(x.latitude).toBeGreaterThan(18.4);expect(x.latitude).toBeLessThan(18.6);expect(x.longitude).toBeGreaterThan(73.7);expect(x.longitude).toBeLessThan(74);}});
 it('plans seven Assets, six reports and reuses compatible BR-101',()=>{const plan=createDemoGeoPlan(assets(),reports());expect(plan).toMatchObject({assetsToEnrich:7,reportsToEnrich:6,alreadyMapped:1,conflicts:0});expect(plan.actions.find(x=>x.label.startsWith('BR-101'))?.action).toBe('REUSE');});
 it('dry-run performs zero mutation and never prints reporter PII',async()=>{const fixture=store(),lines:string[]=[];await runDemoGeo(fixture.value,{dryRun:true,write:x=>lines.push(x)});expect(fixture.apply).not.toHaveBeenCalled();expect(lines.join('\n')).not.toMatch(/must-not-be-output|reporterName/);});
 it('touches only known manifest records and only coordinate fields',async()=>{const fixture=store([...assets(),{id:'unknown-a',assetCode:'REAL-1',name:'Unknown',assetType:'ROAD',latitude:null,longitude:null}], [...reports(),{id:'unknown-r',title:'Unknown report',locationText:'Elsewhere',category:'OTHER',latitude:null,longitude:null,status:'SUBMITTED'}]);const before=structuredClone({assets:fixture.assetRows,reports:fixture.reportRows});await runDemoGeo(fixture.value,{dryRun:false,env:{NODE_ENV:'test'},write:()=>{}});const updates=fixture.apply.mock.calls[0][0];expect(updates).toHaveLength(13);expect(updates.every((x:any)=>Object.keys(x).sort().join(',')==='id,kind,latitude,longitude')).toBe(true);expect(fixture.assetRows.at(-1)).toEqual(before.assets.at(-1));expect(fixture.reportRows.at(-1)).toEqual(before.reports.at(-1));for(let i=0;i<reports().length;i++){expect(fixture.reportRows[i].status).toBe(before.reports[i].status);expect(fixture.reportRows[i].departmentId).toBe(before.reports[i].departmentId);expect(fixture.reportRows[i].assetId).toBe(before.reports[i].assetId);expect(fixture.reportRows[i].createdCaseId).toBe(before.reports[i].createdCaseId);}});
 it('stops safely on conflicting existing coordinates',async()=>{const rows=assets();rows[1].latitude=18.5;rows[1].longitude=73.8;const fixture=store(rows);await expect(runDemoGeo(fixture.value,{dryRun:false,env:{NODE_ENV:'test'},write:()=>{}})).rejects.toThrow(/conflict/i);expect(fixture.apply).not.toHaveBeenCalled();});
 it('reports missing expected records as skipped without enriching unknown records',()=>{const plan=createDemoGeoPlan(assets().slice(0,7),reports().slice(0,5));expect(plan.skipped).toBe(2);expect(plan.conflicts).toBe(0);});
 it('rejects duplicate controlled identifiers as conflicts',()=>{const rows=assets();rows.push({...rows[0],id:'duplicate'});expect(createDemoGeoPlan(rows,reports()).conflicts).toBe(1);});
 it('refuses production mutation but permits production dry-run',()=>{expect(()=>assertGeoMutationAllowed({NODE_ENV:'production'},false)).toThrow(/DEMO_BOOTSTRAP_FORBIDDEN_IN_PRODUCTION/);expect(()=>assertGeoMutationAllowed({NODE_ENV:'production'},true)).not.toThrow();});
 it('is idempotent after one successful enrichment',async()=>{const fixture=store();await runDemoGeo(fixture.value,{dryRun:false,env:{NODE_ENV:'test'},write:()=>{}});const second=createDemoGeoPlan(fixture.assetRows,fixture.reportRows);expect(second).toMatchObject({assetsToEnrich:0,reportsToEnrich:0,alreadyMapped:14,conflicts:0});});
 it('has no Case or workflow mutation capability',()=>{const fixture=store();expect(Object.keys(fixture.value).sort()).toEqual(['apply','listAssets','listReports']);});
});
