import { describe, expect, it } from 'vitest';
import { ExecutionTaskStatus } from '../src/generated/prisma';
import { derivePlanStatus, executionGovernanceMode, governedExecutableActions, hasClientActorFields } from '../src/modules/execution/execution.service';
describe('execution state rules', () => {
  it('derives plan states', () => { expect(derivePlanStatus([{status:ExecutionTaskStatus.PENDING,isMandatory:true}])).toBe('PLANNED'); expect(derivePlanStatus([{status:ExecutionTaskStatus.ASSIGNED,isMandatory:true}])).toBe('IN_PROGRESS'); expect(derivePlanStatus([{status:ExecutionTaskStatus.COMPLETION_SUBMITTED,isMandatory:true},{status:ExecutionTaskStatus.VERIFIED,isMandatory:true}])).toBe('VERIFICATION_PENDING'); expect(derivePlanStatus([{status:ExecutionTaskStatus.VERIFIED,isMandatory:true}])).toBe('COMPLETED'); });
  it('mandatory cancellation prevents completion', () => expect(derivePlanStatus([{status:ExecutionTaskStatus.CANCELLED,isMandatory:true}])).toBe('IN_PROGRESS'));
  it('active optional work delays completion without becoming mandatory', () => expect(derivePlanStatus([{status:ExecutionTaskStatus.VERIFIED,isMandatory:true},{status:ExecutionTaskStatus.PENDING,isMandatory:false}])).toBe('VERIFICATION_PENDING'));
  it.each([ExecutionTaskStatus.VERIFIED, ExecutionTaskStatus.CANCELLED])('optional terminal state %s permits completion', status => expect(derivePlanStatus([{status:ExecutionTaskStatus.VERIFIED,isMandatory:true},{status,isMandatory:false}])).toBe('COMPLETED'));
  it.each(['createdById','assignedById','submittedById','completionSubmittedById','verifiedById','cancelledById'])('rejects actor field %s', f=>expect(hasClientActorFields({[f]:'u'})).toBe(true));
  it('preserves legacy execution and blocks governed plans from legacy code-only templates',()=>{expect(executionGovernanceMode('LEGACY',null)).toBe('LEGACY');expect(executionGovernanceMode('GOVERNED_POLICY','package')).toBe('GOVERNED');expect(executionGovernanceMode('GOVERNED_ENGINEERING_NO_POLICY','package')).toBe('GOVERNED');});
  it('rejects inconsistent provenance combinations',()=>{expect(executionGovernanceMode('LEGACY','package')).toBe('INVALID');expect(executionGovernanceMode('GOVERNED_POLICY',null)).toBe('INVALID');});
  it('executes only mandatory and recommended exact action versions',()=>{const action=(classification:string,id:string,code:string)=>({actionId:id,actionCode:code,actionVersion:3,classification});const ids=['11111111-1111-4111-8111-111111111111','22222222-2222-4222-8222-222222222222','33333333-3333-4333-8333-333333333333','44444444-4444-4444-8444-444444444444'];const value={packageId:'pkg',packageVersion:1,MANDATORY:[action('MANDATORY',ids[0],'ACT_M')],RECOMMENDED:[action('RECOMMENDED',ids[1],'ACT_R')],OPTIONAL:[action('OPTIONAL',ids[2],'ACT_O')],PROHIBITED:[action('PROHIBITED',ids[3],'ACT_P')],ENGINEERING_RECOMMENDED:[]};expect(governedExecutableActions(value,['ACT_M','ACT_R']).executable.map(item=>item.actionCode)).toEqual(['ACT_M','ACT_R']);expect(()=>governedExecutableActions(value,['ACT_M','ACT_R','ACT_O'])).toThrow();expect(()=>governedExecutableActions(value,['ACT_M','ACT_P'])).toThrow();});
});
