import { beforeEach, describe, expect, it, vi } from 'vitest';
import { ExecutionTaskStatus } from '../src/generated/prisma';
const m=vi.hoisted(()=>({plan:vi.fn(),task:vi.fn(),taskMany:vi.fn(),revision:vi.fn(),planUpdate:vi.fn(),taskUpdate:vi.fn(),deps:vi.fn(),depCreate:vi.fn(),depDelete:vi.fn()}));
vi.mock('../src/lib/prisma',()=>{const tx={executionPlan:{findFirst:m.plan,update:m.planUpdate},executionTask:{findFirst:m.task,findMany:m.taskMany,update:m.taskUpdate},executionScheduleRevision:{create:m.revision},executionTaskDependency:{findMany:m.deps,create:m.depCreate,deleteMany:m.depDelete}};return{default:{...tx,$transaction:vi.fn((f:any)=>f(tx))}}});
import { addDependency, analyzeSchedule, taskScheduleStatus, updatePlanSchedule, updateTaskSchedule } from '../src/modules/execution/execution-schedule.service';
import { unmetDependencyMessage } from '../src/modules/execution/execution.service';
const principal:any={id:'u',role:'OFFICER',status:'ACTIVE',departmentId:'d',jurisdictionId:'j'},start=new Date('2026-08-24T09:00:00Z'),end=new Date('2026-08-24T17:00:00Z');
beforeEach(()=>{vi.clearAllMocks();m.plan.mockResolvedValue({id:'p',plannedStartAt:null,plannedEndAt:null,tasks:[]});m.planUpdate.mockResolvedValue({id:'p'});m.task.mockResolvedValue({id:'t',executionPlanId:'p',plannedStartAt:null,plannedEndAt:null,executionPlan:{id:'p',plannedStartAt:start,plannedEndAt:end}});m.taskMany.mockResolvedValue([]);m.taskUpdate.mockResolvedValue({id:'t'});m.deps.mockResolvedValue([]);m.depCreate.mockResolvedValue({id:'dep'});m.revision.mockResolvedValue({})});
describe('governed execution scheduling',()=>{
  it('records attributable plan and task schedule revisions',async()=>{await updatePlanSchedule('p',{plannedStartAt:start,plannedEndAt:end,reason:'Approved sequence'},principal);expect(m.revision).toHaveBeenCalledWith({data:expect.objectContaining({executionPlanId:'p',changedById:'u',changeReason:'Approved sequence'})});await updateTaskSchedule('t',{plannedStartAt:start,plannedEndAt:end,reason:'Task window'},principal);expect(m.revision).toHaveBeenLastCalledWith({data:expect.objectContaining({executionTaskId:'t',changedById:'u'})})});
  it('rejects invalid ranges and task dates outside the plan',async()=>{await expect(updatePlanSchedule('p',{plannedStartAt:end,plannedEndAt:start,reason:'x'},principal)).rejects.toMatchObject({code:'INVALID_SCHEDULE_RANGE'});await expect(updateTaskSchedule('t',{plannedStartAt:new Date('2026-08-23'),plannedEndAt:end,reason:'x'},principal)).rejects.toMatchObject({code:'TASK_SCHEDULE_OUTSIDE_PLAN'})});
  it('rejects self, cross-plan, direct and multi-hop cycles',async()=>{await expect(addDependency('t','t',principal)).rejects.toMatchObject({code:'SELF_DEPENDENCY'});m.task.mockResolvedValueOnce({id:'t',executionPlanId:'p'}).mockResolvedValueOnce(null);await expect(addDependency('t','other',principal)).rejects.toMatchObject({code:'DEPENDENCY_TASK_NOT_FOUND'});m.task.mockResolvedValueOnce({id:'a',executionPlanId:'p'}).mockResolvedValueOnce({id:'b'});m.deps.mockResolvedValue([{predecessorTaskId:'a',dependentTaskId:'c'},{predecessorTaskId:'c',dependentTaskId:'b'}]);await expect(addDependency('a','b',principal)).rejects.toMatchObject({code:'DEPENDENCY_CYCLE'})});
  it('requires every predecessor verified and treats cancellation as unmet',()=>{expect(unmetDependencyMessage([])).toBeNull();expect(unmetDependencyMessage([{predecessorTask:{id:'a',status:ExecutionTaskStatus.CANCELLED}},{predecessorTask:{id:'b',status:ExecutionTaskStatus.IN_PROGRESS}}])).toContain('a (CANCELLED), b (IN_PROGRESS)')});
  it('classifies schedule variance deterministically',()=>{expect(taskScheduleStatus({plannedStartAt:start,plannedEndAt:end},new Date('2026-08-24T08:00Z'))).toBe('NOT_STARTED_ON_SCHEDULE');expect(taskScheduleStatus({plannedStartAt:start,plannedEndAt:end},new Date('2026-08-24T18:00Z'))).toBe('OVERDUE');expect(taskScheduleStatus({plannedStartAt:start,plannedEndAt:end,startedAt:new Date('2026-08-24T10:00Z'),verifiedAt:new Date('2026-08-24T18:00Z')},end)).toBe('COMPLETED_LATE');expect(taskScheduleStatus({},end)).toBe('UNSCHEDULED')});
  it('summarizes mixed plans and exact observed cycle times',async()=>{m.plan.mockResolvedValue({id:'p',status:'IN_PROGRESS',createdAt:new Date('2026-08-24T07:00Z'),plannedStartAt:start,plannedEndAt:end,completedAt:null,scheduleRevisions:[]});m.taskMany.mockResolvedValue([{id:'a',sequenceNumber:1,status:ExecutionTaskStatus.IN_PROGRESS,plannedStartAt:start,plannedEndAt:new Date('2026-08-24T10:00Z'),assignedAt:new Date('2026-08-24T08:00Z'),startedAt:new Date('2026-08-24T09:00Z'),completionSubmittedAt:null,verifiedAt:null,dependencies:[]},{id:'b',sequenceNumber:2,status:ExecutionTaskStatus.BLOCKED,plannedStartAt:null,plannedEndAt:null,assignedAt:null,startedAt:null,completionSubmittedAt:null,verifiedAt:null,dependencies:[] }]);const result=await analyzeSchedule('p',principal,new Date('2026-08-24T11:00Z'));expect(result.health).toMatchObject({status:'OVERDUE',overdueTaskCount:1,blockedTaskCount:1,unscheduledTaskCount:1});expect(result.tasks[0].cycleTimes.assignmentToStartMinutes).toBe(60);expect(result.tasks[1].cycleTimes.assignmentToStartMinutes).toBeNull()});
  it('evaluates every task across the 500-row boundary while bounding presentation',async()=>{const scheduled=(index:number)=>({id:`t-${String(index).padStart(4,'0')}`,sequenceNumber:index,status:ExecutionTaskStatus.ASSIGNED,plannedStartAt:start,plannedEndAt:end,assignedAt:null,startedAt:null,completionSubmittedAt:null,verifiedAt:null,dependencies:[]});const rows=Array.from({length:503},(_,index)=>scheduled(index+1));rows[500]={...scheduled(501),status:ExecutionTaskStatus.ASSIGNED,plannedEndAt:new Date('2026-08-24T10:00Z')};rows[501]={...scheduled(502),status:ExecutionTaskStatus.BLOCKED,plannedStartAt:null,plannedEndAt:null};rows[502]={...scheduled(503),dependencies:[{predecessorTask:{id:'t-0501',sequenceNumber:501,status:ExecutionTaskStatus.ASSIGNED}}]};m.plan.mockResolvedValue({id:'p',status:'IN_PROGRESS',createdAt:new Date('2026-08-24T07:00Z'),plannedStartAt:start,plannedEndAt:end,completedAt:null,scheduleRevisions:[]});m.taskMany.mockImplementation(async({cursor}:any)=>cursor?rows.slice(500):rows.slice(0,500));const result=await analyzeSchedule('p',principal,new Date('2026-08-24T11:00Z'));expect(result.health).toMatchObject({status:'OVERDUE',taskCount:503,scheduledTaskCount:502,unscheduledTaskCount:1,overdueTaskCount:1,blockedTaskCount:1,unresolvedDependencyCount:1});expect(result.health.reasons).toEqual(expect.arrayContaining([expect.stringContaining('1 task(s) are overdue'),expect.stringContaining('1 task(s) have a recorded unresolved blocker'),expect.stringContaining('1 task(s) have no planned schedule')]));expect(result.tasks).toHaveLength(100);expect(result.tasksTruncated).toBe(true);expect(m.taskMany).toHaveBeenNthCalledWith(1,expect.objectContaining({take:500}));expect(m.taskMany).toHaveBeenNthCalledWith(2,expect.objectContaining({take:500,cursor:{id:'t-0500'},skip:1}));});
});
