import express from 'express'; import request from 'supertest'; import { SignJWT } from 'jose'; import { beforeEach,describe,expect,it,vi } from 'vitest'; import { getAuthConfig } from '../src/config/auth';
const m=vi.hoisted(()=>({user:vi.fn(),generate:vi.fn(),list:vi.fn(),get:vi.fn(),tasks:vi.fn(),eligible:vi.fn(),assign:vi.fn()}));
vi.mock('../src/lib/prisma',()=>({default:{user:{findUnique:m.user}}}));
vi.mock('../src/modules/execution/execution.service',async o=>({...await o<any>(),generateExecutionPlan:m.generate,listCaseExecutionPlans:m.list,getExecutionPlan:m.get,listExecutionTasks:m.tasks,resolveEligibleExecutionAssignees:m.eligible,assignTask:m.assign}));
import routes from '../src/modules/execution/execution.routes'; const app=express(); app.use(express.json()); app.use('/api/v1',routes);
async function auth(role='OFFICER'){m.user.mockResolvedValue({id:`user-${role}`,role,status:'ACTIVE',departmentId:'dep',jurisdictionId:'jur'});const c=getAuthConfig();return `Bearer ${await new SignJWT({}).setProtectedHeader({alg:'HS256'}).setSubject(`user-${role}`).setIssuer(c.issuer).setAudience(c.audience).setIssuedAt().setExpirationTime('5m').sign(c.secret)}`;}
beforeEach(()=>{vi.clearAllMocks();m.generate.mockResolvedValue({created:true,plan:{id:'plan'}});m.get.mockResolvedValue({id:'plan'});m.eligible.mockResolvedValue([{id:'22222222-2222-4222-8222-222222222222',name:'Asha',designation:'Engineer',employeeCode:'E-1'}]);m.assign.mockResolvedValue({id:'11111111-1111-4111-8111-111111111111',status:'ASSIGNED'});});
describe('execution routes',()=>{it('creates and idempotently returns plan',async()=>{await request(app).post('/api/v1/orps/orp/execution-plan').set('Authorization',await auth()).send({}).expect(201);expect(m.generate).toHaveBeenCalledWith('orp',expect.objectContaining({id:'user-OFFICER'}));m.generate.mockResolvedValue({created:false,plan:{id:'plan'}});await request(app).post('/api/v1/orps/orp/execution-plan').set('Authorization',await auth()).send({}).expect(200);});it('rejects actor identity',async()=>{const r=await request(app).post('/api/v1/orps/orp/execution-plan').set('Authorization',await auth()).send({createdById:'x'}).expect(400);expect(r.body.error.code).toBe('ACTOR_FIELDS_NOT_ALLOWED');});it.each(['AUDITOR','POLICY_ADMIN','SYSTEM_ADMIN'])('rejects %s mutations',async role=>{await request(app).post('/api/v1/orps/orp/execution-plan').set('Authorization',await auth(role)).send({}).expect(403);});it.each(['OFFICER','AUDITOR','POLICY_ADMIN','SYSTEM_ADMIN'])('allows %s reads',async role=>{await request(app).get('/api/v1/execution-plans/plan').set('Authorization',await auth(role)).expect(200);});});
describe('assignment routes',()=>{const task='11111111-1111-4111-8111-111111111111',candidate='22222222-2222-4222-8222-222222222222';it('lists candidates and assigns a returned officer',async()=>{const token=await auth();const listed=await request(app).get(`/api/v1/execution-tasks/${task}/eligible-assignees`).set('Authorization',token).expect(200);expect(listed.body.data[0]).toEqual({id:candidate,name:'Asha',designation:'Engineer',employeeCode:'E-1'});await request(app).patch(`/api/v1/execution-tasks/${task}/assignment`).set('Authorization',token).send({assigneeId:candidate}).expect(200);expect(m.assign).toHaveBeenCalledWith(task,candidate,expect.objectContaining({role:'OFFICER'}));});it.each(['AUDITOR','POLICY_ADMIN','SYSTEM_ADMIN'])('denies %s candidate and assignment access',async role=>{const token=await auth(role);await request(app).get(`/api/v1/execution-tasks/${task}/eligible-assignees`).set('Authorization',token).expect(403);await request(app).patch(`/api/v1/execution-tasks/${task}/assignment`).set('Authorization',token).send({assigneeId:candidate}).expect(403);});it('denies anonymous and malformed identifiers',async()=>{await request(app).get(`/api/v1/execution-tasks/${task}/eligible-assignees`).expect(401);await request(app).get('/api/v1/execution-tasks/not-a-uuid/eligible-assignees').set('Authorization',await auth()).expect(400);await request(app).patch(`/api/v1/execution-tasks/${task}/assignment`).set('Authorization',await auth()).send({assigneeId:'forged'}).expect(400);expect(m.assign).not.toHaveBeenCalled();});});
