import { beforeEach,describe,expect,it,vi } from 'vitest';
import { PriorityLevel,RiskLevel,SystemRole,UserStatus } from '../src/generated/prisma';
const m=vi.hoisted(()=>({assets:vi.fn(),cases:vi.fn(),reports:vi.fn()}));
vi.mock('../src/lib/prisma',()=>{const tx={asset:{findMany:m.assets},case:{findMany:m.cases},publicReport:{findMany:m.reports}};return{default:{$transaction:vi.fn((callback:any)=>callback(tx))}}});
import { analyzeGeospatialHotspots,centroid,coordinateState,gridCell,validCoordinate } from '../src/modules/geospatial/geospatial-hotspot.service';
const organization={id:'d',name:'Public Works'},jurisdiction={id:'j',name:'Pune Division'};
const principal:any={id:'u',role:SystemRole.OFFICER,status:UserStatus.ACTIVE,departmentId:'d',jurisdictionId:'j'};
beforeEach(()=>{vi.clearAllMocks();m.assets.mockResolvedValue([]);m.cases.mockResolvedValue([]);m.reports.mockResolvedValue([])});
describe('geospatial hotspot analytics',()=>{
 it('validates coordinates without coercing malformed values',()=>{expect(validCoordinate(18.52,73.85)).toEqual({latitude:18.52,longitude:73.85});expect(validCoordinate('18.52',73.85)).toBeNull();expect(coordinateState(null,null)).toBe('MISSING');expect(coordinateState(91,0)).toBe('INVALID');expect(validCoordinate(-90,-180)).toBeTruthy();expect(validCoordinate(90,180)).toBeTruthy();expect(validCoordinate(Number.NaN,0)).toBeNull()});
 it('uses stable grid identities, boundaries, negative coordinates and deterministic centroids',()=>{expect(gridCell({latitude:18.5201,longitude:73.8501})).toEqual(gridCell({latitude:18.5299,longitude:73.8599}));expect(gridCell({latitude:18.5299,longitude:73.8599})).not.toEqual(gridCell({latitude:18.5301,longitude:73.8601}));expect(gridCell({latitude:-0.001,longitude:-0.001}).cellId).toBe('G001:-1:-1');expect(gridCell({latitude:90,longitude:180}).cellId).toBe('G001:9000:18000');expect(centroid([{latitude:1,longitude:2},{latitude:3,longitude:4}])).toEqual({latitude:2,longitude:3})});
 it('aggregates the complete authorized dataset beyond 500 while separating reports and deduplicating assets',async()=>{const assets=Array.from({length:501},(_,index)=>({id:`a-${String(index+1).padStart(3,'0')}`,latitude:18.52,longitude:73.85,department:organization,jurisdiction}));m.assets.mockImplementation(async({cursor}:any)=>cursor?assets.slice(500):assets.slice(0,500));m.cases.mockResolvedValue([{id:'case-current',riskLevel:RiskLevel.VERY_HIGH,priorityLevel:PriorityLevel.CRITICAL,asset:{id:'a-501',latitude:18.52,longitude:73.85,department:organization,jurisdiction}}]);m.reports.mockResolvedValue([{id:'report-safe',latitude:18.521,longitude:73.851,department:organization,jurisdiction},{id:'report-invalid',latitude:18.52,longitude:null,department:organization,jurisdiction}]);const result=await analyzeGeospatialHotspots(principal);expect(result.complete).toBe(true);expect(result.coverage.overall).toMatchObject({eligibleRecords:504,mappedRecords:503,unmappedRecords:1,invalidCoordinateCount:1});expect(result.hotspots[0]).toMatchObject({assetCount:501,activeCaseCount:1,publicReportCount:1,severityIndex:5,highestPriority:'CRITICAL'});expect(result.hotspots[0].riskCounts).toEqual({VERY_HIGH:1});expect(result.summary.uniqueMappedAssets).toBe(501);expect(m.assets).toHaveBeenNthCalledWith(2,expect.objectContaining({cursor:{id:'a-500'},skip:1,take:500}));expect(JSON.stringify(result)).not.toMatch(/reporter|contact|phone|email|tracking/i);});
 it.each([SystemRole.OFFICER,SystemRole.AUDITOR,SystemRole.POLICY_ADMIN])('applies department and jurisdiction scope before %s aggregation',async role=>{await analyzeGeospatialHotspots({...principal,role},{departmentId:'other-department',jurisdictionId:'other-jurisdiction'});const assetWhere=m.assets.mock.calls[0][0].where,caseWhere=m.cases.mock.calls[0][0].where,reportWhere=m.reports.mock.calls[0][0].where;for(const where of[assetWhere,caseWhere,reportWhere]){const serialized=JSON.stringify(where);expect(serialized).toContain('"departmentId":"d"');expect(serialized).toContain('"jurisdictionId":"j"');expect(serialized).toContain('other-jurisdiction');}});
 it('allows system-admin global analysis while applying narrowing filters',async()=>{await analyzeGeospatialHotspots({...principal,role:SystemRole.SYSTEM_ADMIN},{jurisdictionId:'filter-j'});expect(JSON.stringify(m.assets.mock.calls[0][0].where)).not.toContain('"departmentId":"d"');expect(JSON.stringify(m.assets.mock.calls[0][0].where)).toContain('filter-j');});
 it('excludes closed/cancelled cases, rejected reports, history, observations and schedules at the query contract',async()=>{await analyzeGeospatialHotspots(principal);const caseOptions=m.cases.mock.calls[0][0],caseQuery=JSON.stringify(caseOptions),reportQuery=JSON.stringify(m.reports.mock.calls[0][0]);expect(caseQuery).toContain('"status":{"in"');expect(caseQuery).not.toContain('CLOSED');expect(caseQuery).not.toContain('CANCELLED');expect(reportQuery).toContain('"status":{"not":"REJECTED"}');expect(caseOptions).not.toHaveProperty('include');expect(Object.keys(caseOptions.select).sort()).toEqual(['asset','id','priorityLevel','riskLevel']);});
 it('returns explicit empty and no-coordinate coverage states',async()=>{let result=await analyzeGeospatialHotspots(principal);expect(result.coverage.overall).toEqual({eligibleRecords:0,mappedRecords:0,unmappedRecords:0,invalidCoordinateCount:0,coveragePercentage:0});expect(result.hotspots).toEqual([]);m.assets.mockResolvedValue([{id:'missing',latitude:null,longitude:null,department:organization,jurisdiction}]);m.reports.mockResolvedValue([{id:'partial',latitude:18.52,longitude:null,department:organization,jurisdiction}]);result=await analyzeGeospatialHotspots(principal);expect(result.coverage.overall).toMatchObject({eligibleRecords:2,mappedRecords:0,unmappedRecords:2,invalidCoordinateCount:1,coveragePercentage:0});expect(result.mapBounds).toBeNull();expect(result.hotspots).toEqual([]);});
 it('keeps jurisdiction cells separate even at identical coordinates',async()=>{const secondJurisdiction={id:'j2',name:'Second Division'};m.cases.mockResolvedValue([{id:'c1',riskLevel:RiskLevel.CRITICAL,priorityLevel:PriorityLevel.CRITICAL,asset:{id:'a1',latitude:18.52,longitude:73.85,department:organization,jurisdiction}},{id:'c2',riskLevel:RiskLevel.CRITICAL,priorityLevel:PriorityLevel.CRITICAL,asset:{id:'a2',latitude:18.52,longitude:73.85,department:organization,jurisdiction:secondJurisdiction}}]);const result=await analyzeGeospatialHotspots({...principal,role:SystemRole.SYSTEM_ADMIN});expect(result.hotspots).toHaveLength(2);expect(new Set(result.hotspots.map(item=>item.jurisdiction?.id))).toEqual(new Set(['j','j2']));});
 it('qualifies public-report-only concentration without treating it as authoritative severity',async()=>{m.reports.mockResolvedValue([{id:'r1',latitude:18.52,longitude:73.85,department:organization,jurisdiction},{id:'r2',latitude:18.521,longitude:73.851,department:organization,jurisdiction}]);const result=await analyzeGeospatialHotspots(principal);expect(result.hotspots[0]).toMatchObject({publicReportCount:2,activeCaseCount:0,severityIndex:0,qualification:'MULTI_RECORD_CONCENTRATION'});});
});
