import{describe,expect,it}from'vitest';import{assertRecordScope,authorityScopePayload,resolveAuthoritativeActorScope,scopePayload}from'../scripts/governed-demo-scope';
const departments=[{id:'department-pwd',code:'PWD',name:'Public Works Department'},{id:'department-demo',code:'DEMO-PWD',name:'Leftover Demo Department'}],jurisdictions=[{id:'jurisdiction-pune',name:'Pune Division',departmentId:'department-pwd'},{id:'jurisdiction-demo',name:'DEMO-PUNE',departmentId:'department-demo'}];
const actor=(key:string,departmentId='department-pwd',jurisdictionId='jurisdiction-pune')=>({key,employeeCode:`EMP-${key}`,role:'OFFICER',departmentId,jurisdictionId,department:departments.find(x=>x.id===departmentId),jurisdiction:jurisdictions.find(x=>x.id===jurisdictionId)});const actors={primary:actor('primary'),verifier:actor('verifier'),closer:actor('closer')};
describe('G6 authoritative organizational scope',()=>{
 it('resolves matching existing operational actors',()=>expect(resolveAuthoritativeActorScope(actors,departments,jurisdictions)).toMatchObject({department:{code:'PWD'},jurisdiction:{name:'Pune Division'},source:'RESOLVED_FROM_AUTHORIZED_ACTORS'}));
 it('does not allow leftover synthetic organizations to hijack actor scope',()=>expect(resolveAuthoritativeActorScope(actors,[departments[1],departments[0]],[jurisdictions[1],jurisdictions[0]]).department.code).toBe('PWD'));
 it('abstains when operational actors disagree',()=>expect(()=>resolveAuthoritativeActorScope({...actors,verifier:actor('verifier','department-demo','jurisdiction-demo')},departments,jurisdictions)).toThrow(/G6_ACTOR_SCOPE_CONFLICT/));
 it('accepts matching expected configuration',()=>expect(resolveAuthoritativeActorScope(actors,departments,jurisdictions,{departmentCode:'PWD',jurisdictionName:'Pune Division'}).department.code).toBe('PWD'));
 it('fails safely for mismatching expected configuration',()=>expect(()=>resolveAuthoritativeActorScope(actors,departments,jurisdictions,{departmentCode:'DEMO-PWD'})).toThrow(/G6_EXPECTED_SCOPE_MISMATCH/));
 it('fails safely when an operational actor is absent',()=>expect(()=>resolveAuthoritativeActorScope({primary:actors.primary,verifier:actors.verifier},departments,jurisdictions)).toThrow(/G6_ACTOR_MISSING/));
 it('fails on an invalid Department/Jurisdiction relationship',()=>expect(()=>resolveAuthoritativeActorScope(actors,departments,[{...jurisdictions[0],departmentId:'department-demo'}])).toThrow(/G6_ORGANIZATIONAL_SCOPE_INVALID/));
 it('scopes assets, policies and templates from the resolved organization',()=>{const scope=resolveAuthoritativeActorScope(actors,departments,jurisdictions);expect(scopePayload(scope)).toEqual({departmentId:'department-pwd',jurisdictionId:'jurisdiction-pune'});expect(()=>assertRecordScope(scopePayload(scope),scope,'asset')).not.toThrow()});
 it('only requests authority in the target officer scope',()=>{const scope=resolveAuthoritativeActorScope(actors,departments,jurisdictions);expect(authorityScopePayload(actors.verifier,scope)).toEqual(scopePayload(scope));expect(()=>authorityScopePayload(actor('other','department-demo','jurisdiction-demo'),scope)).toThrow(/G6_ACTOR_SCOPE_CONFLICT/)});
 it('preserves four-eyes identities without changing users',()=>expect(new Set([actors.primary.employeeCode,actors.verifier.employeeCode,actors.closer.employeeCode]).size).toBe(3));
});
