import { describe, expect, it } from 'vitest';
import { PriorityLevel, RiskLevel } from '../src/generated/prisma';
import { generateGovernedORPActions } from '../src/modules/orp/orp.service';
const actionIds={mandatory:'11111111-1111-4111-8111-111111111111',recommended:'22222222-2222-4222-8222-222222222222',optional:'33333333-3333-4333-8333-333333333333',prohibited:'44444444-4444-4444-8444-444444444444'};
const inspection={structuralCondition:'POOR',crackSeverity:'SEVERE',corrosionLevel:'MODERATE',trafficImportance:'HIGH',hospitalRoute:true,weatherRisk:'HIGH',heavyRainExpected:true} as any;
function governedPackage(){const groups=['MANDATORY','RECOMMENDED','OPTIONAL','PROHIBITED'] as const;const codes={MANDATORY:'ACT_M',RECOMMENDED:'ACT_R',OPTIONAL:'ACT_O',PROHIBITED:'ACT_P'};const ids={MANDATORY:actionIds.mandatory,RECOMMENDED:actionIds.recommended,OPTIONAL:actionIds.optional,PROHIBITED:actionIds.prohibited};return{id:'package',packageVersion:3,packageContractVersion:'ODYSSEY_DECISION_PACKAGE_V1',preparedAt:new Date(),actionSnapshot:Object.fromEntries(groups.map(level=>[level,[{actionId:ids[level],actionCode:codes[level],actionVersion:2,title:`${level} action`,category:'SAFETY',description:'Persisted description',sourceReference:'Official source',enforcementClassification:level}]])),policySnapshot:{state:'APPLICABLE_GOVERNANCE',rules:groups.map((level,index)=>({rule:{id:`00000000-0000-4000-8000-00000000000${index}`,code:`RULE_${level}`,description:'Persisted rule',enforcementLevel:level},policy:{id:'55555555-5555-4555-8555-555555555555',policyCode:'POLICY_1',versionNumber:7,title:'Policy',sourceReference:'Gazette'},action:{id:ids[level],actionCode:codes[level],versionNumber:2}}))}};}
describe('governed Action Plan projection',()=>{
  it('selects mandatory/recommended, separates optional and excludes prohibited',()=>{const result=generateGovernedORPActions(governedPackage(),RiskLevel.HIGH,PriorityLevel.CRITICAL,inspection);expect(result.recommendedActionCodes).toEqual(['ACT_M','ACT_R']);expect(result.alternativeActionCodes).toEqual(['ACT_O']);expect(result.recommendedActionCodes).not.toContain('ACT_P');expect(result.governedActions.PROHIBITED).toHaveLength(1);expect((result.governedActions.MANDATORY[0] as any).sources[0]).toMatchObject({policyCode:'POLICY_1',policyVersion:7,ruleCode:'RULE_MANDATORY'});});
  it('abstains when exact rule provenance is absent',()=>{const input=governedPackage();(input.policySnapshot.rules as any[]).shift();expect(()=>generateGovernedORPActions(input,RiskLevel.HIGH,PriorityLevel.HIGH,inspection)).toThrow(/lacks exact policy/i);});
  it('abstains on duplicate classifications',()=>{const input=governedPackage();(input.actionSnapshot.RECOMMENDED as any[])[0].actionCode='ACT_M';expect(()=>generateGovernedORPActions(input,RiskLevel.HIGH,PriorityLevel.HIGH,inspection)).toThrow(/conflicting governed action/i);});
  it('labels no-policy fallback as engineering-only',()=>{const result=generateGovernedORPActions({id:'package',packageVersion:1,packageContractVersion:'V1',preparedAt:new Date(),policySnapshot:{state:'NO_APPLICABLE_ACTIVE_POLICY_GOVERNANCE',rules:[]},actionSnapshot:{MANDATORY:[],RECOMMENDED:[],OPTIONAL:[],PROHIBITED:[]}},RiskLevel.VERY_HIGH,PriorityLevel.CRITICAL,inspection);expect(result.governanceMode).toBe('GOVERNED_ENGINEERING_NO_POLICY');expect(result.governedActions.MANDATORY).toEqual([]);expect(result.governedActions.ENGINEERING_RECOMMENDED.length).toBeGreaterThan(0);});
});
