import{describe,expect,it,vi}from'vitest';import{appendIntegrityEvent,canonicalIntegrityPayload,chainKeyForScope,evidenceIntegrityFacts,integrityEventHash,integrityPayloadHash,INTEGRITY_CHAIN_VERSION,INTEGRITY_PAYLOAD_VERSION}from'../src/modules/integrity/integrity.service';
const input={eventType:'RISK_ASSESSMENT_RECORDED' as const,sourceEventKey:'RISK_ASSESSMENT:r1',resourceType:'RiskAssessment',resourceId:'r1',actor:{id:'u',role:'OFFICER' as any},departmentId:'d',jurisdictionId:'j',occurredAt:new Date('2026-08-24T00:00:00Z'),facts:{riskScore:77,riskLevel:'VERY_HIGH'}};
function fake(){const events:any[]=[];let head:any=null;return{events,tx:{$executeRawUnsafe:vi.fn(),integrityAuditEvent:{findUnique:vi.fn(({where}:any)=>events.find(e=>e.sourceEventKey===where.sourceEventKey)??null),create:vi.fn(({data}:any)=>{const e={id:`e${events.length+1}`,...data};events.push(e);return e})},integrityChainHead:{upsert:vi.fn(({create}:any)=>head??(head={...create,latestSequence:0,latestEventId:null,latestEventHash:null})),update:vi.fn(({data}:any)=>(head={...head,...data}))}}as any};}
describe('P3.4 integrity contracts',()=>{
 it('canonicalizes stable property order while detecting material changes',()=>{const p=canonicalIntegrityPayload(input),h=integrityPayloadHash(p);expect(h).toMatch(/^sha256:[a-f0-9]{64}$/);expect(integrityPayloadHash({...p,facts:{riskLevel:'VERY_HIGH',riskScore:77}})).toBe(h);expect(integrityPayloadHash({...p,facts:{...p.facts,riskScore:76}})).not.toBe(h);expect(canonicalIntegrityPayload({...input,facts:input.facts,irrelevant:'excluded'} as any)).toEqual(p);});
 it('creates a truthful genesis then exact linked successor',async()=>{const f=fake(),first=await appendIntegrityEvent(f.tx,input),second=await appendIntegrityEvent(f.tx,{...input,sourceEventKey:'RISK_ASSESSMENT:r2',resourceId:'r2'});expect(first).toMatchObject({chainKey:'scope:d:j',chainVersion:INTEGRITY_CHAIN_VERSION,sequenceNumber:1,previousEventId:null,previousEventHash:null,payloadContractVersion:INTEGRITY_PAYLOAD_VERSION});expect(second).toMatchObject({sequenceNumber:2,previousEventId:first.id,previousEventHash:first.eventHash});expect(second.eventHash).toBe(integrityEventHash({chainKey:'scope:d:j',sequenceNumber:2,previousEventHash:first.eventHash,payloadHash:second.payloadHash}));});
 it('preserves idempotency for the same authoritative source event',async()=>{const f=fake(),a=await appendIntegrityEvent(f.tx,input),b=await appendIntegrityEvent(f.tx,input);expect(b).toBe(a);expect(f.events).toHaveLength(1);});
 it('derives organizational and global chains only on the server',()=>{expect(chainKeyForScope('d','j')).toBe('scope:d:j');expect(chainKeyForScope(null,null)).toBe('system:global');});
 it('protects evidence records without falsely claiming external content verification',()=>{const facts=evidenceIntegrityFacts({id:'x',executionTaskId:'t',submittedById:'u',evidenceType:'DOCUMENT_REFERENCE',description:'Observed repair',referenceUrl:'https://records.invalid/x',documentReference:'DOC-1',measurementData:{mm:2},capturedAt:null});expect(facts).toMatchObject({digestType:'RECORD_DIGEST',contentDigest:null,contentVerified:false});expect(facts.descriptionDigest).toMatch(/^sha256:/);expect(evidenceIntegrityFacts({id:'x',executionTaskId:'t',submittedById:'u',evidenceType:'DOCUMENT_REFERENCE',description:'Changed',referenceUrl:'https://records.invalid/x',documentReference:'DOC-1',measurementData:{mm:2},capturedAt:null}).descriptionDigest).not.toBe(facts.descriptionDigest);});
 it('detects event, prior-link, payload, sequence and version tampering by deterministic reproduction',()=>{const payload=canonicalIntegrityPayload(input),payloadHash=integrityPayloadHash(payload),eventHash=integrityEventHash({chainKey:'scope:d:j',sequenceNumber:1,previousEventHash:null,payloadHash});expect(integrityPayloadHash({...payload,facts:{riskScore:1}})).not.toBe(payloadHash);expect(integrityEventHash({chainKey:'scope:d:j',sequenceNumber:1,previousEventHash:'sha256:'+'0'.repeat(64),payloadHash})).not.toBe(eventHash);expect(integrityEventHash({chainKey:'scope:d:j',sequenceNumber:2,previousEventHash:null,payloadHash})).not.toBe(eventHash);expect(INTEGRITY_CHAIN_VERSION).not.toBe('UNSUPPORTED');});
});
