import { afterEach, describe, expect, it, vi } from 'vitest';
import { invokeIntelligenceProvider, providerResponseSchema } from '../src/modules/intelligence/intelligence.adapter';
const provenance={provider:'ODYSSEY_REFERENCE_PROVIDER_V1',providerType:'REFERENCE_NON_ML',modelName:'ODYSSEY_REFERENCE_HEURISTIC',modelVersion:'1',featureSchemaVersion:'ODYSSEY_INFRA_FEATURES_V1',contractVersion:'ODYSSEY_INTELLIGENCE_V1',inferredAt:'2026-08-22T12:00:00Z',productionTrained:false};
const completed={status:'COMPLETED',predictedRiskScore:77,predictedRiskLevel:'VERY_HIGH',recommendedPriority:'CRITICAL',confidence:1,confidenceSemantics:'INPUT_COMPLETENESS_NOT_CALIBRATED_PROBABILITY',contributingFactors:[],explanation:'Controlled reference explanation.',recommendedActions:[{actionCode:'ACT_INSPECT_DETAILED',rationale:'Review.'}],abstentionReasons:[],provenance};
afterEach(()=>{vi.unstubAllEnvs();});
describe('intelligence provider adapter',()=>{
 it('accepts the exact completed contract and sends no authorization header',async()=>{const fetchMock=vi.fn().mockResolvedValue(new Response(JSON.stringify(completed),{status:200}));expect(await invokeIntelligenceProvider({safe:true},fetchMock)).toMatchObject({kind:'PROVIDER',data:{status:'COMPLETED'}});const init=fetchMock.mock.calls[0][1];expect(init.headers).toEqual({'content-type':'application/json'});});
 it.each([['invalid enum',{...completed,predictedRiskLevel:'EXTREME'}],['confidence above one',{...completed,confidence:1.1}],['wrong contract',{...completed,provenance:{...provenance,contractVersion:'OTHER'}}],['wrong schema',{...completed,provenance:{...provenance,featureSchemaVersion:'OTHER'}}],['wrong provider',{...completed,provenance:{...provenance,provider:'OTHER'}}],['wrong provider type',{...completed,provenance:{...provenance,providerType:'TRAINED_ML'}}],['wrong model',{...completed,provenance:{...provenance,modelName:'OTHER'}}],['false production-training claim violated',{...completed,provenance:{...provenance,productionTrained:true}}]])('maps %s to INVALID_RESPONSE',async(_label,body)=>{const result=await invokeIntelligenceProvider({},vi.fn().mockResolvedValue(new Response(JSON.stringify(body),{status:200})));expect(result).toEqual({kind:'INVALID_RESPONSE',reasonCode:'SCHEMA_INVALID'});});
 it('maps malformed JSON without throwing',async()=>{expect(await invokeIntelligenceProvider({},vi.fn().mockResolvedValue(new Response('{',{status:200})))).toEqual({kind:'INVALID_RESPONSE',reasonCode:'MALFORMED_JSON'});});
 it('maps HTTP and network failures without retrying',async()=>{const http=vi.fn().mockResolvedValue(new Response('',{status:503}));expect(await invokeIntelligenceProvider({},http)).toEqual({kind:'UNAVAILABLE',reasonCode:'SERVICE_HTTP_ERROR'});expect(http).toHaveBeenCalledTimes(1);const network=vi.fn().mockRejectedValue(new Error('private'));expect(await invokeIntelligenceProvider({},network)).toEqual({kind:'UNAVAILABLE',reasonCode:'SERVICE_UNAVAILABLE'});});
 it('enforces a bounded timeout',async()=>{vi.stubEnv('ODYSSEY_INTELLIGENCE_TIMEOUT_MS','100');const hanging=vi.fn((_u,_i)=>new Promise((_resolve,reject)=>_i.signal.addEventListener('abort',()=>reject(new DOMException('aborted','AbortError')))));expect(await invokeIntelligenceProvider({},hanging as any)).toEqual({kind:'UNAVAILABLE',reasonCode:'SERVICE_TIMEOUT'});});
 it('forbids completed fields in abstained responses',()=>{expect(providerResponseSchema.safeParse({status:'ABSTAINED',predictedRiskScore:1,contributingFactors:[],explanation:'Reference provider abstained; no advisory prediction was produced.',recommendedActions:[],abstentionReasons:[{code:'INSUFFICIENT_FEATURES',message:'Missing.'}],provenance}).success).toBe(false);});
});
