import{describe,expect,it}from'vitest';import{RegistryLifecycleStatus}from'../src/generated/prisma';import{reconcileIntelligenceActions}from'../src/modules/intelligence/intelligence-governance.service';
const at=new Date('2026-08-22T12:00:00Z'),scope={departmentId:'dep',jurisdictionId:'jur'};const rule=(level:string)=>({rule:{id:`rule-${level}`,code:`RULE_${level}`,description:'Rule',enforcementLevel:level},policy:{id:'policy',policyCode:'POLICY_PWD',versionNumber:3,title:'Policy',sourceReference:'REF'},action:{id:'action',actionCode:'ACT_TEST',versionNumber:2,title:'Action',category:'SAFETY',description:'Governed',sourceReference:'REF',enforcementClassification:level}})as any;const resolved=(rules:any[])=>({status:'RESOLVED',issues:[],applicableRules:rules,asOf:at})as any;const suggestion=[{actionCode:'ACT_TEST',rationale:'Provider rationale'}];
describe('intelligence policy/AAL reconciliation',()=>{
 it.each(['MANDATORY','RECOMMENDED','OPTIONAL','PROHIBITED'])('takes %s solely from exact policy provenance',level=>{const value=reconcileIntelligenceActions(suggestion,resolved([rule(level)]),[],scope,at)[0]as any;expect(value.enforcementClassification).toBe(level);expect(value.resolution).toBe(level==='PROHIBITED'?'PROHIBITED':'APPROVED_ACTIVE');expect(value.approvedActionVersion).toMatchObject({id:'action',versionNumber:2});expect(value.policy).toMatchObject({id:'policy',versionNumber:3});expect(value.rule.id).toBe(`rule-${level}`);});
 it('does not authorize an unknown action',()=>{expect(reconcileIntelligenceActions(suggestion,resolved([]),[],scope,at)[0]).toMatchObject({resolution:'UNKNOWN'});});
 it('distinguishes inactive, expired and organizationally out-of-scope versions',()=>{const base={id:'a',actionCode:'ACT_TEST',versionNumber:1,status:RegistryLifecycleStatus.ACTIVE,effectiveFrom:new Date('2026-01-01'),effectiveUntil:null,departmentId:null,jurisdictionId:null};expect(reconcileIntelligenceActions(suggestion,resolved([]),[{...base,status:RegistryLifecycleStatus.ARCHIVED}],scope,at)[0]).toMatchObject({resolution:'INACTIVE'});expect(reconcileIntelligenceActions(suggestion,resolved([]),[{...base,effectiveUntil:new Date('2026-08-01')}],scope,at)[0]).toMatchObject({resolution:'EXPIRED'});expect(reconcileIntelligenceActions(suggestion,resolved([]),[{...base,departmentId:'other'}],scope,at)[0]).toMatchObject({resolution:'OUT_OF_SCOPE'});expect(reconcileIntelligenceActions(suggestion,resolved([]),[{...base,jurisdictionId:'other'}],scope,at)[0]).toMatchObject({resolution:'OUT_OF_SCOPE'});});
 it('preserves policy abstention and conflict without fallback authority',()=>{const abstained={status:'ABSTAINED',applicableRules:[],asOf:at,issues:[{code:'NO_APPLICABLE_ACTIVE_POLICY',message:'None'}]}as any;expect(reconcileIntelligenceActions(suggestion,abstained,[],scope,at)[0]).toMatchObject({resolution:'POLICY_ABSTAINED'});expect(reconcileIntelligenceActions(suggestion,{...abstained,issues:[{code:'CONFLICTING_ENFORCEMENT',message:'Conflict'}]},[],scope,at)[0]).toMatchObject({resolution:'GOVERNANCE_CONFLICT'});});
 it('retains raw rationale and grants no authority to rejected suggestions',()=>{const value=reconcileIntelligenceActions(suggestion,resolved([]),[],scope,at)[0]as any;expect(value.rationale).toBe('Provider rationale');expect(value).not.toHaveProperty('approvedActionVersion');expect(value).not.toHaveProperty('policy');expect(value).not.toHaveProperty('rule');});
});
