import { describe, expect, it, vi } from 'vitest';
import { OpenMeteoAdapter, WeatherProviderError } from '../src/modules/observations/open-meteo.adapter';
const config={enabled:true,provider:'OPEN_METEO' as const,deploymentClass:'EVALUATION_ONLY' as const,baseUrl:'https://api.open-meteo.com',sourceCode:'OPEN_METEO_CURRENT',timeoutMs:250,maxRetries:1};
const payload={latitude:18.52,longitude:73.86,timezone:'GMT',current_units:{time:'iso8601',interval:'seconds',temperature_2m:'°C',precipitation:'mm',wind_speed_10m:'km/h',weather_code:'wmo code'},current:{time:'2026-08-24T10:00',interval:900,temperature_2m:25.5,precipitation:2.2,wind_speed_10m:12,weather_code:61}};
const response=(body:unknown,status=200,headers?:HeadersInit)=>new Response(typeof body==='string'?body:JSON.stringify(body),{status,headers:{'Content-Type':'application/json',...headers}});
describe('Open-Meteo governed adapter',()=>{
 it('uses a fixed bounded contract and deterministically normalizes current model-derived weather',async()=>{const transport=vi.fn().mockImplementation(()=>Promise.resolve(response({...payload,irrelevant:'ignored'})));const adapter=new OpenMeteoAdapter(config,transport,vi.fn());const first=await adapter.fetchCurrent({assetId:'asset',latitude:18.52,longitude:73.86});const second=await adapter.fetchCurrent({assetId:'asset',latitude:18.52,longitude:73.86});expect(first.sourceRecordId).toBe(second.sourceRecordId);expect(first.normalizedData).toEqual({temperatureC:25.5,rainfallMm:2.2,windSpeedKph:12,weatherCondition:'RAIN'});expect(first.sourceMetadata).toMatchObject({providerId:'OPEN_METEO',dataSemantics:'CURRENT_MODEL_DERIVED',deploymentClass:'EVALUATION_ONLY'});const called=new URL(transport.mock.calls[0][0]);expect(called.origin).toBe('https://api.open-meteo.com');expect(called.pathname).toBe('/v1/forecast');expect(called.searchParams.get('current')).toBe('temperature_2m,precipitation,wind_speed_10m,weather_code')});
 it.each([{body:{...payload,current_units:{...payload.current_units,temperature_2m:'°F'}}},{body:{...payload,current:{...payload.current,time:'bad'}}},{body:{...payload,current:{...payload.current,precipitation:null}}}])('rejects schema drift and unsupported units',async({body})=>{await expect(new OpenMeteoAdapter(config,vi.fn().mockResolvedValue(response(body)),vi.fn()).fetchCurrent({assetId:'a',latitude:1,longitude:1})).rejects.toMatchObject({code:'PROVIDER_RESPONSE_INVALID'})});
 it('does not retry deterministic 400 or authentication failures',async()=>{for(const status of[400,401,403]){const transport=vi.fn().mockResolvedValue(response({},status));await expect(new OpenMeteoAdapter(config,transport,vi.fn()).fetchCurrent({assetId:'a',latitude:1,longitude:1})).rejects.toBeInstanceOf(WeatherProviderError);expect(transport).toHaveBeenCalledTimes(1)}});
 it('bounds 500 retry and controls 429 Retry-After',async()=>{const sleep=vi.fn();const transient=vi.fn().mockResolvedValueOnce(response({},500)).mockResolvedValueOnce(response(payload));await expect(new OpenMeteoAdapter(config,transient,sleep).fetchCurrent({assetId:'a',latitude:1,longitude:1})).resolves.toBeTruthy();expect(transient).toHaveBeenCalledTimes(2);const limited=vi.fn().mockResolvedValue(response({},429,{'Retry-After':'30'}));await expect(new OpenMeteoAdapter(config,limited,sleep).fetchCurrent({assetId:'a',latitude:1,longitude:1})).rejects.toMatchObject({code:'PROVIDER_RATE_LIMITED'});expect(limited).toHaveBeenCalledTimes(1)});
 it('maps malformed JSON, disablement, invalid coordinates and timeout without leaking internals',async()=>{await expect(new OpenMeteoAdapter(config,vi.fn().mockResolvedValue(response('{',200)),vi.fn()).fetchCurrent({assetId:'a',latitude:1,longitude:1})).rejects.toMatchObject({code:'PROVIDER_RESPONSE_INVALID'});await expect(new OpenMeteoAdapter({...config,enabled:false,deploymentClass:'DISABLED'},vi.fn(),vi.fn()).fetchCurrent({assetId:'a',latitude:1,longitude:1})).rejects.toMatchObject({code:'PROVIDER_DISABLED'});await expect(new OpenMeteoAdapter(config,vi.fn(),vi.fn()).fetchCurrent({assetId:'a',latitude:100,longitude:1})).rejects.toMatchObject({code:'TARGET_COORDINATES_INVALID'});const aborting=vi.fn((_url:string,init:RequestInit)=>new Promise<Response>((_resolve,reject)=>init.signal?.addEventListener('abort',()=>reject(new DOMException('aborted','AbortError')))));await expect(new OpenMeteoAdapter({...config,maxRetries:0},aborting,vi.fn()).fetchCurrent({assetId:'a',latitude:1,longitude:1})).rejects.toMatchObject({code:'PROVIDER_TIMEOUT'})});
});
