import express from'express';import request from'supertest';import{beforeEach,describe,expect,it,vi}from'vitest';import{SignJWT}from'jose';import{getAuthConfig}from'../src/config/auth';
const mocks=vi.hoisted(()=>({user:vi.fn(),policies:vi.fn(),actions:vi.fn(),resolve:vi.fn(),createPolicy:vi.fn()}));vi.mock('../src/lib/prisma',()=>({default:{user:{findUnique:mocks.user}}}));vi.mock('../src/modules/policy-registry/policy-registry.service',()=>{class PolicyRegistryError extends Error{constructor(public code:string,public status:number,message:string){super(message)}}return{PolicyRegistryError,listPolicies:mocks.policies,listApprovedActions:mocks.actions,resolveCasePolicy:mocks.resolve,createPolicy:mocks.createPolicy,createApprovedAction:vi.fn(),createPolicyRule:vi.fn(),listPolicyRules:vi.fn(),transitionAction:vi.fn(),transitionPolicy:vi.fn()}});
import routes from'../src/modules/policy-registry/policy-registry.routes';const app=express();app.use(express.json());app.use('/api/v1',routes);async function auth(role:string){const id=`user-${role}`;mocks.user.mockResolvedValue({id,role,status:'ACTIVE',departmentId:'dep',jurisdictionId:'jur'});const c=getAuthConfig();const token=await new SignJWT({}).setProtectedHeader({alg:'HS256'}).setSubject(id).setIssuer(c.issuer).setAudience(c.audience).setIssuedAt().setExpirationTime('5m').sign(c.secret);return`Bearer ${token}`}
describe('policy registry routes',()=>{beforeEach(()=>{vi.clearAllMocks();mocks.policies.mockResolvedValue([]);mocks.actions.mockResolvedValue([]);mocks.resolve.mockResolvedValue({status:'ABSTAINED'});mocks.createPolicy.mockResolvedValue({id:'policy'});});
 it.each(['POLICY_ADMIN','SYSTEM_ADMIN'])('allows privileged %s registry administration',async role=>{const header=await auth(role);await request(app).get('/api/v1/policies').set('Authorization',header).expect(200);await request(app).post('/api/v1/policies').set('Authorization',header).send({policyCode:'POLICY_1',versionNumber:1,title:'Policy',sourceTitle:'Official source',sourceReference:'REF-1',effectiveFrom:'2026-08-20T00:00:00Z'}).expect(201);});
 it.each(['OFFICER','AUDITOR'])('rejects %s registry administration',async role=>{await request(app).get('/api/v1/policies').set('Authorization',await auth(role)).expect(403);});
 it('requires authentication everywhere',async()=>{await request(app).get('/api/v1/policies').expect(401);await request(app).get('/api/v1/cases/case/policy-resolution').expect(401);});
 it.each(['OFFICER','AUDITOR','POLICY_ADMIN','SYSTEM_ADMIN'])('allows authenticated scoped %s Case resolution',async role=>{await request(app).get('/api/v1/cases/case/policy-resolution').set('Authorization',await auth(role)).expect(200);expect(mocks.resolve).toHaveBeenCalledWith('case',expect.objectContaining({role}));});
 it('rejects arbitrary fields and generated-authority bypass attempts',async()=>{await request(app).post('/api/v1/policies').set('Authorization',await auth('POLICY_ADMIN')).send({policyCode:'POLICY_1',versionNumber:1,title:'Policy',sourceTitle:'Source',sourceReference:'REF',effectiveFrom:'2026-08-20',aiApproved:true,status:'ACTIVE'}).expect(400);expect(mocks.createPolicy).not.toHaveBeenCalled();});
});
