import{beforeEach,describe,expect,it,vi}from'vitest';
const mocks=vi.hoisted(()=>({caseFind:vi.fn(),rules:vi.fn(),visible:vi.fn()}));
vi.mock('../src/lib/prisma',()=>({default:{case:{findUnique:mocks.caseFind},policyRule:{findMany:mocks.rules}}}));vi.mock('../src/security/organizational-scope',async(importOriginal)=>({...await importOriginal<typeof import('../src/security/organizational-scope')>(),assertVisibleCase:mocks.visible}));
import{resolveCasePolicy}from'../src/modules/policy-registry/policy-registry.service';
const principal={id:'officer',role:'OFFICER',status:'ACTIVE',departmentId:'dep',jurisdictionId:'jur'}as any;const target={id:'case',caseNumber:'CASE-1',status:'ORP_READY',riskLevel:'VERY_HIGH',priorityLevel:'CRITICAL',emergencyFlag:false,asset:{assetType:'BRIDGE',departmentId:'dep',jurisdictionId:'jur'}};const levels=['MANDATORY','RECOMMENDED','OPTIONAL','PROHIBITED']as const;
function rule(level:typeof levels[number],index:number,conditions:unknown={}){return{id:`rule-${index}`,ruleCode:`RULE_${index}`,description:`${level} governed rule`,conditions,enforcementLevel:level,enabled:true,createdAt:new Date(),policyDocument:{id:`policy-${index}`,policyCode:'PWD-BRIDGE',versionNumber:2,title:'Synthetic governed bridge policy'},action:{id:`action-${index}`,actionCode:`ACT_TEST_${index}`,versionNumber:3,title:`${level} action`,enforcementClassification:level,applicability:{}}}}
describe('Case policy resolution',()=>{beforeEach(()=>{vi.clearAllMocks();mocks.visible.mockResolvedValue(target);mocks.caseFind.mockResolvedValue(target);mocks.rules.mockResolvedValue(levels.map((level,index)=>rule(level,index)));});
 it('returns exact policy/action versions and all enforcement classifications without mutation',async()=>{const result=await resolveCasePolicy('case',principal,new Date('2026-08-20T00:00:00Z'));expect(result).toMatchObject({status:'RESOLVED',issues:[]});expect(result.applicableRules.map(item=>item.rule.enforcementLevel)).toEqual(levels);expect(result.applicableRules[0]).toMatchObject({policy:{policyCode:'PWD-BRIDGE',versionNumber:2},action:{actionCode:'ACT_TEST_0',versionNumber:3}});expect(result.governance).toEqual({advisoryOnly:true,caseMutated:false,automaticDecision:false});expect(Object.keys((await import('../src/lib/prisma')).default)).toEqual(['case','policyRule']);});
 it('queries only active effective policy/action versions within Case organizational context',async()=>{await resolveCasePolicy('case',principal,new Date('2026-08-20T00:00:00Z'));const where=mocks.rules.mock.calls[0][0].where;expect(where.policyDocument).toMatchObject({status:'ACTIVE',effectiveFrom:{lte:new Date('2026-08-20T00:00:00Z')}});expect(where.action.status).toBe('ACTIVE');expect(JSON.stringify(where)).toContain('departmentId');expect(JSON.stringify(where)).toContain('jurisdictionId');});
 it('abstains on conflicting prohibition and permission',async()=>{const mandatory=rule('MANDATORY',1),prohibited=rule('PROHIBITED',2);prohibited.action={...mandatory.action,enforcementClassification:'PROHIBITED'};mocks.rules.mockResolvedValue([mandatory,prohibited]);const result=await resolveCasePolicy('case',principal);expect(result.status).toBe('ABSTAINED');expect(result.issues).toContainEqual(expect.objectContaining({code:'CONFLICTING_ENFORCEMENT',actionCode:mandatory.action.actionCode}));expect(result.applicableRules).toEqual([]);});
 it('abstains when required context is missing instead of guessing',async()=>{mocks.caseFind.mockResolvedValue({...target,riskLevel:null});mocks.rules.mockResolvedValue([rule('MANDATORY',1,{riskLevels:['VERY_HIGH']})]);const result=await resolveCasePolicy('case',principal);expect(result.status).toBe('ABSTAINED');expect(result.issues[0].code).toBe('MISSING_CASE_CONTEXT');});
 it('abstains when no active in-scope effective policy exists',async()=>{mocks.rules.mockResolvedValue([]);const result=await resolveCasePolicy('case',principal);expect(result.status).toBe('ABSTAINED');expect(result.issues[0].code).toBe('NO_APPLICABLE_ACTIVE_POLICY');});
 it('returns an allow-listed DTO without actors, reporter PII, notes, decisions or execution',async()=>{const body=JSON.stringify(await resolveCasePolicy('case',principal));for(const field of ['createdById','approvedById','reporterName','reporterContact','passwordHash','decision','executionPlan','inspectionNotes'])expect(body).not.toContain(field);});
});
