import {beforeEach,describe,expect,it,vi} from 'vitest';
import {PriorityLevel,RiskLevel,SystemRole,UserStatus} from '../src/generated/prisma';

const m=vi.hoisted(()=>({caseFirst:vi.fn(),caseMany:vi.fn(),estimateFirst:vi.fn(),estimateUpdate:vi.fn(),estimateCreate:vi.fn(),scenarioCreate:vi.fn(),scenarioFirst:vi.fn()}));
vi.mock('../src/lib/prisma',()=>{const tx={case:{findFirst:m.caseFirst,findMany:m.caseMany},caseResourceEstimate:{findFirst:m.estimateFirst,updateMany:m.estimateUpdate,create:m.estimateCreate},portfolioScenario:{create:m.scenarioCreate,findFirst:m.scenarioFirst}};return{default:{...tx,$transaction:vi.fn((callback:any)=>callback(tx))}}});
import {createEstimate,createScenario,getScenario,listCandidates,PortfolioError,PORTFOLIO_ALGORITHM_VERSION} from '../src/modules/portfolio/portfolio.service';

const principal:any={id:'officer',role:SystemRole.OFFICER,status:UserStatus.ACTIVE,departmentId:'dep',jurisdictionId:'jur'};
const actor={id:'officer',name:'Officer',designation:'Engineer'};
const row=(id:string,overrides:any={})=>({id,caseNumber:`CASE-${id}`,title:'Bridge repair',status:'ORP_READY',riskLevel:RiskLevel.VERY_HIGH,priorityLevel:PriorityLevel.CRITICAL,emergencyFlag:false,createdAt:new Date(`2026-01-${String((Number(id.replace(/\D/g,''))||1)%28+1).padStart(2,'0')}`),updatedAt:new Date('2026-08-24'),asset:{id:`a-${id}`,assetCode:`A-${id}`,name:'Asset',departmentId:'dep',jurisdictionId:'jur',department:{id:'dep',name:'Department'},jurisdiction:{id:'jur',name:'Jurisdiction'}},inspections:[{hospitalRoute:false}],resourceEstimates:[],...overrides});

beforeEach(()=>{vi.clearAllMocks();m.caseFirst.mockResolvedValue({id:'c1',status:'ORP_READY'});m.caseMany.mockResolvedValue([]);m.estimateFirst.mockResolvedValue({estimateVersion:1});m.estimateUpdate.mockResolvedValue({count:1});m.estimateCreate.mockImplementation(async({data}:any)=>({id:'e2',...data,status:'ACTIVE',preparedAt:new Date(),preparedBy:actor}));m.scenarioCreate.mockImplementation(async({data}:any)=>({id:'s1',scenarioVersion:1,...data,createdAt:new Date(),createdBy:actor}))});

describe('governed portfolio planning',()=>{
 it('versions estimates, preserves provenance and supersedes only the previous active version',async()=>{const result=await createEstimate('c1',{estimatedCostMinor:123456789012345n,currency:'INR',estimatedDurationDays:20,resourceRequirements:[{category:'STRUCTURAL_ENGINEER',quantity:5,unit:'UNIT_DAYS'}],estimateBasis:'Engineering schedule of rates',sourceReference:'PWD-SOR-2026'},principal);expect(result).toMatchObject({estimateVersion:2,estimatedCostMinor:'123456789012345',estimateBasis:'Engineering schedule of rates',sourceReference:'PWD-SOR-2026'});expect(m.estimateUpdate).toHaveBeenCalledWith({where:{caseId:'c1',status:'ACTIVE'},data:{status:'SUPERSEDED'}});expect(m.caseFirst.mock.calls[0][0].where).toEqual(expect.objectContaining({id:'c1',asset:{departmentId:'dep',jurisdictionId:'jur'}}))});
 it('rejects unsupported roles, currencies, unsafe money and closed cases',async()=>{for(const role of[SystemRole.AUDITOR,SystemRole.POLICY_ADMIN,SystemRole.SYSTEM_ADMIN])await expect(createEstimate('c1',{estimatedCostMinor:1n,currency:'INR',resourceRequirements:[],estimateBasis:'basis',sourceReference:'source'},{...principal,role})).rejects.toMatchObject({status:403});await expect(createEstimate('c1',{estimatedCostMinor:1n,currency:'USD',resourceRequirements:[],estimateBasis:'basis',sourceReference:'source'},principal)).rejects.toMatchObject({code:'UNSUPPORTED_CURRENCY'});await expect(createEstimate('c1',{estimatedCostMinor:9000000000000001n,currency:'INR',resourceRequirements:[],estimateBasis:'basis',sourceReference:'source'},principal)).rejects.toMatchObject({code:'INVALID_COST'});m.caseFirst.mockResolvedValue({id:'c1',status:'CLOSED'});await expect(createEstimate('c1',{estimatedCostMinor:1n,currency:'INR',resourceRequirements:[],estimateBasis:'basis',sourceReference:'source'},principal)).rejects.toMatchObject({code:'CASE_NOT_PLANNING_ELIGIBLE'})});
 it('defines zero as a valid explicit estimate while rejecting negative money',async()=>{await expect(createEstimate('c1',{estimatedCostMinor:0n,currency:'INR',resourceRequirements:[],estimateBasis:'No-cost inspection',sourceReference:'Officer estimate'},principal)).resolves.toMatchObject({estimatedCostMinor:'0'});await expect(createEstimate('c1',{estimatedCostMinor:-1n,currency:'INR',resourceRequirements:[],estimateBasis:'basis',sourceReference:'source'},principal)).rejects.toMatchObject({code:'INVALID_COST'})});
 it('ranks deterministically, keeps missing estimates visible and paginates by ranked identity',async()=>{const estimate={id:'e1',caseId:'2',estimateVersion:1,status:'ACTIVE',currency:'INR',estimatedCostMinor:100n,estimatedDurationDays:5,resourceRequirements:[],estimateBasis:'basis',sourceReference:'source',preparedAt:new Date(),preparedBy:actor};m.caseMany.mockResolvedValue([row('1',{priorityLevel:PriorityLevel.HIGH}),row('2',{resourceEstimates:[estimate]}),row('3',{priorityLevel:PriorityLevel.CRITICAL,riskLevel:RiskLevel.CRITICAL,emergencyFlag:true})]);const first=await listCandidates(principal,{limit:2});expect(first.items.map(x=>x.id)).toEqual(['3','2']);expect(first.summary).toMatchObject({totalCandidates:3,readyCases:1,missingEstimateCases:2,totalEstimatedCostMinor:'100'});expect(first.nextCursor).toBeTruthy();const parsed=JSON.parse(Buffer.from(first.nextCursor!,'base64url').toString());const second=await listCandidates(principal,{limit:2,cursor:{at:parsed.at,id:parsed.id}});expect(second.items.map(x=>x.id)).toEqual(['1']);expect(JSON.stringify(first)).not.toMatch(/reporter|phone|email|contact/i)});
 it('reads the complete authorized population beyond 500 before ranking',async()=>{const rows=Array.from({length:501},(_,index)=>row(String(index+1)));m.caseMany.mockImplementation(async({cursor}:any)=>cursor?rows.slice(500):rows.slice(0,500));const result=await listCandidates(principal,{limit:25});expect(result.summary.totalCandidates).toBe(501);expect(m.caseMany).toHaveBeenNthCalledWith(2,expect.objectContaining({cursor:{id:'500'},skip:1,take:500}));expect(JSON.stringify(m.caseMany.mock.calls[0][0].where)).toContain('departmentId')});
 it('allocates by governed order, reports resource shortage and critical unfunded without workflow mutation',async()=>{const estimate=(id:string,cost:bigint,quantity:number)=>({id:`e-${id}`,caseId:id,estimateVersion:1,status:'ACTIVE',currency:'INR',estimatedCostMinor:cost,estimatedDurationDays:5,resourceRequirements:[{category:'STRUCTURAL_ENGINEER',quantity,unit:'UNIT_DAYS'}],estimateBasis:'basis',sourceReference:'source',preparedAt:new Date(),preparedBy:actor});m.caseMany.mockResolvedValue([row('1',{riskLevel:RiskLevel.CRITICAL,resourceEstimates:[estimate('1',80n,2)]}),row('2',{priorityLevel:PriorityLevel.HIGH,resourceEstimates:[estimate('2',20n,2)]})]);const result:any=await createScenario({name:'Envelope',budgetMinor:100n,currency:'INR',resourceCapacities:[{category:'STRUCTURAL_ENGINEER',quantity:2,unit:'UNIT_DAYS'}]},principal);expect(result.algorithmVersion).toBe(PORTFOLIO_ALGORITHM_VERSION);expect(result.resultSnapshot.selected.map((x:any)=>x.caseId)).toEqual(['1']);expect(result.resultSnapshot.unselected[0]).toMatchObject({caseId:'2',status:'CONSTRAINT_EXCEEDED'});expect(m.scenarioCreate).toHaveBeenCalledWith({data:expect.objectContaining({inputSnapshot:expect.any(Array),resultSnapshot:expect.any(Object)}),select:expect.any(Object)});expect((m as any).caseUpdate).toBeUndefined()});
 it('uses explicit CRITICAL_UNFUNDED when the authoritative critical case exceeds budget',async()=>{m.caseMany.mockResolvedValue([row('1',{riskLevel:RiskLevel.CRITICAL,resourceEstimates:[{id:'e',caseId:'1',estimateVersion:1,status:'ACTIVE',currency:'INR',estimatedCostMinor:101n,estimatedDurationDays:1,resourceRequirements:[],estimateBasis:'basis',sourceReference:'source',preparedAt:new Date(),preparedBy:actor}]})]);const result:any=await createScenario({name:'Small budget',budgetMinor:100n,currency:'INR',resourceCapacities:[]},principal);expect(result.resultSnapshot).toMatchObject({criticalUnfundedCount:1,unselected:[expect.objectContaining({status:'CRITICAL_UNFUNDED'})]})});
 it('selects all fitting Cases and produces identical results for identical inputs',async()=>{const estimate=(id:string,cost:bigint)=>({id:`e-${id}`,caseId:id,estimateVersion:1,status:'ACTIVE',currency:'INR',estimatedCostMinor:cost,estimatedDurationDays:1,resourceRequirements:[],estimateBasis:'basis',sourceReference:'source',preparedAt:new Date(),preparedBy:actor});m.caseMany.mockResolvedValue([row('1',{resourceEstimates:[estimate('1',40n)]}),row('2',{priorityLevel:PriorityLevel.LOW,riskLevel:RiskLevel.LOW,resourceEstimates:[estimate('2',60n)]})]);const input={name:'Full fit',budgetMinor:100n,currency:'INR',resourceCapacities:[]} as const;const first:any=await createScenario(input,principal),second:any=await createScenario(input,principal);expect(first.resultSnapshot.selected.map((x:any)=>x.caseId)).toEqual(['1','2']);expect(first.resultSnapshot).toEqual(second.resultSnapshot)});
 it('keeps safety ordering dominant over cost and marks missing risk not ready',async()=>{const estimate=(id:string,cost:bigint)=>({id:`e-${id}`,caseId:id,estimateVersion:1,status:'ACTIVE',currency:'INR',estimatedCostMinor:cost,estimatedDurationDays:1,resourceRequirements:[],estimateBasis:'basis',sourceReference:'source',preparedAt:new Date(),preparedBy:actor});m.caseMany.mockResolvedValue([row('cheap',{priorityLevel:PriorityLevel.LOW,riskLevel:RiskLevel.LOW,resourceEstimates:[estimate('cheap',1n)]}),row('critical',{resourceEstimates:[estimate('critical',100n)]}),row('unknown',{riskLevel:null,resourceEstimates:[estimate('unknown',0n)]})]);const result=await listCandidates(principal,{limit:10});expect(result.items.map(x=>x.id)).toEqual(['critical','unknown','cheap']);expect(result.items[1].readiness.state).toBe('NOT_READY');expect(result.items.findIndex(x=>x.id==='critical')).toBeLessThan(result.items.findIndex(x=>x.id==='cheap'))});
 it('detects persisted scenario staleness from changed authoritative inputs',async()=>{const snapshot={caseId:'c1',updatedAt:'2026-08-24T00:00:00.000Z',riskLevel:'VERY_HIGH',priorityLevel:'CRITICAL',estimateId:'e1',estimateVersion:1};m.scenarioFirst.mockResolvedValue({id:'s1',scenarioVersion:1,name:'Saved',departmentId:'dep',jurisdictionId:'jur',budgetMinor:100n,currency:'INR',resourceCapacities:[],algorithmVersion:PORTFOLIO_ALGORITHM_VERSION,inputSnapshot:[snapshot],resultSnapshot:{},createdAt:new Date(),createdBy:actor});m.caseMany.mockResolvedValue([{id:'c1',updatedAt:new Date('2026-08-25'),riskLevel:'CRITICAL',priorityLevel:'CRITICAL',resourceEstimates:[{id:'e2',estimateVersion:2}]}]);const result=await getScenario('s1',principal);expect(result.staleness.status).toBe('STALE');expect(result.staleness.reasons[0]).toContain('inputs changed');expect(m.scenarioFirst.mock.calls[0][0].where).toEqual({id:'s1',departmentId:'dep',jurisdictionId:'jur'})});
 it('fails closed on a stale or foreign pagination cursor',async()=>{m.caseMany.mockResolvedValue([row('1')]);await expect(listCandidates(principal,{limit:25,cursor:{at:new Date().toISOString(),id:'foreign'}})).rejects.toBeInstanceOf(PortfolioError)});
});
