import express from 'express';import request from 'supertest';import{SignJWT}from'jose';import{beforeEach,describe,expect,it,vi}from'vitest';import{getAuthConfig}from'../src/config/auth';
const m=vi.hoisted(()=>({user:vi.fn(),createEstimate:vi.fn(),listEstimates:vi.fn(),listCandidates:vi.fn(),createScenario:vi.fn(),getScenario:vi.fn()}));
vi.mock('../src/lib/prisma',()=>({default:{user:{findUnique:m.user}}}));
vi.mock('../src/modules/portfolio/portfolio.service',()=>({resourceCategories:['STRUCTURAL_ENGINEER'],PortfolioError:class PortfolioError extends Error{constructor(public code:string,public status:number,message:string){super(message)}},createEstimate:m.createEstimate,listEstimates:m.listEstimates,listCandidates:m.listCandidates,createScenario:m.createScenario,getScenario:m.getScenario}));
import routes from'../src/modules/portfolio/portfolio.routes';const app=express();app.use(express.json());app.use('/api/v1',routes);const id='10000000-0000-4000-8000-000000000001';
async function auth(role='OFFICER'){const user={id:`u-${role}`,role,status:'ACTIVE',departmentId:'dep',jurisdictionId:'jur'};m.user.mockResolvedValue(user);const config=getAuthConfig();return`Bearer ${await new SignJWT({}).setProtectedHeader({alg:'HS256'}).setSubject(user.id).setIssuer(config.issuer).setAudience(config.audience).setIssuedAt().setExpirationTime('5m').sign(config.secret)}`}
beforeEach(()=>{vi.clearAllMocks();m.createEstimate.mockResolvedValue({id:'e'});m.listEstimates.mockResolvedValue([]);m.listCandidates.mockResolvedValue({items:[],nextCursor:null});m.createScenario.mockResolvedValue({id:'s'});m.getScenario.mockResolvedValue({id:'s'})});
describe('portfolio planning routes',()=>{
 it('requires authentication on every planning endpoint',async()=>{for(const path of[`/api/v1/cases/${id}/resource-estimates`,'/api/v1/portfolio/candidates',`/api/v1/portfolio-scenarios/${id}`])await request(app).get(path).expect(401);await request(app).post(`/api/v1/cases/${id}/resource-estimates`).send({}).expect(401);await request(app).post('/api/v1/portfolio-scenarios').send({}).expect(401)});
 it('binds the authenticated actor and converts validated minor units to bigint',async()=>{const token=await auth();await request(app).post(`/api/v1/cases/${id}/resource-estimates`).set('Authorization',token).send({estimatedCostMinor:'123456789012345',currency:'INR',estimatedDurationDays:2,resourceRequirements:[],estimateBasis:'Schedule basis',sourceReference:'SOR'}).expect(201);expect(m.createEstimate).toHaveBeenCalledWith(id,expect.objectContaining({estimatedCostMinor:123456789012345n}),expect.objectContaining({id:'u-OFFICER'}));await request(app).post('/api/v1/portfolio-scenarios').set('Authorization',token).send({name:'Envelope',budgetMinor:'10000',currency:'INR',resourceCapacities:[]}).expect(201);expect(m.createScenario).toHaveBeenCalledWith(expect.objectContaining({budgetMinor:10000n}),expect.objectContaining({id:'u-OFFICER'}))});
 it('rejects malformed money, currencies, resources and forged actor fields',async()=>{const token=await auth(),base={estimatedCostMinor:'100',currency:'INR',resourceRequirements:[],estimateBasis:'basis',sourceReference:'source'};for(const body of[{...base,estimatedCostMinor:'1.5'},{...base,currency:'USD'},{...base,preparedById:'forged'},{...base,resourceRequirements:[{category:'UNCONTROLLED',quantity:1,unit:'UNIT_DAYS'}]}])await request(app).post(`/api/v1/cases/${id}/resource-estimates`).set('Authorization',token).send(body).expect(400);expect(m.createEstimate).not.toHaveBeenCalled()});
 it('exposes scoped read operations to authenticated roles and validates pagination',async()=>{for(const role of['OFFICER','AUDITOR','POLICY_ADMIN','SYSTEM_ADMIN']){const token=await auth(role);await request(app).get(`/api/v1/cases/${id}/resource-estimates`).set('Authorization',token).expect(200);await request(app).get('/api/v1/portfolio/candidates?limit=100').set('Authorization',token).expect(200);await request(app).get(`/api/v1/portfolio-scenarios/${id}`).set('Authorization',token).expect(200)}await request(app).get('/api/v1/portfolio/candidates?limit=101').set('Authorization',await auth()).expect(400);await request(app).get('/api/v1/portfolio/candidates?cursor=bad').set('Authorization',await auth()).expect(400)});
});
