import { beforeEach, describe, expect, it, vi } from 'vitest';
import { PredictiveProvenanceClass, PredictiveRecordStatus, SystemRole } from '../src/generated/prisma';
const mocks=vi.hoisted(()=>({task:vi.fn(),snapshotUpsert:vi.fn(),snapshotFindMany:vi.fn(),outcomeUpsert:vi.fn(),workflowWrite:vi.fn()}));
vi.mock('../src/lib/prisma',()=>({default:{executionTask:{findUnique:mocks.task,update:mocks.workflowWrite},caseResourceEstimate:{findFirst:vi.fn(async()=>null)},predictiveFeatureSnapshot:{upsert:mocks.snapshotUpsert,findMany:mocks.snapshotFindMany,updateMany:vi.fn()},predictiveOutcome:{upsert:mocks.outcomeUpsert,updateMany:vi.fn()},case:{update:mocks.workflowWrite},riskAssessment:{update:mocks.workflowWrite},executionPlan:{update:mocks.workflowWrite}}}));
import { captureTaskAssignmentSnapshot, captureTaskOutcome, getTaskLatenessDataset } from '../src/modules/predictive-data/predictive-data.service';
const ids={task:'00000000-0000-4000-8000-000000000001',plan:'00000000-0000-4000-8000-000000000002',case:'00000000-0000-4000-8000-000000000003',asset:'00000000-0000-4000-8000-000000000004',dep:'00000000-0000-4000-8000-000000000005',jur:'00000000-0000-4000-8000-000000000006',to:'00000000-0000-4000-8000-000000000007',by:'00000000-0000-4000-8000-000000000008'};
const assignedAt=new Date('2026-01-01T00:00:00Z');
const assignment={id:ids.task,executionPlanId:ids.plan,sourceActionCode:'ACT_INSPECT',sourceActionVersion:1,templateTaskKey:'INSPECT',sourceTemplateCode:'TPL',sourceTemplateVersion:1,categorySnapshot:'INSPECTION',isMandatory:true,plannedStartAt:assignedAt,plannedEndAt:new Date('2026-01-02T00:00:00Z'),assignedAt,assignedToId:ids.to,assignedById:ids.by,dependencies:[],scheduleRevisions:[],executionPlan:{case:{id:ids.case,riskLevel:'VERY_HIGH',priorityLevel:'CRITICAL',emergencyFlag:false,asset:{id:ids.asset,assetCode:'BR-101',departmentId:ids.dep,jurisdictionId:ids.jur,assetType:'BRIDGE',constructionYear:1995,conditionStatus:'POOR'}}}};
describe('predictive data collection service',()=>{beforeEach(()=>{vi.clearAllMocks();mocks.task.mockResolvedValue(assignment);mocks.snapshotUpsert.mockResolvedValue({id:'snapshot'});mocks.outcomeUpsert.mockResolvedValue({id:'outcome'})});
 it('captures assignment idempotently by the governed task/target/contract key without workflow writes',async()=>{await captureTaskAssignmentSnapshot(ids.task,ids.by);await captureTaskAssignmentSnapshot(ids.task,ids.by);const calls=mocks.snapshotUpsert.mock.calls.map(([arg])=>arg.where.executionTaskId_targetType_featureContractVersion);expect(calls[0]).toEqual(calls[1]);expect(mocks.snapshotUpsert).toHaveBeenCalledTimes(2);expect(mocks.workflowWrite).not.toHaveBeenCalled();const create=mocks.snapshotUpsert.mock.calls[0][0].create;expect(create.provenanceClass).toBe(PredictiveProvenanceClass.DEMO);expect(JSON.stringify(create.featurePayload)).not.toMatch(/completion|verified|reporter|evidence|password/i)});
 it('records a later objective outcome against the immutable snapshot',async()=>{mocks.task.mockResolvedValue({completionSubmittedAt:new Date('2026-01-03T00:00:00Z'),cancelledAt:null,predictiveSnapshots:[{id:'snapshot',predictionTimestamp:assignedAt,featurePayload:mocks.snapshotUpsert.mock.calls[0]?.[0]?.create?.featurePayload??{...awaitFeature()},provenanceClass:PredictiveProvenanceClass.PILOT,sourceFingerprint:'source'}]});await captureTaskOutcome(ids.task,'COMPLETION',ids.by);expect(mocks.outcomeUpsert).toHaveBeenCalledWith(expect.objectContaining({create:expect.objectContaining({outcomeValue:'LATE'})}));expect(mocks.workflowWrite).not.toHaveBeenCalled()});
 it('requests only real provenance by default and returns a deterministic empty export',async()=>{mocks.snapshotFindMany.mockResolvedValue([]);const result=await getTaskLatenessDataset({id:ids.by,role:SystemRole.AUDITOR,status:'ACTIVE',departmentId:ids.dep,jurisdictionId:ids.jur} as any,{includeDemo:false,limit:25,offset:0});expect(mocks.snapshotFindMany).toHaveBeenCalledWith(expect.objectContaining({where:expect.objectContaining({departmentId:ids.dep,jurisdictionId:ids.jur,provenanceClass:{in:['PRODUCTION','PILOT']}})}));expect(result.items).toEqual([]);expect(result.manifest.eligibleSampleCount).toBe(0)});
 it('traverses a complete scoped export in bounded keyset batches',async()=>{const rows=Array.from({length:500},(_,index)=>({id:`snapshot-${String(index).padStart(4,'0')}`,featurePayload:{},provenanceClass:PredictiveProvenanceClass.PILOT,outcomes:[]}));mocks.snapshotFindMany.mockResolvedValueOnce(rows).mockResolvedValueOnce([]);const result=await getTaskLatenessDataset({id:ids.by,role:SystemRole.AUDITOR,status:'ACTIVE',departmentId:ids.dep,jurisdictionId:ids.jur} as any,{includeDemo:false,limit:25,offset:0});expect(mocks.snapshotFindMany).toHaveBeenCalledTimes(2);expect(mocks.snapshotFindMany.mock.calls[0][0]).toEqual(expect.objectContaining({take:500,orderBy:{id:'asc'}}));expect(mocks.snapshotFindMany.mock.calls[1][0].where.id).toEqual({gt:'snapshot-0499'});expect(result.manifest.invalidCount).toBe(500);expect(result.items).toEqual([])});
});
function awaitFeature(){return{executionTaskId:ids.task,caseId:ids.case,assetId:ids.asset,departmentId:ids.dep,jurisdictionId:ids.jur,sourceActionCode:'ACT_INSPECT',sourceActionVersion:1,templateTaskKey:'INSPECT',sourceTemplateCode:'TPL',sourceTemplateVersion:1,categorySnapshot:'INSPECTION',isMandatory:true,plannedStartAt:'2026-01-01T00:00:00.000Z',plannedEndAt:'2026-01-02T00:00:00.000Z',assignedAt:'2026-01-01T00:00:00.000Z',assignedToId:ids.to,assignedById:ids.by,caseRiskLevel:'VERY_HIGH',casePriorityLevel:'CRITICAL',emergencyFlag:false,assetType:'BRIDGE',constructionYear:1995,conditionStatus:'POOR',dependencyCount:0,unmetDependencyCount:0,scheduleRevisionCount:0,activeEstimate:null}}
