import { describe, expect, it } from 'vitest';
import { projectPublicTracking } from '../src/modules/public-reports/public-tracking.service';
const date=(value:string)=>new Date(value);
function record(status='SUBMITTED',caseStatus?:string){return {reportNumber:'JNV-PUB-20260819-12EE4F',title:'Flyover surface deterioration',category:'BRIDGE_OR_FLYOVER',locationText:'University Road flyover, Pune',submittedAt:date('2026-08-19T08:00:00Z'),status,reviewStartedAt:status==='SUBMITTED'?null:date('2026-08-19T09:00:00Z'),decisionAt:['ACCEPTED','REJECTED'].includes(status)?date('2026-08-19T10:00:00Z'):null,createdCase:caseStatus?{caseNumber:'CASE-PUB-260819-7ABAA4',status:caseStatus,createdAt:date('2026-08-19T10:00:00Z'),closedAt:caseStatus==='CLOSED'?date('2026-08-24T10:00:00Z'):null,inspections:[{createdAt:date('2026-08-20T10:00:00Z')}],operationalResponsePlans:[{createdAt:date('2026-08-21T10:00:00Z')}],executionPlans:[{createdAt:date('2026-08-22T09:00:00Z'),startedAt:date('2026-08-22T10:00:00Z'),completedAt:date('2026-08-23T10:00:00Z')}],closure:caseStatus==='CLOSED'?{createdAt:date('2026-08-24T10:00:00Z')}:null}:null,reporterName:'Sensitive Citizen',reporterContact:'secret@example.test',reviewedById:'officer-id',rejectionReason:'internal notes',triageAnalyses:[{confidence:99}],riskLevel:'CRITICAL',riskScore:99} as never;}
describe('public tracking projection',()=>{
 it.each([['SUBMITTED',undefined,'REPORT_RECEIVED'],['UNDER_REVIEW',undefined,'UNDER_GOVERNMENT_REVIEW'],['REJECTED',undefined,'CLOSED_AFTER_REVIEW'],['ACCEPTED','NEW','CASE_RECORDED'],['ACCEPTED','INSPECTION_IN_PROGRESS','ASSESSMENT_IN_PROGRESS'],['ACCEPTED','UNDER_ANALYSIS','ASSESSMENT_IN_PROGRESS'],['ACCEPTED','ORP_READY','ACTION_PLANNED'],['ACCEPTED','UNDER_REVIEW','ACTION_PLANNED'],['ACCEPTED','APPROVED','ACTION_IN_PROGRESS'],['ACCEPTED','EXECUTION','ACTION_IN_PROGRESS'],['ACCEPTED','VERIFICATION','VERIFICATION'],['ACCEPTED','CLOSED','RESOLVED'],['ACCEPTED','CANCELLED','RESOLVED']])('translates %s / %s truthfully',(reportStatus,caseStatus,expected)=>expect(projectPublicTracking(record(reportStatus,caseStatus))).toMatchObject({status:expected}));
 it('constructs an allow-listed DTO with no sensitive internals',()=>{const dto=projectPublicTracking(record('ACCEPTED','EXECUTION'));expect(Object.keys(dto).sort()).toEqual(['caseReference','category','governedCaseCreated','lastProgressAt','locationText','outcome','reportReference','status','statusLabel','submittedAt','timeline','title'].sort());const body=JSON.stringify(dto);for(const secret of ['Sensitive Citizen','secret@example.test','officer-id','internal notes','confidence','riskScore','riskLevel','operationalResponsePlans','executionPlans','createdCaseId','reviewedById'])expect(body).not.toContain(secret);});
 it('uses authoritative timestamps and never manufactures missing milestone dates',()=>{const input=record('ACCEPTED','NEW') as any;input.createdCase.inspections=[];input.createdCase.operationalResponsePlans=[];input.createdCase.executionPlans=[];const dto=projectPublicTracking(input);expect(dto.timeline.find((item)=>item.key==='RECEIVED')?.occurredAt).toEqual(input.submittedAt);expect(dto.timeline.find((item)=>item.key==='CASE')?.occurredAt).toEqual(input.createdCase.createdAt);expect(dto.timeline.find((item)=>item.key==='ASSESSMENT')?.occurredAt).toBeNull();expect(dto.timeline.find((item)=>item.key==='ACTION')?.occurredAt).toBeNull();});
 it('does not disclose the persisted rejection reason',()=>{const dto=projectPublicTracking(record('REJECTED'));expect(dto.statusLabel).toBe('Closed after government review');expect(JSON.stringify(dto)).not.toContain('internal notes');});
});
