import express from 'express';import request from 'supertest';import {SignJWT} from 'jose';import {expect,it,vi} from 'vitest';
import {getAuthConfig} from '../src/config/auth';
const mocks=vi.hoisted(()=>({user:vi.fn(),snapshot:vi.fn()}));
vi.mock('../src/lib/prisma',()=>({default:{user:{findUnique:mocks.user}}}));
vi.mock('../src/modules/assets/recorded-outcomes.repository',async original=>({...await original<any>(),createRecordedOutcomesRepository:()=>({snapshot:mocks.snapshot})}));
import router from '../src/modules/assets/asset.routes';
import {OutcomeRepositoryError} from '../src/modules/assets/recorded-outcomes.repository';
const app=express();app.use('/api/v1/assets',router);const id='00000000-0000-4000-8000-000000000001';
async function auth(role='OFFICER') {mocks.user.mockResolvedValue({id:'u',role,status:'ACTIVE',departmentId:'d',jurisdictionId:'j'});const c=getAuthConfig();return `Bearer ${await new SignJWT({}).setProtectedHeader({alg:'HS256'}).setSubject('u').setIssuer(c.issuer).setAudience(c.audience).setIssuedAt().setExpirationTime('5m').sign(c.secret)}`;}
function healthy(){mocks.snapshot.mockResolvedValue({complete:true,asOf:'2026-01-01T00:00:00.000Z',sources:{assets:[{id}],cases:[],inspections:[],assessments:[],plans:[],tasks:[],evidence:[],closures:[],estimates:[]},coverage:{zeroCaseAssets:1},sourceFingerprint:'hash'});}
it('protects both mounted routes',async()=>{await request(app).get(`/api/v1/assets/${id}/outcomes`).expect(401);await request(app).get('/api/v1/assets/outcomes/summary').expect(401);});
it.each(['OFFICER','SYSTEM_ADMIN','AUDITOR','POLICY_ADMIN'])('uses existing scoped read principal %s',async role=>{healthy();const token=await auth(role);await request(app).get(`/api/v1/assets/${id}/outcomes`).set('Authorization',token).expect(200);expect(mocks.snapshot.mock.lastCall).toEqual([expect.objectContaining({role}),{assetId:id}]);const r=await request(app).get('/api/v1/assets/outcomes/summary').set('Authorization',token).expect(200);expect(r.body.data).not.toHaveProperty('items');expect(mocks.snapshot.mock.lastCall?.[1]).toEqual({});});
it('maps inaccessible asset and failed read to safe responses',async()=>{const token=await auth();mocks.snapshot.mockRejectedValue(new OutcomeRepositoryError('ASSET_NOT_FOUND'));await request(app).get(`/api/v1/assets/${id}/outcomes`).set('Authorization',token).expect(404);mocks.snapshot.mockRejectedValue(new Error('password PRIVATE_SENTINEL'));const r=await request(app).get('/api/v1/assets/outcomes/summary').set('Authorization',token).expect(503);expect(JSON.stringify(r.body)).not.toMatch(/password|PRIVATE_SENTINEL/);expect(r.body).not.toHaveProperty('data');});
it('rejects malformed IDs and query overrides',async()=>{healthy();const token=await auth();await request(app).get('/api/v1/assets/bad/outcomes').set('Authorization',token).expect(400);await request(app).get('/api/v1/assets/outcomes/summary?departmentId=other').set('Authorization',token).expect(400);});
