import{execFileSync}from'node:child_process';import{mkdtempSync,readFileSync,rmSync}from'node:fs';import{tmpdir}from'node:os';import{join,resolve}from'node:path';import{afterEach,describe,expect,it}from'vitest';
const apiRoot=resolve(__dirname,'..'),repoRoot=resolve(apiRoot,'../..'),temporary:string[]=[];
afterEach(()=>{for(const directory of temporary.splice(0))rmSync(directory,{recursive:true,force:true});});
describe('local runtime startup architecture',()=>{
 it('does not use the failing tsx launcher for the API development command',()=>{const pkg=JSON.parse(readFileSync(join(apiRoot,'package.json'),'utf8'));expect(pkg.scripts.dev).toBe('npm run build && node dist/server.js');expect(pkg.scripts.dev).not.toContain('tsx');});
 it('packages a complete generated Prisma runtime into a clean target',()=>{const target=mkdtempSync(join(tmpdir(),'janseva-prisma-runtime-'));temporary.push(target);execFileSync(process.execPath,[join(apiRoot,'scripts/copy-generated-prisma.cjs'),'--target',target],{stdio:'pipe'});expect(readFileSync(join(target,'index.js'),'utf8')).toContain('PrismaClient');expect(readFileSync(join(target,'schema.prisma'),'utf8')).toContain('datasource db');});
 it('keeps the build responsible for packaging Prisma',()=>{const pkg=JSON.parse(readFileSync(join(apiRoot,'package.json'),'utf8'));expect(pkg.scripts.build).toContain('copy-generated-prisma.cjs');});
 it('provides one supervised root development command with Windows-safe launch and process-tree shutdown',()=>{const pkg=JSON.parse(readFileSync(join(repoRoot,'package.json'),'utf8'));const supervisor=readFileSync(join(repoRoot,'scripts/dev.mjs'),'utf8');expect(pkg.scripts.dev).toBe('node scripts/dev.mjs');expect(supervisor).toContain('process.env.npm_execpath');expect(supervisor).toContain('apps/api/');expect(supervisor).toContain('apps/web/');expect(supervisor).toContain('--strictPort');expect(supervisor).toContain("spawnSync('taskkill'");expect(supervisor).toContain('Stopping the local JanSeva workspace');});
});
