import { Prisma } from '../generated/prisma';import prisma from '../lib/prisma';import { getRuntimeConfig,type RuntimeConfig } from '../config/runtime';import { getProcessHealthState } from './state';
export type DependencyStatus='AVAILABLE'|'UNAVAILABLE'|'DISABLED'|'CONFIGURED_UNKNOWN';
export type HealthStatus='READY'|'DEGRADED'|'NOT_READY';
export type DatabaseProbe=()=>Promise<void>;export type AiProbe=()=>Promise<boolean>;
const bounded=<T>(promise:Promise<T>,timeoutMs:number)=>new Promise<T>((resolve,reject)=>{const timer=setTimeout(()=>reject(new Error('DEPENDENCY_TIMEOUT')),timeoutMs);promise.then(value=>{clearTimeout(timer);resolve(value)},error=>{clearTimeout(timer);reject(error)})});
export const databaseProbe:DatabaseProbe=async()=>{await prisma.$queryRaw(Prisma.sql`SELECT 1`)};
async function defaultAiProbe(config:RuntimeConfig){if(!config.intelligence.serviceUrl)return false;const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),Math.min(config.intelligence.timeoutMs,2000));try{const response=await fetch(new URL('/health',config.intelligence.serviceUrl),{signal:controller.signal,headers:{Accept:'application/json'}});return response.ok}catch{return false}finally{clearTimeout(timer)}}
export async function evaluateHealth(options:{config?:RuntimeConfig;db?:DatabaseProbe;ai?:AiProbe;timeoutMs?:number}={}){const config=options.config??getRuntimeConfig(),started=performance.now();let database:DependencyStatus='UNAVAILABLE';try{await bounded((options.db??databaseProbe)(),options.timeoutMs??1500);database='AVAILABLE'}catch{}
 let ai:DependencyStatus='DISABLED';if(config.intelligence.enabled)ai=await(options.ai?options.ai():defaultAiProbe(config))?'AVAILABLE':'UNAVAILABLE';const weather:DependencyStatus=config.weatherProvider.enabled?'CONFIGURED_UNKNOWN':'DISABLED';const processState=getProcessHealthState();const status:HealthStatus=database!=='AVAILABLE'||processState==='SHUTTING_DOWN'?'NOT_READY':ai==='UNAVAILABLE'||weather==='CONFIGURED_UNKNOWN'?'DEGRADED':'READY';return{status,processState,checkedAt:new Date().toISOString(),durationMs:Math.round((performance.now()-started)*100)/100,dependencies:{database:{status:database,mandatory:true},advisoryIntelligence:{status:ai,mandatory:false},weatherProvider:{status:weather,mandatory:false,deploymentClass:config.weatherProvider.deploymentClass,provider:config.weatherProvider.provider}},migrationStatus:{status:'DEPLOYMENT_PREFLIGHT',detail:'Prisma migrate status is enforced by deployment procedure and is not executed per health request.'}}}
