import prisma from '../../lib/prisma';
import { PredictiveOutcomeValue, PredictiveProvenanceClass, PredictiveRecordStatus, PredictiveTargetType, Prisma, SystemRole } from '../../generated/prisma';
import type { OrganizationalPrincipal } from '../../security/organizational-scope';
import { PREDICTIVE_DATASET_CONTRACT_VERSION, TASK_LATENESS_FEATURE_CONTRACT_VERSION, TASK_LATENESS_OUTCOME_CONTRACT_VERSION, classifyPredictiveProvenance, deriveTaskLatenessOutcome, predictiveFingerprint, taskLatenessFeatureSchema } from './predictive-data.contracts';
import { appendIntegrityEvent, integrityTextDigest } from '../integrity/integrity.service';

export class PredictiveDataError extends Error { constructor(public code:string,public status:number,message:string){super(message);} }
const scopeWhere=(principal:OrganizationalPrincipal)=>principal.role===SystemRole.SYSTEM_ADMIN?{}:{departmentId:principal.departmentId,jurisdictionId:principal.jurisdictionId};

type PredictiveActor=OrganizationalPrincipal|string;
const predictiveActor=(value:PredictiveActor)=>typeof value==='string'?{id:value,role:SystemRole.OFFICER}:value;
export async function captureTaskAssignmentSnapshot(taskId:string,actorValue:PredictiveActor){
 return prisma.$transaction(async tx=>{
  const task=await tx.executionTask.findUnique({where:{id:taskId},include:{executionPlan:{include:{case:{include:{asset:true}}}},dependencies:{include:{predecessorTask:{select:{status:true}}}},scheduleRevisions:true}});
  if(!task?.assignedAt||!task.assignedToId||!task.assignedById)return null;
  const {case:targetCase}=task.executionPlan,asset=targetCase.asset,estimate=await tx.caseResourceEstimate.findFirst({where:{caseId:targetCase.id,preparedAt:{lte:task.assignedAt}},orderBy:[{estimateVersion:'desc'},{id:'desc'}]});
  const feature={executionTaskId:task.id,caseId:targetCase.id,assetId:asset.id,departmentId:asset.departmentId,jurisdictionId:asset.jurisdictionId,sourceActionCode:task.sourceActionCode,sourceActionVersion:task.sourceActionVersion,templateTaskKey:task.templateTaskKey,sourceTemplateCode:task.sourceTemplateCode,sourceTemplateVersion:task.sourceTemplateVersion,categorySnapshot:task.categorySnapshot,isMandatory:task.isMandatory,plannedStartAt:task.plannedStartAt?.toISOString()??null,plannedEndAt:task.plannedEndAt?.toISOString()??null,assignedAt:task.assignedAt.toISOString(),assignedToId:task.assignedToId,assignedById:task.assignedById,caseRiskLevel:targetCase.riskLevel,casePriorityLevel:targetCase.priorityLevel,emergencyFlag:targetCase.emergencyFlag,assetType:asset.assetType,constructionYear:asset.constructionYear,conditionStatus:asset.conditionStatus,dependencyCount:task.dependencies.length,unmetDependencyCount:task.dependencies.filter(item=>item.predecessorTask.status!=='VERIFIED').length,scheduleRevisionCount:task.scheduleRevisions.filter(item=>item.changedAt<=task.assignedAt!).length,activeEstimate:estimate?{estimateId:estimate.id,estimateVersion:estimate.estimateVersion,currency:estimate.currency,estimatedCostMinor:estimate.estimatedCostMinor.toString(),estimatedDurationDays:estimate.estimatedDurationDays,resourceRequirements:estimate.resourceRequirements}:null};
  const parsed=taskLatenessFeatureSchema.parse(feature),provenanceClass=classifyPredictiveProvenance(asset.assetCode),sourceReferences={executionTaskId:task.id,executionPlanId:task.executionPlanId,caseId:targetCase.id,assetId:asset.id},sourceFingerprint=predictiveFingerprint({contract:TASK_LATENESS_FEATURE_CONTRACT_VERSION,feature:parsed});
  const snapshot=await tx.predictiveFeatureSnapshot.upsert({where:{executionTaskId_targetType_featureContractVersion:{executionTaskId:task.id,targetType:PredictiveTargetType.TASK_LATENESS,featureContractVersion:TASK_LATENESS_FEATURE_CONTRACT_VERSION}},update:{},create:{targetType:PredictiveTargetType.TASK_LATENESS,executionTaskId:task.id,caseId:targetCase.id,assetId:asset.id,departmentId:asset.departmentId,jurisdictionId:asset.jurisdictionId,predictionTimestamp:task.assignedAt,featureContractVersion:TASK_LATENESS_FEATURE_CONTRACT_VERSION,featurePayload:parsed as Prisma.InputJsonValue,provenanceClass,sourceReferences,sourceFingerprint,createdById:predictiveActor(actorValue).id}});
  await appendIntegrityEvent(tx,{eventType:'PREDICTIVE_FEATURE_SNAPSHOT_CREATED',sourceEventKey:`PREDICTIVE_FEATURE_SNAPSHOT:${snapshot.id}`,resourceType:'PredictiveFeatureSnapshot',resourceId:snapshot.id,actor:predictiveActor(actorValue),departmentId:snapshot.departmentId??asset.departmentId,jurisdictionId:snapshot.jurisdictionId??asset.jurisdictionId,occurredAt:snapshot.createdAt??new Date(),facts:{targetType:snapshot.targetType??PredictiveTargetType.TASK_LATENESS,executionTaskId:snapshot.executionTaskId??task.id,caseId:snapshot.caseId??targetCase.id,assetId:snapshot.assetId??asset.id,predictionTimestamp:(snapshot.predictionTimestamp??task.assignedAt).toISOString(),featureContractVersion:snapshot.featureContractVersion??TASK_LATENESS_FEATURE_CONTRACT_VERSION,provenanceClass:snapshot.provenanceClass??provenanceClass,sourceFingerprint:snapshot.sourceFingerprint??sourceFingerprint,status:snapshot.status??PredictiveRecordStatus.ACTIVE}});return snapshot;
 });
}

export async function captureTaskOutcome(taskId:string,event:'COMPLETION'|'CANCELLED',actorValue:PredictiveActor){
 return prisma.$transaction(async tx=>{
  const task=await tx.executionTask.findUnique({where:{id:taskId},select:{completionSubmittedAt:true,cancelledAt:true,predictiveSnapshots:{where:{targetType:PredictiveTargetType.TASK_LATENESS,status:PredictiveRecordStatus.ACTIVE},orderBy:{createdAt:'desc'},take:1}}});
  const snapshot=task?.predictiveSnapshots[0];if(!task||!snapshot)return null;
  const parsed=taskLatenessFeatureSchema.safeParse(snapshot.featurePayload);if(!parsed.success)return null;
  const outcomeTimestamp=event==='CANCELLED'?task.cancelledAt:task.completionSubmittedAt;if(!outcomeTimestamp||outcomeTimestamp<=snapshot.predictionTimestamp)return null;
  const outcomeValue=deriveTaskLatenessOutcome(parsed.data.plannedEndAt,outcomeTimestamp,event==='CANCELLED');if(!outcomeValue)return null;
  const refs={executionTaskId:taskId,snapshotId:snapshot.id,event};
  const outcome=await tx.predictiveOutcome.upsert({where:{snapshotId_outcomeContractVersion:{snapshotId:snapshot.id,outcomeContractVersion:TASK_LATENESS_OUTCOME_CONTRACT_VERSION}},update:{},create:{snapshotId:snapshot.id,outcomeContractVersion:TASK_LATENESS_OUTCOME_CONTRACT_VERSION,outcomeTimestamp,outcomeValue,provenanceClass:snapshot.provenanceClass,sourceReferences:refs,sourceFingerprint:predictiveFingerprint({contract:TASK_LATENESS_OUTCOME_CONTRACT_VERSION,snapshot:snapshot.sourceFingerprint,outcomeTimestamp:outcomeTimestamp.toISOString(),outcomeValue}),recordedById:predictiveActor(actorValue).id}});
  await appendIntegrityEvent(tx,{eventType:'PREDICTIVE_OUTCOME_RECORDED',sourceEventKey:`PREDICTIVE_OUTCOME:${outcome.id}`,resourceType:'PredictiveOutcome',resourceId:outcome.id,actor:predictiveActor(actorValue),departmentId:snapshot.departmentId??parsed.data.departmentId,jurisdictionId:snapshot.jurisdictionId??parsed.data.jurisdictionId,occurredAt:outcome.recordedAt??new Date(),facts:{snapshotId:outcome.snapshotId??snapshot.id,outcomeContractVersion:outcome.outcomeContractVersion??TASK_LATENESS_OUTCOME_CONTRACT_VERSION,outcomeTimestamp:(outcome.outcomeTimestamp??outcomeTimestamp).toISOString(),outcomeValue:outcome.outcomeValue??outcomeValue,provenanceClass:outcome.provenanceClass??snapshot.provenanceClass,sourceFingerprint:outcome.sourceFingerprint??predictiveFingerprint({contract:TASK_LATENESS_OUTCOME_CONTRACT_VERSION,snapshot:snapshot.sourceFingerprint,outcomeTimestamp:outcomeTimestamp.toISOString(),outcomeValue}),status:outcome.status??PredictiveRecordStatus.ACTIVE,event}});return outcome;
 });
}

export async function collectAssignmentBestEffort(taskId:string,actorValue:PredictiveActor){try{await captureTaskAssignmentSnapshot(taskId,actorValue);}catch(error){console.error('PREDICTIVE_COLLECTION_ASSIGNMENT_FAILED',{taskId,error:error instanceof Error?error.message:'unknown'});}}
export async function collectOutcomeBestEffort(taskId:string,event:'COMPLETION'|'CANCELLED',actorValue:PredictiveActor){try{await captureTaskOutcome(taskId,event,actorValue);}catch(error){console.error('PREDICTIVE_COLLECTION_OUTCOME_FAILED',{taskId,event,error:error instanceof Error?error.message:'unknown'});}}

function allowedProvenance(principal:OrganizationalPrincipal,includeDemo:boolean){if(includeDemo&&principal.role!==SystemRole.SYSTEM_ADMIN)throw new PredictiveDataError('FORBIDDEN',403,'Demo dataset access requires system administration authority.');return includeDemo?undefined:{in:[PredictiveProvenanceClass.PRODUCTION,PredictiveProvenanceClass.PILOT]};}
const DATASET_SCAN_BATCH_SIZE=500;
async function scopedRows(principal:OrganizationalPrincipal,includeDemo:boolean,cursor?:string,enforceDemoAuthority=true){const provenance=enforceDemoAuthority?allowedProvenance(principal,includeDemo):undefined;return prisma.predictiveFeatureSnapshot.findMany({where:{targetType:PredictiveTargetType.TASK_LATENESS,status:PredictiveRecordStatus.ACTIVE,...scopeWhere(principal),...(provenance?{provenanceClass:provenance}:{}),...(cursor?{id:{gt:cursor}}:{})},include:{outcomes:{where:{status:PredictiveRecordStatus.ACTIVE},orderBy:{recordedAt:'desc'},take:1}},orderBy:{id:'asc'},take:DATASET_SCAN_BATCH_SIZE});}
function analyze(rows:Awaited<ReturnType<typeof scopedRows>>){const eligible:any[]=[],pending:any[]=[],invalid:any[]=[],cancelled:any[]=[];for(const row of rows){const feature=taskLatenessFeatureSchema.safeParse(row.featurePayload),outcome=row.outcomes[0];if(!feature.success||!feature.data.plannedEndAt){invalid.push(row);continue;}if(!outcome){pending.push(row);continue;}if(outcome.outcomeTimestamp<=row.predictionTimestamp){invalid.push(row);continue;}if(outcome.outcomeValue===PredictiveOutcomeValue.CANCELLED){cancelled.push(row);continue;}eligible.push({snapshotId:row.id,outcomeId:outcome.id,predictionTimestamp:row.predictionTimestamp.toISOString(),outcomeTimestamp:outcome.outcomeTimestamp.toISOString(),label:outcome.outcomeValue,provenanceClass:row.provenanceClass,featureContractVersion:row.featureContractVersion,outcomeContractVersion:outcome.outcomeContractVersion,features:feature.data,sourceReferences:row.sourceReferences});}return{eligible,pending,invalid,cancelled};}
export async function getTaskLatenessDataset(principal:OrganizationalPrincipal,input:{includeDemo:boolean;limit:number;offset:number}){let cursor:string|undefined,eligibleSampleCount=0,pendingOutcomeCount=0,invalidCount=0,cancelledCount=0,late=0,onTime=0,from:string|null=null,to:string|null=null;const page:any[]=[],identities:Array<{snapshotId:string;outcomeId:string}>=[];do{const rows=await scopedRows(principal,input.includeDemo,cursor);if(!rows.length)break;cursor=rows.at(-1)!.id;const batch=analyze(rows);pendingOutcomeCount+=batch.pending.length;invalidCount+=batch.invalid.length;cancelledCount+=batch.cancelled.length;for(const item of batch.eligible){if(eligibleSampleCount>=input.offset&&page.length<input.limit)page.push(item);eligibleSampleCount++;identities.push({snapshotId:item.snapshotId,outcomeId:item.outcomeId});if(item.label==='LATE')late++;else onTime++;if(!from||item.predictionTimestamp<from)from=item.predictionTimestamp;if(!to||item.predictionTimestamp>to)to=item.predictionTimestamp;}if(rows.length<DATASET_SCAN_BATCH_SIZE)break;}while(true);const datasetFingerprint=predictiveFingerprint(identities);return{contractVersion:PREDICTIVE_DATASET_CONTRACT_VERSION,targetType:'TASK_LATENESS',generatedAt:new Date().toISOString(),manifest:{eligibleSampleCount,pendingOutcomeCount,invalidCount,cancelledCount,scope:scopeWhere(principal),includedProvenance:input.includeDemo?'ALL':'PRODUCTION_PILOT_ONLY',classBalance:{LATE:late,ON_TIME:onTime},dateRange:from&&to?{from,to}:null,datasetFingerprint},items:page,nextOffset:input.offset+input.limit<eligibleSampleCount?input.offset+input.limit:null};}
export async function getPredictiveReadiness(principal:OrganizationalPrincipal){let cursor:string|undefined,snapshots=0,eligibleRealOutcomes=0,pendingRealOutcomes=0,invalidRealRecords=0;const counts=Object.fromEntries(Object.values(PredictiveProvenanceClass).map(p=>[p,0])) as Record<string,number>;do{const rows=await scopedRows(principal,true,cursor,false);if(!rows.length)break;cursor=rows.at(-1)!.id;snapshots+=rows.length;for(const row of rows)counts[row.provenanceClass]++;const real=analyze(rows.filter(row=>row.provenanceClass===PredictiveProvenanceClass.PRODUCTION||row.provenanceClass===PredictiveProvenanceClass.PILOT));eligibleRealOutcomes+=real.eligible.length;pendingRealOutcomes+=real.pending.length;invalidRealRecords+=real.invalid.length;if(rows.length<DATASET_SCAN_BATCH_SIZE)break;}while(true);return{state:eligibleRealOutcomes===0?'NO_REAL_OUTCOMES':pendingRealOutcomes?'COLLECTING':'REVIEW_REQUIRED',modelStatus:'NO_MODEL_YET',disclosures:['ODYSSEY is collecting governed historical outcomes for future validation. No predictive model is trained or deployed from this data.','Demo and synthetic records are excluded from real predictive datasets by default.'],targetContracts:[{targetType:'TASK_LATENESS',status:'COLLECTING',featureContractVersion:TASK_LATENESS_FEATURE_CONTRACT_VERSION,outcomeContractVersion:TASK_LATENESS_OUTCOME_CONTRACT_VERSION},{targetType:'PLAN_DELAY',status:'FUTURE_EXTENSION'},{targetType:'ASSET_DETERIORATION',status:'FUTURE_EXTENSION'}],counts:{snapshots,eligibleRealOutcomes,pendingRealOutcomes,invalidRealRecords,provenance:counts}};}
export async function voidSnapshot(id:string,reason:string,replacementSnapshotId:string|undefined,principal:OrganizationalPrincipal){return prisma.$transaction(async tx=>{const current=await tx.predictiveFeatureSnapshot.findUnique({where:{id}});if(!current||current.status!==PredictiveRecordStatus.ACTIVE)throw new PredictiveDataError('PREDICTIVE_SNAPSHOT_NOT_FOUND',404,'Active predictive snapshot not found.');const updated=await tx.predictiveFeatureSnapshot.update({where:{id},data:{status:PredictiveRecordStatus.VOID,voidedAt:new Date(),voidedById:principal.id,voidReason:reason,replacementSnapshotId}});await appendIntegrityEvent(tx,{eventType:'PREDICTIVE_FEATURE_SNAPSHOT_VOIDED',sourceEventKey:`PREDICTIVE_FEATURE_SNAPSHOT_VOIDED:${id}`,resourceType:'PredictiveFeatureSnapshot',resourceId:id,actor:principal,departmentId:updated.departmentId,jurisdictionId:updated.jurisdictionId,occurredAt:updated.voidedAt!,facts:{targetType:updated.targetType,sourceFingerprint:updated.sourceFingerprint,status:updated.status,voidedById:principal.id,voidReasonDigest:integrityTextDigest(updated.voidReason),replacementSnapshotId:updated.replacementSnapshotId}});return{id,status:'VOID'};});}
export async function voidOutcome(id:string,reason:string,replacementOutcomeId:string|undefined,principal:OrganizationalPrincipal){return prisma.$transaction(async tx=>{const current=await tx.predictiveOutcome.findUnique({where:{id},include:{snapshot:true}});if(!current||current.status!==PredictiveRecordStatus.ACTIVE)throw new PredictiveDataError('PREDICTIVE_OUTCOME_NOT_FOUND',404,'Active predictive outcome not found.');const updated=await tx.predictiveOutcome.update({where:{id},data:{status:PredictiveRecordStatus.VOID,voidedAt:new Date(),voidedById:principal.id,voidReason:reason,replacementOutcomeId}});await appendIntegrityEvent(tx,{eventType:'PREDICTIVE_OUTCOME_VOIDED',sourceEventKey:`PREDICTIVE_OUTCOME_VOIDED:${id}`,resourceType:'PredictiveOutcome',resourceId:id,actor:principal,departmentId:current.snapshot.departmentId,jurisdictionId:current.snapshot.jurisdictionId,occurredAt:updated.voidedAt!,facts:{snapshotId:updated.snapshotId,sourceFingerprint:updated.sourceFingerprint,status:updated.status,voidedById:principal.id,voidReasonDigest:integrityTextDigest(updated.voidReason),replacementOutcomeId:updated.replacementOutcomeId}});return{id,status:'VOID'};});}
