import prisma from '../../lib/prisma';
import { PredictiveOutcomeValue, PredictiveProvenanceClass, PredictiveRecordStatus, PredictiveTargetType, Prisma, SystemRole } from '../../generated/prisma';
import type { OrganizationalPrincipal } from '../../security/organizational-scope';
import { PREDICTIVE_DATASET_CONTRACT_VERSION, TASK_LATENESS_FEATURE_CONTRACT_VERSION, TASK_LATENESS_OUTCOME_CONTRACT_VERSION, classifyPredictiveProvenance, deriveTaskLatenessOutcome, predictiveFingerprint, taskLatenessFeatureSchema } from './predictive-data.contracts';

export class PredictiveDataError extends Error { constructor(public code:string,public status:number,message:string){super(message);} }
const scopeWhere=(principal:OrganizationalPrincipal)=>principal.role===SystemRole.SYSTEM_ADMIN?{}:{departmentId:principal.departmentId,jurisdictionId:principal.jurisdictionId};

export async function captureTaskAssignmentSnapshot(taskId:string,createdById:string){
  const task=await prisma.executionTask.findUnique({where:{id:taskId},include:{executionPlan:{include:{case:{include:{asset:true}}}},dependencies:{include:{predecessorTask:{select:{status:true}}}},scheduleRevisions:true}});
  if(!task?.assignedAt||!task.assignedToId||!task.assignedById)return null;
  const {case:targetCase}=task.executionPlan,asset=targetCase.asset,estimate=await prisma.caseResourceEstimate.findFirst({where:{caseId:targetCase.id,preparedAt:{lte:task.assignedAt}},orderBy:[{estimateVersion:'desc'},{id:'desc'}]});
  const feature={executionTaskId:task.id,caseId:targetCase.id,assetId:asset.id,departmentId:asset.departmentId,jurisdictionId:asset.jurisdictionId,sourceActionCode:task.sourceActionCode,sourceActionVersion:task.sourceActionVersion,templateTaskKey:task.templateTaskKey,sourceTemplateCode:task.sourceTemplateCode,sourceTemplateVersion:task.sourceTemplateVersion,categorySnapshot:task.categorySnapshot,isMandatory:task.isMandatory,plannedStartAt:task.plannedStartAt?.toISOString()??null,plannedEndAt:task.plannedEndAt?.toISOString()??null,assignedAt:task.assignedAt.toISOString(),assignedToId:task.assignedToId,assignedById:task.assignedById,caseRiskLevel:targetCase.riskLevel,casePriorityLevel:targetCase.priorityLevel,emergencyFlag:targetCase.emergencyFlag,assetType:asset.assetType,constructionYear:asset.constructionYear,conditionStatus:asset.conditionStatus,dependencyCount:task.dependencies.length,unmetDependencyCount:task.dependencies.filter(item=>item.predecessorTask.status!=='VERIFIED').length,scheduleRevisionCount:task.scheduleRevisions.filter(item=>item.changedAt<=task.assignedAt!).length,activeEstimate:estimate?{estimateId:estimate.id,estimateVersion:estimate.estimateVersion,currency:estimate.currency,estimatedCostMinor:estimate.estimatedCostMinor.toString(),estimatedDurationDays:estimate.estimatedDurationDays,resourceRequirements:estimate.resourceRequirements}:null};
  const parsed=taskLatenessFeatureSchema.parse(feature),provenanceClass=classifyPredictiveProvenance(asset.assetCode),sourceReferences={executionTaskId:task.id,executionPlanId:task.executionPlanId,caseId:targetCase.id,assetId:asset.id};
  return prisma.predictiveFeatureSnapshot.upsert({where:{executionTaskId_targetType_featureContractVersion:{executionTaskId:task.id,targetType:PredictiveTargetType.TASK_LATENESS,featureContractVersion:TASK_LATENESS_FEATURE_CONTRACT_VERSION}},update:{},create:{targetType:PredictiveTargetType.TASK_LATENESS,executionTaskId:task.id,caseId:targetCase.id,assetId:asset.id,departmentId:asset.departmentId,jurisdictionId:asset.jurisdictionId,predictionTimestamp:task.assignedAt,featureContractVersion:TASK_LATENESS_FEATURE_CONTRACT_VERSION,featurePayload:parsed as Prisma.InputJsonValue,provenanceClass,sourceReferences,sourceFingerprint:predictiveFingerprint({contract:TASK_LATENESS_FEATURE_CONTRACT_VERSION,feature:parsed}),createdById}});
}

export async function captureTaskOutcome(taskId:string,event:'COMPLETION'|'CANCELLED',recordedById:string){
  const task=await prisma.executionTask.findUnique({where:{id:taskId},select:{completionSubmittedAt:true,cancelledAt:true,predictiveSnapshots:{where:{targetType:PredictiveTargetType.TASK_LATENESS,status:PredictiveRecordStatus.ACTIVE},orderBy:{createdAt:'desc'},take:1}}});
  const snapshot=task?.predictiveSnapshots[0];if(!task||!snapshot)return null;
  const parsed=taskLatenessFeatureSchema.safeParse(snapshot.featurePayload);if(!parsed.success)return null;
  const outcomeTimestamp=event==='CANCELLED'?task.cancelledAt:task.completionSubmittedAt;if(!outcomeTimestamp||outcomeTimestamp<=snapshot.predictionTimestamp)return null;
  const outcomeValue=deriveTaskLatenessOutcome(parsed.data.plannedEndAt,outcomeTimestamp,event==='CANCELLED');if(!outcomeValue)return null;
  const refs={executionTaskId:taskId,snapshotId:snapshot.id,event};
  return prisma.predictiveOutcome.upsert({where:{snapshotId_outcomeContractVersion:{snapshotId:snapshot.id,outcomeContractVersion:TASK_LATENESS_OUTCOME_CONTRACT_VERSION}},update:{},create:{snapshotId:snapshot.id,outcomeContractVersion:TASK_LATENESS_OUTCOME_CONTRACT_VERSION,outcomeTimestamp,outcomeValue,provenanceClass:snapshot.provenanceClass,sourceReferences:refs,sourceFingerprint:predictiveFingerprint({contract:TASK_LATENESS_OUTCOME_CONTRACT_VERSION,snapshot:snapshot.sourceFingerprint,outcomeTimestamp:outcomeTimestamp.toISOString(),outcomeValue}),recordedById}});
}

export async function collectAssignmentBestEffort(taskId:string,actorId:string){try{await captureTaskAssignmentSnapshot(taskId,actorId);}catch(error){console.error('PREDICTIVE_COLLECTION_ASSIGNMENT_FAILED',{taskId,error:error instanceof Error?error.message:'unknown'});}}
export async function collectOutcomeBestEffort(taskId:string,event:'COMPLETION'|'CANCELLED',actorId:string){try{await captureTaskOutcome(taskId,event,actorId);}catch(error){console.error('PREDICTIVE_COLLECTION_OUTCOME_FAILED',{taskId,event,error:error instanceof Error?error.message:'unknown'});}}

function allowedProvenance(principal:OrganizationalPrincipal,includeDemo:boolean){if(includeDemo&&principal.role!==SystemRole.SYSTEM_ADMIN)throw new PredictiveDataError('FORBIDDEN',403,'Demo dataset access requires system administration authority.');return includeDemo?undefined:{in:[PredictiveProvenanceClass.PRODUCTION,PredictiveProvenanceClass.PILOT]};}
async function scopedRows(principal:OrganizationalPrincipal,includeDemo:boolean){return prisma.predictiveFeatureSnapshot.findMany({where:{targetType:PredictiveTargetType.TASK_LATENESS,status:PredictiveRecordStatus.ACTIVE,...scopeWhere(principal),...(allowedProvenance(principal,includeDemo)?{provenanceClass:allowedProvenance(principal,includeDemo)}:{})},include:{outcomes:{where:{status:PredictiveRecordStatus.ACTIVE},orderBy:{recordedAt:'desc'},take:1}},orderBy:[{predictionTimestamp:'asc'},{id:'asc'}]});}
function analyze(rows:Awaited<ReturnType<typeof scopedRows>>){const eligible:any[]=[],pending:any[]=[],invalid:any[]=[],cancelled:any[]=[];for(const row of rows){const feature=taskLatenessFeatureSchema.safeParse(row.featurePayload),outcome=row.outcomes[0];if(!feature.success||!feature.data.plannedEndAt){invalid.push(row);continue;}if(!outcome){pending.push(row);continue;}if(outcome.outcomeTimestamp<=row.predictionTimestamp){invalid.push(row);continue;}if(outcome.outcomeValue===PredictiveOutcomeValue.CANCELLED){cancelled.push(row);continue;}eligible.push({snapshotId:row.id,outcomeId:outcome.id,predictionTimestamp:row.predictionTimestamp.toISOString(),outcomeTimestamp:outcome.outcomeTimestamp.toISOString(),label:outcome.outcomeValue,provenanceClass:row.provenanceClass,featureContractVersion:row.featureContractVersion,outcomeContractVersion:outcome.outcomeContractVersion,features:feature.data,sourceReferences:row.sourceReferences});}return{eligible,pending,invalid,cancelled};}
export async function getTaskLatenessDataset(principal:OrganizationalPrincipal,input:{includeDemo:boolean;limit:number;offset:number}){const rows=await scopedRows(principal,input.includeDemo),analysis=analyze(rows),ordered=analysis.eligible,datasetFingerprint=predictiveFingerprint(ordered.map(item=>({snapshotId:item.snapshotId,outcomeId:item.outcomeId}))),page=ordered.slice(input.offset,input.offset+input.limit);return{contractVersion:PREDICTIVE_DATASET_CONTRACT_VERSION,targetType:'TASK_LATENESS',generatedAt:new Date().toISOString(),manifest:{eligibleSampleCount:ordered.length,pendingOutcomeCount:analysis.pending.length,invalidCount:analysis.invalid.length,cancelledCount:analysis.cancelled.length,scope:scopeWhere(principal),includedProvenance:input.includeDemo?'ALL':'PRODUCTION_PILOT_ONLY',classBalance:{LATE:ordered.filter(x=>x.label==='LATE').length,ON_TIME:ordered.filter(x=>x.label==='ON_TIME').length},dateRange:ordered.length?{from:ordered[0].predictionTimestamp,to:ordered.at(-1).predictionTimestamp}:null,datasetFingerprint},items:page,nextOffset:input.offset+input.limit<ordered.length?input.offset+input.limit:null};}
export async function getPredictiveReadiness(principal:OrganizationalPrincipal){const all=await prisma.predictiveFeatureSnapshot.findMany({where:{targetType:PredictiveTargetType.TASK_LATENESS,status:PredictiveRecordStatus.ACTIVE,...scopeWhere(principal)},include:{outcomes:{where:{status:PredictiveRecordStatus.ACTIVE},take:1}}}),real=analyze(all.filter(row=>row.provenanceClass===PredictiveProvenanceClass.PRODUCTION||row.provenanceClass===PredictiveProvenanceClass.PILOT)),counts=Object.values(PredictiveProvenanceClass).reduce((a,p)=>({...a,[p]:all.filter(r=>r.provenanceClass===p).length}),{} as Record<string,number>);return{state:real.eligible.length===0?'NO_REAL_OUTCOMES':real.pending.length?'COLLECTING':'REVIEW_REQUIRED',modelStatus:'NO_MODEL_YET',disclosures:['ODYSSEY is collecting governed historical outcomes for future validation. No predictive model is trained or deployed from this data.','Demo and synthetic records are excluded from real predictive datasets by default.'],targetContracts:[{targetType:'TASK_LATENESS',status:'COLLECTING',featureContractVersion:TASK_LATENESS_FEATURE_CONTRACT_VERSION,outcomeContractVersion:TASK_LATENESS_OUTCOME_CONTRACT_VERSION},{targetType:'PLAN_DELAY',status:'FUTURE_EXTENSION'},{targetType:'ASSET_DETERIORATION',status:'FUTURE_EXTENSION'}],counts:{snapshots:all.length,eligibleRealOutcomes:real.eligible.length,pendingRealOutcomes:real.pending.length,invalidRealRecords:real.invalid.length,provenance:counts}};}
export async function voidSnapshot(id:string,reason:string,replacementSnapshotId:string|undefined,principal:OrganizationalPrincipal){const changed=await prisma.predictiveFeatureSnapshot.updateMany({where:{id,status:PredictiveRecordStatus.ACTIVE},data:{status:PredictiveRecordStatus.VOID,voidedAt:new Date(),voidedById:principal.id,voidReason:reason,replacementSnapshotId}});if(changed.count!==1)throw new PredictiveDataError('PREDICTIVE_SNAPSHOT_NOT_FOUND',404,'Active predictive snapshot not found.');return{id,status:'VOID'};}
export async function voidOutcome(id:string,reason:string,replacementOutcomeId:string|undefined,principal:OrganizationalPrincipal){const changed=await prisma.predictiveOutcome.updateMany({where:{id,status:PredictiveRecordStatus.ACTIVE},data:{status:PredictiveRecordStatus.VOID,voidedAt:new Date(),voidedById:principal.id,voidReason:reason,replacementOutcomeId}});if(changed.count!==1)throw new PredictiveDataError('PREDICTIVE_OUTCOME_NOT_FOUND',404,'Active predictive outcome not found.');return{id,status:'VOID'};}
