import { useEffect, useState } from 'react';
import { getIntelligenceAssessmentsPage, requestIntelligenceAssessment, type GovernanceReconciliation, type IntelligenceAssessment, type IntelligenceSnapshot, type ReconciledAction, type SafetyReconciliation } from '../../api/intelligence.api';
import { useAuth } from '../../auth/useAuth';
import { ErrorState, Loading } from '../AsyncState';
import StatusBadge, { humanize } from '../StatusBadge';

export default function AdvisoryIntelligence({caseId,canOperate,refreshKey=0}:{caseId:string;canOperate:boolean;refreshKey?:number}){
 const{token}=useAuth();const[history,setHistory]=useState<IntelligenceAssessment[]|null>(null);const[error,setError]=useState<unknown>(null);const[loading,setLoading]=useState(true);const[running,setRunning]=useState(false);const[transient,setTransient]=useState<IntelligenceAssessment|null>(null);const[reload,setReload]=useState(0);const[nextCursor,setNextCursor]=useState<string|null>(null);const[loadingMore,setLoadingMore]=useState(false);const[pageError,setPageError]=useState<unknown>(null);
 useEffect(()=>{if(!token)return;const controller=new AbortController();setLoading(true);setError(null);setPageError(null);getIntelligenceAssessmentsPage(caseId,token,'',controller.signal).then(page=>{setHistory(page.items);setNextCursor(page.nextCursor)}).catch(reason=>{if(!controller.signal.aborted)setError(reason)}).finally(()=>{if(!controller.signal.aborted)setLoading(false)});return()=>controller.abort()},[caseId,refreshKey,reload,token]);
 async function loadMore(){if(!token||!nextCursor||loadingMore)return;setLoadingMore(true);setPageError(null);try{const page=await getIntelligenceAssessmentsPage(caseId,token,`limit=25&cursor=${encodeURIComponent(nextCursor)}`);setHistory(current=>{const rows=current??[],ids=new Set(rows.map(x=>x.id));return[...rows,...page.items.filter(x=>!x.id||!ids.has(x.id))]});setNextCursor(page.nextCursor)}catch(reason){setPageError(reason)}finally{setLoadingMore(false)}}
 async function run(){if(!token||running)return;setRunning(true);setError(null);setTransient(null);try{const result=await requestIntelligenceAssessment(caseId,token);if(result.persisted)setReload(value=>value+1);else setTransient(result)}catch(reason){setError(reason)}finally{setRunning(false)}}
 const current=transient??history?.[0]??null;
 return <section className="advisory-intelligence" aria-labelledby="advisory-intelligence-heading"><header><div><p className="section-label">DECISION SUPPORT · OPTIONAL</p><h2 id="advisory-intelligence-heading">Advisory intelligence</h2></div>{current&&<span className="advisory-status">{current.currentlyStale?'Historical':humanize(current.status)}</span>}</header><p className="advisory-boundary">The authoritative deterministic assessment remains primary. Advisory intelligence cannot approve, authorize, or lower the deterministic safety floor.</p>
 {loading?<Loading label="advisory intelligence"/>:error?<ErrorState error={error} retry={()=>setReload(value=>value+1)}/>:!current?<div className="advisory-empty" role="status"><div><h3>Not yet requested</h3><p>This optional analysis is not required to continue the governed workflow.</p></div>{canOperate&&<button type="button" className="primary-button" onClick={run} disabled={running}>{running?'Running analysis…':'Run advisory analysis'}</button>}</div>:<AssessmentView value={current}/>}
 {current&&canOperate&&(current.status==='UNAVAILABLE'||current.status==='INVALID_RESPONSE')&&<button type="button" className="secondary-button" onClick={run} disabled={running}>{running?'Running analysis…':'Retry advisory analysis'}</button>}
 {pageError?<ErrorState error={pageError} retry={loadMore}/>:null}{nextCursor?<button type="button" className="secondary-button" onClick={loadMore} disabled={loadingMore}>{loadingMore?'Loading more…':'Load more intelligence history'}</button>:history?.length?<p>All intelligence history loaded.</p>:null}
 </section>
}

export function AssessmentView({value}:{value:IntelligenceAssessment}){
 if(value.currentlyStale)return <div className="advisory-message stale" role="status"><strong>Historical intelligence — source data has changed.</strong><p>This record is retained for audit history and is not presented as current advice.</p></div>;
 if(value.status==='UNAVAILABLE')return <div className="advisory-message warning" role="status"><strong>Advisory intelligence is unavailable.</strong><p>The authoritative deterministic assessment remains in effect.</p></div>;
 if(value.status==='INVALID_RESPONSE')return <div className="advisory-message warning" role="status"><strong>Advisory intelligence response could not be validated.</strong><p>The authoritative deterministic assessment remains in effect.</p></div>;
 if(value.status==='ABSTAINED')return <div className="advisory-message neutral" role="status"><strong>Advisory analysis abstained</strong><ul>{value.abstentionReasons.map((reason,index)=><li key={index}>{typeof reason==='string'?reason:reason.message}</li>)}</ul><p>No advisory recommendation was asserted.</p></div>;
 const governance=value.governanceReconciliations?.[0]??value.governanceReconciliation??null;
 return <div className="advisory-result"><section><h3>Advisory result</h3>{value.providerType==='REFERENCE_NON_ML'&&<p className="reference-provider">Reference provider — non-ML integration validation</p>}<dl className="advisory-facts"><Fact label="Advisory predicted risk"><StatusBadge value={value.predictedRiskLevel}/></Fact><Fact label="Recommended priority"><StatusBadge value={value.recommendedPriority}/></Fact><Fact label="Confidence">{value.confidence===null?'Not available':`${Math.round(value.confidence*100)}%`}</Fact><Fact label="Provider">{value.provider}</Fact><Fact label="Model / version">{value.modelName} · {value.modelVersion}</Fact><Fact label="Provider type">{humanize(value.providerType)}</Fact></dl><p className="confidence-note">Confidence reflects structured input completeness for this provider. It is not a probability of failure or approval.</p>{value.explanation&&<p>{value.explanation}</p>}</section>
 <SafetyView value={value.reconciliation}/><Factors value={value.contributingFactors}/>{governance&&<GovernanceView value={governance}/>}</div>
}

export function IntelligenceSnapshotView({value}:{value:IntelligenceSnapshot}){const a=value.assessment;return <section className="package-advisory" aria-labelledby={`package-advisory-${a.id}`}><p className="section-label">OPTIONAL ADVISORY SNAPSHOT</p><h4 id={`package-advisory-${a.id}`}>Advisory Intelligence Snapshot</h4>{a.providerType==='REFERENCE_NON_ML'&&<p className="reference-provider">Reference provider — non-ML integration validation</p>}<dl className="advisory-facts"><Fact label="Prediction">{humanize(a.predictedRiskLevel)}</Fact><Fact label="Recommended priority">{humanize(a.recommendedPriority)}</Fact><Fact label="Confidence">{a.confidence===null?'Not available':`${Math.round(a.confidence*100)}%`}</Fact><Fact label="Provider / model">{a.provider} · {a.modelName} {a.modelVersion}</Fact></dl><p className="confidence-note">Confidence reflects structured input completeness for this provider. It is not a probability of failure or approval.</p><SafetyView value={a.reconciliation}/><GovernanceView value={{...value.governance,currentlyStale:false}}/><p className="advisory-boundary">Advisory intelligence only. Human review is required; this snapshot grants no approval or execution authority.</p></section>}

function SafetyView({value}:{value:SafetyReconciliation}){return <section className="safety-reconciliation"><h3>Safety reconciliation</h3><div className="safety-columns"><div><strong>Authoritative deterministic assessment</strong><span>Risk: {humanize(value.deterministicRisk)}</span><span>Priority: {humanize(value.deterministicPriority)}</span></div><div><strong>Advisory intelligence</strong><span>Risk: {humanize(value.advisoryRisk)}</span><span>Priority: {humanize(value.advisoryPriority)}</span></div><div><strong>Effective advisory safety floor</strong><span>Risk: {humanize(value.effectiveSafetyFloorRisk)}</span><span>Priority: {humanize(value.effectiveSafetyFloorPriority)}</span></div></div>{value.deterministicFloorPreserved&&<p className="floor-preserved">Deterministic safety floor preserved.</p>}{value.disagreement&&<p className="advisory-disagreement" role="status">Advisory intelligence differs from the deterministic safety assessment. The deterministic safety floor remains authoritative.</p>}</section>}
function Factors({value}:{value:IntelligenceAssessment['contributingFactors']}){if(!value.length)return null;return <section><h3>Contributing factors</h3><ul className="factor-list">{value.map((factor,index)=><li key={`${factor.code}-${index}`}><strong>{humanize(factor.code)}</strong><span>{humanize(factor.direction)} · observed: {String(factor.observedValue)} · importance: {factor.importance}</span><p>{factor.explanation}</p></li>)}</ul></section>}
function GovernanceView({value}:{value:GovernanceReconciliation}){return <section className="advisory-governance"><h3>Policy constraints on suggested actions</h3>{value.reconciledActions.length?<ul>{value.reconciledActions.map((action,index)=><Action key={`${action.actionCode}-${index}`} value={action}/>)}</ul>:<p>No advisory actions were suggested.</p>}</section>}
function Action({value}:{value:ReconciledAction}){const labels:Record<string,string>={APPROVED_ACTIVE:'Matched to active approved action',PROHIBITED:'Prohibited by applicable policy',UNKNOWN:'No governed approved-action match',OUT_OF_SCOPE:'Not applicable to this organizational scope',EXPIRED:'Approved action version expired',INACTIVE:'Approved action version is not active',POLICY_ABSTAINED:'Policy authority not established',GOVERNANCE_CONFLICT:'Governance conflict — officer review required'};return <li className={`governance-${value.resolution.toLowerCase().replaceAll('_','-')}`}><strong>{humanize(value.actionCode)}</strong><span>{value.rationale}</span><b>{labels[value.resolution]}</b>{value.enforcementClassification&&<small>Classification: {value.enforcementClassification}</small>}{value.approvedActionVersion&&<small>Approved Action {value.approvedActionVersion.actionCode} v{value.approvedActionVersion.versionNumber} · {value.approvedActionVersion.title}</small>}{value.policy&&value.rule&&<small>Policy {value.policy.policyCode} v{value.policy.versionNumber} · rule {value.rule.ruleCode}</small>}</li>}
function Fact({label,children}:{label:string;children:React.ReactNode}){return <div><dt>{label}</dt><dd>{children}</dd></div>}
