import{fireEvent,render,screen,waitFor,within}from'@testing-library/react';import{afterEach,describe,expect,it,vi}from'vitest';import{AuthContext,type AuthContextValue}from'../../auth/AuthProvider';import AdvisoryIntelligence,{AssessmentView}from'./AdvisoryIntelligence';import type{IntelligenceAssessment}from'../../api/intelligence.api';
const safety={deterministicRisk:'VERY_HIGH',deterministicPriority:'CRITICAL',advisoryRisk:'HIGH',advisoryPriority:'HIGH',effectiveSafetyFloorRisk:'VERY_HIGH',effectiveSafetyFloorPriority:'CRITICAL',disagreement:true,deterministicFloorPreserved:true};
const governance={id:'g',contractVersion:'GOV_V1',policyResolutionStatus:'RESOLVED',reconciledAt:'2026-08-22',currentlyStale:false,issues:[],reconciledActions:[{actionCode:'ACT_OK',rationale:'Suggested inspection',resolution:'APPROVED_ACTIVE' as const,enforcementClassification:'MANDATORY' as const,approvedActionVersion:{id:'a',actionCode:'ACT_OK',versionNumber:3,title:'Detailed inspection',category:'SAFETY',sourceReference:'OFFICIAL'},policy:{id:'p',policyCode:'POLICY_PWD',versionNumber:2},rule:{id:'r',ruleCode:'RULE_SAFE'}},{actionCode:'ACT_NO',rationale:'Suggested closure',resolution:'PROHIBITED' as const,enforcementClassification:'PROHIBITED' as const},{actionCode:'ACT_UNKNOWN',rationale:'Unmatched',resolution:'UNKNOWN' as const},{actionCode:'ACT_POLICY',rationale:'No authority',resolution:'POLICY_ABSTAINED' as const},{actionCode:'ACT_CONFLICT',rationale:'Conflict',resolution:'GOVERNANCE_CONFLICT' as const}]};
const completed:Intel= {id:'i',persisted:true,status:'COMPLETED',currentlyStale:false,predictedRiskScore:60,predictedRiskLevel:'HIGH',recommendedPriority:'HIGH',confidence:1,provider:'ODYSSEY_REFERENCE_PROVIDER_V1',providerType:'REFERENCE_NON_ML',productionTrained:false,modelName:'ODYSSEY_REFERENCE_PROVIDER_V1',modelVersion:'1.0.0',confidenceSemantics:'INPUT_COMPLETENESS_NOT_CALIBRATED_PROBABILITY',contributingFactors:[{code:'STRUCTURAL_CONDITION_SIGNAL',direction:'INCREASES_RISK',observedValue:'POOR',importance:1,explanation:'Degraded structural condition was recorded.'}],explanation:'Controlled explanation.',abstentionReasons:[],reconciliation:safety,governanceReconciliations:[governance]};type Intel=IntelligenceAssessment;
const response=(data:unknown)=>Promise.resolve(new Response(JSON.stringify({success:true,data}),{status:200,headers:{'Content-Type':'application/json'}}));const context=(role='OFFICER'):AuthContextValue=>({user:{id:'u',name:'Officer',email:'officer@test',employeeCode:'E1',designation:'Engineer',role:role as any,status:'ACTIVE',departmentId:'d',jurisdictionId:'j'},token:'token',organization:null,isAuthenticated:true,authStatus:'authenticated',sessionMessage:null,login:vi.fn(),logout:vi.fn()});afterEach(()=>vi.unstubAllGlobals());
describe('Advisory intelligence decision support',()=>{
 it('keeps authoritative safety visually primary and explains a prevented downgrade',()=>{render(<AssessmentView value={completed}/>);expect(screen.getByText('Advisory result')).toBeInTheDocument();expect(screen.getByText('Authoritative deterministic assessment')).toBeInTheDocument();expect(screen.getByText('Deterministic safety floor preserved.')).toBeInTheDocument();expect(screen.getByRole('status')).toHaveTextContent('differs from the deterministic safety assessment');});
 it('labels the reference provider, confidence semantics and structured factors without raw JSON',()=>{render(<AssessmentView value={completed}/>);expect(screen.getByText('Reference provider — non-ML integration validation')).toBeInTheDocument();expect(screen.getByText(/not a probability of failure or approval/i)).toBeInTheDocument();expect(screen.getByText(/Structural condition signal/i)).toBeInTheDocument();expect(screen.getByText('Degraded structural condition was recorded.')).toBeInTheDocument();expect(document.body.textContent).not.toMatch(/[{}]|chain-of-thought|reporter/i);});
 it('shows exact governed provenance and never hides prohibited, unknown, abstained or conflicting suggestions',()=>{render(<AssessmentView value={completed}/>);expect(screen.getByText(/Approved Action ACT_OK v3/)).toBeInTheDocument();expect(screen.getByText(/POLICY_PWD v2.*RULE_SAFE/)).toBeInTheDocument();for(const text of['Prohibited by applicable policy','No governed approved-action match','Policy authority not established','Governance conflict — officer review required'])expect(screen.getByText(text)).toBeInTheDocument();expect(screen.queryByRole('button',{name:/ACT_NO|permit|approve/i})).not.toBeInTheDocument();});
 it.each([['UNAVAILABLE','Advisory intelligence is unavailable'],['INVALID_RESPONSE','response could not be validated']]as const)('renders controlled %s fallback',(status,text)=>{render(<AssessmentView value={{...completed,id:null,persisted:false,status,predictedRiskLevel:null,recommendedPriority:null,confidence:null}}/>);expect(screen.getByRole('status')).toHaveTextContent(text);expect(screen.getByText(/authoritative deterministic assessment remains in effect/i)).toBeInTheDocument();});
 it('renders abstention and stale history as non-current',()=>{const{rerender}=render(<AssessmentView value={{...completed,status:'ABSTAINED',abstentionReasons:[{code:'INSUFFICIENT_DATA',message:'Insufficient structured inputs.'}]}}/>);expect(screen.getByRole('status')).toHaveTextContent('Insufficient structured inputs');rerender(<AssessmentView value={{...completed,currentlyStale:true}}/>);expect(screen.getByRole('status')).toHaveTextContent('Historical intelligence — source data has changed');});
 it('shows optional not-requested state and allows only an OFFICER to invoke',async()=>{const fetchMock=vi.fn().mockImplementation((_url:string,init?:RequestInit)=>init?.method==='POST'?response(completed):response([]));vi.stubGlobal('fetch',fetchMock);const{rerender}=render(<AuthContext.Provider value={context('AUDITOR')}><AdvisoryIntelligence caseId="case" canOperate={false}/></AuthContext.Provider>);expect(await screen.findByText('Not yet requested')).toBeInTheDocument();expect(screen.queryByRole('button',{name:'Run advisory analysis'})).not.toBeInTheDocument();rerender(<AuthContext.Provider value={context()}><AdvisoryIntelligence caseId="case" canOperate/></AuthContext.Provider>);fireEvent.click(await screen.findByRole('button',{name:'Run advisory analysis'}));await waitFor(()=>expect(fetchMock.mock.calls.some(call=>call[1]?.method==='POST')).toBe(true));});
 it('announces loading with an accessible busy status',()=>{vi.stubGlobal('fetch',vi.fn(()=>new Promise(()=>{})));render(<AuthContext.Provider value={context()}><AdvisoryIntelligence caseId="case" canOperate/></AuthContext.Provider>);expect(screen.getByText(/Loading advisory intelligence/i)).toBeInTheDocument();expect(within(document.body).getByText(/Loading advisory intelligence/i)).toBeVisible();});
 it('contains no language claiming intelligence approval',()=>{render(<AssessmentView value={completed}/>);expect(document.body.textContent).not.toMatch(/AI decided|AI approved|approved by AI|autonomous decision/i);});
});
