import{render,screen}from'@testing-library/react';import{afterEach,describe,expect,it,vi}from'vitest';import{AuthContext,type AuthContextValue}from'../../auth/AuthProvider';import ConditionHistory,{HistoryView}from'./ConditionHistory';import type{ConditionHistory as History}from'../../api/condition-history.api';
const context:AuthContextValue={user:{id:'u',name:'Officer',email:'o@test',employeeCode:'E',designation:'Engineer',role:'OFFICER',status:'ACTIVE',departmentId:'d',jurisdictionId:'j'},token:'token',organization:null,isAuthenticated:true,authStatus:'authenticated',sessionMessage:null,login:vi.fn(),logout:vi.fn()};
const history:History={contractVersion:'V1',methodVersion:'M1',asset:{id:'asset',assetCode:'BR-1',name:'Bridge',assetType:'BRIDGE',departmentId:'d',jurisdictionId:'j'},analysisWindow:{maximumObservations:100,observationsAnalyzed:2,truncated:false,oldestInspectionDate:'2026-01-01',latestInspectionDate:'2026-03-01'},summary:{observationCount:2,spanDays:59,pairedAssessmentCount:2,latestVsPrevious:{riskScoreDelta:30,observationIntervalDays:59,riskLevelChanged:true,priorityLevelChanged:true,structuralConditionChanged:true,crackSeverityChanged:true,corrosionLevelChanged:false},trend:{state:'WORSENING',reasons:['Risk score increased from 40 to 70.']},readiness:{state:'LIMITED',reasons:['Only 2 observations are available.']},completeness:{coordinates:{available:true,status:'COMPLETE'},fields:{}}},observations:[{inspectionId:'i2',caseId:'case-2',inspectionDate:'2026-03-01',structuralCondition:'POOR',crackSeverity:'SEVERE',corrosionLevel:'MODERATE',trafficImportance:'HIGH',hospitalRoute:true,weatherRisk:'HIGH',heavyRainExpected:true,estimatedDailyUsers:1000,assessment:{id:'r2',riskScore:70,riskLevel:'HIGH',priorityLevel:'HIGH',assessmentVersion:'V1',createdAt:'2026-03-01'}},{inspectionId:'i1',caseId:'case-1',inspectionDate:'2026-01-01',structuralCondition:'FAIR',crackSeverity:'MODERATE',corrosionLevel:'MODERATE',trafficImportance:'HIGH',hospitalRoute:true,weatherRisk:'LOW',heavyRainExpected:false,estimatedDailyUsers:1000,assessment:{id:'r1',riskScore:40,riskLevel:'MODERATE',priorityLevel:'MEDIUM',assessmentVersion:'V1',createdAt:'2026-01-01'}}],provenance:{sourceInspectionIds:['i1','i2'],sourceRiskAssessmentIds:['r1','r2'],sourceFingerprint:'sha256:x'}};
const response=(data:unknown,ok=true)=>Promise.resolve(new Response(JSON.stringify(ok?{success:true,data}:{success:false,error:{code:'FAILED',message:'Unavailable'}}),{status:ok?200:500,headers:{'Content-Type':'application/json'}}));afterEach(()=>vi.unstubAllGlobals());
describe('asset condition history',()=>{
 it('shows worsening history, readiness reasons, multiple-case provenance and non-predictive disclosure',()=>{render(<HistoryView data={history}/>);expect(screen.getAllByText('Worsening')).toHaveLength(2);expect(screen.getByText('Only 2 observations are available.')).toBeInTheDocument();expect(screen.getByText('case-2')).toBeInTheDocument();expect(screen.getByText(/\+30 risk-score points/)).toBeInTheDocument()});
 it('shows loading then sparse baseline without inventing a comparison',async()=>{vi.stubGlobal('fetch',vi.fn(()=>response({...history,summary:{...history.summary,observationCount:1,spanDays:0,latestVsPrevious:null,trend:{state:'INSUFFICIENT_DATA',reasons:['At least two historical observations are required.']},readiness:{state:'INSUFFICIENT',reasons:['Only one inspection is recorded; it provides a baseline but not a trend.']}},observations:[history.observations[0]]})));render(<AuthContext.Provider value={context}><ConditionHistory assetId="asset"/></AuthContext.Provider>);expect(screen.getByText(/Loading condition history/i)).toBeInTheDocument();expect(await screen.findByText('Not available')).toBeInTheDocument();expect(screen.getByText(/baseline but not a trend/i)).toBeInTheDocument();expect(screen.getByText(/not a prediction of failure, future risk, or remaining asset life/i)).toBeInTheDocument()});
 it('renders no-history and controlled API failure states',async()=>{vi.stubGlobal('fetch',vi.fn(()=>response({...history,summary:{...history.summary,observationCount:0},observations:[]})));const{unmount}=render(<AuthContext.Provider value={context}><ConditionHistory assetId="asset"/></AuthContext.Provider>);expect(await screen.findByText(/No longitudinal history is available/)).toBeInTheDocument();unmount();vi.stubGlobal('fetch',vi.fn(()=>response(null,false)));render(<AuthContext.Provider value={context}><ConditionHistory assetId="asset"/></AuthContext.Provider>);expect(await screen.findByText(/currently unavailable/i)).toBeInTheDocument()});
});
