import { z } from 'zod';
export const TASK_LATENESS_EVALUATION_CONTRACT_VERSION='TASK_LATENESS_EVALUATION_V1';
export const TASK_LATENESS_DEPLOYMENT_SLOT='TASK_LATENESS_ADVISORY';
const rate=z.number().finite().min(0).max(1),count=z.number().int().nonnegative();
export const baselineEvidenceSchema=z.array(z.object({name:z.enum(['MAJORITY_CLASS','HISTORICAL_LATE_RATE','TRANSPARENT_PRIORITY_HEURISTIC','LOGISTIC_REGRESSION']),metricName:z.string().min(1).max(100),metricValue:rate,reference:z.string().min(1).max(1000)}).strict()).min(1).max(10);
export const modelEvaluationSchema=z.object({datasetSnapshotId:z.string().uuid(),evaluationContractVersion:z.literal(TASK_LATENESS_EVALUATION_CONTRACT_VERSION),splitStrategy:z.string().trim().min(3).max(1000),evaluationPeriodStart:z.coerce.date(),evaluationPeriodEnd:z.coerce.date(),testSampleCount:count,lateCount:count,onTimeCount:count,truePositiveCount:count,trueNegativeCount:count,falsePositiveCount:count,falseNegativeCount:count,precision:rate,recall:rate,f1:rate,prAuc:rate,calibrationError:rate,falseNegativeRate:rate,baselineEvidence:baselineEvidenceSchema,subgroupMetricsReference:z.record(z.unknown()).optional(),featureDistributionReference:z.record(z.unknown()).optional(),missingnessReference:z.record(z.unknown()).optional(),evaluationArtifactReference:z.string().trim().min(1).max(2000)}).strict().superRefine((v,ctx)=>{if(v.evaluationPeriodEnd<v.evaluationPeriodStart)ctx.addIssue({code:'custom',message:'Evaluation period is invalid.'});if(v.lateCount+v.onTimeCount!==v.testSampleCount)ctx.addIssue({code:'custom',message:'Class counts must equal test sample count.'});if(v.truePositiveCount+v.trueNegativeCount+v.falsePositiveCount+v.falseNegativeCount!==v.testSampleCount)ctx.addIssue({code:'custom',message:'Confusion matrix must equal test sample count.'});if(v.truePositiveCount+v.falseNegativeCount!==v.lateCount)ctx.addIssue({code:'custom',message:'Positive-class counts must equal late count.'});if(v.trueNegativeCount+v.falsePositiveCount!==v.onTimeCount)ctx.addIssue({code:'custom',message:'Negative-class counts must equal on-time count.'});});
export const sha256Digest=/^sha256:[a-f0-9]{64}$/;
export const legalModelTransitions={EXPERIMENTAL:['EVALUATED'],EVALUATED:['VALIDATED','REJECTED'],VALIDATED:['APPROVED','REJECTED'],APPROVED:['ACTIVE','DEPRECATED'],ACTIVE:['APPROVED','DEPRECATED'],REJECTED:[],DEPRECATED:[]} as const;
export function isLegalModelTransition(from:keyof typeof legalModelTransitions,to:string){return(legalModelTransitions[from] as readonly string[]).includes(to)}
