import {Router}from'express';import{z}from'zod';import{SystemRole}from'../../generated/prisma';import{authenticate}from'../../middleware/authenticate';import{requireRole}from'../../middleware/require-role';import{parseCursor,parseLimit,queryError}from'../../lib/pagination';import{modelEvaluationSchema,sha256Digest}from'./predictive-model-governance.contracts';import{activateModel,approveModel,createDatasetSnapshot,deprecateModel,getDatasetSnapshot,getModel,governanceSummary,listDatasetSnapshots,listEvaluations,listModels,ModelGovernanceError,recordEvaluation,registerModel,rejectModel,rollbackModel,validateModel}from'./predictive-model-governance.service';
const router=Router(),read=[SystemRole.AUDITOR,SystemRole.SYSTEM_ADMIN],snapshot=z.object({departmentId:z.string().uuid().optional(),jurisdictionId:z.string().uuid().optional(),includedProvenance:z.array(z.enum(['PRODUCTION','PILOT'])).min(1).max(2)}).strict().superRefine((v,c)=>{if(v.jurisdictionId&&!v.departmentId)c.addIssue({code:'custom',message:'Department is required with jurisdiction.'})}),registration=z.object({modelName:z.string().trim().min(2).max(200),modelVersion:z.string().trim().min(1).max(100),datasetSnapshotId:z.string().uuid(),intendedUse:z.string().trim().min(20).max(4000),forbiddenUse:z.string().trim().min(20).max(4000),featureContractVersion:z.literal('TASK_LATENESS_FEATURES_V1'),outcomeContractVersion:z.literal('TASK_LATENESS_OUTCOME_V1'),trainingCodeVersion:z.string().trim().min(1).max(200),artifactReference:z.string().trim().min(1).max(2000),artifactDigest:z.string().regex(sha256Digest),artifactFormat:z.string().trim().min(1).max(100),artifactSizeBytes:z.string().regex(/^\d+$/).optional(),trainingTimestamp:z.coerce.date()}).strict(),reason=z.object({reason:z.string().trim().min(3).max(2000)}).strict(),approval=reason.extend({restrictions:z.record(z.unknown()).optional(),reviewDueAt:z.coerce.date().optional(),approvalExpiresAt:z.coerce.date().optional()}).strict();
function fail(res:any,error:unknown){const q=queryError(res,error);if(q)return q;if(error instanceof ModelGovernanceError)return res.status(error.status).json({success:false,error:{code:error.code,message:error.message}});console.error('Predictive model governance operation failed:',error);return res.status(500).json({success:false,error:{code:'MODEL_GOVERNANCE_OPERATION_FAILED',message:'Predictive model governance is currently unavailable.'}})}
router.get('/predictive-models/summary',authenticate,requireRole(...read),async(req,res)=>{try{return res.json({success:true,data:await governanceSummary(req.user!)})}catch(e){return fail(res,e)}});
router.get('/predictive-models',authenticate,requireRole(...read),async(req,res)=>{try{return res.json({success:true,data:await listModels({limit:parseLimit(req.query.limit),cursor:parseCursor(req.query.cursor)},req.user!)})}catch(e){return fail(res,e)}});
router.post('/predictive-models',authenticate,requireRole(SystemRole.SYSTEM_ADMIN),async(req,res)=>{const p=registration.safeParse(req.body);if(!p.success)return res.status(400).json({success:false,error:{code:'INVALID_INPUT',message:'A complete immutable model identity and artifact digest are required.'}});try{return res.status(201).json({success:true,data:await registerModel({...p.data,artifactSizeBytes:p.data.artifactSizeBytes?BigInt(p.data.artifactSizeBytes):undefined},req.user!)})}catch(e){return fail(res,e)}});
router.get('/predictive-models/:id',authenticate,requireRole(...read),async(req,res)=>{try{return res.json({success:true,data:await getModel(String(req.params.id),req.user!)})}catch(e){return fail(res,e)}});
router.post('/predictive-data/dataset-snapshots',authenticate,requireRole(SystemRole.SYSTEM_ADMIN),async(req,res)=>{const p=snapshot.safeParse(req.body);if(!p.success)return res.status(400).json({success:false,error:{code:'INVALID_INPUT',message:'Only explicit production/pilot provenance may create a governed dataset snapshot.'}});try{return res.status(201).json({success:true,data:await createDatasetSnapshot(req.user!,p.data)})}catch(e){return fail(res,e)}});
router.get('/predictive-data/dataset-snapshots',authenticate,requireRole(...read),async(req,res)=>{try{return res.json({success:true,data:await listDatasetSnapshots({limit:parseLimit(req.query.limit),cursor:parseCursor(req.query.cursor)},req.user!)})}catch(e){return fail(res,e)}});
router.get('/predictive-data/dataset-snapshots/:id',authenticate,requireRole(...read),async(req,res)=>{try{return res.json({success:true,data:await getDatasetSnapshot(String(req.params.id),req.user!)})}catch(e){return fail(res,e)}});
router.post('/predictive-models/:id/evaluations',authenticate,requireRole(SystemRole.SYSTEM_ADMIN),async(req,res)=>{const p=modelEvaluationSchema.safeParse(req.body);if(!p.success)return res.status(400).json({success:false,error:{code:'INVALID_EVALUATION_EVIDENCE',message:'Evaluation counts, metrics and baseline evidence must reconcile.'}});try{return res.status(201).json({success:true,data:await recordEvaluation(String(req.params.id),p.data,req.user!)})}catch(e){return fail(res,e)}});
router.get('/predictive-models/:id/evaluations',authenticate,requireRole(...read),async(req,res)=>{try{return res.json({success:true,data:await listEvaluations(String(req.params.id),req.user!)})}catch(e){return fail(res,e)}});
router.post('/predictive-models/:id/validate',authenticate,requireRole(SystemRole.AUDITOR),async(req,res)=>{const p=reason.safeParse(req.body),id=String(req.params.id);if(!p.success)return res.status(400).json({success:false,error:{code:'INVALID_INPUT',message:'Independent validation reason is required.'}});try{await getModel(id,req.user!);return res.json({success:true,data:await validateModel(id,p.data.reason,req.user!)})}catch(e){return fail(res,e)}});
router.post('/predictive-models/:id/approve',authenticate,requireRole(SystemRole.AUDITOR),async(req,res)=>{const p=approval.safeParse(req.body),id=String(req.params.id);if(!p.success)return res.status(400).json({success:false,error:{code:'INVALID_INPUT',message:'Independent approval evidence is required.'}});try{await getModel(id,req.user!);return res.json({success:true,data:await approveModel(id,p.data,req.user!)})}catch(e){return fail(res,e)}});
router.post('/predictive-models/:id/reject',authenticate,requireRole(SystemRole.AUDITOR),async(req,res)=>{const p=reason.safeParse(req.body),id=String(req.params.id);if(!p.success)return res.status(400).json({success:false,error:{code:'INVALID_INPUT',message:'Rejection reason is required.'}});try{await getModel(id,req.user!);return res.json({success:true,data:await rejectModel(id,p.data.reason,req.user!)})}catch(e){return fail(res,e)}});
for(const [path,fn] of [['activate',activateModel],['deprecate',deprecateModel],['rollback',rollbackModel]] as const)router.post(`/predictive-models/:id/${path}`,authenticate,requireRole(SystemRole.SYSTEM_ADMIN),async(req,res)=>{const p=reason.safeParse(req.body);if(!p.success)return res.status(400).json({success:false,error:{code:'INVALID_INPUT',message:'A governed lifecycle reason is required.'}});try{return res.json({success:true,data:await fn(String(req.params.id),p.data.reason,req.user!)})}catch(e){return fail(res,e)}});
export default router;
