import { Router } from 'express';import{z}from'zod';import{RegistryLifecycleStatus,SystemRole}from'../../generated/prisma';import{authenticate}from'../../middleware/authenticate';import{requireRole}from'../../middleware/require-role';import{addGovernedTemplateTask,createGovernedTemplate,getGovernedTemplate,GovernedTemplateError,listGovernedTemplates,transitionGovernedTemplate}from'./governed-execution-template.service';
const router=Router(),admin=requireRole(SystemRole.POLICY_ADMIN,SystemRole.SYSTEM_ADMIN),uuid=z.string().uuid(),text=z.string().trim().min(1),date=z.coerce.date(),optionalUuid=uuid.nullable().optional();
const createSchema=z.object({templateCode:z.string().trim().min(2).max(100).regex(/^EXEC_[A-Z0-9_]+$/),versionNumber:z.number().int().positive(),approvedActionVersionId:uuid,title:text.max(240),description:text.max(2000),effectiveFrom:date,effectiveUntil:date.nullable().optional(),departmentId:optionalUuid,jurisdictionId:optionalUuid}).strict();
const taskSchema=z.object({sequenceNumber:z.number().int().positive(),taskCode:z.string().trim().min(2).max(100).regex(/^[A-Z0-9_]+$/),title:text.max(240),description:text.max(2000),mandatory:z.boolean().default(true),evidenceRequired:z.boolean().default(true),verificationRequired:z.boolean().default(true),enabled:z.boolean().default(true)}).strict();
function fail(res:any,error:unknown){if(error instanceof GovernedTemplateError)return res.status(error.status).json({success:false,error:{code:error.code,message:error.message}});console.error('Execution template registry operation failed:',error);return res.status(500).json({success:false,error:{code:'EXECUTION_TEMPLATE_REGISTRY_FAILED',message:'The execution template registry operation could not be completed.'}});}
router.get('/execution-templates',authenticate,admin,async(_req,res)=>{try{return res.json({success:true,data:await listGovernedTemplates()});}catch(error){return fail(res,error);}});
router.post('/execution-templates',authenticate,admin,async(req,res)=>{const parsed=createSchema.safeParse(req.body);if(!parsed.success)return res.status(400).json({success:false,error:{code:'INVALID_INPUT',message:'Execution template input is invalid.'}});try{return res.status(201).json({success:true,data:await createGovernedTemplate(parsed.data,req.user!)});}catch(error){return fail(res,error);}});
router.get('/execution-templates/:id',authenticate,admin,async(req,res)=>{try{return res.json({success:true,data:await getGovernedTemplate(String(req.params.id))});}catch(error){return fail(res,error);}});
router.post('/execution-templates/:id/tasks',authenticate,admin,async(req,res)=>{const parsed=taskSchema.safeParse(req.body);if(!parsed.success)return res.status(400).json({success:false,error:{code:'INVALID_INPUT',message:'Execution task template input is invalid.'}});try{return res.status(201).json({success:true,data:await addGovernedTemplateTask(String(req.params.id),parsed.data)});}catch(error){return fail(res,error);}});
router.patch('/execution-templates/:id/lifecycle',authenticate,admin,async(req,res)=>{const parsed=z.object({status:z.nativeEnum(RegistryLifecycleStatus)}).strict().safeParse(req.body);if(!parsed.success)return res.status(400).json({success:false,error:{code:'INVALID_INPUT',message:'Lifecycle input is invalid.'}});try{return res.json({success:true,data:await transitionGovernedTemplate(String(req.params.id),parsed.data.status,req.user!)});}catch(error){return fail(res,error);}});
export default router;
