import { Prisma, RegistryLifecycleStatus } from '../../generated/prisma';
import prisma from '../../lib/prisma';
import type { OrganizationalPrincipal } from '../../security/organizational-scope';
import { assertGovernanceCreateScope, assertGovernanceEntityMutationScope, buildGovernanceRegistryReadWhere, governanceScopeAppliesToTarget, GovernanceResourceNotFoundError } from '../../security/organizational-scope';

export class GovernedTemplateError extends Error { constructor(public code:string,public status:number,message:string){super(message);} }
const organization={select:{id:true,name:true}} as const;
export const templateSelect={id:true,templateCode:true,versionNumber:true,title:true,description:true,status:true,effectiveFrom:true,effectiveUntil:true,approvedAt:true,createdAt:true,updatedAt:true,approvedActionVersion:{select:{id:true,actionCode:true,versionNumber:true,title:true,category:true,status:true}},department:organization,jurisdiction:organization,createdBy:{select:{id:true,name:true,designation:true}},approvedBy:{select:{id:true,name:true,designation:true}},tasks:{select:{id:true,sequenceNumber:true,taskCode:true,title:true,description:true,mandatory:true,evidenceRequired:true,verificationRequired:true,enabled:true},orderBy:{sequenceNumber:'asc'}}} satisfies Prisma.GovernedExecutionTemplateSelect;

function dates(from:Date,until?:Date|null){if(until&&until<=from)throw new GovernedTemplateError('INVALID_EFFECTIVE_PERIOD',400,'Effective end must be after effective start.');}
export async function listGovernedTemplates(principal:OrganizationalPrincipal){return prisma.governedExecutionTemplate.findMany({where:buildGovernanceRegistryReadWhere(principal),select:templateSelect,orderBy:[{templateCode:'asc'},{versionNumber:'desc'}]});}
export async function getGovernedTemplate(id:string,principal:OrganizationalPrincipal){const value=await prisma.governedExecutionTemplate.findFirst({where:{id,AND:[buildGovernanceRegistryReadWhere(principal)]},select:templateSelect});if(!value)throw new GovernanceResourceNotFoundError();return value;}
export async function createGovernedTemplate(input:{templateCode:string;versionNumber:number;approvedActionVersionId:string;title:string;description:string;effectiveFrom:Date;effectiveUntil?:Date|null;departmentId?:string|null;jurisdictionId?:string|null},principal:OrganizationalPrincipal){dates(input.effectiveFrom,input.effectiveUntil);const target=await assertGovernanceCreateScope(principal,input.departmentId,input.jurisdictionId);const action=await prisma.approvedActionVersion.findFirst({where:{id:input.approvedActionVersionId,AND:[buildGovernanceRegistryReadWhere(principal)]},select:{departmentId:true,jurisdictionId:true}});if(!action||!governanceScopeAppliesToTarget(action,target))throw new GovernanceResourceNotFoundError();try{return await prisma.governedExecutionTemplate.create({data:{...input,status:'DRAFT',createdById:principal.id},select:templateSelect});}catch(error){if(error instanceof Prisma.PrismaClientKnownRequestError&&error.code==='P2002')throw new GovernedTemplateError('EXECUTION_TEMPLATE_VERSION_EXISTS',409,'That execution template version already exists.');throw error;}}
export async function addGovernedTemplateTask(templateId:string,input:{sequenceNumber:number;taskCode:string;title:string;description:string;mandatory:boolean;evidenceRequired:boolean;verificationRequired:boolean;enabled:boolean},principal:OrganizationalPrincipal){const template=await prisma.governedExecutionTemplate.findUnique({where:{id:templateId},select:{status:true,departmentId:true,jurisdictionId:true}});assertGovernanceEntityMutationScope(principal,template);if(template!.status!=='DRAFT')throw new GovernedTemplateError('EXECUTION_TEMPLATE_IMMUTABLE',409,'Task definitions may only be changed while the template is in draft.');try{await prisma.governedExecutionTaskTemplate.create({data:{executionTemplateId:templateId,...input}});return getGovernedTemplate(templateId,principal);}catch(error){if(error instanceof Prisma.PrismaClientKnownRequestError&&error.code==='P2002')throw new GovernedTemplateError('EXECUTION_TASK_TEMPLATE_CONFLICT',409,'Task code and sequence must be unique within the template.');throw error;}}
const transitions:Record<RegistryLifecycleStatus,RegistryLifecycleStatus[]>={DRAFT:['VALIDATION','ARCHIVED'],VALIDATION:['APPROVED','DRAFT','ARCHIVED'],APPROVED:['ACTIVE','ARCHIVED'],ACTIVE:['SUPERSEDED','ARCHIVED'],SUPERSEDED:['ARCHIVED'],ARCHIVED:[]};
export async function transitionGovernedTemplate(id:string,next:RegistryLifecycleStatus,principal:OrganizationalPrincipal){const current=await prisma.governedExecutionTemplate.findUnique({where:{id},select:{status:true,approvedById:true,departmentId:true,jurisdictionId:true,_count:{select:{tasks:{where:{enabled:true}}}}}});assertGovernanceEntityMutationScope(principal,current);if(!transitions[current!.status].includes(next))throw new GovernedTemplateError('INVALID_LIFECYCLE_TRANSITION',409,'Execution template lifecycle transition is not allowed.');if(next==='APPROVED'&&current!._count.tasks===0)throw new GovernedTemplateError('EXECUTION_TEMPLATE_TASKS_REQUIRED',409,'At least one enabled task definition is required before approval.');if(next==='ACTIVE'&&!current!.approvedById)throw new GovernedTemplateError('EXECUTION_TEMPLATE_APPROVAL_REQUIRED',409,'Human approval is required before activation.');return prisma.governedExecutionTemplate.update({where:{id},data:{status:next,approvedById:next==='APPROVED'?principal.id:undefined,approvedAt:next==='APPROVED'?new Date():undefined},select:templateSelect});}

export async function resolveGovernedTemplate(approvedActionVersionId:string,departmentId:string,jurisdictionId:string,asOf=new Date(),client:Prisma.TransactionClient|typeof prisma=prisma){const matches=await client.governedExecutionTemplate.findMany({where:{approvedActionVersionId,status:'ACTIVE',effectiveFrom:{lte:asOf},OR:[{effectiveUntil:null},{effectiveUntil:{gt:asOf}}],AND:[{OR:[{departmentId:null},{departmentId}]},{OR:[{jurisdictionId:null},{jurisdictionId}]}]},include:{tasks:{where:{enabled:true},orderBy:{sequenceNumber:'asc'}},approvedActionVersion:true},orderBy:[{versionNumber:'desc'},{id:'asc'}]});if(matches.length===0)throw new GovernedTemplateError('EXECUTION_TEMPLATE_NOT_GOVERNED',409,'An authorized execution template has not been established for this action version.');const specificity=Math.max(...matches.map(item=>(item.departmentId?1:0)+(item.jurisdictionId?1:0)));const selected=matches.filter(item=>(item.departmentId?1:0)+(item.jurisdictionId?1:0)===specificity);if(selected.length!==1)throw new GovernedTemplateError('EXECUTION_TEMPLATE_GOVERNANCE_CONFLICT',409,'Multiple applicable governed execution templates create an unresolved conflict.');if(!selected[0].tasks.length)throw new GovernedTemplateError('EXECUTION_TEMPLATE_NOT_GOVERNED',409,'The authorized execution template has no enabled task definitions.');return selected[0];}
