import { fireEvent, render, screen, waitFor, within } from '@testing-library/react';
import { afterEach, describe, expect, it, vi } from 'vitest';
import CaseTimeline from './CaseTimeline';
import { AuthContext, type AuthContextValue } from '../../auth/AuthProvider';
const context:AuthContextValue={user:{id:'u',employeeCode:'E',name:'User',email:'u@test',designation:'Officer',role:'OFFICER',status:'ACTIVE',departmentId:'d',jurisdictionId:'j'},token:'token',organization:null,isAuthenticated:true,authStatus:'authenticated',sessionMessage:null,login:vi.fn(),logout:vi.fn()};
const actor={id:'a',name:'Rahul Patil',designation:'Executive Engineer',email:'private@test',employeeCode:'SECRET'};
const event=(eventType:string,occurredAt:string,id:string,summary:string,who:unknown=null,metadata:Record<string,unknown>={})=>({eventType,occurredAt,actor:who,source:{type:'SOURCE',id},summary,metadata});
const ok=(events:unknown[],nextCursor:string|null)=>new Response(JSON.stringify({success:true,data:{caseId:'c',events,page:{limit:100,nextCursor}}}),{status:200});
function show(fetchMock:ReturnType<typeof vi.fn>){vi.stubGlobal('fetch',fetchMock);return render(<AuthContext.Provider value={context}><CaseTimeline caseId="c"/></AuthContext.Provider>);}
afterEach(()=>vi.unstubAllGlobals());
describe('Case Timeline',()=>{
 it('preserves loading and empty states',async()=>{let resolve:(value:Response)=>void=()=>undefined;const pending=new Promise<Response>((done)=>{resolve=done});show(vi.fn().mockReturnValue(pending));expect(screen.getByText('Loading case timeline…')).toBeInTheDocument();resolve(ok([],null));expect(await screen.findByText('No timeline events are available for this case.')).toBeInTheDocument();});
 it('preserves the safe initial error state',async()=>{show(vi.fn().mockResolvedValue(new Response(JSON.stringify({success:false,error:{code:'UNAVAILABLE',message:'private backend detail'}}),{status:500})));expect(await screen.findByRole('alert')).toHaveTextContent('This data is currently unavailable.');expect(screen.queryByText('private backend detail')).not.toBeInTheDocument();});
 it('renders compact events collapsed by default and expands persisted safe details',async()=>{show(vi.fn().mockResolvedValue(ok([event('ORP_DECIDED','2026-01-02','2','Human decision recorded',actor,{decisionType:'APPROVED',referenceUrl:'https://secret',description:'secret',measurementData:{x:1}}),event('CASE_CREATED','2026-01-01','1','Case registered',null,{unknown:'hidden'})],null)));await screen.findByText('A human decision was recorded for the action plan.');const items=screen.getAllByRole('listitem');expect(items[0]).toHaveTextContent('Action Plan Decision');expect(items[1]).toHaveTextContent('Case registered');expect(items[0]).toHaveTextContent('Rahul Patil');expect(items[1]).toHaveTextContent('System workflow');const toggle=within(items[0]).getByRole('button');const detail=screen.getByText('Approved');expect(toggle).toHaveAttribute('aria-expanded','false');expect(detail).not.toBeVisible();fireEvent.click(toggle);expect(toggle).toHaveAttribute('aria-expanded','true');expect(detail).toBeVisible();expect(screen.getByText('Actor').closest('p')).toHaveTextContent('Rahul Patil · Executive Engineer');expect(screen.queryByText(/private@test|SECRET|secret|hidden|TASK_BLOCKED|TASK_RESUMED/)).not.toBeInTheDocument();fireEvent.click(toggle);expect(toggle).toHaveAttribute('aria-expanded','false');expect(detail).not.toBeVisible();expect(screen.queryByRole('button',{name:'Load more'})).not.toBeInTheDocument();});
 it('expands events independently and supports expand-all and collapse-all',async()=>{show(vi.fn().mockResolvedValue(ok([event('RISK_ASSESSED','2026-01-02','2','Risk recorded',actor,{sourceActionCode:'ACT_ONE'}),event('CASE_CREATED','2026-01-01','1','Case registered',null,{versionNumber:1})],null)));await screen.findByText('Risk recorded');const toggles=screen.getAllByRole('button',{name:/Risk recorded|Case registered/});fireEvent.click(toggles[0]);expect(toggles[0]).toHaveAttribute('aria-expanded','true');expect(toggles[1]).toHaveAttribute('aria-expanded','false');fireEvent.click(screen.getByRole('button',{name:'Expand all'}));expect(toggles[0]).toHaveAttribute('aria-expanded','true');expect(toggles[1]).toHaveAttribute('aria-expanded','true');fireEvent.click(screen.getByRole('button',{name:'Collapse all'}));expect(toggles[0]).toHaveAttribute('aria-expanded','false');expect(toggles[1]).toHaveAttribute('aria-expanded','false');});
 it('presents the authoritative ORP_GENERATED event type as Action Plan Generated',async()=>{show(vi.fn().mockResolvedValue(ok([event('ORP_GENERATED','2026-01-02','o1','Recommendation persisted',actor,{versionNumber:1})],null)));expect(await screen.findByText('Action Plan Generated')).toBeInTheDocument();expect(screen.queryByText('Orp Generated')).not.toBeInTheDocument();});
 it('requests 100 events, appends the next page, and encodes nextCursor',async()=>{const fetchMock=vi.fn().mockResolvedValueOnce(ok([event('CASE_CREATED','2026-01-01','1','First')],'opaque +/=')).mockResolvedValueOnce(ok([event('INSPECTION_RECORDED','2026-01-02','2','Second')],null));show(fetchMock);await screen.findByText('First');expect(fetchMock.mock.calls[0][0]).toContain('limit=100');fireEvent.click(screen.getByRole('button',{name:'Load more'}));expect(await screen.findByText('Second')).toBeInTheDocument();expect(screen.getByText('First')).toBeInTheDocument();expect(fetchMock.mock.calls[1][0]).toContain('cursor=opaque+%2B%2F%3D');expect(screen.queryByRole('button',{name:'Load more'})).not.toBeInTheDocument();});
 it('retains existing events when pagination fails and permits retry',async()=>{const failure=new Response(JSON.stringify({success:false,error:{code:'NETWORK_PAGE',message:'raw'}}),{status:500});const fetchMock=vi.fn().mockResolvedValueOnce(ok([event('CASE_CREATED','2026-01-01','1','Existing')],'next')).mockResolvedValueOnce(failure).mockResolvedValueOnce(ok([event('RISK_ASSESSED','2026-01-02','2','Recovered')],null));show(fetchMock);await screen.findByText('Existing');fireEvent.click(screen.getByRole('button',{name:'Load more'}));expect(await screen.findByRole('alert')).toBeInTheDocument();expect(screen.getByText('Existing')).toBeInTheDocument();fireEvent.click(within(screen.getByRole('alert')).getByRole('button',{name:'Retry'}));expect(await screen.findByText('Recovered')).toBeInTheDocument();});
 it('prevents rapid duplicate cursor requests',async()=>{let resolvePage:(value:Response)=>void=()=>undefined;const pending=new Promise<Response>((resolve)=>{resolvePage=resolve;});const fetchMock=vi.fn().mockResolvedValueOnce(ok([event('CASE_CREATED','2026-01-01','1','Existing')],'next')).mockReturnValueOnce(pending);show(fetchMock);await screen.findByText('Existing');const button=screen.getByRole('button',{name:'Load more'});fireEvent.click(button);fireEvent.click(button);expect(fetchMock).toHaveBeenCalledTimes(2);resolvePage(ok([event('RISK_ASSESSED','2026-01-02','2','Only once')],null));await waitFor(()=>expect(screen.getAllByText('Only once')).toHaveLength(1));});
});
