import { useEffect, useState, type ReactNode } from 'react';
import { getDecisionBrief, type DecisionBriefDto, type ReportingActor, type ReportingReason } from '../../api/reporting.api';
import { useAuth } from '../../auth/useAuth';
import { ErrorState, Loading } from '../AsyncState';
import StatusBadge, { humanize } from '../StatusBadge';
import { formatDate } from '../../pages/CasesPage';

export default function DecisionBrief({ caseId, refreshKey = 0 }: { caseId: string; refreshKey?: number }) {
  const { token } = useAuth(); const [brief, setBrief] = useState<DecisionBriefDto | null>(null); const [error, setError] = useState<unknown>(null); const [loading, setLoading] = useState(true); const [reload, setReload] = useState(0);
  useEffect(() => { if (!token) return; const controller = new AbortController(); setLoading(true); setError(null); getDecisionBrief(caseId, token, controller.signal).then(setBrief).catch((reason) => { if (!controller.signal.aborted) setError(reason); }).finally(() => { if (!controller.signal.aborted) setLoading(false); }); return () => controller.abort(); }, [caseId, refreshKey, reload, token]);
  if (loading) return <div aria-busy="true"><Loading label="decision brief" /></div>;
  if (error) return <ErrorState error={error} retry={() => setReload((v) => v + 1)} />;
  if (!brief) return null;
  return <article className="decision-brief" aria-labelledby="brief-heading">
    <header className="report-heading"><p className="eyebrow">AUTHORITATIVE REPORTING PROJECTION</p><h2 id="brief-heading">Decision Brief</h2><p>Read-only governance summary of the persisted workflow.</p></header>
    <ReportSection title="1. Case & Asset Context"><div className="report-grid"><Fact label="Case">{brief.case.caseNumber} · {brief.case.title}</Fact><Fact label="Status"><StatusBadge value={brief.case.status} /></Fact><Fact label="Status explanation">{brief.case.statusExplanation}</Fact><Fact label="Description">{brief.case.description ?? 'Not available'}</Fact><Fact label="Emergency">{brief.case.emergencyFlag ? 'Yes — emergency' : 'No'}</Fact><Fact label="Created">{formatDate(brief.case.createdAt)}</Fact><Fact label="Updated">{formatDate(brief.case.updatedAt)}</Fact><Fact label="Closed">{formatDate(brief.case.closedAt)}</Fact><Fact label="Asset">{brief.asset.name} ({brief.asset.assetCode}) · {humanize(brief.asset.assetType)}</Fact><Fact label="Department">{brief.asset.department.name}</Fact><Fact label="Jurisdiction">{brief.asset.jurisdiction.name}</Fact></div></ReportSection>
    <ReportSection title="Workflow integrity"><p className={brief.workflow.coherent ? 'coherence good' : 'coherence warning'}>{brief.workflow.coherent ? 'Authoritative workflow chain' : 'Workflow reporting warnings are present.'}</p>{brief.workflow.warnings.length > 0 && <ul className="report-warnings">{brief.workflow.warnings.map((warning) => <li key={warning}>{warning}</li>)}</ul>}</ReportSection>
    <ReportSection title="Inspection record">{brief.inspection ? <div className="report-grid"><Fact label="Inspection date">{formatDate(brief.inspection.inspectionDate)}</Fact><Fact label="Inspector"><Actor actor={brief.inspection.inspector} /></Fact><Fact label="Structural condition">{humanize(brief.inspection.structuralCondition)}</Fact><Fact label="Crack severity">{humanize(brief.inspection.crackSeverity)}</Fact><Fact label="Corrosion">{humanize(brief.inspection.corrosionLevel)}</Fact><Fact label="Traffic importance">{humanize(brief.inspection.trafficImportance)}</Fact><Fact label="Hospital route">{brief.inspection.hospitalRoute ? 'Yes' : 'No'}</Fact><Fact label="Weather risk">{humanize(brief.inspection.weatherRisk)}</Fact><Fact label="Heavy rain expected">{brief.inspection.heavyRainExpected ? 'Yes' : 'No'}</Fact><Fact label="Estimated daily users">{brief.inspection.estimatedDailyUsers?.toLocaleString('en-IN') ?? 'Not available'}</Fact></div> : <LifecycleEmpty>No inspection has been recorded for this workflow.</LifecycleEmpty>}</ReportSection>
    <ReportSection title="2. Deterministic Assessment"><p className="section-note">Persisted assessment output; no values are recalculated in this report.</p>{brief.risk ? <><div className="report-grid"><Fact label="Risk score">{brief.risk.riskScore}</Fact><Fact label="Risk level"><StatusBadge value={brief.risk.riskLevel} kind="risk" /></Fact><Fact label="Priority"><StatusBadge value={brief.risk.priorityLevel} kind="priority" /></Fact><Fact label="Assessment version">{brief.risk.assessmentVersion}</Fact></div><StringList label="Reason codes" values={brief.risk.reasonCodes} /><ReasonList label="Persisted reasons" values={brief.risk.reasons} /></> : <LifecycleEmpty>No persisted risk assessment is available yet.</LifecycleEmpty>}</ReportSection>
    <ReportSection title="3. Recommended Action Plan">{brief.orp ? <><div className="report-grid"><Fact label="Action Plan version">{brief.orp.versionNumber}</Fact><Fact label="Status"><StatusBadge value={brief.orp.status} /></Fact><Fact label="Urgency">{humanize(brief.orp.urgency)}</Fact><Fact label="Policy version">{brief.orp.planVersion}</Fact><Fact label="Created">{formatDate(brief.orp.createdAt)}</Fact></div><StringList label="Recommended actions" values={brief.orp.recommendedActionCodes.map(actionLabel)} /><StringList label="Temporary measures" values={brief.orp.temporaryMeasures} /><StringList label="Alternative actions" values={brief.orp.alternativeActionCodes.map(actionLabel)} /><ReasonList label="Why these actions were recommended" values={brief.orp.reasons} /></> : <LifecycleEmpty>No recommended action plan is available yet.</LifecycleEmpty>}</ReportSection>
    <ReportSection title="4. Human Decision">{brief.decision ? <div className="report-grid"><Fact label="Decision"><StatusBadge value={brief.decision.decisionType} /></Fact><Fact label="Reviewer"><Actor actor={brief.decision.reviewer} /></Fact><Fact label="Reason">{brief.decision.reason ?? 'Not available'}</Fact><Fact label="Remarks">{brief.decision.remarks ?? 'Not available'}</Fact><Fact label="Recorded">{formatDate(brief.decision.createdAt)}</Fact></div> : <LifecycleEmpty>No human decision has been recorded yet.</LifecycleEmpty>}</ReportSection>
    <ReportSection title="5. Recorded Execution">{brief.execution ? <><div className="report-grid metrics"><Metric label="Total tasks" value={brief.execution.metrics.totalTasks} /><Metric label="Mandatory" value={brief.execution.metrics.mandatoryTasks} /><Metric label="Verified mandatory" value={brief.execution.metrics.verifiedMandatoryTasks} /><Metric label="Optional" value={brief.execution.metrics.optionalTasks} /><Metric label="Terminal optional" value={brief.execution.metrics.terminalOptionalTasks} /><Metric label="Verified" value={brief.execution.metrics.verifiedTasks} /><Metric label="Blocked" value={brief.execution.metrics.blockedTasks} /><Metric label="Cancelled" value={brief.execution.metrics.cancelledTasks} /><Metric label="Evidence" value={brief.execution.metrics.evidenceCount} /><Metric label="Completion" value={brief.execution.metrics.completionPercentage === null ? 'Not available' : `${brief.execution.metrics.completionPercentage}%`} /></div><div className="report-grid"><Fact label="Plan status"><StatusBadge value={brief.execution.status} /></Fact><Fact label="Template">{brief.execution.templateVersion}</Fact><Fact label="Created">{formatDate(brief.execution.createdAt)}</Fact><Fact label="Started">{formatDate(brief.execution.startedAt)}</Fact><Fact label="Completed">{formatDate(brief.execution.completedAt)}</Fact></div></> : <LifecycleEmpty>No execution plan is associated with this workflow yet.</LifecycleEmpty>}</ReportSection>
    <ReportSection title="6. Independent Accountability / Verification">{brief.execution ? <div className="accountability-grid"><ActorGroup title="Work assignment" actors={brief.execution.accountability.assignees} /><ActorGroup title="Completion submission" actors={brief.execution.accountability.completionSubmitters} /><ActorGroup title="Independent verification" actors={brief.execution.accountability.verifiers} /></div> : <LifecycleEmpty>No execution accountability record is available yet.</LifecycleEmpty>}<h4>Evidence summary</h4>{brief.evidence ? <><p>Total evidence: <strong>{brief.evidence.totalEvidence}</strong></p><dl className="evidence-counts">{Object.entries(brief.evidence.countsByType).map(([type,count]) => <div key={type}><dt>{humanize(type)}</dt><dd>{count}</dd></div>)}</dl></> : <p>No execution evidence summary is available yet.</p>}</ReportSection>
    <ReportSection title="7. Formal Workflow Closure">{brief.closure ? <><div className="report-grid"><Fact label="Closure reason">{humanize(brief.closure.closureReason)}</Fact><Fact label="Closed by"><Actor actor={brief.closure.closedBy} /></Fact><Fact label="Recorded">{formatDate(brief.closure.createdAt)}</Fact><Fact label="Closure summary">{brief.closure.closureSummary}</Fact></div><p className="section-note">Closure records the formal conclusion of the verified workflow by an authorized officer.</p></> : <LifecycleEmpty>The workflow has not been formally closed.</LifecycleEmpty>}</ReportSection>
  </article>;
}
function ReportSection({ title, children }: { title: string; children: ReactNode }) { return <section className="report-section"><h3>{title}</h3>{children}</section>; }
function Fact({ label, children }: { label: string; children: ReactNode }) { return <div className="report-fact"><dt>{label}</dt><dd>{children}</dd></div>; }
function Metric({ label, value }: { label: string; value: ReactNode }) { return <div className="metric"><strong>{value}</strong><span>{label}</span></div>; }
function Actor({ actor }: { actor: ReportingActor }) { return <>{actor.name} · {actor.designation}</>; }
function ActorGroup({ title, actors }: { title: string; actors: ReportingActor[] }) { return <section><h4>{title}</h4>{actors.length ? <ul>{actors.map((actor) => <li key={actor.id}><Actor actor={actor} /></li>)}</ul> : <p>None recorded</p>}</section>; }
function LifecycleEmpty({ children }: { children: string }) { return <p className="lifecycle-empty">{children}</p>; }
function StringList({ label, values }: { label: string; values: string[] }) { return <div className="report-list"><h4>{label}</h4>{values.length ? <ul>{values.map((value) => <li key={value}>{value}</li>)}</ul> : <p>None recorded</p>}</div>; }
function ReasonList({ label, values }: { label: string; values: ReportingReason[] }) { return <div className="report-list reason-list"><h4>{label}</h4>{values.length ? <ul>{values.map((value, index) => <li key={`${value.code ?? 'legacy'}-${index}`}>{value.code && <strong>{value.code}</strong>}<span>{value.message}</span></li>)}</ul> : <p>None recorded</p>}</div>; }
const actionLabels:Record<string,string>={ACT_RESTRICT_HEAVY_VEHICLES:'Restrict heavy vehicles',ACT_TEMP_STABILIZATION:'Temporary structural stabilization'};
function actionLabel(value:string){return actionLabels[value]??value;}
