import { fireEvent, render, screen } from '@testing-library/react';
import { afterEach, describe, expect, it, vi } from 'vitest';
import DecisionBrief from './DecisionBrief';
import { AuthContext, type AuthContextValue } from '../../auth/AuthProvider';
const actor={id:'u1',name:'Officer One',designation:'Engineer'};
const base={case:{id:'c',caseNumber:'CASE-1',title:'Bridge Case',description:'Bridge assessment',status:'CLOSED',statusExplanation:'The verified workflow has been formally closed.',emergencyFlag:true,createdAt:'2026-01-01',updatedAt:'2026-01-02',closedAt:'2026-01-08'},asset:{id:'a',assetCode:'BR-1',name:'River Bridge',assetType:'BRIDGE',department:{id:'d',code:'PWD',name:'Public Works'},jurisdiction:{id:'j',name:'Pune',type:'DIVISION'}},workflow:{coherent:true,warnings:[],statusExplanationVersion:'V1',anchor:'CASE_CLOSURE'},inspection:null,risk:null,orp:null,decision:null,execution:null,evidence:null,closure:null};
const full={...base,inspection:{id:'i',inspectionDate:'2026-01-02',structuralCondition:'POOR',crackSeverity:'SEVERE',corrosionLevel:'MODERATE',trafficImportance:'HIGH',hospitalRoute:true,weatherRisk:'HIGH',heavyRainExpected:true,estimatedDailyUsers:42000,createdAt:'2026-01-02',inspector:{...actor,email:'private@test',employeeCode:'SECRET'}},risk:{id:'r',riskScore:77,riskLevel:'VERY_HIGH',priorityLevel:'CRITICAL',reasonCodes:['POLICY_R002'],reasons:[{code:'POLICY_R002',message:'Persisted risk reason'}],assessmentVersion:'RISK_V1',createdAt:'2026-01-03'},orp:{id:'o',versionNumber:1,status:'APPROVED',urgency:'IMMEDIATE',recommendedActionCodes:['ACT_TEMP_STABILIZATION'],temporaryMeasures:['Restrict access'],alternativeActionCodes:[],reasons:[{code:'ORP_RULE_A002',message:'Persisted ORP reason'}],planVersion:'ORP_V1',createdAt:'2026-01-04'},decision:{id:'d',decisionType:'APPROVED',reason:'Human approval',remarks:'Reviewed',createdAt:'2026-01-05',reviewer:actor},execution:{id:'p',status:'COMPLETED',templateVersion:'EXEC_V1',createdAt:'2026-01-05',startedAt:'2026-01-06',completedAt:'2026-01-07',metrics:{totalTasks:2,mandatoryTasks:1,verifiedMandatoryTasks:1,optionalTasks:1,terminalOptionalTasks:1,verifiedTasks:2,blockedTasks:0,cancelledTasks:0,evidenceCount:2,completionPercentage:100},accountability:{assignees:[actor],completionSubmitters:[actor],verifiers:[{id:'u2',name:'Independent Verifier',designation:'Chief Engineer'}]}},evidence:{totalEvidence:2,countsByType:{PHOTO_REFERENCE:2},referenceUrl:'https://secret.test',description:'secret description',measurementData:{secret:true}},closure:{id:'cl',closureReason:'EXECUTION_VERIFIED',closureSummary:'Verified workflow complete',createdAt:'2026-01-08',closedBy:actor}};
const context:AuthContextValue={user:{id:'u',employeeCode:'E',name:'User',email:'u@test',designation:'Officer',role:'OFFICER',status:'ACTIVE',departmentId:'d',jurisdictionId:'j'},token:'token',organization:null,isAuthenticated:true,authStatus:'authenticated',sessionMessage:null,login:vi.fn(),logout:vi.fn()};
const response=(data:unknown,status=200)=>new Response(JSON.stringify(status===200?{success:true,data}:{success:false,error:data}),{status});
function show(data:unknown){vi.stubGlobal('fetch',vi.fn().mockResolvedValue(response(data)));return render(<AuthContext.Provider value={context}><DecisionBrief caseId="c"/></AuthContext.Provider>);}
afterEach(()=>vi.unstubAllGlobals());
describe('Decision Brief',()=>{
 it('renders full authoritative lifecycle, metrics, actors and closure with Action Plan terminology and privacy controls',async()=>{show(full);expect(await screen.findByText((_text,element)=>element?.tagName==='DD' && Boolean(element.textContent?.includes('Bridge Case')))).toBeInTheDocument();expect(screen.getByText('Persisted risk reason')).toBeInTheDocument();expect(screen.getAllByText('POLICY_R002')).toHaveLength(2);expect(screen.getByText('ORP_RULE_A002')).toBeInTheDocument();expect(screen.getByText('Persisted ORP reason')).toBeInTheDocument();expect(screen.getByRole('heading',{name:/Recommended Action Plan/})).toBeInTheDocument();expect(screen.queryByRole('heading',{name:/System-Generated Response Recommendation/})).not.toBeInTheDocument();expect(screen.getByRole('heading',{name:/Human Decision/})).toBeInTheDocument();expect(screen.getByText('100%')).toBeInTheDocument();expect(screen.getByText(/Independent Verifier/)).toBeInTheDocument();expect(screen.getByText('Verified workflow complete')).toBeInTheDocument();expect(screen.queryByText(/secret\.test|secret description|private@test|SECRET/)).not.toBeInTheDocument();});
 it('renders every explicit null lifecycle section as a legitimate state',async()=>{show({...base,case:{...base.case,status:'NEW',closedAt:null}});for(const text of ['No inspection has been recorded','No persisted risk assessment','No recommended action plan','No human decision','No execution plan','workflow has not been formally closed'])expect(await screen.findByText(new RegExp(text,'i'))).toBeInTheDocument();});
 it('shows controlled reporting-integrity wording and retries',async()=>{const fetchMock=vi.fn().mockResolvedValueOnce(response({code:'REPORTING_DATA_INTEGRITY_ERROR',message:'database internals'},409)).mockResolvedValueOnce(response(base));vi.stubGlobal('fetch',fetchMock);render(<AuthContext.Provider value={context}><DecisionBrief caseId="c"/></AuthContext.Provider>);expect(await screen.findByText(/authoritative workflow record could not be presented/i)).toBeInTheDocument();expect(screen.queryByText(/database internals/)).not.toBeInTheDocument();fireEvent.click(screen.getByRole('button',{name:'Retry'}));expect(await screen.findByText((_text,element)=>element?.tagName==='DD' && Boolean(element.textContent?.includes('Bridge Case')))).toBeInTheDocument();});
 it('renders governed classifications, exact provenance and the human authority boundary',async()=>{const action={actionId:'a1',actionCode:'ACT_SAFE',actionVersion:3,title:'Restrict traffic',category:'SAFETY',description:'Restriction',sourceReference:'Gazette',classification:'MANDATORY',sources:[{policyId:'p1',policyCode:'PWD-SAFE',policyVersion:2,policyTitle:'Safety policy',policySourceReference:'Gazette',ruleId:'r1',ruleCode:'BRIDGE-04',ruleDescription:'Rule'}]};show({...base,orp:{id:'o',versionNumber:2,status:'AWAITING_REVIEW',urgency:'IMMEDIATE',recommendedActionCodes:['ACT_SAFE'],temporaryMeasures:[],alternativeActionCodes:[],reasons:[{code:'GOVERNED_MANDATORY_ACTION',message:'Persisted governed reason'}],planVersion:'ODYSSEY_ORP_GOVERNED_V1',actionPlanContractVersion:'ODYSSEY_ORP_GOVERNED_V1',governanceMode:'GOVERNED_POLICY',governedActions:{basis:'POLICY_BACKED',packageId:'pkg',packageVersion:4,MANDATORY:[action],RECOMMENDED:[],OPTIONAL:[],PROHIBITED:[{...action,actionId:'a2',actionCode:'ACT_FORBIDDEN',title:'Forbidden action',classification:'PROHIBITED'}],ENGINEERING_RECOMMENDED:[]},decisionPackage:{id:'pkg',packageVersion:4,packageContractVersion:'ODYSSEY_DECISION_PACKAGE_V1',preparedAt:'2026-01-04',policyGovernance:{}},humanReviewBoundary:{decisionSupportOnly:true,executionAuthorized:false},createdAt:'2026-01-04'}});expect(await screen.findByText('Mandatory')).toBeInTheDocument();expect(screen.getByText('Prohibited')).toBeInTheDocument();expect(screen.getAllByText(/PWD-SAFE v2; rule BRIDGE-04/)).toHaveLength(2);expect(screen.getByText(/does not itself authorize execution/i)).toBeInTheDocument();expect(screen.queryByText(/AI decided|AI approved|autonomous decision/i)).not.toBeInTheDocument();});
});
