import{Router}from'express';import{z}from'zod';import{authenticate}from'../../middleware/authenticate';import{parseCursor,parseLimit,queryError}from'../../lib/pagination';import{createEstimate,createScenario,getScenario,listCandidates,listEstimates,PortfolioError,resourceCategories}from'./portfolio.service';
const router=Router(),money=z.string().regex(/^\d{1,16}$/),resource=z.object({category:z.enum(resourceCategories),quantity:z.number().int().nonnegative(),unit:z.literal('UNIT_DAYS')}).strict(),estimate=z.object({estimatedCostMinor:money,currency:z.literal('INR'),estimatedDurationDays:z.number().int().positive().nullable().optional(),resourceRequirements:z.array(resource).max(7),estimateBasis:z.string().trim().min(3).max(2000),sourceReference:z.string().trim().min(1).max(500)}).strict(),scenario=z.object({name:z.string().trim().min(1).max(200),budgetMinor:money,currency:z.literal('INR'),resourceCapacities:z.array(resource).max(7)}).strict();
function fail(res:any,error:unknown){const query=queryError(res,error);if(query)return query;if(error instanceof PortfolioError)return res.status(error.status).json({success:false,error:{code:error.code,message:error.message}});console.error('Portfolio planning operation failed:',error);return res.status(500).json({success:false,error:{code:'PORTFOLIO_OPERATION_FAILED',message:'Portfolio planning is currently unavailable.'}});}
router.post('/cases/:caseId/resource-estimates',authenticate,async(req,res)=>{const parsed=estimate.safeParse(req.body);if(!parsed.success)return res.status(400).json({success:false,error:{code:'INVALID_INPUT',message:'A valid INR planning estimate is required.'}});try{return res.status(201).json({success:true,data:await createEstimate(String(req.params.caseId),{...parsed.data,estimatedCostMinor:BigInt(parsed.data.estimatedCostMinor)},req.user!)});}catch(error){return fail(res,error);}});
router.get('/cases/:caseId/resource-estimates',authenticate,async(req,res)=>{try{return res.status(200).json({success:true,data:await listEstimates(String(req.params.caseId),req.user!)});}catch(error){return fail(res,error);}});
router.get('/portfolio/candidates',authenticate,async(req,res)=>{try{return res.status(200).json({success:true,data:await listCandidates(req.user!,{limit:parseLimit(req.query.limit),cursor:parseCursor(req.query.cursor)})});}catch(error){return fail(res,error);}});
router.post('/portfolio-scenarios',authenticate,async(req,res)=>{const parsed=scenario.safeParse(req.body);if(!parsed.success)return res.status(400).json({success:false,error:{code:'INVALID_INPUT',message:'A valid INR scenario is required.'}});try{return res.status(201).json({success:true,data:await createScenario({...parsed.data,budgetMinor:BigInt(parsed.data.budgetMinor)},req.user!)});}catch(error){return fail(res,error);}});
router.get('/portfolio-scenarios/:scenarioId',authenticate,async(req,res)=>{try{return res.status(200).json({success:true,data:await getScenario(String(req.params.scenarioId),req.user!)});}catch(error){return fail(res,error);}});
export default router;
