export type DemoActor={key:string;employeeCode:string;role:string;departmentId:string;jurisdictionId:string;department?:{id:string;code:string;name:string}|null;jurisdiction?:{id:string;name:string;departmentId?:string}|null};
export type DemoOrganization={department:{id:string;code:string;name:string};jurisdiction:{id:string;name:string;departmentId:string};source:'RESOLVED_FROM_AUTHORIZED_ACTORS'};
export class G6ScopeError extends Error{constructor(public code:'G6_ACTOR_MISSING'|'G6_ACTOR_SCOPE_CONFLICT'|'G6_EXPECTED_SCOPE_MISMATCH'|'G6_ORGANIZATIONAL_SCOPE_INVALID',message:string){super(`${code}: ${message}`)}}
const operationalKeys=['primary','verifier','closer']as const;
export function resolveAuthoritativeActorScope(actors:Record<string,DemoActor>,departments:Array<{id:string;code:string;name:string}>,jurisdictions:Array<{id:string;name:string;departmentId:string}>,configured:{departmentCode?:string;jurisdictionName?:string}={}):DemoOrganization{
 const required=operationalKeys.map(key=>actors[key]);if(required.some(actor=>!actor))throw new G6ScopeError('G6_ACTOR_MISSING',`Required operational actors are missing: ${operationalKeys.filter(key=>!actors[key]).join(', ')}.`);
 const baseline=required[0];const conflicts=required.filter(actor=>actor.departmentId!==baseline.departmentId||actor.jurisdictionId!==baseline.jurisdictionId);if(conflicts.length)throw new G6ScopeError('G6_ACTOR_SCOPE_CONFLICT',`Operational actor scope differs: ${required.map(actor=>`${actor.key}=${actor.department?.code??'UNKNOWN'}/${actor.jurisdiction?.name??'UNKNOWN'}`).join(', ')}.`);
 const department=departments.find(item=>item.id===baseline.departmentId),jurisdiction=jurisdictions.find(item=>item.id===baseline.jurisdictionId);if(!department||!jurisdiction||jurisdiction.departmentId!==department.id)throw new G6ScopeError('G6_ORGANIZATIONAL_SCOPE_INVALID','Actor-backed Department/Jurisdiction relationships are missing or inconsistent.');
 if(configured.departmentCode&&configured.departmentCode!==department.code)throw new G6ScopeError('G6_EXPECTED_SCOPE_MISMATCH',`Configured department ${configured.departmentCode} does not match actor scope ${department.code}.`);if(configured.jurisdictionName&&configured.jurisdictionName!==jurisdiction.name)throw new G6ScopeError('G6_EXPECTED_SCOPE_MISMATCH',`Configured jurisdiction ${configured.jurisdictionName} does not match actor scope ${jurisdiction.name}.`);
 return{department,jurisdiction,source:'RESOLVED_FROM_AUTHORIZED_ACTORS'};
}
export function scopePayload(scope:DemoOrganization){return{departmentId:scope.department.id,jurisdictionId:scope.jurisdiction.id}}
export function assertRecordScope(record:{departmentId?:string|null;jurisdictionId?:string|null},scope:DemoOrganization,label:string){if(record.departmentId!==scope.department.id||record.jurisdictionId!==scope.jurisdiction.id)throw new G6ScopeError('G6_ACTOR_SCOPE_CONFLICT',`${label} is outside the resolved actor scope ${scope.department.code}/${scope.jurisdiction.name}.`)}
export function authorityScopePayload(actor:DemoActor,scope:DemoOrganization){assertRecordScope(actor,scope,`ApprovalAuthority target ${actor.key}`);return scopePayload(scope)}
