import { EnforcementClassification, Prisma, RegistryLifecycleStatus, SystemRole } from '../../generated/prisma';
import prisma from '../../lib/prisma';
import type { OrganizationalPrincipal } from '../../security/organizational-scope';
import { assertGovernanceCreateScope, assertGovernanceEntityMutationScope, assertVisibleCase, buildGovernanceRegistryReadWhere, governanceScopeAppliesToTarget, GovernanceResourceNotFoundError } from '../../security/organizational-scope';
import { z } from 'zod';
import { pageFromRows, type Page, type StableCursor } from '../../lib/pagination';
import { appendIntegrityEvent, integrityTextDigest } from '../integrity/integrity.service';

export class PolicyRegistryError extends Error { constructor(public code:string,public status:number,message:string){super(message);} }

export const applicabilitySchema=z.object({assetTypes:z.array(z.enum(['BRIDGE','ROAD','FLYOVER'])).optional(),caseStatuses:z.array(z.string().min(1)).optional(),riskLevels:z.array(z.string().min(1)).optional(),priorityLevels:z.array(z.string().min(1)).optional(),emergencyFlag:z.boolean().optional()}).strict();
export const ruleConditionSchema=applicabilitySchema;
const organization={select:{id:true,name:true}} as const;
const policySelect={id:true,policyCode:true,versionNumber:true,title:true,sourceTitle:true,sourceReference:true,sourceUrl:true,effectiveFrom:true,effectiveUntil:true,status:true,validationState:true,approvedAt:true,createdAt:true,updatedAt:true,department:organization,jurisdiction:organization,_count:{select:{rules:true}}} satisfies Prisma.PolicyDocumentSelect;
const actionSelect={id:true,actionCode:true,versionNumber:true,title:true,category:true,description:true,applicability:true,enforcementClassification:true,sourceReference:true,effectiveFrom:true,effectiveUntil:true,status:true,approvedAt:true,createdAt:true,updatedAt:true,department:organization,jurisdiction:organization,provenancePolicyDocument:{select:{id:true,policyCode:true,versionNumber:true,title:true}}} satisfies Prisma.ApprovedActionVersionSelect;
const ruleSelect={id:true,ruleCode:true,description:true,conditions:true,enforcementLevel:true,enabled:true,createdAt:true,policyDocument:{select:{id:true,policyCode:true,versionNumber:true,title:true,sourceReference:true}},action:{select:{id:true,actionCode:true,versionNumber:true,title:true,category:true,description:true,sourceReference:true,enforcementClassification:true,applicability:true}}} satisfies Prisma.PolicyRuleSelect;

function dates(from:Date,until:Date|null|undefined){if(until&&until<=from)throw new PolicyRegistryError('INVALID_EFFECTIVE_PERIOD',400,'Effective end must be after effective start.');}
type RegistryPage={limit:number;cursor?:StableCursor;status?:RegistryLifecycleStatus;search?:string};
const after=(cursor?:StableCursor)=>cursor?{OR:[{createdAt:{lt:new Date(cursor.at)}},{createdAt:new Date(cursor.at),id:{lt:cursor.id}}]}:{};
export async function listPolicies(principal:OrganizationalPrincipal,query:RegistryPage):Promise<Page<any>>{const rows=await prisma.policyDocument.findMany({where:{AND:[buildGovernanceRegistryReadWhere(principal),after(query.cursor),query.status?{status:query.status}:{},query.search?{OR:[{policyCode:{contains:query.search,mode:'insensitive'}},{title:{contains:query.search,mode:'insensitive'}}]}:{}]},select:policySelect,orderBy:[{createdAt:'desc'},{id:'desc'}],take:query.limit+1});return pageFromRows(rows,query.limit,row=>row.createdAt.toISOString());}
export async function listApprovedActions(principal:OrganizationalPrincipal,query:RegistryPage):Promise<Page<any>>{const rows=await prisma.approvedActionVersion.findMany({where:{AND:[buildGovernanceRegistryReadWhere(principal),after(query.cursor),query.status?{status:query.status}:{},query.search?{OR:[{actionCode:{contains:query.search,mode:'insensitive'}},{title:{contains:query.search,mode:'insensitive'}}]}:{}]},select:actionSelect,orderBy:[{createdAt:'desc'},{id:'desc'}],take:query.limit+1});return pageFromRows(rows,query.limit,row=>row.createdAt.toISOString());}
export async function listPolicyRules(policyDocumentId:string,principal:OrganizationalPrincipal,query:{limit:number;cursor?:StableCursor}){const policy=await prisma.policyDocument.findFirst({where:{id:policyDocumentId,AND:[buildGovernanceRegistryReadWhere(principal)]},select:{id:true}});if(!policy)throw new GovernanceResourceNotFoundError();const rows=await prisma.policyRule.findMany({where:{policyDocumentId,...after(query.cursor)},select:ruleSelect,orderBy:[{createdAt:'desc'},{id:'desc'}],take:query.limit+1});return pageFromRows(rows,query.limit,row=>row.createdAt.toISOString());}

export async function createPolicy(input:{policyCode:string;versionNumber:number;title:string;sourceTitle:string;sourceReference:string;sourceUrl?:string|null;departmentId?:string|null;jurisdictionId?:string|null;effectiveFrom:Date;effectiveUntil?:Date|null},principal:OrganizationalPrincipal){dates(input.effectiveFrom,input.effectiveUntil);await assertGovernanceCreateScope(principal,input.departmentId,input.jurisdictionId);try{return await prisma.$transaction(async tx=>{const created=await tx.policyDocument.create({data:{...input,createdById:principal.id,status:'DRAFT',validationState:'NOT_VALIDATED'},select:policySelect});await appendIntegrityEvent(tx,{eventType:'POLICY_VERSION_CREATED',sourceEventKey:`POLICY_VERSION:${created.id}`,resourceType:'PolicyDocument',resourceId:created.id,actor:principal,departmentId:input.departmentId??null,jurisdictionId:input.jurisdictionId??null,occurredAt:created.createdAt,facts:{policyCode:created.policyCode,versionNumber:created.versionNumber,status:created.status,validationState:created.validationState,effectiveFrom:created.effectiveFrom.toISOString(),effectiveUntil:created.effectiveUntil?.toISOString()??null,sourceReferenceDigest:integrityTextDigest(created.sourceReference)}});return created;});}catch(error){if(error instanceof Prisma.PrismaClientKnownRequestError&&error.code==='P2002')throw new PolicyRegistryError('POLICY_VERSION_EXISTS',409,'That policy version already exists.');throw error;}}
export async function createApprovedAction(input:{actionCode:string;versionNumber:number;title:string;category:string;description:string;applicability:unknown;enforcementClassification:EnforcementClassification;provenancePolicyDocumentId?:string|null;sourceReference:string;departmentId?:string|null;jurisdictionId?:string|null;effectiveFrom:Date;effectiveUntil?:Date|null},principal:OrganizationalPrincipal){dates(input.effectiveFrom,input.effectiveUntil);const target=await assertGovernanceCreateScope(principal,input.departmentId,input.jurisdictionId);const applicability=applicabilitySchema.safeParse(input.applicability);if(!applicability.success)throw new PolicyRegistryError('INVALID_APPLICABILITY',400,'Action applicability is invalid.');if(input.provenancePolicyDocumentId){const policy=await prisma.policyDocument.findFirst({where:{id:input.provenancePolicyDocumentId,AND:[buildGovernanceRegistryReadWhere(principal)]},select:{departmentId:true,jurisdictionId:true}});if(!policy||!governanceScopeAppliesToTarget(policy,target))throw new GovernanceResourceNotFoundError();}try{return await prisma.$transaction(async tx=>{const created=await tx.approvedActionVersion.create({data:{...input,applicability:applicability.data,createdById:principal.id,status:'DRAFT'},select:actionSelect});await appendIntegrityEvent(tx,{eventType:'APPROVED_ACTION_VERSION_CREATED',sourceEventKey:`APPROVED_ACTION_VERSION:${created.id}`,resourceType:'ApprovedActionVersion',resourceId:created.id,actor:principal,departmentId:input.departmentId??null,jurisdictionId:input.jurisdictionId??null,occurredAt:created.createdAt,facts:{actionCode:created.actionCode,versionNumber:created.versionNumber,category:created.category,enforcementClassification:created.enforcementClassification,status:created.status,provenancePolicyDocumentId:input.provenancePolicyDocumentId??null,effectiveFrom:created.effectiveFrom.toISOString(),effectiveUntil:created.effectiveUntil?.toISOString()??null,sourceReferenceDigest:integrityTextDigest(created.sourceReference)}});return created;});}catch(error){if(error instanceof Prisma.PrismaClientKnownRequestError&&error.code==='P2002')throw new PolicyRegistryError('ACTION_VERSION_EXISTS',409,'That action version already exists.');throw error;}}
export async function createPolicyRule(policyDocumentId:string,input:{ruleCode:string;description:string;conditions:unknown;actionId:string;enforcementLevel:EnforcementClassification},principal:OrganizationalPrincipal){const conditions=ruleConditionSchema.safeParse(input.conditions);if(!conditions.success)throw new PolicyRegistryError('INVALID_RULE_CONDITIONS',400,'Policy rule conditions are invalid.');const [policy,action]=await Promise.all([prisma.policyDocument.findUnique({where:{id:policyDocumentId},select:{status:true,departmentId:true,jurisdictionId:true}}),prisma.approvedActionVersion.findUnique({where:{id:input.actionId},select:{id:true,departmentId:true,jurisdictionId:true}})]);assertGovernanceEntityMutationScope(principal,policy);if(!action||!governanceScopeAppliesToTarget(action,policy!))throw new GovernanceResourceNotFoundError();if(policy!.status!==RegistryLifecycleStatus.DRAFT)throw new PolicyRegistryError('POLICY_IMMUTABLE',409,'Rules may only be edited while the policy is in draft.');try{return await prisma.$transaction(async tx=>{const created=await tx.policyRule.create({data:{policyDocumentId,...input,conditions:conditions.data},select:ruleSelect});await appendIntegrityEvent(tx,{eventType:'POLICY_RULE_CREATED',sourceEventKey:`POLICY_RULE:${created.id}`,resourceType:'PolicyRule',resourceId:created.id,actor:principal,departmentId:policy!.departmentId??null,jurisdictionId:policy!.jurisdictionId??null,occurredAt:created.createdAt,facts:{policyDocumentId,ruleCode:created.ruleCode,actionId:input.actionId,enforcementLevel:created.enforcementLevel,conditions:conditions.data,descriptionDigest:integrityTextDigest(created.description)}});return created;});}catch(error){if(error instanceof Prisma.PrismaClientKnownRequestError&&error.code==='P2002')throw new PolicyRegistryError('RULE_CODE_EXISTS',409,'That rule code already exists in this policy version.');throw error;}}

const transitions:Record<RegistryLifecycleStatus,RegistryLifecycleStatus[]>={DRAFT:['VALIDATION','ARCHIVED'],VALIDATION:['APPROVED','DRAFT','ARCHIVED'],APPROVED:['ACTIVE','ARCHIVED'],ACTIVE:['SUPERSEDED','ARCHIVED'],SUPERSEDED:['ARCHIVED'],ARCHIVED:[]};
export async function transitionPolicy(id:string,next:RegistryLifecycleStatus,principal:OrganizationalPrincipal,validationState?:'VALIDATED'|'REJECTED'){const current=await prisma.policyDocument.findUnique({where:{id},select:{status:true,validationState:true,departmentId:true,jurisdictionId:true,updatedAt:true,_count:{select:{rules:true}}}});assertGovernanceEntityMutationScope(principal,current);if(!transitions[current!.status].includes(next))throw new PolicyRegistryError('INVALID_LIFECYCLE_TRANSITION',409,'Policy lifecycle transition is not allowed.');if(next==='APPROVED'&&(validationState!=='VALIDATED'||current!._count.rules===0))throw new PolicyRegistryError('POLICY_VALIDATION_REQUIRED',409,'A validated policy with at least one structured rule is required.');if(next==='ACTIVE'&&current!.validationState!=='VALIDATED')throw new PolicyRegistryError('POLICY_VALIDATION_REQUIRED',409,'Only a validated policy may become active.');return prisma.$transaction(async tx=>{const updated=await tx.policyDocument.update({where:{id},data:{status:next,validationState:validationState??undefined,approvedById:next==='APPROVED'?principal.id:undefined,approvedAt:next==='APPROVED'?new Date():undefined},select:policySelect});await appendIntegrityEvent(tx,{eventType:'POLICY_STATUS_CHANGED',sourceEventKey:`POLICY_STATUS:${id}:${current!.status}:${next}:${current!.updatedAt?.toISOString()??'INITIAL'}`,resourceType:'PolicyDocument',resourceId:id,actor:principal,departmentId:current!.departmentId??null,jurisdictionId:current!.jurisdictionId??null,occurredAt:updated.updatedAt??new Date(),facts:{policyCode:updated.policyCode,versionNumber:updated.versionNumber,fromStatus:current!.status,toStatus:next,validationState:updated.validationState,approvedAt:updated.approvedAt?.toISOString()??null}});return updated;});}
export async function transitionAction(id:string,next:RegistryLifecycleStatus,principal:OrganizationalPrincipal){const current=await prisma.approvedActionVersion.findUnique({where:{id},select:{status:true,departmentId:true,jurisdictionId:true,updatedAt:true}});assertGovernanceEntityMutationScope(principal,current);if(!transitions[current!.status].includes(next))throw new PolicyRegistryError('INVALID_LIFECYCLE_TRANSITION',409,'Action lifecycle transition is not allowed.');return prisma.$transaction(async tx=>{const updated=await tx.approvedActionVersion.update({where:{id},data:{status:next,approvedById:next==='APPROVED'?principal.id:undefined,approvedAt:next==='APPROVED'?new Date():undefined},select:actionSelect});await appendIntegrityEvent(tx,{eventType:'APPROVED_ACTION_STATUS_CHANGED',sourceEventKey:`APPROVED_ACTION_STATUS:${id}:${current!.status}:${next}:${current!.updatedAt?.toISOString()??'INITIAL'}`,resourceType:'ApprovedActionVersion',resourceId:id,actor:principal,departmentId:current!.departmentId??null,jurisdictionId:current!.jurisdictionId??null,occurredAt:updated.updatedAt??new Date(),facts:{actionCode:updated.actionCode,versionNumber:updated.versionNumber,fromStatus:current!.status,toStatus:next,enforcementClassification:updated.enforcementClassification,approvedAt:updated.approvedAt?.toISOString()??null}});return updated;});}

type Context={assetType:string;caseStatus:string;riskLevel:string|null;priorityLevel:string|null;emergencyFlag:boolean};
function matches(condition:z.infer<typeof ruleConditionSchema>,context:Context){if(condition.assetTypes&&!condition.assetTypes.includes(context.assetType as never))return false;if(condition.caseStatuses&&!condition.caseStatuses.includes(context.caseStatus))return false;if(condition.riskLevels){if(!context.riskLevel)return null;if(!condition.riskLevels.includes(context.riskLevel))return false;}if(condition.priorityLevels){if(!context.priorityLevel)return null;if(!condition.priorityLevels.includes(context.priorityLevel))return false;}if(condition.emergencyFlag!==undefined&&condition.emergencyFlag!==context.emergencyFlag)return false;return true;}
export async function resolveCasePolicy(caseId:string,principal:OrganizationalPrincipal,asOf=new Date()){
 await assertVisibleCase(caseId,principal);
 const target=await prisma.case.findUnique({where:{id:caseId},select:{id:true,caseNumber:true,status:true,riskLevel:true,priorityLevel:true,emergencyFlag:true,asset:{select:{assetType:true,departmentId:true,jurisdictionId:true}}}});if(!target)throw new PolicyRegistryError('CASE_NOT_FOUND',404,'Case was not found.');
 const rules=await prisma.policyRule.findMany({where:{enabled:true,policyDocument:{status:'ACTIVE',effectiveFrom:{lte:asOf},OR:[{effectiveUntil:null},{effectiveUntil:{gt:asOf}}],AND:[{OR:[{departmentId:null},{departmentId:target.asset.departmentId}]},{OR:[{jurisdictionId:null},{jurisdictionId:target.asset.jurisdictionId}]}]},action:{status:'ACTIVE',effectiveFrom:{lte:asOf},OR:[{effectiveUntil:null},{effectiveUntil:{gt:asOf}}],AND:[{OR:[{departmentId:null},{departmentId:target.asset.departmentId}]},{OR:[{jurisdictionId:null},{jurisdictionId:target.asset.jurisdictionId}]}]}},select:ruleSelect,orderBy:[{policyDocument:{policyCode:'asc'}},{ruleCode:'asc'}]});
 const issues:Array<{code:string;message:string;ruleCode?:string;actionCode?:string}>=[];const applicable:typeof rules=[];const context={assetType:target.asset.assetType,caseStatus:target.status,riskLevel:target.riskLevel,priorityLevel:target.priorityLevel,emergencyFlag:target.emergencyFlag};
 for(const rule of rules){const parsed=ruleConditionSchema.safeParse(rule.conditions),actionApplicability=applicabilitySchema.safeParse(rule.action.applicability);if(!parsed.success){issues.push({code:'INVALID_RULE_CONDITIONS',message:'An active rule contains unsupported conditions.',ruleCode:rule.ruleCode});continue;}if(!actionApplicability.success){issues.push({code:'INVALID_ACTION_APPLICABILITY',message:'An active action contains unsupported applicability.',actionCode:rule.action.actionCode});continue;}const ruleResult=matches(parsed.data,context),actionResult=matches(actionApplicability.data,context);if(ruleResult===null||actionResult===null)issues.push({code:'MISSING_CASE_CONTEXT',message:'Required Case context is not yet available.',ruleCode:rule.ruleCode});else if(ruleResult&&actionResult)applicable.push(rule);}
 if(!rules.length)issues.push({code:'NO_APPLICABLE_ACTIVE_POLICY',message:'No active policy rules exist for this organizational scope and effective date.'});
 const byCode=new Map<string,typeof applicable>();for(const item of applicable){const group=byCode.get(item.action.actionCode)??[];group.push(item);byCode.set(item.action.actionCode,group);}for(const [actionCode,group] of byCode){const levels=new Set(group.map((item)=>item.enforcementLevel));const versions=new Set(group.map((item)=>item.action.versionNumber));if(levels.has('PROHIBITED')&&[...levels].some((level)=>level!=='PROHIBITED'))issues.push({code:'CONFLICTING_ENFORCEMENT',message:'Active rules both prohibit and permit the same action.',actionCode});if(versions.size>1)issues.push({code:'MULTIPLE_ACTIVE_ACTION_VERSIONS',message:'Multiple active versions of the same action are applicable.',actionCode});}
 const status=issues.length?'ABSTAINED':'RESOLVED';return{status,asOf,caseReference:target.caseNumber,context:{assetType:context.assetType,caseStatus:context.caseStatus,riskLevel:context.riskLevel,priorityLevel:context.priorityLevel,emergencyFlag:context.emergencyFlag},issues,applicableRules:status==='RESOLVED'?applicable.map((item)=>({rule:{id:item.id,code:item.ruleCode,description:item.description,enforcementLevel:item.enforcementLevel},policy:item.policyDocument,action:{id:item.action.id,actionCode:item.action.actionCode,versionNumber:item.action.versionNumber,title:item.action.title,category:item.action.category,description:item.action.description,sourceReference:item.action.sourceReference,enforcementClassification:item.action.enforcementClassification}})):[],governance:{advisoryOnly:true,caseMutated:false,automaticDecision:false}};
}

export function canAdministerPolicy(principal:OrganizationalPrincipal){return principal.role===SystemRole.POLICY_ADMIN||principal.role===SystemRole.SYSTEM_ADMIN;}
