import { Router } from 'express';import{z}from'zod';import{EnforcementClassification,RegistryLifecycleStatus,SystemRole}from'../../generated/prisma';import{authenticate}from'../../middleware/authenticate';import{requireRole}from'../../middleware/require-role';import{defaultGovernanceCreateScope,GovernanceResourceNotFoundError,ScopedResourceNotFoundError}from'../../security/organizational-scope';import{createApprovedAction,createPolicy,createPolicyRule,listApprovedActions,listPolicies,listPolicyRules,PolicyRegistryError,resolveCasePolicy,transitionAction,transitionPolicy}from'./policy-registry.service';
const router=Router(),admin=requireRole(SystemRole.POLICY_ADMIN,SystemRole.SYSTEM_ADMIN);const uuid=z.string().uuid(),text=z.string().trim().min(1).max(1000),optionalUuid=uuid.nullable().optional(),date=z.coerce.date();const lifecycle=z.nativeEnum(RegistryLifecycleStatus);const enforcement=z.nativeEnum(EnforcementClassification);
const policySchema=z.object({policyCode:z.string().trim().min(2).max(80).regex(/^[A-Z0-9_-]+$/),versionNumber:z.number().int().positive(),title:text.max(240),sourceTitle:text.max(300),sourceReference:text.max(500),sourceUrl:z.string().url().max(1000).nullable().optional(),departmentId:optionalUuid,jurisdictionId:optionalUuid,effectiveFrom:date,effectiveUntil:date.nullable().optional()}).strict();
const actionSchema=z.object({actionCode:z.string().trim().min(2).max(100).regex(/^ACT_[A-Z0-9_]+$/),versionNumber:z.number().int().positive(),title:text.max(240),category:text.max(100),description:text.max(2000),applicability:z.object({}).passthrough(),enforcementClassification:enforcement,provenancePolicyDocumentId:optionalUuid,sourceReference:text.max(500),departmentId:optionalUuid,jurisdictionId:optionalUuid,effectiveFrom:date,effectiveUntil:date.nullable().optional()}).strict();
const ruleSchema=z.object({ruleCode:z.string().trim().min(2).max(100).regex(/^[A-Z0-9_-]+$/),description:text.max(1000),conditions:z.object({}).passthrough(),actionId:uuid,enforcementLevel:enforcement}).strict();
function fail(res:any,error:unknown){if(error instanceof PolicyRegistryError)return res.status(error.status).json({success:false,error:{code:error.code,message:error.message}});if(error instanceof GovernanceResourceNotFoundError)return res.status(404).json({success:false,error:{code:'GOVERNANCE_RESOURCE_NOT_FOUND',message:'Governance registry resource not found.'}});if(error instanceof ScopedResourceNotFoundError)return res.status(404).json({success:false,error:{code:'CASE_NOT_FOUND',message:'Case not found.'}});console.error('Policy registry operation failed:',error);return res.status(500).json({success:false,error:{code:'POLICY_REGISTRY_FAILED',message:'The policy registry operation could not be completed.'}});}
router.get('/policies',authenticate,admin,async(req,res)=>{try{return res.json({success:true,data:await listPolicies(req.user!)});}catch(error){return fail(res,error);}});
router.post('/policies',authenticate,admin,async(req,res)=>{const parsed=policySchema.safeParse(req.body);if(!parsed.success)return res.status(400).json({success:false,error:{code:'INVALID_INPUT',message:'Policy input is invalid.'}});try{return res.status(201).json({success:true,data:await createPolicy(defaultGovernanceCreateScope(parsed.data,req.user!),req.user!)});}catch(error){return fail(res,error);}});
router.get('/policies/:policyId/rules',authenticate,admin,async(req,res)=>{try{return res.json({success:true,data:await listPolicyRules(String(req.params.policyId),req.user!)});}catch(error){return fail(res,error);}});
router.post('/policies/:policyId/rules',authenticate,admin,async(req,res)=>{const parsed=ruleSchema.safeParse(req.body);if(!parsed.success)return res.status(400).json({success:false,error:{code:'INVALID_INPUT',message:'Policy rule input is invalid.'}});try{return res.status(201).json({success:true,data:await createPolicyRule(String(req.params.policyId),parsed.data,req.user!)});}catch(error){return fail(res,error);}});
router.patch('/policies/:policyId/lifecycle',authenticate,admin,async(req,res)=>{const parsed=z.object({status:lifecycle,validationState:z.enum(['VALIDATED','REJECTED']).optional()}).strict().safeParse(req.body);if(!parsed.success)return res.status(400).json({success:false,error:{code:'INVALID_INPUT',message:'Lifecycle input is invalid.'}});try{return res.json({success:true,data:await transitionPolicy(String(req.params.policyId),parsed.data.status,req.user!,parsed.data.validationState)});}catch(error){return fail(res,error);}});
router.get('/approved-actions',authenticate,admin,async(req,res)=>{try{return res.json({success:true,data:await listApprovedActions(req.user!)});}catch(error){return fail(res,error);}});
router.post('/approved-actions',authenticate,admin,async(req,res)=>{const parsed=actionSchema.safeParse(req.body);if(!parsed.success)return res.status(400).json({success:false,error:{code:'INVALID_INPUT',message:'Approved action input is invalid.'}});try{return res.status(201).json({success:true,data:await createApprovedAction(defaultGovernanceCreateScope(parsed.data,req.user!),req.user!)});}catch(error){return fail(res,error);}});
router.patch('/approved-actions/:actionId/lifecycle',authenticate,admin,async(req,res)=>{const parsed=z.object({status:lifecycle}).strict().safeParse(req.body);if(!parsed.success)return res.status(400).json({success:false,error:{code:'INVALID_INPUT',message:'Lifecycle input is invalid.'}});try{return res.json({success:true,data:await transitionAction(String(req.params.actionId),parsed.data.status,req.user!)});}catch(error){return fail(res,error);}});
router.get('/cases/:caseId/policy-resolution',authenticate,async(req,res)=>{try{return res.json({success:true,data:await resolveCasePolicy(String(req.params.caseId),req.user!)});}catch(error){return fail(res,error);}});
export default router;
