import { fireEvent, render, screen, waitFor } from '@testing-library/react'; import { afterEach, describe, expect, it, vi } from 'vitest'; import { AuthContext } from '../../auth/AuthProvider'; import DecisionPackage from './DecisionPackage';
const auth = { token: 'token', accessToken: 'token', user: { role: 'OFFICER' }, isAuthenticated: true } as any;
const response = (data: unknown, status = 200) => new Response(JSON.stringify(status < 400 ? { success: true, data } : { success: false, error: data }), { status });
const readiness = (outcome: 'READY' | 'NOT_READY' | 'BLOCKED', reasons: any[] = []) => ({ caseReference: 'CASE-1', outcome, assessmentVersion: 'ODYSSEY_READINESS_V1', evaluatedAt: '2026-08-20T12:00:00Z', checks: [], reasons, policySummary: { governanceEstablished: false, status: 'NOT_REQUIRED' }, governance: { readOnly: true, caseMutated: false, approvalGranted: false, officerJudgmentRequired: true } });
const pkg = (version = 2, status = 'PREPARED') => ({ id: `package-${version}`, caseId: 'case', packageVersion: version, packageContractVersion: 'ODYSSEY_DECISION_PACKAGE_V1', status, preparedAt: '2026-08-20T12:00:00Z', createdAt: '2026-08-20T12:00:00Z', reused: false, preparedBy: { name: 'Rahul Patil', employeeCode: 'PWD-1', designation: 'Executive Engineer' }, caseContext: { caseReference: 'CASE-1', emergencyFlag: false, asset: { name: 'Pune Bridge', assetCode: 'BR-1', assetType: 'BRIDGE', department: { name: 'Public Works' }, jurisdiction: { name: 'Pune' } } }, inspection: { id: 'inspection-1', inspectionDate: '2026-08-20T10:00:00Z', structuralCondition: 'POOR', crackSeverity: 'SEVERE', corrosionLevel: 'MODERATE', weatherRisk: 'HIGH' }, riskAssessment: { id: 'risk-1', riskScore: 77, riskLevel: 'VERY_HIGH', priorityLevel: 'CRITICAL', assessmentVersion: 'ODYSSEY_RISK_V1', reasons: [{ message: 'Severe structural concern.' }] }, readiness: {}, policyGovernance: { state: 'APPLICABLE_GOVERNANCE', rules: [{ rule: { id: 'rule', code: 'RULE-1' }, policy: { policyCode: 'POLICY', versionNumber: 2 }, action: { actionCode: 'ACT_1', versionNumber: 3 } }] }, governedActions: Object.fromEntries(['MANDATORY', 'RECOMMENDED', 'OPTIONAL', 'PROHIBITED'].map((level) => [level, [{ actionId: `action-${level}`, actionCode: `ACT_${level}`, actionVersion: 3, title: `${level} action`, category: 'SAFETY', description: `${level} description`, sourceReference: 'OFFICIAL-REF', enforcementClassification: level }]])), humanReviewBoundary: { preparedForHumanReview: true, humanDecision: false, executionAuthorized: false, officerRemainsResponsible: true } });
function mock(history: any[], gate: any) { vi.stubGlobal('fetch', vi.fn((url: string) => Promise.resolve(response(url.includes('/readiness') ? gate : history)))); return render(<AuthContext.Provider value={auth}><DecisionPackage caseId="case" /></AuthContext.Provider>); }
afterEach(() => vi.unstubAllGlobals());
describe('Decision Package workspace', () => {
  it('shows loading then a READY preparation action when no package exists', async () => { mock([], readiness('READY')); expect(screen.getByText(/Loading Decision Package history/)).toBeInTheDocument(); expect(await screen.findByRole('button', { name: 'Prepare Decision Package' })).toBeEnabled(); expect(screen.queryByText(/bypass/i)).not.toBeInTheDocument(); });
  it.each([['NOT_READY', 'Complete the missing workflow inputs'], ['BLOCKED', 'Resolve the governance or authoritative-data blocker']])('does not offer preparation for %s', async (outcome, text) => { mock([], readiness(outcome as any, [{ code: 'SAFE_REASON', message: 'Governed reason.' }])); expect(await screen.findByText(new RegExp(text))).toBeInTheDocument(); expect(screen.queryByRole('button', { name: /Prepare Decision Package/ })).not.toBeInTheDocument(); expect(screen.getByText('Governed reason.')).toBeInTheDocument(); });
  it('shows immutable version history, provenance, risk reasons, and all distinct enforcement groups', async () => { mock([pkg(2), pkg(1, 'SUPERSEDED')], readiness('READY')); expect(await screen.findByText('Decision Package v2')).toBeInTheDocument(); expect(screen.getByRole('button', { name: /v1.*Superseded/ })).toBeInTheDocument(); expect(screen.getByText('Very High')).toBeInTheDocument(); expect(screen.getByText('Critical')).toBeInTheDocument(); expect(screen.getByText('Severe structural concern.')).toBeInTheDocument(); expect(screen.getByText('inspection-1')).toBeInTheDocument(); expect(screen.getByText(/POLICY v2.*RULE-1.*ACT_1 v3/)).toBeInTheDocument(); for (const level of ['MANDATORY', 'RECOMMENDED', 'OPTIONAL', 'PROHIBITED']) { expect(screen.getByRole('heading', { name: level })).toBeInTheDocument(); expect(screen.getByText(`${level} action`)).toBeInTheDocument(); } expect(screen.getByText(/not a Human Decision, does not authorize execution/i)).toBeInTheDocument(); expect(screen.queryByText(/AI confidence|automatically approved|AI decision/i)).not.toBeInTheDocument(); });
  it('presents an honest no-policy package', async () => { const item: any = pkg(); item.policyGovernance = { state: 'NO_APPLICABLE_ACTIVE_POLICY_GOVERNANCE', message: 'No applicable active policy governance was established at preparation time.', rules: [] }; item.governedActions = { MANDATORY: [], RECOMMENDED: [], OPTIONAL: [], PROHIBITED: [] }; mock([item], readiness('READY')); expect(await screen.findByText(/No applicable active policy governance was established/)).toBeInTheDocument(); expect(screen.getAllByText('None recorded.')).toHaveLength(4); });
  it('uses controlled API errors and never renders privacy-sensitive fields', async () => { vi.stubGlobal('fetch', vi.fn().mockResolvedValue(response({ code: 'FORBIDDEN', message: 'reporterName passwordHash internal' }, 403))); render(<AuthContext.Provider value={auth}><DecisionPackage caseId="case" /></AuthContext.Provider>); expect(await screen.findByText(/do not have authority/i)).toBeInTheDocument(); expect(screen.queryByText(/reporterName|passwordHash/)).not.toBeInTheDocument(); });
  it('prepares through a body-free governed endpoint and refreshes history', async () => { const fetchMock = vi.fn((url: string, init?: RequestInit) => { if (init?.method === 'POST') return Promise.resolve(response(pkg())); return Promise.resolve(response(url.includes('/readiness') ? readiness('READY') : [])); }); vi.stubGlobal('fetch', fetchMock); render(<AuthContext.Provider value={auth}><DecisionPackage caseId="case" /></AuthContext.Provider>); fireEvent.click(await screen.findByRole('button', { name: 'Prepare Decision Package' })); await waitFor(() => expect(fetchMock.mock.calls.filter((call) => call[1]?.method === 'POST')).toHaveLength(1)); const post = fetchMock.mock.calls.find((call) => call[1]?.method === 'POST'); expect(post?.[1]?.body).toBe('{}'); expect(String(post?.[0])).not.toContain('force'); });
});
