import { useEffect, useState } from 'react';
import { listDecisionPackages, prepareDecisionPackage, type DecisionPackageDto } from '../../api/decision-packages.api';
import { getCaseReadiness, type ReadinessDto } from '../../api/readiness.api';
import { useAuth } from '../../auth/useAuth';
import { ErrorState, Loading } from '../AsyncState';
import { humanize } from '../StatusBadge';

const groups = ['MANDATORY', 'RECOMMENDED', 'OPTIONAL', 'PROHIBITED'] as const;
export default function DecisionPackage({ caseId, refreshKey = 0 }: { caseId: string; refreshKey?: number }) {
  const { token, user } = useAuth(); const [packages, setPackages] = useState<DecisionPackageDto[] | null>(null); const [readiness, setReadiness] = useState<ReadinessDto | null>(null);
  const [selected, setSelected] = useState<string | null>(null); const [error, setError] = useState<unknown>(null); const [loading, setLoading] = useState(true); const [preparing, setPreparing] = useState(false); const [reload, setReload] = useState(0);
  useEffect(() => { if (!token) return; const controller = new AbortController(); setLoading(true); setError(null); Promise.all([listDecisionPackages(caseId, token, controller.signal), getCaseReadiness(caseId, token, controller.signal)]).then(([history, gate]) => { setPackages(history); setReadiness(gate); setSelected((current) => current && history.some((item) => item.id === current) ? current : history[0]?.id ?? null); }).catch((reason) => { if (!controller.signal.aborted) setError(reason); }).finally(() => { if (!controller.signal.aborted) setLoading(false); }); return () => controller.abort(); }, [caseId, refreshKey, reload, token]);
  const prepare = async () => { if (!token) return; setPreparing(true); setError(null); try { const item = await prepareDecisionPackage(caseId, token); setReload((value) => value + 1); setSelected(item.id); } catch (reason) { setError(reason); } finally { setPreparing(false); } };
  const current = packages?.find((item) => item.id === selected) ?? packages?.[0]; const mayPrepare = user?.role === 'OFFICER' || user?.role === 'SYSTEM_ADMIN';
  return <section className="decision-package" aria-labelledby="decision-package-heading"><p className="section-label">GOVERNED DECISION SUPPORT</p><h2 id="decision-package-heading">Decision Package</h2>
    {loading ? <Loading label="Decision Package history" /> : error ? <ErrorState error={error} retry={() => setReload((value) => value + 1)} /> : <>
      <div className={`package-gate package-gate-${readiness?.outcome.toLowerCase().replace('_', '-')}`}><strong>Readiness: {readiness?.outcome.replace('_', ' ')}</strong><span>{readiness?.outcome === 'READY' ? 'Governed inputs are available for package preparation.' : readiness?.outcome === 'NOT_READY' ? 'Complete the missing workflow inputs before preparation.' : 'Resolve the governance or authoritative-data blocker before preparation.'}</span></div>
      {!packages?.length && <div className="package-empty"><h3>No Decision Package has been prepared</h3>{readiness?.reasons.filter((item) => item.code !== 'READINESS_READY').map((item) => <p key={item.code}>{item.message} <code>{item.code}</code></p>)}{mayPrepare && readiness?.outcome === 'READY' && <button className="primary-button" type="button" onClick={prepare} disabled={preparing}>{preparing ? 'Preparing…' : 'Prepare Decision Package'}</button>}</div>}
      {packages && packages.length > 0 && <><div className="package-toolbar"><div><h3>Package History</h3><div className="package-version-list">{packages.map((item) => <button type="button" key={item.id} aria-pressed={current?.id === item.id} onClick={() => setSelected(item.id)}>v{item.packageVersion} · {humanize(item.status)}</button>)}</div></div>{mayPrepare && readiness?.outcome === 'READY' && <button className="primary-button" type="button" onClick={prepare} disabled={preparing}>{preparing ? 'Checking sources…' : 'Prepare current package'}</button>}</div>{current && <PackageView value={current} />}</>}
    </>}
  </section>;
}

function PackageView({ value }: { value: DecisionPackageDto }) { const risk = value.riskAssessment, inspection = value.inspection, context = value.caseContext; const reasons = Array.isArray(risk.reasons) ? risk.reasons : [];
  return <article className="package-record"><header><div><p className="eyebrow">PREPARED FOR HUMAN REVIEW</p><h3>Decision Package v{value.packageVersion}</h3><p>{value.packageContractVersion} · {new Date(value.preparedAt).toLocaleString('en-IN')}</p></div><strong>{humanize(value.status)}</strong></header>
    <section><h4>Case context</h4><dl className="detail-grid compact"><Fact label="Case">{context.caseReference}</Fact><Fact label="Asset">{context.asset.name} · {context.asset.assetCode}</Fact><Fact label="Type">{humanize(context.asset.assetType)}</Fact><Fact label="Department">{context.asset.department.name}</Fact><Fact label="Jurisdiction">{context.asset.jurisdiction.name}</Fact><Fact label="Emergency">{context.emergencyFlag ? 'Yes' : 'No'}</Fact></dl></section>
    <section><h4>Inspection provenance</h4><dl className="detail-grid compact"><Fact label="Inspection reference">{inspection.id}</Fact><Fact label="Inspection date">{new Date(inspection.inspectionDate).toLocaleString('en-IN')}</Fact><Fact label="Structural condition">{humanize(inspection.structuralCondition)}</Fact><Fact label="Crack severity">{humanize(inspection.crackSeverity)}</Fact><Fact label="Corrosion">{humanize(inspection.corrosionLevel)}</Fact><Fact label="Weather risk">{humanize(inspection.weatherRisk)}</Fact></dl></section>
    <section><h4>Authoritative Risk Assessment</h4><dl className="detail-grid compact"><Fact label="Risk">{humanize(risk.riskLevel)}</Fact><Fact label="Priority">{humanize(risk.priorityLevel)}</Fact><Fact label="Risk score">{risk.riskScore}</Fact><Fact label="Assessment version">{risk.assessmentVersion}</Fact><Fact label="Assessment reference">{risk.id}</Fact></dl>{reasons.length > 0 && <ul>{reasons.map((item: any, index: number) => <li key={index}>{typeof item === 'string' ? item : item.message}</li>)}</ul>}</section>
    <section><h4>Policy constraints and governed actions</h4>{value.policyGovernance.state === 'NO_APPLICABLE_ACTIVE_POLICY_GOVERNANCE' && <p>{value.policyGovernance.message}</p>}<div className="package-action-groups">{groups.map((group) => <section className={`package-actions-${group.toLowerCase()}`} key={group}><h5>{group}</h5>{value.governedActions[group]?.length ? <ul>{value.governedActions[group].map((action) => <li key={action.actionId}><strong>{action.title}</strong><span>{action.description}</span><small>{action.actionCode} v{action.actionVersion} · {action.sourceReference}</small></li>)}</ul> : <p>None recorded.</p>}</section>)}</div></section>
    {value.policyGovernance.rules?.length > 0 && <section><h4>Source provenance</h4><ul>{value.policyGovernance.rules.map((item: any) => <li key={item.rule.id}>{item.policy.policyCode} v{item.policy.versionNumber} · {item.rule.code} · {item.action.actionCode} v{item.action.versionNumber}</li>)}</ul></section>}
    <p className="package-disclaimer">This Decision Package is prepared for human review. It is not a Human Decision, does not authorize execution, and does not replace the responsibility or judgment of the authorized officer.</p>
    <p className="record-meta">Prepared by {value.preparedBy.name} · {value.preparedBy.designation}</p></article>;
}
function Fact({ label, children }: { label: string; children: React.ReactNode }) { return <div className="detail"><dt>{label}</dt><dd>{children}</dd></div>; }
