import { useState, type FormEvent } from 'react';
import { recordInspection } from '../../api/workflow.api';
import { useAuth } from '../../auth/useAuth';
import { MutationFeedback } from './MutationFeedback';
const options={structuralCondition:['GOOD','FAIR','POOR','CRITICAL'],crackSeverity:['NONE','MINOR','MODERATE','SEVERE'],corrosionLevel:['NONE','LOW','MODERATE','HIGH'],trafficImportance:['LOW','MEDIUM','HIGH','CRITICAL'],weatherRisk:['LOW','MEDIUM','HIGH','SEVERE']};
export default function InspectionAction({ caseId, onRecorded }: { caseId:string; onRecorded():Promise<void>|void }) {
 const {token}=useAuth(); const [open,setOpen]=useState(false); const [submitting,setSubmitting]=useState(false); const [error,setError]=useState<unknown>(null); const [success,setSuccess]=useState<string|null>(null);
 async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();if(!token||submitting)return;const formElement=event.currentTarget;const form=new FormData(formElement);const usersText=String(form.get('estimatedDailyUsers')??'').trim();const users=usersText===''?undefined:Number(usersText);if(users!==undefined&&(!Number.isFinite(users)||users<0)){setError(new Error('invalid users'));return;}setSubmitting(true);setError(null);setSuccess(null);try{await recordInspection({caseId,inspectionDate:String(form.get('inspectionDate')),structuralCondition:String(form.get('structuralCondition')),crackSeverity:String(form.get('crackSeverity')),corrosionLevel:String(form.get('corrosionLevel')),trafficImportance:String(form.get('trafficImportance')),hospitalRoute:form.get('hospitalRoute')==='on',weatherRisk:String(form.get('weatherRisk')),heavyRainExpected:form.get('heavyRainExpected')==='on',estimatedDailyUsers:users,inspectionNotes:String(form.get('inspectionNotes')??'').trim()||undefined},token);setSuccess('Inspection record saved. Authoritative workflow data has been refreshed.');formElement.reset();setOpen(false);await onRecorded();}catch(reason){setError(reason);}finally{setSubmitting(false);}}
 return <div className="action-panel"><button className="primary-action" onClick={()=>setOpen((value)=>!value)}>{open?'Cancel inspection entry':'Record inspection'}</button><MutationFeedback error={error} success={success}/>{open&&<form className="workflow-form" onSubmit={submit} aria-busy={submitting}><h3>Record inspection findings</h3><p>This records persisted observations; it does not perform a physical inspection.</p><label>Inspection date and time<input name="inspectionDate" type="datetime-local" required/></label><Select name="structuralCondition" label="Structural condition" values={options.structuralCondition}/><Select name="crackSeverity" label="Crack severity" values={options.crackSeverity}/><Select name="corrosionLevel" label="Corrosion level" values={options.corrosionLevel}/><Select name="trafficImportance" label="Traffic importance" values={options.trafficImportance}/><Select name="weatherRisk" label="Weather risk" values={options.weatherRisk}/><label className="check-label"><input name="hospitalRoute" type="checkbox"/> Hospital route</label><label className="check-label"><input name="heavyRainExpected" type="checkbox"/> Heavy rain expected</label><label>Estimated daily users<input name="estimatedDailyUsers" type="number" min="0" step="1"/></label><label>Inspection notes<textarea name="inspectionNotes" rows={3}/></label><button className="primary-button" disabled={submitting}>{submitting?'Recording…':'Record inspection'}</button></form>}</div>;
}
function Select({name,label,values}:{name:string;label:string;values:string[]}){return <label>{label}<select name={name} required defaultValue=""><option value="" disabled>Select</option>{values.map((value)=><option key={value}>{value.replaceAll('_',' ')}</option>)}</select></label>;}
