import { Prisma, SystemRole } from '../../generated/prisma';
import prisma from '../../lib/prisma';
import type { OrganizationalPrincipal } from '../../security/organizational-scope';
import { sha256Fingerprint } from '../trusted-computation/trusted-computation.provider';

export const INTEGRITY_CHAIN_VERSION='ODYSSEY_INTEGRITY_CHAIN_V1';
export const INTEGRITY_PAYLOAD_VERSION='ODYSSEY_INTEGRITY_EVENT_PAYLOAD_V1';
export const INTEGRITY_BATCH_SIZE=200;
export type ProtectedEventType='RISK_ASSESSMENT_RECORDED'|'EXECUTION_EVIDENCE_RECORDED';
export interface IntegrityPayload {eventType:ProtectedEventType;sourceEventKey:string;resourceType:string;resourceId:string;actorUserId:string|null;actorRole:string|null;departmentId:string|null;jurisdictionId:string|null;occurredAt:string;facts:Record<string,unknown>}
export interface AppendIntegrityInput {eventType:ProtectedEventType;sourceEventKey:string;resourceType:string;resourceId:string;actor:Pick<OrganizationalPrincipal,'id'|'role'>|null;departmentId:string|null;jurisdictionId:string|null;occurredAt:Date;facts:Record<string,unknown>}

export const chainKeyForScope=(departmentId:string|null,jurisdictionId:string|null)=>departmentId&&jurisdictionId?`scope:${departmentId}:${jurisdictionId}`:'system:global';
export function canonicalIntegrityPayload(input:AppendIntegrityInput):IntegrityPayload{return{eventType:input.eventType,sourceEventKey:input.sourceEventKey,resourceType:input.resourceType,resourceId:input.resourceId,actorUserId:input.actor?.id??null,actorRole:input.actor?.role??null,departmentId:input.departmentId,jurisdictionId:input.jurisdictionId,occurredAt:input.occurredAt.toISOString(),facts:input.facts};}
export const integrityPayloadHash=(payload:IntegrityPayload)=>sha256Fingerprint(payload);
export function integrityEventHash(input:{chainKey:string;sequenceNumber:number;previousEventHash:string|null;payloadHash:string}){return sha256Fingerprint({chainVersion:INTEGRITY_CHAIN_VERSION,chainKey:input.chainKey,sequenceNumber:input.sequenceNumber,previousEventHash:input.previousEventHash,payloadHash:input.payloadHash,payloadContractVersion:INTEGRITY_PAYLOAD_VERSION});}

export async function appendIntegrityEvent(tx:Prisma.TransactionClient,input:AppendIntegrityInput){
 const chainKey=chainKeyForScope(input.departmentId,input.jurisdictionId);
 await tx.$executeRawUnsafe('SELECT pg_advisory_xact_lock(hashtext($1))',chainKey);
 const existing=await tx.integrityAuditEvent.findUnique({where:{sourceEventKey:input.sourceEventKey}});if(existing)return existing;
 const head=await tx.integrityChainHead.upsert({where:{chainKey},update:{},create:{chainKey,chainVersion:INTEGRITY_CHAIN_VERSION,departmentId:input.departmentId,jurisdictionId:input.jurisdictionId}});
 if(head.chainVersion!==INTEGRITY_CHAIN_VERSION)throw new Error('UNSUPPORTED_INTEGRITY_CHAIN_VERSION');
 const sequenceNumber=head.latestSequence+1,payload=canonicalIntegrityPayload(input),payloadHash=integrityPayloadHash(payload),eventHash=integrityEventHash({chainKey,sequenceNumber,previousEventHash:head.latestEventHash,payloadHash});
 const event=await tx.integrityAuditEvent.create({data:{chainKey,chainVersion:INTEGRITY_CHAIN_VERSION,sequenceNumber,previousEventId:head.latestEventId,previousEventHash:head.latestEventHash,eventHash,payloadHash,payloadContractVersion:INTEGRITY_PAYLOAD_VERSION,payload:payload as unknown as Prisma.InputJsonValue,eventType:input.eventType,actorUserId:input.actor?.id,actorRoleSnapshot:input.actor?.role,departmentId:input.departmentId,jurisdictionId:input.jurisdictionId,resourceType:input.resourceType,resourceId:input.resourceId,sourceEventKey:input.sourceEventKey,occurredAt:input.occurredAt}});
 await tx.integrityChainHead.update({where:{chainKey},data:{latestSequence:sequenceNumber,latestEventId:event.id,latestEventHash:eventHash}});return event;
}

export class IntegrityNotFoundError extends Error{}
function visibleChainWhere(principal:OrganizationalPrincipal){return principal.role===SystemRole.SYSTEM_ADMIN?{}:{departmentId:principal.departmentId,jurisdictionId:principal.jurisdictionId};}
export async function listIntegrityChains(principal:OrganizationalPrincipal){return prisma.integrityChainHead.findMany({where:visibleChainWhere(principal),select:{chainKey:true,chainVersion:true,departmentId:true,jurisdictionId:true,latestSequence:true,latestEventId:true,latestEventHash:true,createdAt:true,updatedAt:true},orderBy:{chainKey:'asc'},take:101});}
async function assertChain(chainKey:string,principal:OrganizationalPrincipal){const chain=await prisma.integrityChainHead.findFirst({where:{chainKey,...visibleChainWhere(principal)}});if(!chain)throw new IntegrityNotFoundError();return chain;}
export async function listIntegrityEvents(chainKey:string,principal:OrganizationalPrincipal,limit:number,beforeSequence?:number){await assertChain(chainKey,principal);const rows=await prisma.integrityAuditEvent.findMany({where:{chainKey,...(beforeSequence?{sequenceNumber:{lt:beforeSequence}}:{})},select:{id:true,chainKey:true,chainVersion:true,sequenceNumber:true,previousEventId:true,previousEventHash:true,eventHash:true,payloadHash:true,payloadContractVersion:true,eventType:true,actorUserId:true,actorRoleSnapshot:true,departmentId:true,jurisdictionId:true,resourceType:true,resourceId:true,occurredAt:true,recordedAt:true},orderBy:{sequenceNumber:'desc'},take:limit+1});return{items:rows.slice(0,limit),nextBeforeSequence:rows.length>limit?rows[limit-1].sequenceNumber:null,limit,truncated:rows.length>limit};}

async function sourceMaps(rows:any[]){const riskIds=rows.filter(x=>x.eventType==='RISK_ASSESSMENT_RECORDED').map(x=>x.resourceId),evidenceIds=rows.filter(x=>x.eventType==='EXECUTION_EVIDENCE_RECORDED').map(x=>x.resourceId);const[risks,evidence]=await Promise.all([prisma.riskAssessment.findMany({where:{id:{in:riskIds}},include:{trustedComputationReceipt:true,case:{include:{asset:true}}}}),prisma.executionEvidence.findMany({where:{id:{in:evidenceIds}},include:{executionTask:{include:{executionPlan:{include:{case:{include:{asset:true}}}}}}}})]);return{risks:new Map(risks.map(x=>[x.id,x])),evidence:new Map(evidence.map(x=>[x.id,x]))};}
function reconcileSource(event:any,maps:Awaited<ReturnType<typeof sourceMaps>>){const p=event.payload as IntegrityPayload;if(event.eventType==='RISK_ASSESSMENT_RECORDED'){const assessment=maps.risks.get(event.resourceId);if(!assessment||!assessment.trustedComputationReceipt)return'SOURCE_MISMATCH';const rebuilt=canonicalIntegrityPayload({eventType:'RISK_ASSESSMENT_RECORDED',sourceEventKey:event.sourceEventKey,resourceType:event.resourceType,resourceId:event.resourceId,actor:p.actorUserId&&p.actorRole?{id:p.actorUserId,role:p.actorRole as any}:null,departmentId:assessment.case.asset.departmentId,jurisdictionId:assessment.case.asset.jurisdictionId,occurredAt:event.occurredAt,facts:riskIntegrityFacts(assessment,assessment.trustedComputationReceipt)});return integrityPayloadHash(rebuilt)===event.payloadHash?'MATCH':'SOURCE_MISMATCH';}if(event.eventType==='EXECUTION_EVIDENCE_RECORDED'){const evidence=maps.evidence.get(event.resourceId);if(!evidence)return'SOURCE_MISMATCH';const rebuilt=canonicalIntegrityPayload({eventType:'EXECUTION_EVIDENCE_RECORDED',sourceEventKey:event.sourceEventKey,resourceType:event.resourceType,resourceId:event.resourceId,actor:p.actorUserId&&p.actorRole?{id:p.actorUserId,role:p.actorRole as any}:null,departmentId:evidence.executionTask.executionPlan.case.asset.departmentId,jurisdictionId:evidence.executionTask.executionPlan.case.asset.jurisdictionId,occurredAt:event.occurredAt,facts:evidenceIntegrityFacts(evidence)});return integrityPayloadHash(rebuilt)===event.payloadHash?'MATCH':'SOURCE_MISMATCH';}return'NOT_SUPPORTED';}
export async function verifyIntegrityChain(chainKey:string,principal:OrganizationalPrincipal){const head=await assertChain(chainKey,principal);let after=0,expectedPreviousHash:null|string=null,expectedPreviousId:null|string=null,checked=0,sourceStatus='MATCH';while(true){const rows=await prisma.integrityAuditEvent.findMany({where:{chainKey,sequenceNumber:{gt:after}},orderBy:{sequenceNumber:'asc'},take:INTEGRITY_BATCH_SIZE});if(!rows.length)break;const maps=await sourceMaps(rows);for(const event of rows){const failure=(event.chainVersion!==INTEGRITY_CHAIN_VERSION||event.payloadContractVersion!==INTEGRITY_PAYLOAD_VERSION)?'UNSUPPORTED_VERSION':event.sequenceNumber!==checked+1?'CHAIN_GAP':event.previousEventHash!==expectedPreviousHash||event.previousEventId!==expectedPreviousId?'CHAIN_BROKEN':integrityPayloadHash(event.payload as unknown as IntegrityPayload)!==event.payloadHash?'PAYLOAD_MISMATCH':integrityEventHash({chainKey,sequenceNumber:event.sequenceNumber,previousEventHash:event.previousEventHash,payloadHash:event.payloadHash})!==event.eventHash?'EVENT_HASH_MISMATCH':null;if(failure)return{status:failure,chainKey,eventsChecked:checked,firstFailureSequence:event.sequenceNumber,complete:true,genesisSequence:1};const source=reconcileSource(event,maps);if(source==='SOURCE_MISMATCH')sourceStatus='SOURCE_MISMATCH';expectedPreviousHash=event.eventHash;expectedPreviousId=event.id;checked++;after=event.sequenceNumber;}if(rows.length<INTEGRITY_BATCH_SIZE)break;}if(checked!==head.latestSequence||expectedPreviousHash!==head.latestEventHash||expectedPreviousId!==head.latestEventId)return{status:'CHAIN_HEAD_MISMATCH',chainKey,eventsChecked:checked,complete:true,genesisSequence:checked?1:null};return{status:sourceStatus==='SOURCE_MISMATCH'?'SOURCE_MISMATCH':'VALID',chainKey,eventsChecked:checked,firstSequence:checked?1:null,lastSequence:checked||null,genesisSequence:checked?1:null,legacyBoundary:'Integrity coverage begins at the first P3.4 event.',complete:true,sourceReconciliation:sourceStatus};}
export async function verifyIntegrityEvent(id:string,principal:OrganizationalPrincipal){const event=await prisma.integrityAuditEvent.findFirst({where:{id,...visibleChainWhere(principal)}});if(!event)throw new IntegrityNotFoundError();const chain=await verifyIntegrityChain(event.chainKey,principal);return{eventId:id,eventSequence:event.sequenceNumber,chainVerification:chain};}
export function riskIntegrityFacts(assessment:any,receipt:any){return{assessmentVersion:assessment.assessmentVersion,inspectionId:assessment.inspectionId,riskScore:assessment.riskScore,riskLevel:assessment.riskLevel,priorityLevel:assessment.priorityLevel,reasonCodes:assessment.reasonCodes,sourceFingerprint:assessment.sourceFingerprint,receiptVersion:receipt.receiptVersion,inputFingerprint:receipt.inputFingerprint,resultFingerprint:receipt.resultFingerprint,providerId:receipt.providerId,runtimeTrustLevel:receipt.runtimeTrustLevel,attestationState:receipt.attestationState};}
export function evidenceIntegrityFacts(evidence:any){return{digestType:'RECORD_DIGEST',evidenceType:evidence.evidenceType,executionTaskId:evidence.executionTaskId,submittedById:evidence.submittedById,descriptionDigest:sha256Fingerprint(evidence.description),referenceDigest:evidence.referenceUrl?sha256Fingerprint(evidence.referenceUrl):null,documentReferenceDigest:evidence.documentReference?sha256Fingerprint(evidence.documentReference):null,measurementDigest:evidence.measurementData?sha256Fingerprint(evidence.measurementData):null,capturedAt:evidence.capturedAt?.toISOString?.()??null,contentDigest:null,contentVerified:false};}
