import {Router}from'express';import{z}from'zod';import{SystemRole}from'../../generated/prisma';import{authenticate}from'../../middleware/authenticate';import{requireRole}from'../../middleware/require-role';import{getIntegrityCoverageSummary,IntegrityNotFoundError,listIntegrityChains,listIntegrityEvents,verifyIntegrityChain,verifyIntegrityEvent}from'./integrity.service';
const router=Router(),roles=requireRole(SystemRole.AUDITOR,SystemRole.SYSTEM_ADMIN);const chain=z.string().min(1).max(300),uuid=z.string().uuid();function fail(res:any,e:unknown){if(e instanceof IntegrityNotFoundError)return res.status(404).json({success:false,error:{code:'INTEGRITY_RESOURCE_NOT_FOUND',message:'Integrity resource not found.'}});console.error('Integrity verification failed.');return res.status(500).json({success:false,error:{code:'INTEGRITY_VERIFICATION_FAILED',message:'Integrity verification could not be completed.'}})}
router.use('/integrity',authenticate,roles);
router.get('/integrity/chains',async(req,res)=>{try{return res.json({success:true,data:await listIntegrityChains(req.user!)})}catch(e){return fail(res,e)}});
router.get('/integrity/summary',async(req,res)=>{try{return res.json({success:true,data:await getIntegrityCoverageSummary(req.user!)})}catch(e){return fail(res,e)}});
router.get('/integrity/chains/:chainKey/events',async(req,res)=>{const key=chain.safeParse(req.params.chainKey),limit=z.coerce.number().int().min(1).max(100).safeParse(req.query.limit??25),before=z.coerce.number().int().positive().optional().safeParse(req.query.beforeSequence);if(!key.success||!limit.success||!before.success)return res.status(400).json({success:false,error:{code:'INVALID_INPUT',message:'Valid chain and pagination values are required.'}});try{return res.json({success:true,data:await listIntegrityEvents(key.data,req.user!,limit.data,before.data)})}catch(e){return fail(res,e)}});
router.post('/integrity/chains/:chainKey/verify',async(req,res)=>{const key=chain.safeParse(req.params.chainKey);if(!key.success||(req.body&&Object.keys(req.body).length))return res.status(400).json({success:false,error:{code:'INVALID_INPUT',message:'A valid chain and empty body are required.'}});try{return res.json({success:true,data:await verifyIntegrityChain(key.data,req.user!)})}catch(e){return fail(res,e)}});
router.post('/integrity/events/:eventId/verify',async(req,res)=>{const id=uuid.safeParse(req.params.eventId);if(!id.success||(req.body&&Object.keys(req.body).length))return res.status(400).json({success:false,error:{code:'INVALID_INPUT',message:'A valid event ID and empty body are required.'}});try{return res.json({success:true,data:await verifyIntegrityEvent(id.data,req.user!)})}catch(e){return fail(res,e)}});
export default router;
