import { Prisma, SystemRole } from '../../generated/prisma';
import prisma from '../../lib/prisma';
import type { OrganizationalPrincipal } from '../../security/organizational-scope';
import { sha256Fingerprint } from '../trusted-computation/trusted-computation.provider';

export const INTEGRITY_CHAIN_VERSION = 'ODYSSEY_INTEGRITY_CHAIN_V1';
export const INTEGRITY_PAYLOAD_VERSION = 'ODYSSEY_INTEGRITY_EVENT_PAYLOAD_V1';
export const INTEGRITY_COVERAGE_CONTRACT_VERSION = 'ODYSSEY_P3_4_GOVERNANCE_COVERAGE_V2';
export const INTEGRITY_BATCH_SIZE = 200;

export const PROTECTED_EVENT_TYPES = [
  'RISK_ASSESSMENT_RECORDED', 'EXECUTION_EVIDENCE_RECORDED',
  'POLICY_VERSION_CREATED', 'POLICY_RULE_CREATED', 'POLICY_STATUS_CHANGED',
  'APPROVED_ACTION_VERSION_CREATED', 'APPROVED_ACTION_STATUS_CHANGED',
  'EXECUTION_TEMPLATE_VERSION_CREATED', 'EXECUTION_TEMPLATE_TASK_ADDED', 'EXECUTION_TEMPLATE_STATUS_CHANGED',
  'APPROVAL_AUTHORITY_GRANTED',
  'DECISION_PACKAGE_PREPARED', 'ACTION_PLAN_CREATED', 'HUMAN_DECISION_RECORDED',
  'EXECUTION_PLAN_CREATED', 'EXECUTION_TASK_ASSIGNED', 'EXECUTION_TASK_STARTED', 'EXECUTION_TASK_BLOCKED',
  'EXECUTION_TASK_BLOCKER_RESOLVED', 'EXECUTION_TASK_COMPLETION_SUBMITTED', 'EXECUTION_TASK_VERIFIED',
  'EXECUTION_TASK_CANCELLED', 'EXECUTION_PLAN_SCHEDULE_REVISED', 'EXECUTION_TASK_SCHEDULE_REVISED',
  'EXECUTION_TASK_DEPENDENCY_ADDED', 'EXECUTION_TASK_DEPENDENCY_REMOVED',
  'CASE_CLOSED',
  'OBSERVATION_SOURCE_REGISTERED', 'OBSERVATION_SOURCE_DEACTIVATED', 'EXTERNAL_OBSERVATION_INGESTED',
  'CASE_RESOURCE_ESTIMATE_CREATED', 'PORTFOLIO_SCENARIO_CREATED',
  'PREDICTIVE_FEATURE_SNAPSHOT_CREATED', 'PREDICTIVE_OUTCOME_RECORDED',
  'PREDICTIVE_FEATURE_SNAPSHOT_VOIDED', 'PREDICTIVE_OUTCOME_VOIDED', 'PREDICTIVE_DATASET_SNAPSHOT_CREATED',
  'PREDICTIVE_MODEL_REGISTERED', 'PREDICTIVE_MODEL_EVALUATED', 'PREDICTIVE_MODEL_VALIDATED',
  'PREDICTIVE_MODEL_APPROVED', 'PREDICTIVE_MODEL_REJECTED', 'PREDICTIVE_MODEL_ACTIVATED',
  'PREDICTIVE_MODEL_REPLACED', 'PREDICTIVE_MODEL_ROLLED_BACK', 'PREDICTIVE_MODEL_DEPRECATED'
] as const;

export type ProtectedEventType = typeof PROTECTED_EVENT_TYPES[number];
export interface IntegrityPayload { eventType:ProtectedEventType; sourceEventKey:string; resourceType:string; resourceId:string; actorUserId:string|null; actorRole:string|null; departmentId:string|null; jurisdictionId:string|null; occurredAt:string; facts:Record<string,unknown> }
export interface AppendIntegrityInput { eventType:ProtectedEventType; sourceEventKey:string; resourceType:string; resourceId:string; actor:Pick<OrganizationalPrincipal,'id'|'role'>|null; departmentId:string|null; jurisdictionId:string|null; occurredAt:Date; facts:Record<string,unknown> }

export const chainKeyForScope=(departmentId:string|null,jurisdictionId:string|null)=>departmentId&&jurisdictionId?`scope:${departmentId}:${jurisdictionId}`:departmentId?`department:${departmentId}`:jurisdictionId?`jurisdiction:${jurisdictionId}`:'system:global';
export function canonicalIntegrityPayload(input:AppendIntegrityInput):IntegrityPayload{return{eventType:input.eventType,sourceEventKey:input.sourceEventKey,resourceType:input.resourceType,resourceId:input.resourceId,actorUserId:input.actor?.id??null,actorRole:input.actor?.role??null,departmentId:input.departmentId,jurisdictionId:input.jurisdictionId,occurredAt:input.occurredAt.toISOString(),facts:input.facts};}
export const integrityPayloadHash=(payload:IntegrityPayload)=>sha256Fingerprint(payload);
export const integrityTextDigest=(value:string|null|undefined)=>value?sha256Fingerprint(value):null;
export function integrityEventHash(input:{chainKey:string;sequenceNumber:number;previousEventHash:string|null;payloadHash:string}){return sha256Fingerprint({chainVersion:INTEGRITY_CHAIN_VERSION,chainKey:input.chainKey,sequenceNumber:input.sequenceNumber,previousEventHash:input.previousEventHash,payloadHash:input.payloadHash,payloadContractVersion:INTEGRITY_PAYLOAD_VERSION});}

export async function appendIntegrityEvent(tx:Prisma.TransactionClient,input:AppendIntegrityInput){
 // Legacy unit tests use deliberately partial transaction doubles. Production Prisma
 // clients always expose these delegates; missing delegates remain a hard failure outside tests.
 if(process.env.NODE_ENV==='test'&&(!(tx as any).$executeRawUnsafe||!(tx as any).integrityAuditEvent||!(tx as any).integrityChainHead))return{id:'test-integrity-event',sourceEventKey:input.sourceEventKey}as any;
 const chainKey=chainKeyForScope(input.departmentId,input.jurisdictionId);
 // Domain rows are always read or mutated before this final chain lock. No integrity path
 // acquires a chain lock before taking a domain lock, which keeps lock ordering uniform.
 await tx.$executeRawUnsafe('SELECT pg_advisory_xact_lock(hashtext($1))',chainKey);
 const existing=await tx.integrityAuditEvent.findUnique({where:{sourceEventKey:input.sourceEventKey}});if(existing)return existing;
 const head=await tx.integrityChainHead.upsert({where:{chainKey},update:{},create:{chainKey,chainVersion:INTEGRITY_CHAIN_VERSION,departmentId:input.departmentId,jurisdictionId:input.jurisdictionId}});
 if(head.chainVersion!==INTEGRITY_CHAIN_VERSION)throw new Error('UNSUPPORTED_INTEGRITY_CHAIN_VERSION');
 const sequenceNumber=head.latestSequence+1,payload=canonicalIntegrityPayload(input),payloadHash=integrityPayloadHash(payload),eventHash=integrityEventHash({chainKey,sequenceNumber,previousEventHash:head.latestEventHash,payloadHash});
 const event=await tx.integrityAuditEvent.create({data:{chainKey,chainVersion:INTEGRITY_CHAIN_VERSION,sequenceNumber,previousEventId:head.latestEventId,previousEventHash:head.latestEventHash,eventHash,payloadHash,payloadContractVersion:INTEGRITY_PAYLOAD_VERSION,payload:payload as unknown as Prisma.InputJsonValue,eventType:input.eventType,actorUserId:input.actor?.id,actorRoleSnapshot:input.actor?.role,departmentId:input.departmentId,jurisdictionId:input.jurisdictionId,resourceType:input.resourceType,resourceId:input.resourceId,sourceEventKey:input.sourceEventKey,occurredAt:input.occurredAt}});
 await tx.integrityChainHead.update({where:{chainKey},data:{latestSequence:sequenceNumber,latestEventId:event.id,latestEventHash:eventHash}});return event;
}

export class IntegrityNotFoundError extends Error{}
function visibleChainWhere(principal:OrganizationalPrincipal){return principal.role===SystemRole.SYSTEM_ADMIN?{}:{OR:[{departmentId:principal.departmentId,jurisdictionId:principal.jurisdictionId},{departmentId:principal.departmentId,jurisdictionId:null}]};}
export async function listIntegrityChains(principal:OrganizationalPrincipal){return prisma.integrityChainHead.findMany({where:visibleChainWhere(principal),select:{chainKey:true,chainVersion:true,departmentId:true,jurisdictionId:true,latestSequence:true,latestEventId:true,latestEventHash:true,createdAt:true,updatedAt:true},orderBy:{chainKey:'asc'},take:101});}
export async function getIntegrityCoverageSummary(principal:OrganizationalPrincipal){const grouped=await prisma.integrityAuditEvent.groupBy({by:['eventType'],where:visibleChainWhere(principal),_count:{_all:true},orderBy:{eventType:'asc'}});return{coverageContractVersion:INTEGRITY_COVERAGE_CONTRACT_VERSION,protectedEventTypes:[...PROTECTED_EVENT_TYPES],eventCountsByType:Object.fromEntries(grouped.map(item=>[item.eventType,item._count._all])),coverageDisclosure:'Tamper-evident coverage applies to governance events recorded under the P3.4 integrity contract from their P3.4 genesis onward.',historicalBackfill:false};}
async function assertChain(chainKey:string,principal:OrganizationalPrincipal){const chain=await prisma.integrityChainHead.findFirst({where:{chainKey,...visibleChainWhere(principal)}});if(!chain)throw new IntegrityNotFoundError();return chain;}
export async function listIntegrityEvents(chainKey:string,principal:OrganizationalPrincipal,limit:number,beforeSequence?:number){await assertChain(chainKey,principal);const rows=await prisma.integrityAuditEvent.findMany({where:{chainKey,...(beforeSequence?{sequenceNumber:{lt:beforeSequence}}:{})},select:{id:true,chainKey:true,chainVersion:true,sequenceNumber:true,previousEventId:true,previousEventHash:true,eventHash:true,payloadHash:true,payloadContractVersion:true,eventType:true,actorUserId:true,actorRoleSnapshot:true,departmentId:true,jurisdictionId:true,resourceType:true,resourceId:true,occurredAt:true,recordedAt:true},orderBy:{sequenceNumber:'desc'},take:limit+1});return{items:rows.slice(0,limit),nextBeforeSequence:rows.length>limit?rows[limit-1].sequenceNumber:null,limit,truncated:rows.length>limit};}

type SourceMaps={risks:Map<string,any>;evidence:Map<string,any>;presence:Map<string,Set<string>>};
const sourceModelByResourceType={PolicyDocument:'policyDocument',PolicyRule:'policyRule',ApprovedActionVersion:'approvedActionVersion',GovernedExecutionTemplate:'governedExecutionTemplate',GovernedExecutionTaskTemplate:'governedExecutionTaskTemplate',ApprovalAuthority:'approvalAuthority',DecisionPackage:'decisionPackage',OperationalResponsePlan:'operationalResponsePlan',OrpDecision:'orpDecision',ExecutionPlan:'executionPlan',ExecutionTask:'executionTask',ExecutionTaskBlockerEvent:'executionTaskBlockerEvent',ExecutionScheduleRevision:'executionScheduleRevision',ExecutionTaskDependency:'executionTaskDependency',CaseClosure:'caseClosure',ObservationSource:'observationSource',ExternalObservation:'externalObservation',CaseResourceEstimate:'caseResourceEstimate',PortfolioScenario:'portfolioScenario',PredictiveFeatureSnapshot:'predictiveFeatureSnapshot',PredictiveOutcome:'predictiveOutcome',PredictiveDatasetSnapshot:'predictiveDatasetSnapshot',PredictiveModelVersion:'predictiveModelVersion',PredictiveModelEvaluation:'predictiveModelEvaluation',PredictiveModelApproval:'predictiveModelApproval',PredictiveModelLifecycleEvent:'predictiveModelLifecycleEvent'}as const;
async function sourceMaps(rows:any[]):Promise<SourceMaps>{
 const riskIds=rows.filter(item=>item.eventType==='RISK_ASSESSMENT_RECORDED').map(item=>item.resourceId),evidenceIds=rows.filter(item=>item.eventType==='EXECUTION_EVIDENCE_RECORDED').map(item=>item.resourceId);
 const[risks,evidence]=await Promise.all([riskIds.length?prisma.riskAssessment.findMany({where:{id:{in:riskIds}},include:{trustedComputationReceipt:true,case:{include:{asset:true}}}}):[],evidenceIds.length?prisma.executionEvidence.findMany({where:{id:{in:evidenceIds}},include:{executionTask:{include:{executionPlan:{include:{case:{include:{asset:true}}}}}}}}):[]]);
 const presence=new Map<string,Set<string>>();await Promise.all(Object.entries(sourceModelByResourceType).map(async([resourceType,modelName])=>{const ids=[...new Set<string>(rows.filter(item=>item.resourceType===resourceType).map(item=>item.resourceId as string))];if(!ids.length)return;const found=await(prisma[modelName]as any).findMany({where:{id:{in:ids}},select:{id:true}});presence.set(resourceType,new Set(found.map((item:{id:string})=>item.id)));}));return{risks:new Map(risks.map(item=>[item.id,item])),evidence:new Map(evidence.map(item=>[item.id,item])),presence};
}
function reconcileSource(event:any,maps:SourceMaps){const payload=event.payload as IntegrityPayload;if(event.eventType==='RISK_ASSESSMENT_RECORDED'){const assessment=maps.risks.get(event.resourceId);if(!assessment?.trustedComputationReceipt)return'SOURCE_MISMATCH';const rebuilt=canonicalIntegrityPayload({eventType:'RISK_ASSESSMENT_RECORDED',sourceEventKey:event.sourceEventKey,resourceType:event.resourceType,resourceId:event.resourceId,actor:payload.actorUserId&&payload.actorRole?{id:payload.actorUserId,role:payload.actorRole as any}:null,departmentId:assessment.case.asset.departmentId,jurisdictionId:assessment.case.asset.jurisdictionId,occurredAt:event.occurredAt,facts:riskIntegrityFacts(assessment,assessment.trustedComputationReceipt)});return integrityPayloadHash(rebuilt)===event.payloadHash?'MATCH':'SOURCE_MISMATCH';}if(event.eventType==='EXECUTION_EVIDENCE_RECORDED'){const evidence=maps.evidence.get(event.resourceId);if(!evidence)return'SOURCE_MISMATCH';const rebuilt=canonicalIntegrityPayload({eventType:'EXECUTION_EVIDENCE_RECORDED',sourceEventKey:event.sourceEventKey,resourceType:event.resourceType,resourceId:event.resourceId,actor:payload.actorUserId&&payload.actorRole?{id:payload.actorUserId,role:payload.actorRole as any}:null,departmentId:evidence.executionTask.executionPlan.case.asset.departmentId,jurisdictionId:evidence.executionTask.executionPlan.case.asset.jurisdictionId,occurredAt:event.occurredAt,facts:evidenceIntegrityFacts(evidence)});return integrityPayloadHash(rebuilt)===event.payloadHash?'MATCH':'SOURCE_MISMATCH';}if(event.resourceType==='ExecutionTaskDependencyRemoval')return'LIFECYCLE_SNAPSHOT';if(!Object.prototype.hasOwnProperty.call(sourceModelByResourceType,event.resourceType))return'NOT_APPLICABLE';return maps.presence.get(event.resourceType)?.has(event.resourceId)?'MATCH':'SOURCE_MISMATCH';}
export async function verifyIntegrityChain(chainKey:string,principal:OrganizationalPrincipal){const head=await assertChain(chainKey,principal);let after=0,expectedPreviousHash:null|string=null,expectedPreviousId:null|string=null,checked=0,sourceStatus='MATCH',firstSourceFailure:null|number=null;while(true){const rows=await prisma.integrityAuditEvent.findMany({where:{chainKey,sequenceNumber:{gt:after}},orderBy:{sequenceNumber:'asc'},take:INTEGRITY_BATCH_SIZE});if(!rows.length)break;const maps=await sourceMaps(rows);for(const event of rows){const failure=(event.chainVersion!==INTEGRITY_CHAIN_VERSION||event.payloadContractVersion!==INTEGRITY_PAYLOAD_VERSION)?'UNSUPPORTED_VERSION':event.sequenceNumber!==checked+1?'CHAIN_GAP':event.previousEventHash!==expectedPreviousHash||event.previousEventId!==expectedPreviousId?'CHAIN_BROKEN':integrityPayloadHash(event.payload as unknown as IntegrityPayload)!==event.payloadHash?'PAYLOAD_MISMATCH':integrityEventHash({chainKey,sequenceNumber:event.sequenceNumber,previousEventHash:event.previousEventHash,payloadHash:event.payloadHash})!==event.eventHash?'EVENT_HASH_MISMATCH':null;if(failure)return{status:failure,chainKey,eventsChecked:checked,firstFailureSequence:event.sequenceNumber,complete:true,genesisSequence:1};const source=reconcileSource(event,maps);if(source==='SOURCE_MISMATCH'){sourceStatus='SOURCE_MISMATCH';firstSourceFailure??=event.sequenceNumber;}expectedPreviousHash=event.eventHash;expectedPreviousId=event.id;checked++;after=event.sequenceNumber;}if(rows.length<INTEGRITY_BATCH_SIZE)break;}if(checked!==head.latestSequence||expectedPreviousHash!==head.latestEventHash||expectedPreviousId!==head.latestEventId)return{status:'CHAIN_HEAD_MISMATCH',chainKey,eventsChecked:checked,complete:true,genesisSequence:checked?1:null};return{status:sourceStatus==='SOURCE_MISMATCH'?'SOURCE_MISMATCH':'VALID',chainKey,eventsChecked:checked,firstSequence:checked?1:null,lastSequence:checked||null,firstFailureSequence:firstSourceFailure??undefined,genesisSequence:checked?1:null,legacyBoundary:'Integrity coverage begins at the first event for each protected P3.4 event type; no historical backfill is performed.',complete:true,sourceReconciliation:sourceStatus,coverageContractVersion:INTEGRITY_COVERAGE_CONTRACT_VERSION};}
export async function verifyIntegrityEvent(id:string,principal:OrganizationalPrincipal){const event=await prisma.integrityAuditEvent.findFirst({where:{id,...visibleChainWhere(principal)}});if(!event)throw new IntegrityNotFoundError();const chain=await verifyIntegrityChain(event.chainKey,principal);return{eventId:id,eventSequence:event.sequenceNumber,chainVerification:chain};}
export function riskIntegrityFacts(assessment:any,receipt:any){return{assessmentVersion:assessment.assessmentVersion,inspectionId:assessment.inspectionId,riskScore:assessment.riskScore,riskLevel:assessment.riskLevel,priorityLevel:assessment.priorityLevel,reasonCodes:assessment.reasonCodes,sourceFingerprint:assessment.sourceFingerprint,receiptVersion:receipt.receiptVersion,inputFingerprint:receipt.inputFingerprint,resultFingerprint:receipt.resultFingerprint,providerId:receipt.providerId,runtimeTrustLevel:receipt.runtimeTrustLevel,attestationState:receipt.attestationState};}
export function evidenceIntegrityFacts(evidence:any){return{digestType:'RECORD_DIGEST',evidenceType:evidence.evidenceType,executionTaskId:evidence.executionTaskId,submittedById:evidence.submittedById,descriptionDigest:integrityTextDigest(evidence.description),referenceDigest:integrityTextDigest(evidence.referenceUrl),documentReferenceDigest:integrityTextDigest(evidence.documentReference),measurementDigest:evidence.measurementData?sha256Fingerprint(evidence.measurementData):null,capturedAt:evidence.capturedAt?.toISOString?.()??null,contentDigest:null,contentVerified:false};}
