import { useEffect, useState, type ReactNode } from 'react';
import type { CaseSummary } from '../api/cases.api';
import { getExecutionPlan, listDecisions, listExecutionPlans, listInspections, listOrps, listRiskAssessments, type DecisionDto, type ExecutionPlanDto, type InspectionDto, type OrpDto, type RiskAssessmentDto } from '../api/workflow.api';
import { useAuth } from '../auth/useAuth';
import { Empty, ErrorState, Loading } from '../components/AsyncState';
import StatusBadge, { humanize } from '../components/StatusBadge';
import { formatDate } from './CasesPage';

type Tab = 'overview' | 'inspection' | 'risk' | 'response' | 'execution';
const tabs: Array<{ id: Tab; label: string }> = [{ id: 'overview', label: 'Overview' }, { id: 'inspection', label: 'Inspection' }, { id: 'risk', label: 'Risk' }, { id: 'response', label: 'Response & Decision' }, { id: 'execution', label: 'Execution' }];

export default function CaseWorkspace({ caseItem, onBack }: { caseItem: CaseSummary; onBack(): void }) {
  const [tab, setTab] = useState<Tab>('overview');
  return <section aria-labelledby="workspace-heading">
    <button className="back-button" onClick={onBack}>← Back to Cases</button>
    <div className="case-workspace-header"><div><p className="eyebrow">CASE WORKSPACE</p><h1 id="workspace-heading">{caseItem.caseNumber}</h1><p className="workspace-title">{caseItem.title}</p></div><div className="header-badges"><StatusBadge value={caseItem.status} /><StatusBadge value={caseItem.priorityLevel} kind="priority" />{caseItem.emergencyFlag && <span className="emergency-marker">Emergency case</span>}</div></div>
    <p className="case-context"><strong>{caseItem.asset.name}</strong> · {caseItem.asset.assetCode} · {caseItem.asset.department.name} · {caseItem.asset.jurisdiction.name}</p>
    <nav className="workspace-tabs" aria-label="Case workspace sections">{tabs.map((item) => <button key={item.id} aria-current={tab === item.id ? 'page' : undefined} className={tab === item.id ? 'active' : ''} onClick={() => setTab(item.id)}>{item.label}</button>)}</nav>
    <div className="workspace-section">{tab === 'overview' && <Overview item={caseItem} />}{tab === 'inspection' && <InspectionHistory caseId={caseItem.id} />}{tab === 'risk' && <RiskHistory caseId={caseItem.id} />}{tab === 'response' && <ResponseHistory caseId={caseItem.id} />}{tab === 'execution' && <ExecutionHistory caseId={caseItem.id} />}</div>
  </section>;
}

function Overview({ item }: { item: CaseSummary }) { return <><h2>Case overview</h2><div className="detail-grid"><Detail label="Description">{item.description || 'No description recorded.'}</Detail><Detail label="Lifecycle status"><StatusBadge value={item.status} /></Detail><Detail label="Risk"><StatusBadge value={item.riskLevel} kind="risk" /></Detail><Detail label="Priority"><StatusBadge value={item.priorityLevel} kind="priority" /></Detail><Detail label="Emergency flag">{item.emergencyFlag ? 'Yes — emergency' : 'No'}</Detail><Detail label="Asset">{item.asset.name} ({item.asset.assetCode}) · {humanize(item.asset.assetType)}</Detail><Detail label="Department">{item.asset.department.name}</Detail><Detail label="Jurisdiction">{item.asset.jurisdiction.name}</Detail><Detail label="Created">{formatDate(item.createdAt)}</Detail><Detail label="Updated">{formatDate(item.updatedAt)}</Detail><Detail label="Closed">{formatDate(item.closedAt)}</Detail></div></>; }
function Detail({ label, children }: { label: string; children: ReactNode }) { return <div className="detail"><dt>{label}</dt><dd>{children}</dd></div>; }

function useSection<T>(loader: (token: string, signal: AbortSignal) => Promise<T>, dependency: string) {
  const { token } = useAuth(); const [data, setData] = useState<T | null>(null); const [error, setError] = useState<unknown>(null); const [loading, setLoading] = useState(true); const [reload, setReload] = useState(0);
  useEffect(() => { if (!token) return; const controller = new AbortController(); setLoading(true); setError(null); loader(token, controller.signal).then(setData).catch((reason) => { if (!controller.signal.aborted) setError(reason); }).finally(() => { if (!controller.signal.aborted) setLoading(false); }); return () => controller.abort(); }, [dependency, reload, token]);
  return { data, error, loading, retry: () => setReload((v) => v + 1) };
}
function Section<T>({ state, label, empty, children }: { state: ReturnType<typeof useSection<T>>; label: string; empty: string; children(data: T): ReactNode }) { if (state.loading) return <Loading label={label} />; if (state.error) return <ErrorState error={state.error} retry={state.retry} />; if (!state.data || (Array.isArray(state.data) && state.data.length === 0)) return <Empty>{empty}</Empty>; return <>{children(state.data)}</>; }

function InspectionHistory({ caseId }: { caseId: string }) { const state = useSection<InspectionDto[]>((token, signal) => listInspections(caseId, token, signal), caseId); return <><h2>Inspection history</h2><Section state={state} label="inspection history" empty="No persisted inspections are available for this case.">{(items) => <div className="history-list">{items.map((item) => <article className="history-card" key={item.id}><h3>{formatDate(item.inspectionDate)}</h3><div className="detail-grid compact"><Detail label="Structural condition">{humanize(item.structuralCondition)}</Detail><Detail label="Crack severity">{humanize(item.crackSeverity)}</Detail><Detail label="Corrosion">{humanize(item.corrosionLevel)}</Detail><Detail label="Traffic importance">{humanize(item.trafficImportance)}</Detail><Detail label="Hospital route">{item.hospitalRoute ? 'Yes' : 'No'}</Detail><Detail label="Weather risk">{humanize(item.weatherRisk)}</Detail><Detail label="Heavy rain expected">{item.heavyRainExpected ? 'Yes' : 'No'}</Detail><Detail label="Estimated daily users">{item.estimatedDailyUsers?.toLocaleString('en-IN') ?? 'Not recorded'}</Detail>{item.inspector && <Detail label="Inspector">{item.inspector.name} · {item.inspector.designation}</Detail>}</div></article>)}</div>}</Section></>; }

function JsonList({ value }: { value: unknown }) { const values = Array.isArray(value) ? value : []; return values.length ? <ul>{values.map((entry, i) => <li key={i}>{typeof entry === 'string' ? entry : JSON.stringify(entry)}</li>)}</ul> : <span>None recorded</span>; }
function RiskHistory({ caseId }: { caseId: string }) { const state = useSection<RiskAssessmentDto[]>((token, signal) => listRiskAssessments(caseId, token, signal), caseId); return <><h2>Risk-assessment history</h2><p className="section-note">Persisted deterministic assessments; values are displayed without recalculation.</p><Section state={state} label="risk history" empty="No persisted risk assessments are available for this case.">{(items) => <div className="history-list">{items.map((item) => <article className="history-card" key={item.id}><div className="card-heading"><h3>Score {item.riskScore}</h3><StatusBadge value={item.riskLevel} kind="risk" /><StatusBadge value={item.priorityLevel} kind="priority" /></div><Detail label="Reason codes"><JsonList value={item.reasonCodes} /></Detail><Detail label="Persisted reasons"><JsonList value={item.reasons} /></Detail><p className="record-meta">{item.assessmentVersion} · {formatDate(item.createdAt)}</p></article>)}</div>}</Section></>; }

function ResponseHistory({ caseId }: { caseId: string }) { const orps = useSection<OrpDto[]>((token, signal) => listOrps(caseId, token, signal), `${caseId}-orps`); const decisions = useSection<DecisionDto[]>((token, signal) => listDecisions(caseId, token, signal), `${caseId}-decisions`); return <><h2>Response and decision history</h2><h3 className="subheading">System-generated response recommendations</h3><Section state={orps} label="response recommendations" empty="No operational response recommendations are available.">{(items) => <div className="history-list">{items.map((item) => <article className="history-card" key={item.id}><div className="card-heading"><h3>ORP version {item.versionNumber}</h3><StatusBadge value={item.status} /></div><Detail label="Urgency">{humanize(item.urgency)}</Detail><Detail label="Recommended actions"><JsonList value={item.recommendedActionCodes} /></Detail><Detail label="Temporary measures"><JsonList value={item.temporaryMeasures} /></Detail><Detail label="Alternative actions"><JsonList value={item.alternativeActionCodes} /></Detail><Detail label="Persisted reasons"><JsonList value={item.reasons} /></Detail><p className="record-meta">{item.planVersion} · {formatDate(item.createdAt)}</p></article>)}</div>}</Section><h3 className="subheading">Human decisions</h3><Section state={decisions} label="human decisions" empty="No human decisions are recorded for this case.">{(items) => <div className="history-list">{items.map((item) => <article className="history-card" key={item.id}><h3>{humanize(item.decisionType)}</h3><Detail label="Reason">{item.reason || 'Not recorded'}</Detail><Detail label="Remarks">{item.remarks || 'Not recorded'}</Detail>{item.reviewer && <Detail label="Reviewer">{item.reviewer.name} · {item.reviewer.designation}</Detail>}<p className="record-meta">{formatDate(item.createdAt)}</p></article>)}</div>}</Section></>; }

function ExecutionHistory({ caseId }: { caseId: string }) { const state = useSection<ExecutionPlanDto[]>(async (token, signal) => { const plans = await listExecutionPlans(caseId, token, signal); return Promise.all(plans.map((plan) => getExecutionPlan(plan.id, token, signal))); }, caseId); return <><h2>Execution history</h2><Section state={state} label="execution history" empty="No execution plans are available for this case.">{(plans) => <div className="history-list">{plans.map((plan) => <article className="history-card" key={plan.id}><div className="card-heading"><h3>Execution plan</h3><StatusBadge value={plan.status} /></div><div className="detail-grid compact"><Detail label="Template">{plan.templateVersion}</Detail><Detail label="Created">{formatDate(plan.createdAt)}</Detail><Detail label="Started">{formatDate(plan.startedAt)}</Detail><Detail label="Completed">{formatDate(plan.completedAt)}</Detail></div>{!plan.tasks?.length ? <p>No tasks are recorded.</p> : <ol className="task-list">{plan.tasks.map((task) => <li key={task.id}><div className="card-heading"><strong>{task.titleSnapshot}</strong><StatusBadge value={task.status} /></div><p>{task.descriptionSnapshot}</p><p>{task.isMandatory ? 'Mandatory task' : 'Optional task'}</p>{task.assignedTo && <p>Assigned officer: {task.assignedTo.name} · {task.assignedTo.designation}</p>}{task.completionSubmittedBy && <p>Completion submitted by: {task.completionSubmittedBy.name} · {task.completionSubmittedBy.designation}</p>}{task.verifiedBy && <p>Verified by: {task.verifiedBy.name} · {task.verifiedBy.designation}</p>}<p>Evidence: {task.evidence?.length ?? 0}{task.evidence?.length ? ` (${[...new Set(task.evidence.map((item) => humanize(item.evidenceType)))].join(', ')})` : ''}</p></li>)}</ol>}</article>)}</div>}</Section></>; }
