import { fireEvent, render, screen, waitFor, within } from '@testing-library/react';
import { afterEach, describe, expect, it, vi } from 'vitest';
import CasesPage from './CasesPage';
import { AuthContext, type AuthContextValue } from '../auth/AuthProvider';
import type { CaseSummary } from '../api/cases.api';

const cases: CaseSummary[] = [
  { id:'c1',caseNumber:'CASE-BR101-001',title:'Bridge distress',description:'Structural review',status:'ORP_READY',riskLevel:'VERY_HIGH',priorityLevel:'CRITICAL',emergencyFlag:true,createdAt:'2026-01-02T00:00:00Z',updatedAt:'2026-01-03T00:00:00Z',closedAt:null,asset:{id:'a1',assetCode:'BR-101',name:'Pune River Bridge',assetType:'BRIDGE',departmentId:'d1',jurisdictionId:'j1',department:{id:'d1',name:'Public Works'},jurisdiction:{id:'j1',name:'Pune'}}},
  { id:'c2',caseNumber:'CASE-RD-002',title:'Road surface',description:null,status:'NEW',riskLevel:'LOW',priorityLevel:'LOW',emergencyFlag:false,createdAt:'2026-01-01T00:00:00Z',updatedAt:'2026-01-01T00:00:00Z',closedAt:null,asset:{id:'a2',assetCode:'RD-2',name:'Market Road',assetType:'ROAD',departmentId:'d2',jurisdictionId:'j2',department:{id:'d2',name:'Roads'},jurisdiction:{id:'j2',name:'Mumbai'}}}
];
const response = (data: unknown, status=200) => new Response(JSON.stringify(status === 200 ? { success:true,data } : data), { status });
function context(role: 'OFFICER'|'SYSTEM_ADMIN'='OFFICER'): AuthContextValue { return { user:{id:'u',employeeCode:'secret-code',name:'Officer',email:'private@test',designation:'Engineer',role,status:'ACTIVE',departmentId:'d1',jurisdictionId:'j1'}, token:'token',organization:null,isAuthenticated:true,authStatus:'authenticated',sessionMessage:null,login:vi.fn(),logout:vi.fn() }; }
function setup(role: 'OFFICER'|'SYSTEM_ADMIN'='OFFICER') { vi.stubGlobal('fetch', vi.fn().mockResolvedValue(response(cases))); return render(<AuthContext.Provider value={context(role)}><CasesPage /></AuthContext.Provider>); }
afterEach(() => vi.unstubAllGlobals());
describe('Cases page', () => {
  it('renders cases, searches, filters, clears, and sorts deterministically', async () => { setup(); await screen.findByText('CASE-BR101-001'); expect(screen.getByText('CASE-RD-002')).toBeInTheDocument(); fireEvent.change(screen.getByLabelText('Search cases'), {target:{value:'BR-101'}}); expect(screen.queryByText('CASE-RD-002')).not.toBeInTheDocument(); fireEvent.click(screen.getByRole('button',{name:'Clear filters'})); fireEvent.change(screen.getByLabelText('Status'), {target:{value:'NEW'}}); expect(screen.getByText('1 case shown')).toBeInTheDocument(); fireEvent.change(screen.getByLabelText('Status'), {target:{value:''}}); fireEvent.change(screen.getByLabelText('Priority'), {target:{value:'LOW'}}); expect(screen.getByText('CASE-RD-002')).toBeInTheDocument(); fireEvent.change(screen.getByLabelText('Emergency'), {target:{value:'true'}}); expect(screen.getByText(/no cases match/i)).toBeInTheDocument(); fireEvent.click(screen.getByRole('button',{name:'Clear filters'})); expect(within(screen.getByRole('table')).getAllByRole('row')[1]).toHaveTextContent('CASE-BR101-001'); });
  it('does not show organization display filters to a normal user', async () => { setup(); await screen.findByText('CASE-BR101-001'); expect(screen.queryByLabelText(/Department/)).not.toBeInTheDocument(); });
  it('labels system-admin organization controls as display-only filters', async () => { setup('SYSTEM_ADMIN'); await screen.findByText('CASE-BR101-001'); expect(screen.getByLabelText('Department (display only)')).toBeInTheDocument(); expect(screen.queryByText(/acting/i)).not.toBeInTheDocument(); });
  it('opens the selected workspace, shows overview, and returns', async () => { setup(); await screen.findByText('CASE-BR101-001'); fireEvent.click(screen.getByRole('button',{name:/CASE-BR101-001/})); expect(screen.getByRole('heading',{name:'CASE-BR101-001'})).toBeInTheDocument(); expect(screen.getByText('Structural review')).toBeInTheDocument(); fireEvent.click(screen.getByRole('button',{name:/Back to Cases/})); expect(screen.getByRole('heading',{name:'Cases'})).toBeInTheDocument(); });
  it('shows deliberate empty and neutral 404 states', async () => { const fetchMock=vi.fn().mockResolvedValueOnce(response(cases)).mockResolvedValueOnce(response({success:false,error:{code:'CASE_NOT_FOUND',message:'Case not found.'}},404)); vi.stubGlobal('fetch',fetchMock); render(<AuthContext.Provider value={context()}><CasesPage /></AuthContext.Provider>); await screen.findByText('CASE-BR101-001'); fireEvent.click(screen.getByRole('button',{name:/CASE-BR101-001/})); fireEvent.click(screen.getByRole('button',{name:'Inspection'})); expect(await screen.findByText('Case unavailable or no longer accessible.')).toBeInTheDocument(); expect(screen.queryByText('Case not found.')).not.toBeInTheDocument(); });
  it('renders safe inspection identity but not email or employee code', async () => { const fetchMock=vi.fn().mockResolvedValueOnce(response(cases)).mockResolvedValueOnce(response([{id:'i',inspectionDate:'2026-01-01',structuralCondition:'POOR',crackSeverity:'SEVERE',corrosionLevel:'MODERATE',trafficImportance:'HIGH',hospitalRoute:true,weatherRisk:'HIGH',heavyRainExpected:true,estimatedDailyUsers:42000,inspectionNotes:null,createdAt:'2026-01-01',inspector:{name:'Rahul Patil',designation:'Executive Engineer',email:'hidden@test',employeeCode:'PWD-1'}}])); vi.stubGlobal('fetch',fetchMock); render(<AuthContext.Provider value={context()}><CasesPage /></AuthContext.Provider>); await screen.findByText('CASE-BR101-001'); fireEvent.click(screen.getByRole('button',{name:/CASE-BR101-001/})); fireEvent.click(screen.getByRole('button',{name:'Inspection'})); expect(await screen.findByText(/Rahul Patil/)).toHaveTextContent('Executive Engineer'); expect(screen.queryByText(/hidden@test|PWD-1/)).not.toBeInTheDocument(); });
  it('separates persisted ORP recommendations from human decisions', async () => { vi.stubGlobal('fetch', vi.fn(async (url: string) => url.endsWith('/cases') ? response(cases) : url.endsWith('/orps') ? response([{id:'o1',versionNumber:1,status:'AWAITING_REVIEW',urgency:'IMMEDIATE',recommendedActionCodes:['ACT_TEMP_STABILIZATION'],temporaryMeasures:['Restrict access'],reasons:['Persisted reason'],alternativeActionCodes:[],planVersion:'ODYSSEY_ORP_V1',createdAt:'2026-01-02'}]) : response([{id:'d1',decisionType:'APPROVED',reason:'Reviewed evidence',remarks:null,createdAt:'2026-01-03',reviewer:{name:'Review Officer',designation:'Chief Engineer',email:'private@test',employeeCode:'SECRET'}}]))); render(<AuthContext.Provider value={context()}><CasesPage /></AuthContext.Provider>); await screen.findByText('CASE-BR101-001'); fireEvent.click(screen.getByRole('button',{name:/CASE-BR101-001/})); fireEvent.click(screen.getByRole('button',{name:'Response & Decision'})); expect(await screen.findByText('System-generated response recommendations')).toBeInTheDocument(); expect(await screen.findByText('Human decisions')).toBeInTheDocument(); expect(await screen.findByText(/Review Officer/)).toHaveTextContent('Chief Engineer'); expect(screen.queryByText(/private@test|SECRET|AI approved/i)).not.toBeInTheDocument(); });
  it('shows task evidence counts and types without sensitive evidence fields', async () => {
    vi.stubGlobal('fetch', vi.fn(async (url: string) => {
      if (url.endsWith('/cases')) return response(cases);
      if (url.endsWith('/execution-plans')) return response([{id:'p1',status:'IN_PROGRESS',templateVersion:'V1',createdAt:'2026-01-01',startedAt:'2026-01-02',completedAt:null}]);
      return response({id:'p1',status:'IN_PROGRESS',templateVersion:'V1',createdAt:'2026-01-01',startedAt:'2026-01-02',completedAt:null,tasks:[{id:'t1',sequenceNumber:1,titleSnapshot:'Stabilize bridge',descriptionSnapshot:'Install supports',isMandatory:true,status:'IN_PROGRESS',assignedTo:{name:'Field Officer',designation:'Engineer'},completionSubmittedBy:null,verifiedBy:null,evidence:[{evidenceType:'PHOTO_REFERENCE',referenceUrl:'https://secret.test/photo',documentReference:'SECRET-DOC',description:'sensitive'}]}]});
    }));
    render(<AuthContext.Provider value={context()}><CasesPage /></AuthContext.Provider>); await screen.findByText('CASE-BR101-001'); fireEvent.click(screen.getByRole('button',{name:/CASE-BR101-001/})); fireEvent.click(screen.getByRole('button',{name:'Execution'})); expect(await screen.findByText('Stabilize bridge')).toBeInTheDocument(); expect(screen.getByText(/Evidence: 1 \(Photo Reference\)/)).toBeInTheDocument(); expect(screen.queryByText(/secret\.test|SECRET-DOC|sensitive/)).not.toBeInTheDocument();
  });
});
