import { fireEvent, render, screen, waitFor, within } from '@testing-library/react';
import { afterEach, describe, expect, it, vi } from 'vitest';
import CasesPage from './CasesPage';
import { AuthContext, type AuthContextValue } from '../auth/AuthProvider';
import type { CaseSummary } from '../api/cases.api';
import type { SystemRole } from '../types/api';

const cases: CaseSummary[] = [
  { id:'c1',caseNumber:'CASE-BR101-001',title:'Bridge distress',description:'Structural review',status:'ORP_READY',riskLevel:'VERY_HIGH',priorityLevel:'CRITICAL',emergencyFlag:true,createdAt:'2026-01-02T00:00:00Z',updatedAt:'2026-01-03T00:00:00Z',closedAt:null,asset:{id:'a1',assetCode:'BR-101',name:'Pune River Bridge',assetType:'BRIDGE',departmentId:'d1',jurisdictionId:'j1',department:{id:'d1',name:'Public Works'},jurisdiction:{id:'j1',name:'Pune'}}},
  { id:'c2',caseNumber:'CASE-RD-002',title:'Road surface',description:null,status:'NEW',riskLevel:'LOW',priorityLevel:'LOW',emergencyFlag:false,createdAt:'2026-01-01T00:00:00Z',updatedAt:'2026-01-01T00:00:00Z',closedAt:null,asset:{id:'a2',assetCode:'RD-2',name:'Market Road',assetType:'ROAD',departmentId:'d2',jurisdictionId:'j2',department:{id:'d2',name:'Roads'},jurisdiction:{id:'j2',name:'Mumbai'}}}
];
const operationalCases: CaseSummary[] = [
  ...cases,
  {...cases[1],id:'c3',caseNumber:'CASE-EXEC-003',status:'EXECUTION'},
  {...cases[1],id:'c4',caseNumber:'CASE-CLOSED-004',status:'CLOSED'},
  {...cases[1],id:'c5',caseNumber:'CASE-UNASSESSED-005',riskLevel:null,priorityLevel:null},
];
const response = (data: unknown, status=200) => new Response(JSON.stringify(status === 200 ? { success:true,data } : data), { status });
function context(role: SystemRole='OFFICER'): AuthContextValue { return { user:{id:'u',employeeCode:'secret-code',name:'Officer',email:'private@test',designation:'Engineer',role,status:'ACTIVE',departmentId:'d1',jurisdictionId:'j1'}, token:'token',organization:null,isAuthenticated:true,authStatus:'authenticated',sessionMessage:null,login:vi.fn(),logout:vi.fn() }; }
function setup(role: SystemRole='OFFICER') { vi.stubGlobal('fetch', vi.fn().mockResolvedValue(response(cases))); return render(<AuthContext.Provider value={context(role)}><CasesPage /></AuthContext.Provider>); }
afterEach(() => vi.unstubAllGlobals());
describe('Cases page', () => {
  it('derives the operational summary and assessment labels from loaded cases', async () => { vi.stubGlobal('fetch',vi.fn().mockResolvedValue(response(operationalCases)));render(<AuthContext.Provider value={context()}><CasesPage /></AuthContext.Provider>);await screen.findByText('CASE-BR101-001');const summary=screen.getByLabelText('Operational case summary');expect(within(summary).getByText('Total cases').nextSibling).toHaveTextContent('5');expect(within(summary).getByText('Critical priority').nextSibling).toHaveTextContent('1');expect(within(summary).getByText('Emergency').nextSibling).toHaveTextContent('1');expect(within(summary).getByText('In execution').nextSibling).toHaveTextContent('1');expect(within(summary).getByText('Closed').nextSibling).toHaveTextContent('1');const unassessed=screen.getByRole('button',{name:/Open CASE-UNASSESSED-005/});expect(within(unassessed).getAllByText('Not assessed')).toHaveLength(2);expect(within(unassessed).queryByText('Not assigned')).not.toBeInTheDocument();});
  it('keeps status, risk, and priority semantics explicit on every record',async()=>{setup();await screen.findByText('CASE-BR101-001');const row=screen.getByRole('button',{name:/Open CASE-BR101-001/});expect(within(row).getByText('Status')).toBeInTheDocument();expect(within(row).getByText('Risk')).toBeInTheDocument();expect(within(row).getByText('Priority')).toBeInTheDocument();expect(within(row).getByText('Emergency')).toBeInTheDocument();});
  it('renders cases, searches, filters, clears, and sorts deterministically', async () => { setup(); await screen.findByText('CASE-BR101-001'); expect(screen.getByText('CASE-RD-002')).toBeInTheDocument(); fireEvent.change(screen.getByLabelText('Search cases'), {target:{value:'BR-101'}}); expect(screen.queryByText('CASE-RD-002')).not.toBeInTheDocument(); fireEvent.click(screen.getByRole('button',{name:/Clear all/})); fireEvent.click(screen.getByRole('button',{name:/Filters/})); fireEvent.change(screen.getByLabelText('Status'), {target:{value:'NEW'}}); expect(screen.getByText('1 case shown')).toBeInTheDocument(); fireEvent.change(screen.getByLabelText('Status'), {target:{value:''}}); fireEvent.change(screen.getByLabelText('Priority'), {target:{value:'LOW'}}); expect(screen.getByText('CASE-RD-002')).toBeInTheDocument(); fireEvent.change(screen.getByLabelText('Emergency'), {target:{value:'true'}}); expect(screen.getByText(/no cases match/i)).toBeInTheDocument(); fireEvent.click(screen.getByRole('button',{name:/Clear all/})); expect(screen.getByRole('button',{name:/Open CASE-BR101-001/})).toBeInTheDocument(); });
  it('does not show organization display filters to a normal user', async () => { setup(); await screen.findByText('CASE-BR101-001'); expect(screen.queryByLabelText(/Department/)).not.toBeInTheDocument(); });
  it('labels system-admin organization controls as display-only filters', async () => { setup('SYSTEM_ADMIN'); await screen.findByText('CASE-BR101-001'); fireEvent.click(screen.getByRole('button',{name:/Filters/})); expect(screen.getByLabelText('Department (display only)')).toBeInTheDocument(); expect(screen.queryByText(/acting/i)).not.toBeInTheDocument(); });
  it('opens the selected workspace, shows overview, and returns to the cases registry', async () => { setup(); await screen.findByText('CASE-BR101-001'); fireEvent.click(screen.getByRole('button',{name:/CASE-BR101-001/})); expect(screen.getByRole('heading',{name:'CASE-BR101-001'})).toBeInTheDocument(); expect(screen.getByText('Structural review')).toBeInTheDocument(); const back=screen.getByRole('button',{name:'Back to cases'});expect(back).toBeInTheDocument();fireEvent.click(back); expect(screen.getByRole('heading',{name:'Cases'})).toBeInTheDocument(); });
  it('renders all eight governed lifecycle stages with user-facing Action Plan terminology',async()=>{setup();await screen.findByText('CASE-BR101-001');fireEvent.click(screen.getByRole('button',{name:/CASE-BR101-001/}));const tracker=screen.getByRole('region',{name:'Case lifecycle stages'});for(const label of ['Case','Inspection','Risk Assessment','Action Plan','Human Decision','Execution','Verification','Closure'])expect(within(tracker).getByText(label)).toBeInTheDocument();expect(within(tracker).queryByText('ORP')).not.toBeInTheDocument();expect(within(tracker).getAllByRole('button')).toHaveLength(8);});
  it('opens a dashboard-selected case directly and marks only its persisted lifecycle position', async () => { vi.stubGlobal('fetch',vi.fn().mockResolvedValue(response(cases)));render(<AuthContext.Provider value={context()}><CasesPage initialCaseId="c1"/></AuthContext.Provider>);expect(await screen.findByRole('heading',{name:'CASE-BR101-001'})).toBeInTheDocument();const current=screen.getByRole('button',{name:/Action Plan Current stage/i});expect(current).toHaveAttribute('aria-current','step');expect(screen.getByRole('button',{name:/Risk Assessment Recorded/i})).toBeInTheDocument();expect(screen.getByRole('button',{name:/Human Decision Pending/i})).toBeInTheDocument();});
  it('shows deliberate empty and neutral 404 states', async () => { const fetchMock=vi.fn(async(url:string)=>url.endsWith('/cases')?response(cases):url.endsWith('/policy-resolution')?response({status:'ABSTAINED',issues:[],applicableRules:[],governance:{advisoryOnly:true,caseMutated:false,automaticDecision:false}}):response({success:false,error:{code:'CASE_NOT_FOUND',message:'Case not found.'}},404)); vi.stubGlobal('fetch',fetchMock); render(<AuthContext.Provider value={context()}><CasesPage /></AuthContext.Provider>); await screen.findByText('CASE-BR101-001'); fireEvent.click(screen.getByRole('button',{name:/CASE-BR101-001/})); fireEvent.click(screen.getByRole('button',{name:'Inspection'})); expect(await screen.findByText('Case unavailable or no longer accessible.')).toBeInTheDocument(); expect(screen.queryByText('Case not found.')).not.toBeInTheDocument(); });
  it('renders safe inspection identity but not email or employee code', async () => { const fetchMock=vi.fn(async(url:string)=>url.endsWith('/cases')?response(cases):url.endsWith('/policy-resolution')?response({status:'ABSTAINED',issues:[],applicableRules:[],governance:{advisoryOnly:true,caseMutated:false,automaticDecision:false}}):response([{id:'i',inspectionDate:'2026-01-01',structuralCondition:'POOR',crackSeverity:'SEVERE',corrosionLevel:'MODERATE',trafficImportance:'HIGH',hospitalRoute:true,weatherRisk:'HIGH',heavyRainExpected:true,estimatedDailyUsers:42000,inspectionNotes:null,createdAt:'2026-01-01',inspector:{name:'Rahul Patil',designation:'Executive Engineer',email:'hidden@test',employeeCode:'PWD-1'}}])); vi.stubGlobal('fetch',fetchMock); render(<AuthContext.Provider value={context()}><CasesPage /></AuthContext.Provider>); await screen.findByText('CASE-BR101-001'); fireEvent.click(screen.getByRole('button',{name:/CASE-BR101-001/})); fireEvent.click(screen.getByRole('button',{name:'Inspection'})); expect(await screen.findByText(/Rahul Patil/)).toHaveTextContent('Executive Engineer'); expect(screen.queryByText(/hidden@test|PWD-1/)).not.toBeInTheDocument(); });
  it('presents Action Plan recommendations, structured reasons, and action labels without changing API values', async () => { const fetchMock=vi.fn(async (url: string) => url.endsWith('/cases') ? response(cases) : url.endsWith('/orps') ? response([{id:'o1',versionNumber:1,status:'AWAITING_REVIEW',urgency:'IMMEDIATE',recommendedActionCodes:['ACT_INSPECT_DETAILED','UNKNOWN_ACTION'],temporaryMeasures:['Restrict access'],reasons:[{reasonCode:'ORP_RULE_A002',message:'Persisted reason',privateValue:'hidden'}],alternativeActionCodes:['ACT_TRAFFIC_MANAGEMENT'],planVersion:'ODYSSEY_ORP_V1',createdAt:'2026-01-02'}]) : response([{id:'d1',decisionType:'APPROVED',reason:'Reviewed evidence',remarks:null,createdAt:'2026-01-03',reviewer:{name:'Review Officer',designation:'Chief Engineer',email:'private@test',employeeCode:'SECRET'}}]));vi.stubGlobal('fetch',fetchMock); render(<AuthContext.Provider value={context()}><CasesPage /></AuthContext.Provider>); await screen.findByText('CASE-BR101-001');expect(screen.getByText('Plan Ready')).toBeInTheDocument(); fireEvent.click(screen.getByRole('button',{name:/CASE-BR101-001/})); fireEvent.click(screen.getByRole('button',{name:'Response & Decision'})); expect(await screen.findByText('Recommended Action Plan')).toBeInTheDocument();expect(screen.getByText('Action Plan · Version 1')).toBeInTheDocument();expect(screen.getByText('Detailed inspection')).toBeInTheDocument();expect(screen.getByText('Traffic management')).toBeInTheDocument();expect(screen.getByText('UNKNOWN_ACTION')).toBeInTheDocument();expect(screen.getByText('ORP_RULE_A002')).toBeInTheDocument();expect(screen.getByText('Persisted reason')).toBeInTheDocument();expect(screen.queryByText(/\{"|privateValue|hidden/)).not.toBeInTheDocument();expect(fetchMock.mock.calls.some(([url])=>String(url).endsWith('/orps'))).toBe(true); expect(await screen.findByText('Human decisions')).toBeInTheDocument(); expect(await screen.findByText(/Review Officer/)).toHaveTextContent('Chief Engineer'); expect(screen.queryByText(/private@test|SECRET|AI approved/i)).not.toBeInTheDocument(); });
  it('shows task evidence counts and types without sensitive evidence fields', async () => {
    vi.stubGlobal('fetch', vi.fn(async (url: string) => {
      if (url.endsWith('/cases')) return response(cases);
      if (url.endsWith('/execution-plans')) return response([{id:'p1',status:'IN_PROGRESS',templateVersion:'V1',createdAt:'2026-01-01',startedAt:'2026-01-02',completedAt:null}]);
      return response({id:'p1',status:'IN_PROGRESS',templateVersion:'V1',createdAt:'2026-01-01',startedAt:'2026-01-02',completedAt:null,tasks:[{id:'t1',sequenceNumber:1,titleSnapshot:'Stabilize bridge',descriptionSnapshot:'Install supports',isMandatory:true,status:'IN_PROGRESS',assignedTo:{name:'Field Officer',designation:'Engineer'},completionSubmittedBy:null,verifiedBy:null,evidence:[{evidenceType:'PHOTO_REFERENCE',referenceUrl:'https://secret.test/photo',documentReference:'SECRET-DOC',description:'sensitive'}]}]});
    }));
    render(<AuthContext.Provider value={context()}><CasesPage /></AuthContext.Provider>); await screen.findByText('CASE-BR101-001'); fireEvent.click(screen.getByRole('button',{name:/CASE-BR101-001/})); fireEvent.click(screen.getByRole('button',{name:'Execution'})); expect(await screen.findByText((_text,element)=>element?.tagName==='STRONG'&&Boolean(element.textContent?.includes('Stabilize bridge')))).toBeInTheDocument(); expect(screen.getByText(/Evidence: 1 \(Photo Reference\)/)).toBeInTheDocument(); expect(screen.queryByText(/secret\.test|SECRET-DOC|sensitive/)).not.toBeInTheDocument();
  });
  it('shows operational controls only to OFFICER users', async()=>{setup('OFFICER');await screen.findByText('CASE-BR101-001');fireEvent.click(screen.getByRole('button',{name:/CASE-BR101-001/}));fireEvent.click(screen.getByRole('button',{name:'Inspection'}));expect(screen.getByRole('button',{name:'Record inspection'})).toBeInTheDocument();});
  it.each(['AUDITOR','POLICY_ADMIN','SYSTEM_ADMIN'] as SystemRole[])('keeps %s read-only without OFFICER controls',async(role)=>{setup(role);await screen.findByText('CASE-BR101-001');fireEvent.click(screen.getByRole('button',{name:/CASE-BR101-001/}));fireEvent.click(screen.getByRole('button',{name:'Inspection'}));expect(screen.queryByRole('button',{name:'Record inspection'})).not.toBeInTheDocument();});
  it('keeps CLOSED cases terminal without mutation controls',async()=>{const closed=[{...cases[0],status:'CLOSED' as const}];vi.stubGlobal('fetch',vi.fn().mockResolvedValue(response(closed)));render(<AuthContext.Provider value={context()}><CasesPage/></AuthContext.Provider>);await screen.findByText('CASE-BR101-001');fireEvent.click(screen.getByRole('button',{name:/CASE-BR101-001/}));expect(screen.getByText('Workflow formally closed')).toBeInTheDocument();fireEvent.click(screen.getByRole('button',{name:'Inspection'}));expect(screen.queryByRole('button',{name:'Record inspection'})).not.toBeInTheDocument();});
  it('applies and visibly exposes dashboard emergency and priority presets',async()=>{vi.stubGlobal('fetch',vi.fn().mockResolvedValue(response(cases)));const {rerender}=render(<AuthContext.Provider value={context()}><CasesPage initialFilter="emergency"/></AuthContext.Provider>);await screen.findByText('CASE-BR101-001');expect(screen.getByText('Emergency: Yes')).toBeInTheDocument();expect(screen.queryByText('CASE-RD-002')).not.toBeInTheDocument();rerender(<AuthContext.Provider value={context()}><CasesPage initialFilter="priority-attention"/></AuthContext.Provider>);await waitFor(()=>expect(screen.getByText('Priority: Critical / Very High')).toBeInTheDocument());expect(screen.queryByText('CASE-RD-002')).not.toBeInTheDocument();fireEvent.click(screen.getByRole('button',{name:/Clear all/}));expect(screen.getByText('CASE-RD-002')).toBeInTheDocument();});
  it('renders structured and legacy risk reasons without exposing arbitrary JSON',async()=>{vi.stubGlobal('fetch',vi.fn(async(url:string)=>url.endsWith('/cases')?response(cases):response([{id:'r1',riskScore:77,riskLevel:'VERY_HIGH',priorityLevel:'CRITICAL',reasonCodes:['HEAVY_RAIN_EXPECTED','POLICY_R005'],reasons:[{reasonCode:'HEAVY_RAIN_EXPECTED',message:'Heavy rain is expected.',secret:'do not show'},{reasonCode:'POLICY_R005',message:'High public exposure detected.'},'Legacy observation',{unexpected:'leak me'}],assessmentVersion:'ODYSSEY_RISK_V1',createdAt:'2026-01-03'}])));render(<AuthContext.Provider value={context()}><CasesPage/></AuthContext.Provider>);await screen.findByText('CASE-BR101-001');fireEvent.click(screen.getByRole('button',{name:/CASE-BR101-001/}));fireEvent.click(screen.getByRole('button',{name:'Risk'}));expect(await screen.findByText('Heavy rainfall expected')).toBeInTheDocument();expect(screen.getByText('Heavy rain is expected.')).toBeInTheDocument();expect(screen.getByText('POLICY R005')).toBeInTheDocument();expect(screen.getByText('Legacy observation')).toBeInTheDocument();expect(screen.getByText(/Assessment policy: Risk Policy v1/)).toBeInTheDocument();expect(screen.queryByText(/secret|do not show|unexpected|leak me|\{"/i)).not.toBeInTheDocument();});
});
