import { useEffect, useState, type ReactNode } from 'react';
import type { CaseSummary } from '../api/cases.api';
import { getExecutionPlan, listDecisions, listExecutionPlans, listInspections, listOrps, listRiskAssessments, type DecisionDto, type ExecutionPlanDto, type InspectionDto, type OrpDto, type RiskAssessmentDto } from '../api/workflow.api';
import { useAuth } from '../auth/useAuth';
import { Empty, ErrorState, Loading } from '../components/AsyncState';
import StatusBadge, { humanize } from '../components/StatusBadge';
import { formatDate } from './CasesPage';
import DecisionBrief from '../components/reporting/DecisionBrief';
import CaseTimeline from '../components/reporting/CaseTimeline';
import InspectionAction from '../components/workflow/InspectionAction';
import { DecisionAction, ExecutionPlanAction, SimpleWorkflowAction } from '../components/workflow/RecommendationActions';
import TaskActions from '../components/workflow/TaskActions';
import ClosureAction from '../components/workflow/ClosureAction';
import CasePolicyConstraints from '../components/workflow/CasePolicyConstraints';
import DecisionReadiness from '../components/workflow/DecisionReadiness';
import DecisionPackage from '../components/workflow/DecisionPackage';
import AdvisoryIntelligence from '../components/intelligence/AdvisoryIntelligence';

type Tab = 'overview' | 'inspection' | 'risk' | 'package' | 'response' | 'execution' | 'brief' | 'timeline';
interface ActionSectionProps { caseId: string; refreshKey: number; canOperate: boolean; onRecorded(): Promise<void>|void; }
const tabs: Array<{ id: Tab; label: string }> = [{ id: 'overview', label: 'Overview' }, { id: 'inspection', label: 'Inspection' }, { id: 'risk', label: 'Risk' }, { id: 'package', label: 'Decision Package' }, { id: 'response', label: 'Response & Decision' }, { id: 'execution', label: 'Execution' }, { id: 'brief', label: 'Decision Brief' }, { id: 'timeline', label: 'Timeline' }];
const lifecycleStages: Array<{ label: string; tab: Tab }> = [
  { label: 'Case', tab: 'overview' }, { label: 'Inspection', tab: 'inspection' },
  { label: 'Risk Assessment', tab: 'risk' }, { label: 'Action Plan', tab: 'package' },
  { label: 'Human Decision', tab: 'response' }, { label: 'Execution', tab: 'execution' },
  { label: 'Verification', tab: 'execution' }, { label: 'Closure', tab: 'brief' },
];

export default function CaseWorkspace({ caseItem, onBack, onCaseRefresh }: { caseItem: CaseSummary; onBack(): void; onCaseRefresh(): Promise<void> }) {
  const [tab, setTab] = useState<Tab>('overview');
  const [refreshKey, setRefreshKey] = useState(0); const { user } = useAuth(); const canOperate = user?.role === 'OFFICER' && caseItem.status !== 'CLOSED';
  const refreshWorkflow = async () => { setRefreshKey((value) => value + 1); await onCaseRefresh(); };
  return <section aria-labelledby="workspace-heading">
    <button type="button" className="back-button" onClick={onBack} aria-label="Back to cases">← Back to cases</button>
    <div className="case-workspace-header"><div><p className="eyebrow">CASE COMMAND</p><h1 id="workspace-heading">{caseItem.caseNumber}</h1><p className="workspace-title">{caseItem.title}</p></div><div className="header-badges"><StatusBadge value={caseItem.status} /><StatusBadge value={caseItem.riskLevel} kind="risk" /><StatusBadge value={caseItem.priorityLevel} kind="priority" />{caseItem.emergencyFlag && <span className="emergency-marker">Emergency case</span>}</div>
      <dl className="command-facts"><div><dt>Asset</dt><dd>{caseItem.asset.name} · {caseItem.asset.assetCode}</dd></div><div><dt>Department</dt><dd>{caseItem.asset.department.name}</dd></div><div><dt>Jurisdiction</dt><dd>{caseItem.asset.jurisdiction.name}</dd></div><div><dt>Emergency</dt><dd>{caseItem.emergencyFlag ? 'Yes' : 'No'}</dd></div></dl></div>
    {caseItem.status === 'CLOSED' && <p className="closed-workflow">Workflow formally closed</p>}
    <LifecycleProgress status={caseItem.status} onSelect={setTab} />
    <nav className="workspace-tabs" aria-label="Case workspace sections">{tabs.map((item) => <button key={item.id} aria-current={tab === item.id ? 'page' : undefined} className={tab === item.id ? 'active' : ''} onClick={() => setTab(item.id)}>{item.label}</button>)}</nav>
    <div className="workspace-layout"><main className="workspace-section">{tab === 'overview' && <Overview item={caseItem} />}{tab === 'inspection' && <InspectionHistory caseId={caseItem.id} refreshKey={refreshKey} canOperate={canOperate} onRecorded={refreshWorkflow} />}{tab === 'risk' && <RiskHistory caseId={caseItem.id} refreshKey={refreshKey} canOperate={canOperate} onRecorded={refreshWorkflow} />}{tab === 'package' && <DecisionPackage caseId={caseItem.id} refreshKey={refreshKey} />}{tab === 'response' && <ResponseHistory caseId={caseItem.id} refreshKey={refreshKey} canOperate={canOperate} onRecorded={refreshWorkflow} />}{tab === 'execution' && <ExecutionHistory caseId={caseItem.id} refreshKey={refreshKey} canOperate={canOperate} onRecorded={refreshWorkflow} />}{tab === 'brief' && <DecisionBrief caseId={caseItem.id} refreshKey={refreshKey} />}{tab === 'timeline' && <CaseTimeline caseId={caseItem.id} refreshKey={refreshKey} />}</main><aside className="workspace-context" aria-label="Persisted case context"><p className="section-label">CASE CONTEXT</p><h2>{caseItem.asset.assetCode}</h2><dl><Detail label="Asset">{caseItem.asset.name}</Detail><Detail label="Status"><StatusBadge value={caseItem.status} /></Detail><Detail label="Risk"><StatusBadge value={caseItem.riskLevel} kind="risk" /></Detail><Detail label="Priority"><StatusBadge value={caseItem.priorityLevel} kind="priority" /></Detail><Detail label="Updated">{formatDate(caseItem.updatedAt)}</Detail></dl></aside></div>
  </section>;
}

function LifecycleProgress({ status, onSelect }: { status: string; onSelect(tab: Tab): void }) {
  const current = lifecycleIndex(status); const closed = status === 'CLOSED';
  return <section className="lifecycle-progress" aria-labelledby="lifecycle-progress-title">
    <div><p className="section-label">GOVERNED CASE LIFECYCLE</p><h2 id="lifecycle-progress-title">Current workflow position</h2></div>
    <div className="lifecycle-scroll" role="region" aria-label="Case lifecycle stages" tabIndex={0}><ol>{lifecycleStages.map((stage, index) => {
      const state = closed || index < current ? 'complete' : index === current ? 'current' : 'future';
      return <li className={state} key={stage.label}><button type="button" onClick={() => onSelect(stage.tab)}
        aria-current={state === 'current' ? 'step' : undefined}><span>{state === 'complete' ? '✓' : index + 1}</span>
        <strong>{stage.label}</strong><small>{state === 'complete' ? 'Recorded' : state === 'current' ? 'Current stage' : 'Pending'}</small></button></li>;
    })}</ol></div>
  </section>;
}

function lifecycleIndex(status: string) {
  if (status === 'NEW') return 0;
  if (status === 'INSPECTION_REQUIRED' || status === 'INSPECTION_IN_PROGRESS') return 1;
  if (status === 'UNDER_ANALYSIS') return 2;
  if (status === 'ORP_READY') return 3;
  if (status === 'UNDER_REVIEW') return 4;
  if (status === 'APPROVED' || status === 'EXECUTION') return 5;
  if (status === 'VERIFICATION') return 6;
  if (status === 'CLOSED') return 7;
  return 0;
}

function Overview({ item }: { item: CaseSummary }) { return <><h2>Case overview</h2><div className="detail-grid"><Detail label="Description">{item.description || 'No description recorded.'}</Detail>{item.sourcePublicReport&&<Detail label="Source">Citizen Public Report · {item.sourcePublicReport.reportNumber}</Detail>}<Detail label="Lifecycle status"><StatusBadge value={item.status} /></Detail><Detail label="Risk"><StatusBadge value={item.riskLevel} kind="risk" /></Detail><Detail label="Priority"><StatusBadge value={item.priorityLevel} kind="priority" /></Detail><Detail label="Emergency flag">{item.emergencyFlag ? 'Yes — emergency' : 'No'}</Detail><Detail label="Asset">{item.asset.name} ({item.asset.assetCode}) · {humanize(item.asset.assetType)}</Detail><Detail label="Department">{item.asset.department.name}</Detail><Detail label="Jurisdiction">{item.asset.jurisdiction.name}</Detail><Detail label="Created">{formatDate(item.createdAt)}</Detail><Detail label="Updated">{formatDate(item.updatedAt)}</Detail><Detail label="Closed">{formatDate(item.closedAt)}</Detail></div><DecisionReadiness caseId={item.id}/><CasePolicyConstraints caseId={item.id}/></>; }
function Detail({ label, children }: { label: string; children: ReactNode }) { return <div className="detail"><dt>{label}</dt><dd>{children}</dd></div>; }

function useSection<T>(loader: (token: string, signal: AbortSignal) => Promise<T>, dependency: string) {
  const { token } = useAuth(); const [data, setData] = useState<T | null>(null); const [error, setError] = useState<unknown>(null); const [loading, setLoading] = useState(true); const [reload, setReload] = useState(0);
  useEffect(() => { if (!token) return; const controller = new AbortController(); setLoading(true); setError(null); loader(token, controller.signal).then(setData).catch((reason) => { if (!controller.signal.aborted) setError(reason); }).finally(() => { if (!controller.signal.aborted) setLoading(false); }); return () => controller.abort(); }, [dependency, reload, token]);
  return { data, error, loading, retry: () => setReload((v) => v + 1) };
}
function Section<T>({ state, label, empty, children }: { state: ReturnType<typeof useSection<T>>; label: string; empty: string; children(data: T): ReactNode }) { if (state.loading) return <Loading label={label} />; if (state.error) return <ErrorState error={state.error} retry={state.retry} />; if (!state.data || (Array.isArray(state.data) && state.data.length === 0)) return <Empty>{empty}</Empty>; return <>{children(state.data)}</>; }

function InspectionHistory({ caseId, refreshKey, canOperate, onRecorded }: ActionSectionProps) { const state = useSection<InspectionDto[]>((token, signal) => listInspections(caseId, token, signal), `${caseId}-${refreshKey}`); return <><h2>Inspection history</h2>{canOperate&&<InspectionAction caseId={caseId} onRecorded={onRecorded}/>}<Section state={state} label="inspection history" empty="No persisted inspections are available for this case.">{(items) => <div className="history-list">{items.map((item) => <article className="history-card" key={item.id}><h3>{formatDate(item.inspectionDate)}</h3><div className="detail-grid compact"><Detail label="Structural condition">{humanize(item.structuralCondition)}</Detail><Detail label="Crack severity">{humanize(item.crackSeverity)}</Detail><Detail label="Corrosion">{humanize(item.corrosionLevel)}</Detail><Detail label="Traffic importance">{humanize(item.trafficImportance)}</Detail><Detail label="Hospital route">{item.hospitalRoute ? 'Yes' : 'No'}</Detail><Detail label="Weather risk">{humanize(item.weatherRisk)}</Detail><Detail label="Heavy rain expected">{item.heavyRainExpected ? 'Yes' : 'No'}</Detail><Detail label="Estimated daily users">{item.estimatedDailyUsers?.toLocaleString('en-IN') ?? 'Not recorded'}</Detail>{item.inspector && <Detail label="Inspector">{item.inspector.name} · {item.inspector.designation}</Detail>}</div></article>)}</div>}</Section></>; }

function JsonList({ value }: { value: unknown }) { const values = Array.isArray(value) ? value : []; return values.length ? <ul>{values.map((entry, i) => <li key={i}>{typeof entry === 'string' ? entry : JSON.stringify(entry)}</li>)}</ul> : <span>None recorded</span>; }
const actionLabels: Record<string,string> = { ACT_INSPECT_DETAILED:'Detailed inspection', ACT_RESTRICT_HEAVY_VEHICLES:'Restrict heavy vehicles', ACT_TEMP_STABILIZATION:'Temporary structural stabilization', ACT_INCREASE_MONITORING:'Increase monitoring', ACT_PERMANENT_REPAIR_PLANNING:'Permanent repair planning', ACT_ESCALATE_AUTHORITY:'Escalate to appropriate authority', ACT_TRAFFIC_MANAGEMENT:'Traffic management' };
function ActionList({ value }: { value: unknown }) { const values=Array.isArray(value)?value.filter((entry):entry is string=>typeof entry==='string'):[];return values.length?<ul>{values.map((entry)=><li key={entry}>{actionLabels[entry]??entry}</li>)}</ul>:<span>None recorded</span>; }
function normalizeReasons(value: unknown) { const values:Array<{code:string|null;message:string}>=[];if(Array.isArray(value))for(const entry of value){if(typeof entry==='string')values.push({code:null,message:entry});else if(entry&&typeof entry==='object'&&!Array.isArray(entry)){const reason=entry as Record<string,unknown>;if(typeof reason.reasonCode==='string'&&typeof reason.message==='string')values.push({code:reason.reasonCode,message:reason.message});}}return values; }
function friendlyReasonLabel(code:string){const known:Record<string,string>={STRUCTURAL_CONDITION_CRITICAL:'Critical structural condition',HIGH_TRAFFIC_IMPORTANCE:'High traffic importance',HIGH_WEATHER_RISK:'High weather risk',HEAVY_RAIN_EXPECTED:'Heavy rainfall expected',HIGH_PUBLIC_EXPOSURE:'High public exposure'};return known[code]??code.replaceAll('_',' ').toLowerCase().replace(/^./,(letter)=>letter.toUpperCase());}
function ReasonItems({values}:{values:Array<{code:string|null;message:string}>}){return <ul className="reason-list">{values.map((entry,index)=><li key={`${entry.code??'legacy'}-${index}`}>{entry.code&&<strong>{entry.code.startsWith('POLICY_')?entry.code.replace('_',' '):friendlyReasonLabel(entry.code)}</strong>}<span>{entry.message}</span>{entry.code&&!entry.code.startsWith('POLICY_')&&<small>Code: <span>{entry.code}</span></small>}</li>)}</ul>;}
function ReasonList({ value }: { value: unknown }) { const values=normalizeReasons(value);return values.length?<ReasonItems values={values}/>:<span>None recorded</span>; }
function RiskReasons({value}:{value:unknown}){const values=normalizeReasons(value);if(!values.length)return <span>None recorded</span>;const factors=values.filter((item)=>!item.code?.startsWith('POLICY_'));const policies=values.filter((item)=>item.code?.startsWith('POLICY_'));return <div className="risk-reason-groups">{factors.length>0&&<section><h4>Why this case received this risk rating</h4><ReasonItems values={factors}/></section>}{policies.length>0&&<section><h4>Priority rules applied</h4><ReasonItems values={policies}/></section>}</div>;}
function assessmentVersionLabel(value:string){return value==='ODYSSEY_RISK_V1'?'Assessment policy: Risk Policy v1':`Assessment policy: ${value}`;}
function RiskHistory({ caseId, refreshKey, canOperate, onRecorded }: ActionSectionProps) { const state = useSection<RiskAssessmentDto[]>((token, signal) => listRiskAssessments(caseId, token, signal), `${caseId}-${refreshKey}`); return <><section className="authoritative-risk" aria-labelledby="authoritative-risk-heading"><p className="section-label">AUTHORITATIVE DETERMINISTIC SAFETY</p><h2 id="authoritative-risk-heading">Risk-assessment history</h2><p className="section-note">Persisted deterministic assessments; values are displayed without recalculation and remain authoritative.</p>{canOperate&&<SimpleWorkflowAction kind="risk" caseId={caseId} onRecorded={onRecorded}/>}<Section state={state} label="risk history" empty="No persisted risk assessments are available for this case.">{(items) => <div className="history-list">{items.map((item) => <article className="history-card" key={item.id}><div className="card-heading"><h3>Score {item.riskScore}</h3><StatusBadge value={item.riskLevel} kind="risk" /><StatusBadge value={item.priorityLevel} kind="priority" /></div><RiskReasons value={item.reasons}/><p className="record-meta">{assessmentVersionLabel(item.assessmentVersion)} · {formatDate(item.createdAt)}</p></article>)}</div>}</Section></section><AdvisoryIntelligence caseId={caseId} canOperate={canOperate} refreshKey={refreshKey}/></>; }

function ResponseHistory({ caseId, refreshKey, canOperate, onRecorded }: ActionSectionProps) { const orps = useSection<OrpDto[]>((token, signal) => listOrps(caseId, token, signal), `${caseId}-orps-${refreshKey}`); const decisions = useSection<DecisionDto[]>((token, signal) => listDecisions(caseId, token, signal), `${caseId}-decisions-${refreshKey}`); return <><h2>Response and decision history</h2>{canOperate&&<SimpleWorkflowAction kind="orp" caseId={caseId} onRecorded={onRecorded}/>}<h3 className="subheading">Recommended Action Plan</h3><Section state={orps} label="action plans" empty="No recommended action plans are available.">{(items) => <><div className="history-list">{items.map((item) => <article className="history-card" key={item.id}><div className="card-heading"><h3>{item.governanceMode==='LEGACY'?'Action Plan':'Governed Action Plan'} · Version {item.versionNumber}</h3><StatusBadge value={item.status} /></div><Detail label="Urgency">{humanize(item.urgency)}</Detail>{item.governanceMode==='LEGACY'?<><Detail label="Recommended actions"><ActionList value={item.recommendedActionCodes} /></Detail><Detail label="Temporary measures"><JsonList value={item.temporaryMeasures} /></Detail><Detail label="Alternative actions"><ActionList value={item.alternativeActionCodes} /></Detail></>:<GovernedActionGroups orp={item}/>}<Detail label="Why these actions were recommended"><ReasonList value={item.reasons} /></Detail><p className="section-note">Decision support only. A human decision is required; this record does not authorize execution.</p><p className="record-meta">{item.decisionPackage?`Decision Package v${item.decisionPackage.packageVersion} · `:''}{item.actionPlanContractVersion??item.planVersion} · {formatDate(item.createdAt)}</p></article>)}</div>{canOperate&&items[0]?.status==='AWAITING_REVIEW'&&<DecisionAction orp={items[0]} onRecorded={onRecorded}/>} {canOperate&&items[0]?.status==='APPROVED'&&<ExecutionPlanAction orpId={items[0].id} onRecorded={onRecorded}/>}</>}</Section><h3 className="subheading">Human decisions</h3><Section state={decisions} label="human decisions" empty="No human decisions are recorded for this case.">{(items) => <div className="history-list">{items.map((item) => <article className="history-card" key={item.id}><h3>{humanize(item.decisionType)}</h3><Detail label="Reason">{item.reason || 'Not recorded'}</Detail><Detail label="Remarks">{item.remarks || 'Not recorded'}</Detail>{item.reviewer && <Detail label="Reviewer">{item.reviewer.name} · {item.reviewer.designation}</Detail>}<p className="record-meta">{formatDate(item.createdAt)}</p></article>)}</div>}</Section></>; }

function GovernedActionGroups({orp}:{orp:OrpDto}) { const groups=orp.governedActions; if(!groups)return <p className="error-text">Governed action provenance is unavailable.</p>; return <div className="governed-action-groups"><p><strong>Basis:</strong> {humanize(groups.basis)}</p>{(['MANDATORY','RECOMMENDED','OPTIONAL','PROHIBITED','ENGINEERING_RECOMMENDED'] as const).map((classification)=>groups[classification].length>0&&<section key={classification}><h4>{humanize(classification)}</h4><ul>{groups[classification].map((action)=><li key={`${action.actionId??action.actionCode}-${action.actionVersion??'engineering'}`}><strong>{action.title}</strong> <span>({action.actionCode}{action.actionVersion?` · v${action.actionVersion}`:''})</span>{action.sources?.map((source)=><small key={source.ruleId}>Policy {source.policyCode} v{source.policyVersion}; rule {source.ruleCode}</small>)}</li>)}</ul></section>)}</div>; }

function ExecutionHistory({ caseId, refreshKey, canOperate, onRecorded }: ActionSectionProps) { const state = useSection<ExecutionPlanDto[]>(async (token, signal) => { const plans = await listExecutionPlans(caseId, token, signal); return Promise.all(plans.map((plan) => getExecutionPlan(plan.id, token, signal))); }, `${caseId}-${refreshKey}`); return <><h2>Execution history</h2><Section state={state} label="execution history" empty="No execution plans are available for this case.">{(plans) => <><div className="history-list">{plans.map((plan) => <article className="history-card" key={plan.id}><div className="card-heading"><h3>Execution plan</h3><StatusBadge value={plan.status} /></div><div className="detail-grid compact"><Detail label="Template">{plan.templateVersion}</Detail><Detail label="Created">{formatDate(plan.createdAt)}</Detail><Detail label="Started">{formatDate(plan.startedAt)}</Detail><Detail label="Completed">{formatDate(plan.completedAt)}</Detail></div>{!plan.tasks?.length ? <p>No tasks are recorded.</p> : <ol className="task-list">{plan.tasks.map((task) => <li key={task.id}><div className="card-heading"><strong>{task.sequenceNumber}. {task.titleSnapshot}</strong><StatusBadge value={task.status} /></div><p>Source action: {task.sourceActionCode}{task.sourceActionVersion?` v${task.sourceActionVersion}`:''}</p>{task.sourceTemplateCode&&<p>Authorized template: {task.sourceTemplateCode} v{task.sourceTemplateVersion}</p>}<p>{task.descriptionSnapshot}</p><p>{task.isMandatory ? 'Mandatory task' : 'Optional task'}</p>{task.assignedTo && <p>Assigned officer: {task.assignedTo.name} · {task.assignedTo.designation}</p>}{task.completionSubmittedBy && <p>Completion submitted by: {task.completionSubmittedBy.name} · {task.completionSubmittedBy.designation}</p>}{task.verifiedBy && <p>Verified by: {task.verifiedBy.name} · {task.verifiedBy.designation}</p>}<p>Evidence: {task.evidence?.length ?? 0}{task.evidence?.length ? ` (${[...new Set(task.evidence.map((item) => humanize(item.evidenceType)))].join(', ')})` : ''}</p>{canOperate&&<TaskActions task={task} onRecorded={onRecorded}/>}</li>)}</ol>}</article>)}</div>{canOperate&&plans.some((plan)=>plan.status==='COMPLETED')&&<ClosureAction caseId={caseId} onRecorded={onRecorded}/>}</>}</Section></>; }
