import { useState, type FormEvent } from 'react';
import { Check, Circle, Landmark } from 'lucide-react';
import { isApiClientError } from '../api/errors';
import { trackPublicReport, type PublicTrackingResult } from '../api/public-reports.api';

const referencePattern=/^JNV-PUB-\d{8}-[A-F0-9]{6}$/;
const formatDate=(value:string|null)=>value?new Intl.DateTimeFormat('en-IN',{day:'2-digit',month:'short',year:'numeric'}).format(new Date(value)):'Date not recorded';
const categoryLabel=(value:string)=>value.split('_').map((part)=>part[0]+part.slice(1).toLowerCase()).join(' ');

export default function CitizenTrackingPage({initialReference='',onOfficerLogin,onReportIssue}:{initialReference?:string;onOfficerLogin():void;onReportIssue():void}){
 const[reference,setReference]=useState(initialReference),[result,setResult]=useState<PublicTrackingResult|null>(null),[error,setError]=useState<string|null>(null),[busy,setBusy]=useState(false);
 async function submit(event:FormEvent){event.preventDefault();if(busy)return;const normalized=reference.trim().toUpperCase();setReference(normalized);setResult(null);if(!referencePattern.test(normalized)){setError('Enter a valid report reference, for example JNV-PUB-20260819-ABC123.');return;}setBusy(true);setError(null);try{setResult(await trackPublicReport(normalized));}catch(reason){if(isApiClientError(reason)&&reason.status===404)setError('No report was found for that reference. Check the reference and try again.');else if(isApiClientError(reason)&&reason.kind==='network')setError('The tracking service could not be reached. Please try again later.');else if(isApiClientError(reason)&&reason.status===429)setError('Too many tracking requests. Please wait before trying again.');else setError('Tracking is temporarily unavailable. Please try again later.');}finally{setBusy(false);}
 }
 return <main className="citizen-report-page"><header className="citizen-header"><div><Landmark aria-hidden="true" size={25}/><strong>JANSEVA INTELLIGOV</strong></div><div className="citizen-header-actions"><button type="button" onClick={onReportIssue}>Report an issue</button><button type="button" onClick={onOfficerLogin}>Officer sign in</button></div></header><section className="citizen-tracking-shell"><div className="citizen-tracking-intro"><p className="eyebrow">CITIZEN INFRASTRUCTURE SERVICE</p><h1>Track your report</h1><p>View public-safe progress using the reference provided when your report was submitted.</p></div><form className="tracking-form" onSubmit={submit} noValidate><label htmlFor="tracking-reference">Report reference</label><div><input id="tracking-reference" value={reference} onChange={(event)=>setReference(event.target.value)} placeholder="JNV-PUB-YYYYMMDD-XXXXXX" autoComplete="off" spellCheck={false}/><button className="primary-button" disabled={busy} aria-busy={busy}>{busy?'Tracking…':'Track report'}</button></div>{error&&<p className="form-error" role="alert">{error}</p>}</form>{busy&&<p className="tracking-announcement" role="status">Looking up your report…</p>}{result&&<article className="tracking-result" aria-live="polite"><section className="tracking-summary"><div><p className="section-label">REPORT REFERENCE</p><strong className="tracking-reference">{result.reportReference}</strong><h2>{result.title}</h2><p>{categoryLabel(result.category)}</p></div><dl><div><dt>Current status</dt><dd>{result.statusLabel}</dd></div><div><dt>Submitted</dt><dd>{formatDate(result.submittedAt)}</dd></div><div><dt>Location</dt><dd>{result.locationText}</dd></div><div><dt>Last public progress</dt><dd>{formatDate(result.lastProgressAt)}</dd></div></dl></section><section className="public-progress" aria-labelledby="progress-heading"><h2 id="progress-heading">Progress</h2><ol>{result.timeline.map((item)=><li key={item.key} className={item.state.toLowerCase()}>{item.state==='COMPLETED'?<Check aria-hidden="true"/>:<Circle aria-hidden="true"/>}<div><strong>{item.label}</strong><span>{item.state==='PENDING'?'Pending':item.occurredAt?formatDate(item.occurredAt):item.state==='CURRENT'?'In progress':'Completed'}</span></div></li>)}</ol></section>{result.governedCaseCreated&&<section className="governed-case-public"><p className="section-label">GOVERNED CASE</p><strong>{result.caseReference}</strong><p>A government infrastructure case has been created. This reference is informational and does not provide access to internal government operations.</p></section>}<p className="transparency-note">This page shows broad public progress while protecting personal information and sensitive operational details.</p></article>}</section></main>;
}
