import{fireEvent,render,screen}from'@testing-library/react';import{afterEach,describe,expect,it,vi}from'vitest';import CitizenTrackingPage from'./CitizenTrackingPage';
const reference='JNV-PUB-20260819-12EE4F';const result={reportReference:reference,submittedAt:'2026-08-19T08:00:00Z',category:'BRIDGE_OR_FLYOVER',title:'Flyover surface deterioration',locationText:'University Road flyover, Pune',status:'CASE_RECORDED',statusLabel:'Case recorded',lastProgressAt:'2026-08-19T10:00:00Z',governedCaseCreated:true,caseReference:'CASE-PUB-260819-7ABAA4',outcome:'ACTIVE',timeline:[{key:'RECEIVED',label:'Report received',state:'COMPLETED',occurredAt:'2026-08-19T08:00:00Z'},{key:'REVIEW',label:'Government review',state:'COMPLETED',occurredAt:'2026-08-19T09:00:00Z'},{key:'CASE',label:'Case recorded',state:'CURRENT',occurredAt:'2026-08-19T10:00:00Z'},{key:'ASSESSMENT',label:'Assessment',state:'PENDING',occurredAt:null},{key:'ACTION',label:'Government action',state:'PENDING',occurredAt:null},{key:'VERIFICATION',label:'Verification',state:'PENDING',occurredAt:null},{key:'RESOLUTION',label:'Resolution',state:'PENDING',occurredAt:null}]};
const response=(data:unknown,status=200)=>new Response(JSON.stringify(status===200?{success:true,data}:{success:false,error:data}),{status});afterEach(()=>vi.unstubAllGlobals());function show(initialReference=''){render(<CitizenTrackingPage initialReference={initialReference} onOfficerLogin={vi.fn()} onReportIssue={vi.fn()}/>);}
describe('citizen tracking',()=>{
 it('renders an accessible form and validates before lookup',()=>{const fetchMock=vi.fn();vi.stubGlobal('fetch',fetchMock);show();expect(screen.getByRole('heading',{name:'Track your report'})).toBeInTheDocument();fireEvent.click(screen.getByRole('button',{name:'Track report'}));expect(screen.getByRole('alert')).toHaveTextContent('valid report reference');expect(fetchMock).not.toHaveBeenCalled();});
 it('shows loading then public-safe progress without internal links',async()=>{let resolve!:(value:Response)=>void;vi.stubGlobal('fetch',vi.fn(()=>new Promise<Response>((done)=>{resolve=done;})));show(reference);fireEvent.click(screen.getByRole('button',{name:'Track report'}));expect(screen.getByRole('button',{name:'Tracking…'})).toBeDisabled();resolve(response(result));expect(await screen.findByText('Flyover surface deterioration')).toBeInTheDocument();expect(screen.getByText('CASE-PUB-260819-7ABAA4')).toBeInTheDocument();expect(screen.queryByRole('link')).not.toBeInTheDocument();for(const sensitive of ['risk score','triage','action plan','internal notes'])expect(screen.queryByText(new RegExp(sensitive,'i'))).not.toBeInTheDocument();});
 it.each([[404,'No report was found'],[500,'temporarily unavailable']])('handles controlled %s errors',async(status,message)=>{vi.stubGlobal('fetch',vi.fn().mockResolvedValue(response({code:'ERROR',message:'internal'},status as number)));show(reference);fireEvent.click(screen.getByRole('button',{name:'Track report'}));expect(await screen.findByRole('alert')).toHaveTextContent(message);expect(screen.queryByText('internal')).not.toBeInTheDocument();});
 it('handles an unavailable API',async()=>{vi.stubGlobal('fetch',vi.fn().mockRejectedValue(new Error('offline')));show(reference);fireEvent.click(screen.getByRole('button',{name:'Track report'}));expect(await screen.findByRole('alert')).toHaveTextContent('could not be reached');});
 it('presents rejection neutrally without a reason',async()=>{vi.stubGlobal('fetch',vi.fn().mockResolvedValue(response({...result,status:'CLOSED_AFTER_REVIEW',statusLabel:'Closed after government review',governedCaseCreated:false,caseReference:null,outcome:'CLOSED_AFTER_REVIEW'})));show(reference);fireEvent.click(screen.getByRole('button',{name:'Track report'}));expect(await screen.findByText('Closed after government review')).toBeInTheDocument();expect(screen.queryByText(/rejection reason/i)).not.toBeInTheDocument();});
});
