import { fireEvent, render, screen, within } from '@testing-library/react';
import { afterEach, describe, expect, it, vi } from 'vitest';
import { AuthContext, type AuthContextValue } from '../auth/AuthProvider';
import InfrastructureMapPage from './InfrastructureMapPage';

vi.mock('react-leaflet', () => ({
  MapContainer: ({children}:{children:React.ReactNode}) => <div data-testid="map">{children}</div>,
  TileLayer: () => <span>OpenStreetMap contributors</span>, Tooltip: ({children}:{children:React.ReactNode}) => <span>{children}</span>,
  CircleMarker: ({children,eventHandlers}:{children:React.ReactNode;eventHandlers:{click():void}}) => <button onClick={eventHandlers.click}>{children}</button>,
  Marker: ({children,eventHandlers}:{children:React.ReactNode;eventHandlers:{click():void}}) => <button onClick={eventHandlers.click}>{children}</button>
}));
vi.mock('leaflet', () => ({ divIcon: () => ({}) }));

const auth:AuthContextValue={user:{id:'u',employeeCode:'E',name:'Officer',email:'officer@test',designation:'Engineer',role:'OFFICER',status:'ACTIVE',departmentId:'d',jurisdictionId:'j'},token:'token',organization:null,isAuthenticated:true,authStatus:'authenticated',sessionMessage:null,login:vi.fn(),logout:vi.fn()};
const reports=[{id:'r1',reportNumber:'JNV-PUB-1',title:'Bridge signal',category:'BRIDGE_OR_FLYOVER',status:'UNDER_REVIEW',locationText:'River Road',submittedAt:'2026-08-19T10:00:00Z',department:{id:'d',name:'Public Works'},jurisdiction:{id:'j',name:'Pune Division'},asset:null,latitude:18.52,longitude:73.85,createdCase:null,triageAnalysis:{suggestedCategory:'BRIDGE_OR_FLYOVER',urgencyLevel:'HIGH',confidence:85,reasons:[{reasonCode:'TRIAGE_STRUCTURAL_LANGUAGE',message:'Structural deterioration language was detected.'}]}},{id:'r2',reportNumber:'JNV-PUB-2',title:'Unmapped signal',category:'ROAD_DAMAGE',status:'SUBMITTED',locationText:'Unknown coordinate',submittedAt:'2026-08-19T09:00:00Z',department:null,jurisdiction:null,asset:null,latitude:null,longitude:null,createdCase:null,triageAnalysis:null}];
const cases=[{id:'c1',caseNumber:'CASE-1',title:'Bridge safety case',description:null,status:'EXECUTION',riskLevel:'VERY_HIGH',priorityLevel:'CRITICAL',emergencyFlag:true,createdAt:'',updatedAt:'',closedAt:null,asset:{id:'a1',assetCode:'BR-101',name:'Pune River Bridge',assetType:'BRIDGE',departmentId:'d',jurisdictionId:'j',latitude:18.52,longitude:73.85,department:{id:'d',name:'Public Works'},jurisdiction:{id:'j',name:'Pune Division'}}}];
const assets=[{id:'a1',assetCode:'BR-101',name:'Pune River Bridge',assetType:'BRIDGE',departmentId:'d',jurisdictionId:'j',latitude:18.52,longitude:73.85,conditionStatus:null,createdAt:'',department:{id:'d',name:'Public Works',code:'PWD',createdAt:''},jurisdiction:{id:'j',name:'Pune Division',type:'DIVISION',departmentId:'d',createdAt:'',department:{}}},{id:'a2',assetCode:'BR-2',name:'Unmapped Bridge',assetType:'BRIDGE',departmentId:'d',jurisdictionId:'j',latitude:null,longitude:null,conditionStatus:null,createdAt:'',department:{id:'d',name:'Public Works'},jurisdiction:{id:'j',name:'Pune Division'}}];
const hotspot={analysisVersion:'ODYSSEY_GEOSPATIAL_HOTSPOTS_V1',generatedAt:'2026-08-24',scope:{visibility:'DEPARTMENT_JURISDICTION',departmentId:'d',jurisdictionId:'j'},method:{gridSizeDegrees:.01,severity:'current priority',hotspotThreshold:'two records or critical'},coverage:{overall:{eligibleRecords:5,mappedRecords:3,unmappedRecords:2,invalidCoordinateCount:0,coveragePercentage:60},assets:{eligibleRecords:2,mappedRecords:1,unmappedRecords:1,invalidCoordinateCount:0,coveragePercentage:50},activeCases:{eligibleRecords:1,mappedRecords:1,unmappedRecords:0,invalidCoordinateCount:0,coveragePercentage:100},publicReports:{eligibleRecords:2,mappedRecords:1,unmappedRecords:1,invalidCoordinateCount:0,coveragePercentage:50}},summary:{uniqueMappedAssets:1,activeMappedCases:1,mappedPublicReports:1,totalHotspots:1,hotspotsReturned:1},hotspots:[{cellId:'d:j:G001:1852:7385',center:{latitude:18.52,longitude:73.85},department:{id:'d',name:'Public Works'},jurisdiction:{id:'j',name:'Pune Division'},assetCount:1,activeCaseCount:1,publicReportCount:1,recordCount:3,riskCounts:{VERY_HIGH:1},priorityCounts:{CRITICAL:1},highestPriority:'CRITICAL',severityIndex:5,severityComponents:{CRITICAL:5},qualification:'CRITICAL_RECORD'}],truncation:{limit:100,totalHotspots:1,hotspotsReturned:1,truncated:false},complete:true,disclosure:'descriptive'};
const ok=(data:unknown)=>new Response(JSON.stringify({success:true,data}),{status:200});
const responder=(url:string)=>url.includes('/public-reports')?ok(reports):url.includes('/cases')?ok(cases):url.includes('/geospatial')?ok(hotspot):ok(assets);
function show(fetchMock=vi.fn(async(url:string)=>responder(url))){vi.stubGlobal('fetch',fetchMock);const onOpenReport=vi.fn(),onOpenCase=vi.fn();render(<AuthContext.Provider value={auth}><InfrastructureMapPage onOpenReport={onOpenReport} onOpenCase={onOpenCase}/></AuthContext.Provider>);return{onOpenReport,onOpenCase};}
afterEach(()=>vi.unstubAllGlobals());

describe('Infrastructure Map',()=>{
  it('loads scoped layers once and presents honest coordinate coverage',async()=>{const fetchMock=vi.fn(async(url:string)=>responder(url));show(fetchMock);expect(screen.getByRole('status')).toHaveTextContent('Loading map intelligence');expect(await screen.findByRole('heading',{name:'Pune Division Situation Map'})).toBeInTheDocument();expect(fetchMock).toHaveBeenCalledTimes(4);expect(screen.getByText('3 mapped · 2 unmapped')).toBeInTheDocument();expect(screen.getByText(/covers 3 of 5 eligible records \(60%\)/)).toBeInTheDocument();expect(screen.getByText(/descriptive, not predictions/)).toBeInTheDocument();expect(screen.getByText(/representative test coordinates/)).toBeInTheDocument();expect(screen.queryByText(/verified coordinates/i)).not.toBeInTheDocument();expect(screen.getByText('OpenStreetMap contributors')).toBeInTheDocument();});
  it('renders distinct report, governed Case, and asset list records without PII',async()=>{show();expect(await screen.findByRole('button',{name:'Select Public Report JNV-PUB-1'})).toBeInTheDocument();expect(screen.getByRole('button',{name:'Select Governed Case CASE-1'})).toBeInTheDocument();expect(screen.getByRole('button',{name:'Select Infrastructure Asset BR-101'})).toBeInTheDocument();expect(screen.queryByText(/reporter|contact/i)).not.toBeInTheDocument();});
  it('labels triage urgency advisory and Case risk authoritative',async()=>{show();fireEvent.click(await screen.findByRole('button',{name:'Select Public Report JNV-PUB-1'}));expect(screen.getByText('Advisory urgency · High')).toBeInTheDocument();fireEvent.click(screen.getByRole('button',{name:'Select Governed Case CASE-1'}));const detail=screen.getByText('Authoritative risk').closest('aside')!;expect(within(detail).getByText('Very High')).toBeInTheDocument();});
  it('supports layer toggles and operational filters',async()=>{show();await screen.findByRole('button',{name:'Select Governed Case CASE-1'});fireEvent.click(screen.getByRole('checkbox',{name:'Cases'}));expect(screen.queryByRole('button',{name:'Select Governed Case CASE-1'})).not.toBeInTheDocument();fireEvent.change(screen.getByLabelText('Public Report status'),{target:{value:'ACCEPTED'}});expect(screen.queryByRole('button',{name:'Select Public Report JNV-PUB-1'})).not.toBeInTheDocument();});
  it('renders hotspot detail and reloads authoritative analysis when priority changes',async()=>{const fetchMock=vi.fn(async(url:string)=>responder(url));show(fetchMock);fireEvent.click(await screen.findByRole('button',{name:'Select Observed Hotspot Pune Division'}));expect(screen.getByText('Public Reports are counted separately and do not increase the authoritative severity index.')).toBeInTheDocument();fireEvent.change(screen.getByLabelText('Case priority'),{target:{value:'HIGH'}});await vi.waitFor(()=>expect(fetchMock.mock.calls.some(([url])=>String(url).includes('/geospatial/hotspots?minimumPriority=HIGH'))).toBe(true));});
  it('opens existing report and Case workspaces from keyboard-accessible details',async()=>{const {onOpenReport,onOpenCase}=show();fireEvent.click(await screen.findByRole('button',{name:'Select Public Report JNV-PUB-1'}));fireEvent.click(screen.getByRole('button',{name:'Open Public Report'}));expect(onOpenReport).toHaveBeenCalledWith('r1');fireEvent.click(screen.getByRole('button',{name:'Select Governed Case CASE-1'}));fireEvent.click(screen.getByRole('button',{name:'Open governed case'}));expect(onOpenCase).toHaveBeenCalledWith('c1');});
  it('shows a controlled error state',async()=>{const fetchMock=vi.fn().mockResolvedValue(new Response(JSON.stringify({success:false,error:{code:'FAIL',message:'private'}}),{status:500}));show(fetchMock);expect(await screen.findByRole('alert')).toHaveTextContent('currently unavailable');expect(screen.queryByText('private')).not.toBeInTheDocument();});
  it('handles a filter reload failure without exposing backend detail',async()=>{let hotspotCalls=0;const fetchMock=vi.fn(async(url:string)=>{if(url.includes('/geospatial')&&++hotspotCalls>1)return new Response(JSON.stringify({success:false,error:{code:'PRIVATE',message:'private detail'}}),{status:500});return responder(url)});show(fetchMock);await screen.findByText(/covers 3 of 5 eligible records/);fireEvent.change(screen.getByLabelText('Case priority'),{target:{value:'HIGH'}});expect(await screen.findByRole('alert')).toHaveTextContent('currently unavailable');expect(screen.queryByText('private detail')).not.toBeInTheDocument();});
  it('discloses eligible records when none have usable coordinates',async()=>{const noCoordinates={...hotspot,coverage:{...hotspot.coverage,overall:{eligibleRecords:2,mappedRecords:0,unmappedRecords:2,invalidCoordinateCount:1,coveragePercentage:0}},summary:{uniqueMappedAssets:0,activeMappedCases:0,mappedPublicReports:0,totalHotspots:0,hotspotsReturned:0},hotspots:[]};const fetchMock=vi.fn(async(url:string)=>url.includes('/geospatial')?ok(noCoordinates):ok([]));show(fetchMock);expect(await screen.findByText(/covers 0 of 2 eligible records \(0%\)/)).toBeInTheDocument();expect(screen.getByText(/2 records without valid coordinates/)).toBeInTheDocument();});
  it('shows an honest empty state',async()=>{const emptyHotspot={...hotspot,coverage:{...hotspot.coverage,overall:{eligibleRecords:0,mappedRecords:0,unmappedRecords:0,invalidCoordinateCount:0,coveragePercentage:0}},summary:{uniqueMappedAssets:0,activeMappedCases:0,mappedPublicReports:0,totalHotspots:0,hotspotsReturned:0},hotspots:[]};const empty=vi.fn().mockImplementation(async(url:string)=>url.includes('/geospatial')?ok(emptyHotspot):ok([]));show(empty);expect(await screen.findByText('No map-ready records match the selected layers and filters.')).toBeInTheDocument();expect(screen.getByText('0 hotspots · complete list shown')).toBeInTheDocument();});
});
