import { useEffect, useState } from 'react';
import { getIntegrityCoverageSummary, listIntegrityChains, verifyIntegrityChain, type IntegrityChain, type IntegrityCoverageSummary, type IntegrityVerification } from '../api/integrity.api';
import { useAuth } from '../auth/useAuth';
import { ErrorState, Loading } from '../components/AsyncState';

export default function IntegrityAuditPage(){
 const {token}=useAuth(),[chains,setChains]=useState<IntegrityChain[]|null>(null),[coverage,setCoverage]=useState<IntegrityCoverageSummary|null>(null),[error,setError]=useState<unknown>(null),[results,setResults]=useState<Record<string,IntegrityVerification>>({}),[busy,setBusy]=useState('');
 useEffect(()=>{const controller=new AbortController();if(token)Promise.all([listIntegrityChains(token,controller.signal),getIntegrityCoverageSummary(token,controller.signal)]).then(([nextChains,nextCoverage])=>{setChains(nextChains);setCoverage(nextCoverage)}).catch(value=>{if(!controller.signal.aborted)setError(value)});return()=>controller.abort()},[token]);
 if(error)return <ErrorState error={error}/>;if(!chains||!coverage)return <Loading label="integrity chains"/>;
 const verify=async(key:string)=>{if(!token)return;setBusy(key);try{const result=await verifyIntegrityChain(key,token);setResults(value=>({...value,[key]:result}))}catch(value){setError(value)}finally{setBusy('')}};
 const counts=Object.entries(coverage.eventCountsByType).filter(([,count])=>count>0).sort(([left],[right])=>left.localeCompare(right));
 return <section aria-labelledby="integrity-heading"><p className="eyebrow">AUDIT INTEGRITY</p><h1 id="integrity-heading">Integrity verification</h1><p className="summary">Tamper-evident verification detects inconsistencies in ODYSSEY&apos;s recorded integrity chain. It does not make the database tamper-proof and does not provide external notarization.</p><div className="boundary-note"><strong>Coverage boundary</strong><p>{coverage.coverageDisclosure}</p><p>Earlier records remain legacy and unverified. No historical events were fabricated or backfilled.</p><small>Coverage contract: {coverage.coverageContractVersion}</small></div><section aria-labelledby="coverage-counts"><h2 id="coverage-counts">Recorded event coverage</h2>{counts.length?<dl>{counts.map(([eventType,count])=><div key={eventType}><dt>{eventType.replaceAll('_',' ')}</dt><dd>{count}</dd></div>)}</dl>:<p>No protected events are recorded in your visible scope.</p>}<p>{coverage.protectedEventTypes.length} governed event types are covered prospectively by this contract.</p></section>{chains.length===0?<div className="empty-state"><h2>Empty integrity history</h2><p>No P3.4 integrity events have been recorded in your visible scope.</p></div>:<div className="history-list">{chains.map(chain=>{const result=results[chain.chainKey];return <article className="history-card" key={chain.chainKey}><div className="card-heading"><h2>{chain.departmentId?'Organizational chain':'System chain'}</h2><strong>{result?.status??'NOT VERIFIED'}</strong></div><dl><dt>Chain</dt><dd>{chain.chainKey}</dd><dt>Latest sequence</dt><dd>{chain.latestSequence}</dd><dt>Latest event hash</dt><dd><code title={chain.latestEventHash??''}>{chain.latestEventHash??'Genesis not recorded'}</code></dd></dl><button className="secondary-button" disabled={busy===chain.chainKey} onClick={()=>verify(chain.chainKey)}>{busy===chain.chainKey?'Verifying…':'Verify complete chain'}</button>{result&&<p role="status">{result.status} · {result.eventsChecked} events checked · {result.complete?'Complete verification':'Bounded verification'}</p>}</article>})}</div>}</section>;
}
