import { useEffect, useState, type FormEvent } from 'react';
import { useAuth } from '../auth/useAuth';
import { createApprovedAction, createPolicy, listApprovedActions, listPolicies, type ApprovedActionDto, type PolicyDto } from '../api/policy.api';
import { Loading, ErrorState } from '../components/AsyncState';
import StatusBadge from '../components/StatusBadge';
const format=(value:string|null)=>value?new Intl.DateTimeFormat('en-IN',{day:'2-digit',month:'short',year:'numeric'}).format(new Date(value)):'No end date';
export default function PolicyActionsPage(){
 const {token}=useAuth();const[policies,setPolicies]=useState<PolicyDto[]>([]),[actions,setActions]=useState<ApprovedActionDto[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState<unknown>(null),[reload,setReload]=useState(0),[mode,setMode]=useState<'policies'|'actions'>('policies'),[message,setMessage]=useState<string|null>(null);
 useEffect(()=>{if(!token)return;const controller=new AbortController();setLoading(true);Promise.all([listPolicies(token,controller.signal),listApprovedActions(token,controller.signal)]).then(([p,a])=>{setPolicies(p);setActions(a);setError(null)}).catch(setError).finally(()=>setLoading(false));return()=>controller.abort()},[token,reload]);
 async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();if(!token)return;const form=event.currentTarget,data=new FormData(form),value=(key:string)=>String(data.get(key)||'').trim();try{if(mode==='policies')await createPolicy({policyCode:value('code').toUpperCase(),versionNumber:Number(value('version')),title:value('title'),sourceTitle:value('sourceTitle'),sourceReference:value('sourceReference'),effectiveFrom:new Date(value('effectiveFrom')).toISOString()},token);else await createApprovedAction({actionCode:value('code').toUpperCase(),versionNumber:Number(value('version')),title:value('title'),category:value('category'),description:value('description'),applicability:{},enforcementClassification:value('enforcement'),sourceReference:value('sourceReference'),effectiveFrom:new Date(value('effectiveFrom')).toISOString()},token);form.reset();setMessage('Draft registry record created. It is not authoritative until validated, approved and activated.');setReload(v=>v+1)}catch(reason){setError(reason)}}
 if(loading)return <Loading label="policy and action registries"/>;if(error)return <ErrorState error={error} retry={()=>setReload(v=>v+1)}/>;const rows=mode==='policies'?policies:actions;
 return <section className="policy-workspace"><p className="eyebrow">GOVERNED PLANNING INPUTS</p><h1>Policy &amp; Actions</h1><p className="summary">Manage versioned policy sources and approved operational actions. Draft content never becomes authoritative automatically.</p><div className="governance-notice"><strong>Human governance boundary</strong><p>Registry activation is an administrative act. Case resolution is advisory and cannot approve a plan or start work.</p></div><nav className="admin-tabs" aria-label="Policy registries"><button className={mode==='policies'?'active':''} onClick={()=>setMode('policies')}>Policy documents</button><button className={mode==='actions'?'active':''} onClick={()=>setMode('actions')}>Approved actions</button></nav>{message&&<p role="status" className="mutation-message success">{message}</p>}<div className="admin-workbench"><section className="admin-registry"><h2>{mode==='policies'?'Policy document versions':'Approved Action Library'}</h2><div className="policy-list">{rows.map((row)=><article key={row.id}><div><strong>{'policyCode'in row?row.policyCode:row.actionCode} · v{row.versionNumber}</strong><StatusBadge value={row.status}/></div><h3>{row.title}</h3>{'sourceTitle'in row?<p>{row.sourceTitle} · {row.sourceReference}</p>:<><p>{row.category} · {row.enforcementClassification}</p><p>{row.sourceReference}</p></>}<small>Effective {format(row.effectiveFrom)} to {format(row.effectiveUntil)} · {'_count'in row?`${row._count.rules} structured rule(s)`:row.provenancePolicyDocument?`Policy ${row.provenancePolicyDocument.policyCode} v${row.provenancePolicyDocument.versionNumber}`:'Independent documented source'}</small></article>)}</div></section><aside className="admin-create-panel"><form className="workflow-form admin-form" onSubmit={submit}><h2>Create draft {mode==='policies'?'policy version':'action version'}</h2><label>Stable code<input name="code" required pattern={mode==='actions'?'ACT_[A-Z0-9_]+':'[A-Z0-9_-]+'}/></label><label>Version<input name="version" type="number" min="1" required/></label><label>Title<input name="title" required/></label>{mode==='policies'?<label>Source title<input name="sourceTitle" required/></label>:<><label>Category<input name="category" required/></label><label>Description<textarea name="description" required/></label><label>Default enforcement<select name="enforcement">{['MANDATORY','RECOMMENDED','OPTIONAL','PROHIBITED'].map(v=><option key={v}>{v}</option>)}</select></label></>}<label>Source reference<input name="sourceReference" required/></label><label>Effective from<input name="effectiveFrom" type="datetime-local" required/></label><button className="primary-button">Create governed draft</button></form></aside></div></section>;
}
