import {useEffect,useState,type FormEvent} from 'react';
import {createPortfolioScenario,createResourceEstimate,getPortfolioCandidates,getResourceEstimates,type Candidate,type CandidatePage,type Estimate,type ResourceItem} from '../api/portfolio.api';
import {useAuth} from '../auth/useAuth';
import {Empty,ErrorState,Loading} from '../components/AsyncState';
import StatusBadge,{humanize} from '../components/StatusBadge';

const money=(minor:string)=>{const negative=minor.startsWith('-'),digits=negative?minor.slice(1):minor,padded=digits.padStart(3,'0'),rupees=padded.slice(0,-2).replace(/\B(?=(\d{3})+(?!\d))/g,',');return`${negative?'-':''}₹${rupees}.${padded.slice(-2)}`};
const minorUnits=(value:FormDataEntryValue|null)=>`${BigInt(String(value))*100n}`;

export default function PortfolioPlanningPage(){
 const{token,user}=useAuth();const[data,setData]=useState<CandidatePage|null>(null),[error,setError]=useState<unknown>(null),[reload,setReload]=useState(0),[scenario,setScenario]=useState<any>(null),[busy,setBusy]=useState(false);
 useEffect(()=>{if(!token)return;const controller=new AbortController();setError(null);getPortfolioCandidates(token,'limit=25',controller.signal).then(setData).catch(value=>{if(!controller.signal.aborted)setError(value)});return()=>controller.abort()},[token,reload]);
 if(error&&!data)return <ErrorState error={error} retry={()=>setReload(value=>value+1)}/>;if(!data)return <Loading label="portfolio planning"/>;
 async function loadMore(){if(!token||!data?.nextCursor)return;setBusy(true);try{const next=await getPortfolioCandidates(token,`limit=25&cursor=${encodeURIComponent(data.nextCursor)}`);setData(current=>current?{...next,items:[...current.items,...next.items]}:next)}catch(value){setError(value)}finally{setBusy(false)}}
 async function estimate(event:FormEvent<HTMLFormElement>,candidate:Candidate){event.preventDefault();if(!token)return;const form=new FormData(event.currentTarget),resources:ResourceItem[]=[];const engineerDays=Number(form.get('engineerDays'));if(engineerDays>0)resources.push({category:'STRUCTURAL_ENGINEER',quantity:engineerDays,unit:'UNIT_DAYS'});setBusy(true);setError(null);try{await createResourceEstimate(token,candidate.id,{estimatedCostMinor:minorUnits(form.get('rupees')),currency:'INR',estimatedDurationDays:Number(form.get('duration')),resourceRequirements:resources,estimateBasis:String(form.get('basis')),sourceReference:String(form.get('source'))});setReload(value=>value+1)}catch(value){setError(value)}finally{setBusy(false)}}
 async function run(event:FormEvent<HTMLFormElement>){event.preventDefault();if(!token)return;const form=new FormData(event.currentTarget),resourceCapacities:ResourceItem[]=[];const engineerDays=Number(form.get('engineerCapacity'));if(engineerDays>0)resourceCapacities.push({category:'STRUCTURAL_ENGINEER',quantity:engineerDays,unit:'UNIT_DAYS'});setBusy(true);setError(null);try{setScenario(await createPortfolioScenario(token,{name:String(form.get('name')),budgetMinor:minorUnits(form.get('budget')),currency:'INR',resourceCapacities}))}catch(value){setError(value)}finally{setBusy(false)}}
 return <section className="portfolio-page"><header><p className="eyebrow">GOVERNED DECISION SUPPORT</p><h1>Portfolio Planning</h1><p className="summary">Compare active infrastructure Cases using current safety authority and governed planning estimates.</p></header><div className="boundary-note"><strong>Planning boundary</strong><p>Portfolio scenarios are decision-support estimates. They do not approve expenditure, change case priority, or authorize execution.</p></div><dl className="intelligence-summary"><Metric label="Candidate Cases" value={data.summary.totalCandidates}/><Metric label="Planning ready" value={data.summary.readyCases}/><Metric label="Missing estimate" value={data.summary.missingEstimateCases}/><div><dt>Estimated portfolio cost</dt><dd>{money(data.summary.totalEstimatedCostMinor)}</dd></div></dl>
 {user?.role==='OFFICER'&&<form className="workflow-form portfolio-scenario" onSubmit={run}><h2>Hypothetical budget scenario</h2><label>Scenario name<input name="name" required defaultValue="Current planning envelope"/></label><label>Budget in rupees<input name="budget" type="number" min="0" step="1" required/></label><label>Structural engineer capacity (unit-days, optional)<input name="engineerCapacity" type="number" min="0" step="1" defaultValue="0"/></label><button className="primary-action" disabled={busy}>Run and preserve scenario</button><small>Method: {data.algorithmVersion}. Deterministic governed ordering; this is not an optimization or approved allocation.</small></form>}
 {scenario&&<Scenario value={scenario}/>} {error&&<div role="alert" className="mutation-message error">The planning operation could not be completed.</div>}
 {!data.items.length?<Empty>No active Cases are available for portfolio planning.</Empty>:<div className="portfolio-list">{data.items.map((candidate,index)=><article className="history-card" key={candidate.id}><div className="card-heading"><div><small>Portfolio rank {index+1}</small><h2>{candidate.caseNumber}</h2><p>{candidate.title} · {candidate.asset.name}</p></div><StatusBadge value={candidate.readiness.state}/></div><p><strong>Priority:</strong> {humanize(candidate.priorityLevel??'NOT_RECORDED')} · <strong>Risk:</strong> {humanize(candidate.riskLevel??'NOT_RECORDED')}</p><ul>{candidate.rankReasons.map(reason=><li key={reason}>{reason}</li>)}</ul>{candidate.estimate?<div className="map-provenance"><strong>Planning estimate — not financial approval</strong><span>{money(candidate.estimate.estimatedCostMinor)} · version {candidate.estimate.estimateVersion}</span><small>{candidate.estimate.estimateBasis}</small></div>:<p className="mutation-message">No active planning estimate. This Case remains visible but cannot fit a budget scenario.</p>}<EstimateHistory caseId={candidate.id} token={token!}/>{user?.role==='OFFICER'&&<form className="workflow-form inline-form" onSubmit={event=>estimate(event,candidate)}><h3>{candidate.estimate?'Record revised estimate':'Add planning estimate'}</h3><label>Estimated rupees<input name="rupees" type="number" min="0" step="1" required/></label><label>Duration days<input name="duration" type="number" min="1" step="1" required/></label><label>Structural engineer requirement (unit-days)<input name="engineerDays" type="number" min="0" step="1" defaultValue="0"/></label><label>Estimate basis<textarea name="basis" required/></label><label>Source reference<input name="source" required/></label><button disabled={busy}>Record estimate</button></form>}</article>)}</div>}
 {data.nextCursor&&<button className="secondary-action" disabled={busy} onClick={loadMore}>Load more Cases</button>}</section>;
}
function EstimateHistory({caseId,token}:{caseId:string;token:string}){const[items,setItems]=useState<Estimate[]|null>(null),[error,setError]=useState(false);async function load(){setError(false);try{setItems(await getResourceEstimates(token,caseId))}catch{setError(true)}}return <div><button className="secondary-action" type="button" onClick={load}>View estimate history</button>{error&&<p role="alert">Estimate history could not be loaded.</p>}{items&&<ul aria-label="Estimate version history">{items.map(item=><li key={item.id}>Version {item.estimateVersion} · {humanize(item.status)} · {money(item.estimatedCostMinor)} · {item.sourceReference}</li>)}</ul>}</div>}
function Scenario({value}:{value:any}){const result=value.resultSnapshot;return <section className="scenario-result"><div className="card-heading"><h2>Scenario result</h2><StatusBadge value={value.staleness.status}/></div><p>Remaining budget: {money(result.remainingBudgetMinor)}</p><p>Selected: {result.selected.length} · Unfunded/constrained: {result.unselected.length}</p><p>{value.disclosure??'Portfolio scenarios are decision-support estimates. They do not approve expenditure, change case priority, or authorize execution.'}</p>{result.criticalUnfundedCount>0&&<div role="alert" className="mutation-message error"><strong>Critical Cases remain unfunded in this scenario.</strong> Human escalation and review are required; no expenditure is authorized.</div>}<ul>{result.unselected.map((item:any)=><li key={item.caseId}><strong>{item.status}</strong>: {item.reasons.join(' ')}</li>)}</ul></section>}
function Metric({label,value}:{label:string;value:number}){return <div><dt>{label}</dt><dd>{value}</dd></div>}
