import {fireEvent,render,screen,waitFor} from '@testing-library/react';
import {beforeEach,describe,expect,it,vi} from 'vitest';
const api=vi.hoisted(()=>({list:vi.fn(),history:vi.fn(),estimate:vi.fn(),scenario:vi.fn()}));
vi.mock('../api/portfolio.api',()=>({getPortfolioCandidates:api.list,getResourceEstimates:api.history,createResourceEstimate:api.estimate,createPortfolioScenario:api.scenario}));
vi.mock('../auth/useAuth',()=>({useAuth:()=>({token:'token',user:{role:'OFFICER'}})}));
import PortfolioPlanningPage from './PortfolioPlanningPage';
const candidate={id:'c1',caseNumber:'CASE-1',title:'Bridge',status:'ORP_READY',riskLevel:'CRITICAL',priorityLevel:'CRITICAL',emergencyFlag:true,criticalRoute:true,asset:{assetCode:'A1',name:'River Bridge',department:{name:'PWD'},jurisdiction:{name:'Pune'}},estimate:null,readiness:{state:'LIMITED',reasons:['No estimate']},rankReasons:['Authoritative critical priority.']};
beforeEach(()=>{vi.clearAllMocks();api.list.mockResolvedValue({items:[candidate],nextCursor:null,limit:25,summary:{totalCandidates:1,readyCases:0,missingEstimateCases:1,totalEstimatedCostMinor:'123456789012345'},algorithmVersion:'ODYSSEY_PORTFOLIO_GREEDY_V1'});api.history.mockResolvedValue([{id:'e1',estimateVersion:1,status:'SUPERSEDED',estimatedCostMinor:'10000',sourceReference:'SOR-2025'}]);api.estimate.mockResolvedValue({});api.scenario.mockResolvedValue({staleness:{status:'CURRENT'},resultSnapshot:{remainingBudgetMinor:'0',selected:[],unselected:[{caseId:'c1',status:'CRITICAL_UNFUNDED',reasons:['Budget shortfall.']}],criticalUnfundedCount:1}})});
describe('Portfolio Planning',()=>{
 it('shows governed boundaries, missing estimates and exact minor-unit money without float calculation',async()=>{render(<PortfolioPlanningPage/>);expect(await screen.findByRole('heading',{name:'Portfolio Planning'})).toBeInTheDocument();expect(screen.getByText(/do not approve expenditure/i)).toBeInTheDocument();expect(screen.getByText('₹1,234,567,890,123.45')).toBeInTheDocument();expect(screen.getByText(/No active planning estimate/)).toBeInTheDocument();expect(screen.getByText(/ODYSSEY_PORTFOLIO_GREEDY_V1/)).toBeInTheDocument();fireEvent.click(screen.getByRole('button',{name:'View estimate history'}));expect(await screen.findByText(/Version 1.*Superseded.*₹100.00.*SOR-2025/)).toBeInTheDocument()});
 it('submits provenance and controlled resources, then warns when critical work is unfunded',async()=>{render(<PortfolioPlanningPage/>);await screen.findByText('CASE-1');fireEvent.change(screen.getByLabelText('Estimated rupees'),{target:{value:'500'}});fireEvent.change(screen.getByLabelText('Duration days'),{target:{value:'10'}});fireEvent.change(screen.getByLabelText('Structural engineer requirement (unit-days)'),{target:{value:'3'}});fireEvent.change(screen.getByLabelText('Estimate basis'),{target:{value:'Schedule of rates'}});fireEvent.change(screen.getByLabelText('Source reference'),{target:{value:'SOR-2026'}});fireEvent.click(screen.getByRole('button',{name:'Record estimate'}));await waitFor(()=>expect(api.estimate).toHaveBeenCalledWith('token','c1',expect.objectContaining({estimatedCostMinor:'50000',resourceRequirements:[{category:'STRUCTURAL_ENGINEER',quantity:3,unit:'UNIT_DAYS'}],sourceReference:'SOR-2026'})));fireEvent.change(screen.getByLabelText('Budget in rupees'),{target:{value:'100'}});fireEvent.click(screen.getByRole('button',{name:'Run and preserve scenario'}));expect(await screen.findByText(/Critical Cases remain unfunded/)).toBeInTheDocument()});
});
