import { apiRequest } from './client';

export type IntelligenceStatus='COMPLETED'|'ABSTAINED';
export type InvocationStatus=IntelligenceStatus|'UNAVAILABLE'|'INVALID_RESPONSE';
export type GovernanceStatus='APPROVED_ACTIVE'|'PROHIBITED'|'UNKNOWN'|'OUT_OF_SCOPE'|'EXPIRED'|'INACTIVE'|'GOVERNANCE_CONFLICT'|'POLICY_ABSTAINED';
export interface SafetyReconciliation { deterministicRisk:string; deterministicPriority:string; advisoryRisk:string|null; advisoryPriority:string|null; effectiveSafetyFloorRisk:string; effectiveSafetyFloorPriority:string; disagreement:boolean; deterministicFloorPreserved:boolean; }
export interface IntelligenceFactor { code:string; direction:string; observedValue:string|number|boolean|null; importance:number; explanation:string; }
export interface ReconciledAction { actionCode:string; rationale:string; modelRank?:number; resolution:GovernanceStatus; enforcementClassification?:'MANDATORY'|'RECOMMENDED'|'OPTIONAL'|'PROHIBITED'; approvedActionVersion?:{id:string;actionCode:string;versionNumber:number;title:string;category:string;sourceReference:string}; policy?:{id:string;policyCode:string;versionNumber:number}; rule?:{id:string;ruleCode:string}; }
export interface GovernanceReconciliation { id:string; contractVersion:string; policyResolutionStatus:string; reconciledActions:ReconciledAction[]; issues:Array<{code:string;message:string}>; reconciledAt:string; currentlyStale:boolean; }
export interface IntelligenceAssessment { id:string|null; persisted:boolean; status:InvocationStatus; reasonCode?:string; currentlyStale:boolean; predictedRiskScore:number|null; predictedRiskLevel:string|null; recommendedPriority:string|null; confidence:number|null; provider:string; providerType:string; productionTrained:boolean|null; modelName:string; modelVersion:string; confidenceSemantics:string|null; contributingFactors:IntelligenceFactor[]; explanation:string|null; abstentionReasons:Array<{code:string;message:string}|string>; reconciliation:SafetyReconciliation; governanceReconciliations?:GovernanceReconciliation[]; governanceReconciliation?:GovernanceReconciliation|null; inferredAt?:string; }
export interface IntelligenceSnapshot { state:string; assessment:{id:string;status:string;predictedRiskScore:number|null;predictedRiskLevel:string|null;recommendedPriority:string|null;confidence:number|null;confidenceSemantics:string;provider:string;providerType:string;productionTrained:false;modelName:string;modelVersion:string;featureSchemaVersion:string;contractVersion:string;inferredAt:string;reconciliation:SafetyReconciliation}; governance:{id:string;contractVersion:string;policyResolutionStatus:string;reconciledActions:ReconciledAction[];issues:Array<{code:string;message:string}>;reconciledAt:string}; advisoryOnly:true; humanDecision:false; }

const record=(value:unknown):Record<string,unknown>=>{if(!value||typeof value!=='object'||Array.isArray(value))throw new Error('INVALID_INTELLIGENCE_RESPONSE');return value as Record<string,unknown>};
const text=(value:unknown)=>typeof value==='string'?value:(()=>{throw new Error('INVALID_INTELLIGENCE_RESPONSE')})();
const nullableText=(value:unknown)=>value===null?null:text(value);
const finite=(value:unknown)=>typeof value==='number'&&Number.isFinite(value)?value:(()=>{throw new Error('INVALID_INTELLIGENCE_RESPONSE')})();
const nullableNumber=(value:unknown)=>value===null?null:finite(value);
const boolean=(value:unknown)=>typeof value==='boolean'?value:(()=>{throw new Error('INVALID_INTELLIGENCE_RESPONSE')})();
function parseSafety(value:unknown):SafetyReconciliation{const v=record(value);return{deterministicRisk:text(v.deterministicRisk),deterministicPriority:text(v.deterministicPriority),advisoryRisk:nullableText(v.advisoryRisk),advisoryPriority:nullableText(v.advisoryPriority),effectiveSafetyFloorRisk:text(v.effectiveSafetyFloorRisk),effectiveSafetyFloorPriority:text(v.effectiveSafetyFloorPriority),disagreement:boolean(v.disagreement),deterministicFloorPreserved:boolean(v.deterministicFloorPreserved)}}
function parseFactor(value:unknown):IntelligenceFactor{const v=record(value);if(!['string','number','boolean'].includes(typeof v.observedValue)&&v.observedValue!==null)throw new Error('INVALID_INTELLIGENCE_RESPONSE');return{code:text(v.code),direction:text(v.direction),observedValue:v.observedValue as IntelligenceFactor['observedValue'],importance:finite(v.importance),explanation:text(v.explanation)}}
function parseAction(value:unknown):ReconciledAction{const v=record(value);const allowed:GovernanceStatus[]=['APPROVED_ACTIVE','PROHIBITED','UNKNOWN','OUT_OF_SCOPE','EXPIRED','INACTIVE','GOVERNANCE_CONFLICT','POLICY_ABSTAINED'];const resolution=text(v.resolution)as GovernanceStatus;if(!allowed.includes(resolution))throw new Error('INVALID_INTELLIGENCE_RESPONSE');const result:ReconciledAction={actionCode:text(v.actionCode),rationale:text(v.rationale),resolution};if(typeof v.modelRank==='number')result.modelRank=v.modelRank;if(typeof v.enforcementClassification==='string')result.enforcementClassification=v.enforcementClassification as ReconciledAction['enforcementClassification'];if(v.approvedActionVersion){const a=record(v.approvedActionVersion);result.approvedActionVersion={id:text(a.id),actionCode:text(a.actionCode),versionNumber:finite(a.versionNumber),title:text(a.title),category:text(a.category),sourceReference:text(a.sourceReference)}}if(v.policy){const p=record(v.policy);result.policy={id:text(p.id),policyCode:text(p.policyCode),versionNumber:finite(p.versionNumber)}}if(v.rule){const r=record(v.rule);result.rule={id:text(r.id),ruleCode:text(r.ruleCode)}}return result}
function parseGovernance(value:unknown):GovernanceReconciliation{const v=record(value);if(!Array.isArray(v.reconciledActions)||!Array.isArray(v.issues))throw new Error('INVALID_INTELLIGENCE_RESPONSE');return{id:text(v.id),contractVersion:text(v.contractVersion),policyResolutionStatus:text(v.policyResolutionStatus),reconciledActions:v.reconciledActions.map(parseAction),issues:v.issues.map(item=>{const i=record(item);return{code:text(i.code),message:text(i.message)}}),reconciledAt:text(v.reconciledAt),currentlyStale:boolean(v.currentlyStale)}}
function parseAssessment(value:unknown):IntelligenceAssessment{const v=record(value);const status=text(v.status)as InvocationStatus;if(!['COMPLETED','ABSTAINED','UNAVAILABLE','INVALID_RESPONSE'].includes(status))throw new Error('INVALID_INTELLIGENCE_RESPONSE');const transient=status==='UNAVAILABLE'||status==='INVALID_RESPONSE';const factors=v.contributingFactors??[];const reasons=v.abstentionReasons??[];if(!Array.isArray(factors)||!Array.isArray(reasons))throw new Error('INVALID_INTELLIGENCE_RESPONSE');const governance=Array.isArray(v.governanceReconciliations)?v.governanceReconciliations.map(parseGovernance):undefined;const productionTrained=transient?null:boolean(v.productionTrained);const confidenceSemantics=transient?null:nullableText(v.confidenceSemantics);return{id:v.id===null?null:text(v.id),persisted:v.persisted===undefined?v.id!==null:boolean(v.persisted),status,reasonCode:typeof v.reasonCode==='string'?v.reasonCode:undefined,currentlyStale:boolean(v.currentlyStale),predictedRiskScore:transient?null:nullableNumber(v.predictedRiskScore),predictedRiskLevel:transient?null:nullableText(v.predictedRiskLevel),recommendedPriority:transient?null:nullableText(v.recommendedPriority),confidence:transient?null:nullableNumber(v.confidence),provider:transient?'Unavailable':text(v.provider),providerType:transient?'UNAVAILABLE':text(v.providerType),productionTrained,modelName:transient?'Unavailable':text(v.modelName),modelVersion:transient?'Unavailable':text(v.modelVersion),confidenceSemantics,contributingFactors:factors.map(parseFactor),explanation:transient?null:nullableText(v.explanation),abstentionReasons:reasons.map(item=>typeof item==='string'?item:{code:text(record(item).code),message:text(record(item).message)}),reconciliation:parseSafety(v.reconciliation),governanceReconciliations:governance,governanceReconciliation:v.governanceReconciliation?parseGovernance(v.governanceReconciliation):null,inferredAt:typeof v.inferredAt==='string'?v.inferredAt:undefined}}
export interface IntelligencePage {items:IntelligenceAssessment[];nextCursor:string|null;limit:number}
export async function getIntelligenceAssessmentsPage(caseId:string,token:string,query='',signal?:AbortSignal){const suffix=query?`?${query}`:'';const data=await apiRequest<unknown>(`cases/${encodeURIComponent(caseId)}/intelligence-assessments${suffix}`,{accessToken:token,signal});const raw=Array.isArray(data)?{items:data,nextCursor:null,limit:data.length}:data&&typeof data==='object'&&Array.isArray((data as {items?:unknown}).items)?data as {items:unknown[];nextCursor?:unknown;limit?:unknown}:null;if(!raw)throw new Error('INVALID_INTELLIGENCE_RESPONSE');return{items:raw.items.map(parseAssessment),nextCursor:typeof raw.nextCursor==='string'?raw.nextCursor:null,limit:typeof raw.limit==='number'?raw.limit:raw.items.length}}
export async function listIntelligenceAssessments(caseId:string,token:string,signal?:AbortSignal){return (await getIntelligenceAssessmentsPage(caseId,token,'',signal)).items}
export async function requestIntelligenceAssessment(caseId:string,token:string){return parseAssessment(await apiRequest<unknown>(`cases/${encodeURIComponent(caseId)}/intelligence-assessments`,{accessToken:token,method:'POST'}))}
