import{apiRequest}from'./client';
export type RegistryStatus='DRAFT'|'VALIDATION'|'APPROVED'|'ACTIVE'|'SUPERSEDED'|'ARCHIVED';export type Enforcement='MANDATORY'|'RECOMMENDED'|'OPTIONAL'|'PROHIBITED';
export interface PolicyDto{id:string;policyCode:string;versionNumber:number;title:string;sourceTitle:string;sourceReference:string;sourceUrl:string|null;effectiveFrom:string;effectiveUntil:string|null;status:RegistryStatus;validationState:string;approvedAt:string|null;createdAt:string;updatedAt:string;department:{id:string;name:string}|null;jurisdiction:{id:string;name:string}|null;_count:{rules:number}}
export interface PolicyRuleDto{id:string;ruleCode:string;description:string;conditions:unknown;enforcementLevel:Enforcement;enabled:boolean;createdAt:string;policyDocument:{id:string;policyCode:string;versionNumber:number;title:string;sourceReference:string};action:{id:string;actionCode:string;versionNumber:number;title:string;category:string;description:string;sourceReference:string;enforcementClassification:Enforcement;applicability:unknown}}
export interface ApprovedActionDto{id:string;actionCode:string;versionNumber:number;title:string;category:string;description:string;applicability:unknown;enforcementClassification:Enforcement;sourceReference:string;effectiveFrom:string;effectiveUntil:string|null;status:RegistryStatus;approvedAt:string|null;department:{id:string;name:string}|null;jurisdiction:{id:string;name:string}|null;provenancePolicyDocument:{id:string;policyCode:string;versionNumber:number;title:string}|null}
export interface ExecutionTemplateTaskDto{id:string;sequenceNumber:number;taskCode:string;title:string;description:string;mandatory:boolean;evidenceRequired:boolean;verificationRequired:boolean;enabled:boolean}
export interface ExecutionTemplateDto{id:string;templateCode:string;versionNumber:number;title:string;description:string;status:RegistryStatus;effectiveFrom:string;effectiveUntil:string|null;approvedAt:string|null;approvedActionVersion:{id:string;actionCode:string;versionNumber:number;title:string;category:string;status:RegistryStatus};department:{id:string;name:string}|null;jurisdiction:{id:string;name:string}|null;tasks:ExecutionTemplateTaskDto[]}
export interface PolicyResolution{status:'RESOLVED'|'ABSTAINED';asOf:string;caseReference:string;context:{assetType:string;caseStatus:string;riskLevel:string|null;priorityLevel:string|null;emergencyFlag:boolean};issues:Array<{code:string;message:string;ruleCode?:string;actionCode?:string}>;applicableRules:Array<{rule:{id:string;code:string;description:string;enforcementLevel:Enforcement};policy:{id:string;policyCode:string;versionNumber:number;title:string};action:{id:string;actionCode:string;versionNumber:number;title:string;enforcementClassification:Enforcement}}> ;governance:{advisoryOnly:true;caseMutated:false;automaticDecision:false}}
const get=<T>(path:string,token:string,signal?:AbortSignal)=>apiRequest<T>(path,{accessToken:token,signal});const post=<T>(path:string,body:unknown,token:string)=>apiRequest<T>(path,{method:'POST',body,accessToken:token});const patch=<T>(path:string,body:unknown,token:string)=>apiRequest<T>(path,{method:'PATCH',body,accessToken:token});
export interface RegistryPage<T>{items:T[];nextCursor:string|null;limit:number;truncated?:boolean}const page=<T>(path:string,token:string,signal?:AbortSignal)=>get<RegistryPage<T>|T[]>(path,token,signal).then(value=>Array.isArray(value)?{items:value,nextCursor:null,limit:value.length}:value);const pageItems=<T>(path:string,token:string,signal?:AbortSignal)=>page<T>(path,token,signal).then(value=>value.items);
const queryPath=(path:string,query='')=>query?`${path}?${query}`:path;
export const getPoliciesPage=(token:string,query='',signal?:AbortSignal)=>page<PolicyDto>(queryPath('/policies',query),token,signal);export const listPolicies=(token:string,signal?:AbortSignal)=>getPoliciesPage(token,'',signal).then(value=>value.items);
export const getApprovedActionsPage=(token:string,query='',signal?:AbortSignal)=>page<ApprovedActionDto>(queryPath('/approved-actions',query),token,signal);export const listApprovedActions=(token:string,signal?:AbortSignal)=>getApprovedActionsPage(token,'',signal).then(value=>value.items);export const resolveCasePolicy=(caseId:string,token:string,signal?:AbortSignal)=>get<PolicyResolution>(`/cases/${encodeURIComponent(caseId)}/policy-resolution`,token,signal);export const createPolicy=(body:unknown,token:string)=>post<PolicyDto>('/policies',body,token);export const createApprovedAction=(body:unknown,token:string)=>post<ApprovedActionDto>('/approved-actions',body,token);
export const getExecutionTemplatesPage=(token:string,query='',signal?:AbortSignal)=>page<ExecutionTemplateDto>(queryPath('/execution-templates',query),token,signal);export const listExecutionTemplates=(token:string,signal?:AbortSignal)=>getExecutionTemplatesPage(token,'',signal).then(value=>value.items);export const createExecutionTemplate=(body:unknown,token:string)=>post<ExecutionTemplateDto>('/execution-templates',body,token);export const addExecutionTemplateTask=(id:string,body:unknown,token:string)=>post<ExecutionTemplateDto>(`/execution-templates/${encodeURIComponent(id)}/tasks`,body,token);
export const getPolicyRulesPage=(id:string,token:string,query='',signal?:AbortSignal)=>page<PolicyRuleDto>(queryPath(`/policies/${encodeURIComponent(id)}/rules`,query),token,signal);export const listPolicyRules=(id:string,token:string,signal?:AbortSignal)=>getPolicyRulesPage(id,token,'',signal).then(value=>value.items);export const createPolicyRule=(id:string,body:unknown,token:string)=>post<PolicyRuleDto>(`/policies/${encodeURIComponent(id)}/rules`,body,token);export const transitionPolicy=(id:string,status:RegistryStatus,token:string)=>patch<PolicyDto>(`/policies/${encodeURIComponent(id)}/lifecycle`,status==='APPROVED'?{status,validationState:'VALIDATED'}:{status},token);export const transitionApprovedAction=(id:string,status:RegistryStatus,token:string)=>patch<ApprovedActionDto>(`/approved-actions/${encodeURIComponent(id)}/lifecycle`,{status},token);export const transitionExecutionTemplate=(id:string,status:RegistryStatus,token:string)=>patch<ExecutionTemplateDto>(`/execution-templates/${encodeURIComponent(id)}/lifecycle`,{status},token);
