import { render, screen } from '@testing-library/react';
import { createElement } from 'react';
import { describe, expect, it, vi } from 'vitest';
import Sidebar, { navigationForRole } from './Sidebar';
describe('role-aware navigation', () => {
  it('presents JanSeva IntelliGov as the visible product brand',()=>{render(createElement(Sidebar,{role:'OFFICER',activeItem:'dashboard',onSelect:vi.fn()}));expect(screen.getByText('JANSEVA INTELLIGOV')).toBeInTheDocument();expect(screen.queryByText(/Project Odyssey/i)).not.toBeInTheDocument();});
  it('adds Public Reports, Infrastructure Map and Portfolio Planning to the officer workspace',()=>expect(navigationForRole('OFFICER').map((item)=>item.label)).toEqual(['Dashboard','Public Reports','Infrastructure Map','Cases','Portfolio Planning']));
  it('keeps AUDITOR navigation read-governance focused', () => expect(navigationForRole('AUDITOR').map((item) => item.label)).toEqual(['Dashboard', 'Cases','Portfolio Planning','Predictive Governance','Integrity Audit']));
  it('gives POLICY_ADMIN the governed registry and read-only planning workspaces', () => expect(navigationForRole('POLICY_ADMIN').map((item) => item.label)).toEqual(['Dashboard', 'Cases','Portfolio Planning', 'Policy & Actions']));
  it('shows governed registries, portfolio planning and system administration to SYSTEM_ADMIN', () => expect(navigationForRole('SYSTEM_ADMIN').map((item) => item.label)).toEqual(['Dashboard', 'Public Reports', 'Infrastructure Map', 'Cases','Portfolio Planning', 'Policy & Actions','Predictive Governance','Integrity Audit', 'Administration']));
  it('provides accessible Infrastructure Map navigation',()=>{const onSelect=vi.fn();render(createElement(Sidebar,{role:'OFFICER',activeItem:'infrastructure-map',onSelect}));const button=screen.getByRole('button',{name:/Infrastructure Map Geospatial infrastructure intelligence/});expect(button).toHaveAttribute('aria-current','page');button.click();expect(onSelect).toHaveBeenCalledWith('infrastructure-map');});
  it('provides accessible Public Reports navigation',()=>{const onSelect=vi.fn();render(createElement(Sidebar,{role:'OFFICER',activeItem:'public-reports',onSelect}));const button=screen.getByRole('button',{name:/Public Reports Citizen infrastructure intake/});expect(button).toHaveAttribute('aria-current','page');button.click();expect(onSelect).toHaveBeenCalledWith('public-reports');});
  it('provides accessible Portfolio Planning navigation',()=>{const onSelect=vi.fn();render(createElement(Sidebar,{role:'OFFICER',activeItem:'portfolio-planning',onSelect}));const button=screen.getByRole('button',{name:/Portfolio Planning Governed cost and scenario support/});expect(button).toHaveAttribute('aria-current','page');button.click();expect(onSelect).toHaveBeenCalledWith('portfolio-planning');});
});
